In [2]:
import pandas as pd
import numpy as np
import statistics as st
from pandas import Series,DataFrame

In [3]:
#makingdataframefromimportedEmoNCDatasetcsvfile
data=pd.read_csv('C:/Users/Administrator/Desktop/Missing Handeled2.csv')

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (585,586,587,588,675,699,782,801,810) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']

In [4]:
my_tab = pd.crosstab(data['Q005'], data['Q203G_3'])

In [9]:
per_lis = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)

In [1046]:

del per_lis[0]
del per_lis[-999]

In [491]:
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Curtains for client privacy']

In [492]:
per_lis.columns= labels_of_col[1:]
per_lis.index= labels_of_col1[1:]
per_lis.columns.names= [labels_of_col[0]]
per_lis.index.names= [labels_of_col1[0]]

In [493]:
my_tab1 = pd.crosstab(data['Q203G_3'], data['Q203G_3'])
b = len(data.loc[((data['MA3']))])

In [494]:
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)

In [495]:
per_lis.loc['National'] = cc
#per_lis

In [496]:
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
my_tab = pd.crosstab(data['Q005'], data['Q204_3'])
per_lis0 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_lis0[0]
del per_lis0[-999]
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Clients who shared beds before or after delivery']
per_lis0.columns= labels_of_col[1:]
per_lis0.index= labels_of_col1[1:]
per_lis0.columns.names= [labels_of_col[0]]
per_lis0.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q204_3'], data['Q204_3'])
b = len(data.loc[((data['MA3']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
cc.tolist()
#dd = pd.DataFrame(columns = 'National', cc)
per_lis0.loc['National'] = cc
#per_lis0

In [497]:
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
my_tab = pd.crosstab(data['Q005'], data['Q205_3'])
per_lis1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_lis1[0]
del per_lis1[-999]
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Delivery clients who slept on the floor']
per_lis1.columns= labels_of_col[1:]
per_lis1.index= labels_of_col1[1:]
per_lis1.columns.names= [labels_of_col[0]]
per_lis1.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q205_3'], data['Q205_3'])
b = len(data.loc[((data['MA3']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
cc.tolist()
#dd = pd.DataFrame(columns = 'National', cc)
per_lis1.loc['National'] = cc
#per_lis1

In [498]:
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
my_tab = pd.crosstab(data['Q005'], data['Q205_3'])
per_lis2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_lis2[0]
del per_lis2[-999]
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Clients who delivered on the floor']
per_lis2.columns= labels_of_col[1:]
per_lis2.index= labels_of_col1[1:]
per_lis2.columns.names= [labels_of_col[0]]
per_lis2.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q205_3'], data['Q205_3'])
b = len(data.loc[((data['MA3']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
cc.tolist()
#dd = pd.DataFrame(columns = 'National', cc)
per_lis2.loc['National'] = cc
#per_lis1

In [499]:
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care=(per_lis, per_lis0, per_lis1,per_lis2)
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Regional=pd.concat(Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care, axis=1, sort=False)
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Regional

In [500]:
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Regional.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Policy environment and respectful maternity care/ Percent of facilities according to selected concerns regarding respectful maternity care by Region.csv")

In [501]:
labels_of_col1 = ["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
my_tab = pd.crosstab(data['FT7'], data['Q203G_3'])
per_Curtains_for_client_privacy_by_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Curtains_for_client_privacy_by_facility[0]
del per_Curtains_for_client_privacy_by_facility[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["",'Curtains for client privacy']
per_Curtains_for_client_privacy_by_facility.columns= labels_of_col[1:]
per_Curtains_for_client_privacy_by_facility.index= labels_of_col1[1:]
per_Curtains_for_client_privacy_by_facility.columns.names= [labels_of_col[0]]
per_Curtains_for_client_privacy_by_facility.index.names= [labels_of_col1[0]]
#per_Curtains_for_client_privacy_by_facility

In [502]:
labels_of_col1 = ["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
my_tab = pd.crosstab(data['FT7'], data['Q204_3'])
per_Clients_who_shared_beds_before_by_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_shared_beds_before_by_facility[0]
del per_Clients_who_shared_beds_before_by_facility[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["",'Clients who shared beds before or after delivery']
per_Clients_who_shared_beds_before_by_facility.columns= labels_of_col[1:]
per_Clients_who_shared_beds_before_by_facility.index= labels_of_col1[1:]
per_Clients_who_shared_beds_before_by_facility.columns.names= [labels_of_col[0]]
per_Clients_who_shared_beds_before_by_facility.index.names= [labels_of_col1[0]]
#per_Clients_who_shared_beds_before_by_facility

In [503]:
labels_of_col1 = ["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
my_tab = pd.crosstab(data['FT7'], data['Q205_3'])
per_Delivery_client_who_slept_on_the_floor_by_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Delivery_client_who_slept_on_the_floor_by_facility[0]
del per_Delivery_client_who_slept_on_the_floor_by_facility[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["",'Delivery clients who slept on the floor']
per_Delivery_client_who_slept_on_the_floor_by_facility.columns= labels_of_col[1:]
per_Delivery_client_who_slept_on_the_floor_by_facility.index= labels_of_col1[1:]
per_Delivery_client_who_slept_on_the_floor_by_facility.columns.names= [labels_of_col[0]]
per_Delivery_client_who_slept_on_the_floor_by_facility.index.names= [labels_of_col1[0]]
#per_Delivery_client_who_slept_on_the_floor_by_facility

In [504]:
labels_of_col1 = ["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
my_tab = pd.crosstab(data['FT7'], data['Q206_3'])
per_Clients_who_delivered_on_the_floorr_by_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_delivered_on_the_floorr_by_facility[0]
del per_Clients_who_delivered_on_the_floorr_by_facility[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["",'Clients who delivered on the floor']
per_Clients_who_delivered_on_the_floorr_by_facility.columns= labels_of_col[1:]
per_Clients_who_delivered_on_the_floorr_by_facility.index= labels_of_col1[1:]
per_Clients_who_delivered_on_the_floorr_by_facility.columns.names= [labels_of_col[0]]
per_Clients_who_delivered_on_the_floorr_by_facility.index.names= [labels_of_col1[0]]
#per_Clients_who_delivered_on_the_floorr_by_facility

In [505]:
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care=(per_Curtains_for_client_privacy_by_facility, per_Clients_who_shared_beds_before_by_facility, per_Delivery_client_who_slept_on_the_floor_by_facility,per_Clients_who_delivered_on_the_floorr_by_facility)
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Facility=pd.concat(Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care, axis=1, sort=False)
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Facility

In [506]:
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Facility.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Policy environment and respectful maternity care/ Percent of facilities according to selected concerns regarding respectful maternity care by facility type.csv")

In [507]:
labels_of_col1 = ["","Public/government" , "Private-for-profit ",'Private-not-for-profit' ]
my_tab = pd.crosstab(data['MA3'], data['Q203G_3'])
per_Curtains_for_client_privacy_by_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Curtains_for_client_privacy_by_Managing_authority[0]
del per_Curtains_for_client_privacy_by_Managing_authority[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Managing authority",'Curtains for client privacy']
per_Curtains_for_client_privacy_by_Managing_authority.columns= labels_of_col[1:]
per_Curtains_for_client_privacy_by_Managing_authority.index= labels_of_col1[1:]
per_Curtains_for_client_privacy_by_Managing_authority.columns.names= [labels_of_col[0]]
per_Curtains_for_client_privacy_by_Managing_authority.index.names= [labels_of_col1[0]]
#per_Curtains_for_client_privacy_by_Managing_authority

In [508]:
labels_of_col1 = ["","Public/government" , "Private-for-profit ",'Private-not-for-profit' ]
my_tab = pd.crosstab(data['MA3'], data['Q204_3'])
per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority[0]
del per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Managing authority",'Clients who shared beds before or after delivery']
per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority.columns= labels_of_col[1:]
per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority.index= labels_of_col1[1:]
per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority.columns.names= [labels_of_col[0]]
per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority.index.names= [labels_of_col1[0]]
#per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority

In [509]:
labels_of_col1 = ["","Public/government" , "Private-for-profit ",'Private-not-for-profit' ]
my_tab = pd.crosstab(data['MA3'], data['Q205_3'])
per_Delivery_clients_who_slept_on_the_floor_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Delivery_clients_who_slept_on_the_floor_Managing_authority[0]
del per_Delivery_clients_who_slept_on_the_floor_Managing_authority[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Managing authority",'Delivery clients who slept on the floor']
per_Delivery_clients_who_slept_on_the_floor_Managing_authority.columns= labels_of_col[1:]
per_Delivery_clients_who_slept_on_the_floor_Managing_authority.index= labels_of_col1[1:]
per_Delivery_clients_who_slept_on_the_floor_Managing_authority.columns.names= [labels_of_col[0]]
per_Delivery_clients_who_slept_on_the_floor_Managing_authority.index.names= [labels_of_col1[0]]
#per_Delivery_clients_who_slept_on_the_floor_Managing_authority

In [510]:
labels_of_col1 = ["","Public/government" , "Private-for-profit ",'Private-not-for-profit' ]
my_tab = pd.crosstab(data['MA3'], data['Q206_3'])
per_Clients_who_delivered_on_the_floor_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_delivered_on_the_floor_Managing_authority[0]
del per_Clients_who_delivered_on_the_floor_Managing_authority[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Managing authority",'Clients who delivered on the floor']
per_Clients_who_delivered_on_the_floor_Managing_authority.columns= labels_of_col[1:]
per_Clients_who_delivered_on_the_floor_Managing_authority.index= labels_of_col1[1:]
per_Clients_who_delivered_on_the_floor_Managing_authority.columns.names= [labels_of_col[0]]
per_Clients_who_delivered_on_the_floor_Managing_authority.index.names= [labels_of_col1[0]]
#per_Clients_who_delivered_on_the_floor_Managing_authority

In [511]:
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care=(per_Curtains_for_client_privacy_by_Managing_authority, per_Clients_who_shared_beds_before_or_after_delivery_Managing_authority, per_Delivery_clients_who_slept_on_the_floor_Managing_authority,per_Clients_who_delivered_on_the_floor_Managing_authority)
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Managing_authority=pd.concat(Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care, axis=1, sort=False)
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Managing_authority

In [512]:
labels_of_col1 = ["","Urban" , "Rural" ]
my_tab = pd.crosstab(data['Q009'], data['Q203G_3'])
per_Curtains_for_client_privacy_by_location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Curtains_for_client_privacy_by_location[0]
del per_Curtains_for_client_privacy_by_location[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Location",'Curtains for client privacy']
per_Curtains_for_client_privacy_by_location.columns= labels_of_col[1:]
per_Curtains_for_client_privacy_by_location.index= labels_of_col1[1:]
per_Curtains_for_client_privacy_by_location.columns.names= [labels_of_col[0]]
per_Curtains_for_client_privacy_by_location.index.names= [labels_of_col1[0]]
#per_Curtains_for_client_privacy_by_location

In [513]:
labels_of_col1 = ["","Urban" , "Rural" ]
my_tab = pd.crosstab(data['Q009'], data['Q204_3'])
per_Clients_who_shared_beds_before_or_after_delivery_by_location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_shared_beds_before_or_after_delivery_by_location[0]
del per_Clients_who_shared_beds_before_or_after_delivery_by_location[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Location",'Clients who shared beds before or after delivery']
per_Clients_who_shared_beds_before_or_after_delivery_by_location.columns= labels_of_col[1:]
per_Clients_who_shared_beds_before_or_after_delivery_by_location.index= labels_of_col1[1:]
per_Clients_who_shared_beds_before_or_after_delivery_by_location.columns.names= [labels_of_col[0]]
per_Clients_who_shared_beds_before_or_after_delivery_by_location.index.names= [labels_of_col1[0]]
#per_Clients_who_shared_beds_before_or_after_delivery_by_location

In [514]:
labels_of_col1 = ["","Urban" , "Rural" ]
my_tab = pd.crosstab(data['Q009'], data['Q205_3'])
per_Delivery_clients_who_slept_on_the_floor_by_location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Delivery_clients_who_slept_on_the_floor_by_location[0]
del per_Delivery_clients_who_slept_on_the_floor_by_location[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Location",'Delivery clients who slept on the floor']
per_Delivery_clients_who_slept_on_the_floor_by_location.columns= labels_of_col[1:]
per_Delivery_clients_who_slept_on_the_floor_by_location.index= labels_of_col1[1:]
per_Delivery_clients_who_slept_on_the_floor_by_location.columns.names= [labels_of_col[0]]
per_Delivery_clients_who_slept_on_the_floor_by_location.index.names= [labels_of_col1[0]]
#per_Delivery_clients_who_slept_on_the_floor_by_location

In [515]:
labels_of_col1 = ["","Urban" , "Rural" ]
my_tab = pd.crosstab(data['Q009'], data['Q206_3'])
per_Clients_who_delivered_on_the_floor_location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del per_Clients_who_delivered_on_the_floor_location[0]
del per_Clients_who_delivered_on_the_floor_location[-999]
#labels_of_col1 = ["Region","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres]
labels_of_col = ["Location",'Clients who delivered on the floor']
per_Clients_who_delivered_on_the_floor_location.columns= labels_of_col[1:]
per_Clients_who_delivered_on_the_floor_location.index= labels_of_col1[1:]
per_Clients_who_delivered_on_the_floor_location.columns.names= [labels_of_col[0]]
per_Clients_who_delivered_on_the_floor_location.index.names= [labels_of_col1[0]]
#per_Clients_who_delivered_on_the_floor_location

In [516]:
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care=(per_Curtains_for_client_privacy_by_location, per_Clients_who_shared_beds_before_or_after_delivery_by_location, per_Delivery_clients_who_slept_on_the_floor_by_location,per_Clients_who_delivered_on_the_floor_location)
Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_location=pd.concat(Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care, axis=1, sort=False)
#Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_location

In [517]:
frames = [Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Regional,Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Facility,Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_Managing_authority,Percent_of_facilities_according_to_selected_concerns_regarding_respectful_maternity_care_by_location]
df_keys = pd.concat(frames, keys=['Regional', 'Facility typ','Managing authority','Location'])
df_keys

                                                   Curtains for client privacy  \
Regional           Tigray                                                 92.0
                   Afar                                                   83.0
                   Amhara                                                 82.0
                   Oromia                                                 84.0
                   Somali                                                 78.0
                   Benishangul-Gumuz                                      84.0
                   SNNP                                                   78.0
                   Gambella                                               74.0
                   Harari                                                 93.0
                   Addis Ababa                                            97.0
                   Dire Dawa                                              90.0
                   National                                               83.0
Facility typ       Referral/specialized hospitals                         87.0
                   General hospitals                                      97.0
                   Primary hospital                                       89.0
                   MCH specialty centres                                 100.0
                   Health centres                                         82.0
                   MCH specialty clinics                                 100.0
                   Higher clinics                                         92.0
Managing authority Public/government                                      83.0
                   Private-for-profit                                     99.0
                   Private-not-for-profit                                 90.0
Location           Urban                                                  88.0
                   Rural                                                  80.0

                                                   Clients who shared beds before or after delivery  \
Regional           Tigray                                                                       8.0
                   Afar                                                                         1.0
                   Amhara                                                                       9.0
                   Oromia                                                                       8.0
                   Somali                                                                      10.0
                   Benishangul-Gumuz                                                            7.0
                   SNNP                                                                        14.0
                   Gambella                                                                     4.0
                   Harari                                                                      20.0
                   Addis Ababa                                                                  6.0
                   Dire Dawa                                                                    5.0
                   National                                                                     9.0
Facility typ       Referral/specialized hospitals                                              13.0
                   General hospitals                                                           12.0
                   Primary hospital                                                             8.0
                   MCH specialty centres                                                        9.0
                   Health centres                                                               9.0
                   MCH specialty clinics                                                        6.0
                   Higher clinics                                                               8.0
Managing authority Public/government                                                           10.0
                   Private-for-profit                                                           5.0
                   Private-not-for-profit                                                       8.0
Location           Urban                                                                       10.0
                   Rural                                                                        9.0

                                                   Delivery clients who slept on the floor  \
Regional           Tigray                                                             11.0
                   Afar                                                                0.0
                   Amhara                                                              8.0
                   Oromia                                                              7.0
                   Somali                                                              7.0
                   Benishangul-Gumuz                                                   5.0
                   SNNP                                                               15.0
                   Gambella                                                            7.0
                   Harari                                                              0.0
                   Addis Ababa                                                         3.0
                   Dire Dawa                                                          10.0
                   National                                                            9.0
Facility typ       Referral/specialized hospitals                                     30.0
                   General hospitals                                                  17.0
                   Primary hospital                                                    9.0
                   MCH specialty centres                                               9.0
                   Health centres                                                      8.0
                   MCH specialty clinics                                               0.0
                   Higher clinics                                                      0.0
Managing authority Public/government                                                   9.0
                   Private-for-profit                                                  5.0
                   Private-not-for-profit                                              2.0
Location           Urban                                                               9.0
                   Rural                                                               9.0

                                                   Clients who delivered on the floor
Regional           Tigray                                                        11.0
                   Afar                                                           0.0
                   Amhara                                                         8.0
                   Oromia                                                         7.0
                   Somali                                                         7.0
                   Benishangul-Gumuz                                              5.0
                   SNNP                                                          15.0
                   Gambella                                                       7.0
                   Harari                                                         0.0
                   Addis Ababa                                                    3.0
                   Dire Dawa                                                     10.0
                   National                                                       9.0
Facility typ       Referral/specialized hospitals                                20.0
                   General hospitals                                              7.0
                   Primary hospital                                               8.0
                   MCH specialty centres                                          9.0
                   Health centres                                                 5.0
                   MCH specialty clinics                                          0.0
                   Higher clinics                                                 0.0
Managing authority Public/government                                              6.0
                   Private-for-profit                                             5.0
                   Private-not-for-profit                                         5.0
Location           Urban                                                          6.0
                   Rural                                                          5.0

In [518]:
df_keys.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Policy environment and respectful maternity care/ Percent of facilities according to selected concerns regarding respectful maternity care.csv")

In [519]:

#my_tab = pd.crosstab(data.Q009, [data.Q203G_3,data.Q204_3,data.Q205_3,data.Q206_3],  margins=True)
#my_tab=pd.crosstab(index=data['Q009'], columns=[data['Q203G_3'],data['Q204_3'],data['Q205_3'],data['Q206_3']], margins=True)
#per_Clients_who_delivered_on_the_floor_location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del per_Clients_who_delivered_on_the_floor_location[0]
#del per_Clients_who_delivered_on_the_floor_location[0][0]
#del per_Clients_who_delivered_on_the_floor_location[-999]
#labels_of_col1 = ["","Urban" , "Rural" ,'hhh']
#labels_of_col = ["",'Clients who delivered on the floor','gggg','yyy','lll','lll','lll','lll','lll','lll']
#per_Clients_who_delivered_on_the_floor_location.columns= labels_of_col[1:]
#per_Clients_who_delivered_on_the_floor_location.index= labels_of_col1[1:]
#per_Clients_who_delivered_on_the_floor_location.columns.names= [labels_of_col[0]]
#per_Clients_who_delivered_on_the_floor_location.index.names= [labels_of_col1[0]]
#per_Clients_who_delivered_on_the_floor_location

# Percent of facilities with separate room or space for selected maternal and newbornservices

In [520]:
#labels_of_col1 = ["","Urban" , "Rural" ]
my_tab = pd.crosstab(data['FT7'], data['Q221A_1'])
Percent_of_facilities_with_separate_ANC_room = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_ANC_room[0]
#del Percent_of_facilities_with_separate_ANC_room[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Antenatal room']
Percent_of_facilities_with_separate_ANC_room.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_ANC_room.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_ANC_room.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_ANC_room.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_ANC_room

In [521]:
my_tab = pd.crosstab(data['FT7'], data['Q222A_1'])
Percent_of_facilities_with_separate_Labour_and_delivery_together = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_Labour_and_delivery_together[0]
#del Percent_of_facilities_with_separate_Labour_and_delivery_together[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Labour and delivery together']
Percent_of_facilities_with_separate_Labour_and_delivery_together.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_Labour_and_delivery_together.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_Labour_and_delivery_together.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_Labour_and_delivery_together.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_Labour_and_delivery_together

In [522]:
my_tab = pd.crosstab(data['FT7'], data['Q223A_1'])
Percent_of_facilities_with_separate_1st_stage_of_labour_room = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_1st_stage_of_labour_room[0]
#del Percent_of_facilities_with_separate_1st_stage_of_labour_room[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Labour and delivery together']
Percent_of_facilities_with_separate_1st_stage_of_labour_room.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_1st_stage_of_labour_room.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_1st_stage_of_labour_room.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_1st_stage_of_labour_room.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_1st_stage_of_labour_room

In [523]:
my_tab = pd.crosstab(data['FT7'], data['Q224A_1'])
Percent_of_facilities_with_separate_Delivery_room = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_Delivery_room[0]
#del Percent_of_facilities_with_separate_Delivery_room[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Delivery room']
Percent_of_facilities_with_separate_Delivery_room.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_Delivery_room.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_Delivery_room.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_Delivery_room.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_Delivery_room

In [524]:
my_tab = pd.crosstab(data['FT7'], data['Q226A_1'])
Percent_of_facilities_with_separate_Postnatal_room = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_Postnatal_room[0]
#del Percent_of_facilities_with_separate_DPostnatal_room[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Postnatal room']
Percent_of_facilities_with_separate_Postnatal_room.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_Postnatal_room.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_Postnatal_room.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_Postnatal_room.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_Postnatal_room

In [525]:
my_tab = pd.crosstab(data['FT7'], data['Q231A_1'])
Percent_of_facilities_with_separate_Newborn_corner = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_Newborn_corner[0]
#del Percent_of_facilities_with_separate_DNewborn_corner[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate Newborn corner']
Percent_of_facilities_with_separate_Newborn_corner.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_Newborn_corner.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_Newborn_corner.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_Newborn_corner.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_Newborn_corner

In [526]:
my_tab = pd.crosstab(data['FT7'], data['Q233BA_1'])
Percent_of_facilities_with_separate_IMNCI_clinic = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_separate_IMNCI_clinic[0]
del Percent_of_facilities_with_separate_IMNCI_clinic[-999]
labels_of_col1 =["Types of Facility","Referral/specialized hospitals" , "General hospitals ",'Primary hospital','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics' ]
labels_of_col = ["",'Separate IMNCI clinic']
Percent_of_facilities_with_separate_IMNCI_clinic.columns= labels_of_col[1:]
Percent_of_facilities_with_separate_IMNCI_clinic.index= labels_of_col1[1:]
Percent_of_facilities_with_separate_IMNCI_clinic.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_separate_IMNCI_clinic.index.names= [labels_of_col1[0]]
#Percent_of_facilities_with_separate_IMNCI_clinic

In [527]:
Percent_of_facilities_with_separate_room_or_space_for_selected_maternal_and_newborn=(Percent_of_facilities_with_separate_ANC_room, Percent_of_facilities_with_separate_Labour_and_delivery_together, Percent_of_facilities_with_separate_1st_stage_of_labour_room,Percent_of_facilities_with_separate_Delivery_room,Percent_of_facilities_with_separate_Postnatal_room,Percent_of_facilities_with_separate_Newborn_corner,Percent_of_facilities_with_separate_IMNCI_clinic)
Percent_of_facilities_with_separate_room_or_space_for_selected_maternal_and_newborn_services=pd.concat(Percent_of_facilities_with_separate_room_or_space_for_selected_maternal_and_newborn, axis=1, sort=False)
Percent_of_facilities_with_separate_room_or_space_for_selected_maternal_and_newborn_services

,Separate Antenatal room,Separate Labour and delivery together,Separate Labour and delivery together,Separate Delivery room,Separate Postnatal room,Separate Newborn corner,Separate IMNCI clinic
Types of Facility,,,,,,,
Referral/specialized hospitals,100.0,67.0,93.0,93.0,93.0,80.0,70.0
General hospitals,94.0,65.0,88.0,92.0,92.0,70.0,62.0
Primary hospital,93.0,59.0,89.0,96.0,91.0,59.0,71.0
MCH specialty centres,87.0,61.0,91.0,96.0,87.0,61.0,43.0
Health centres,78.0,65.0,43.0,69.0,65.0,24.0,59.0
MCH specialty clinics,81.0,50.0,81.0,94.0,62.0,25.0,6.0
Higher clinics,77.0,85.0,69.0,92.0,69.0,38.0,15.0

In [528]:
Percent_of_facilities_with_separate_room_or_space_for_selected_maternal_and_newborn_services.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Physical infrastructure/  Percent of facilities with separate room or space for selected maternal and newborn services.csv")

In [529]:
my_tab = pd.crosstab(data['Q005'], data['Q203A_3'])
Percent_of_Sufficient_light_during_the_day_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_during_the_day_Region[0]
del Percent_of_Sufficient_light_during_the_day_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Sufficient light during the day']
Percent_of_Sufficient_light_during_the_day_Region.columns= labels_of_col[1:]
Percent_of_Sufficient_light_during_the_day_Region.index= labels_of_col1[1:]
Percent_of_Sufficient_light_during_the_day_Region.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_during_the_day_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203A_3'], data['Q203A_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Sufficient_light_during_the_day_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Sufficient_light_during_the_day_Region

                   Sufficient light during the day
Region
Tigray                                        97.0
Afar                                          96.0
Amhara                                        93.0
Oromia                                        95.0
Somali                                        96.0
Benishangul-Gumuz                             93.0
SNNP                                          95.0
Gambella                                     100.0
Harari                                       100.0
Addis Ababa                                   98.0
Dire Dawa                                    100.0
National                                      95.0

In [530]:
my_tab = pd.crosstab(data['Q005'], data['Q203B_3'])
Percent_of_Sufficient_light_at_night_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_at_night_Region[0]
del Percent_of_Sufficient_light_at_night_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Sufficient light at night']
Percent_of_Sufficient_light_at_night_Region.columns= labels_of_col[1:]
Percent_of_Sufficient_light_at_night_Region.index= labels_of_col1[1:]
Percent_of_Sufficient_light_at_night_Region.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_at_night_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203B_3'], data['Q203B_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Sufficient_light_at_night_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Sufficient_light_at_night_Region

                   Sufficient light at night
Region
Tigray                                  90.0
Afar                                    69.0
Amhara                                  62.0
Oromia                                  59.0
Somali                                  68.0
Benishangul-Gumuz                       77.0
SNNP                                    71.0
Gambella                                33.0
Harari                                  93.0
Addis Ababa                             94.0
Dire Dawa                               95.0
National                                67.0

In [531]:
my_tab = pd.crosstab(data['Q005'], data['Q203C_3'])
Percent_of_Means_of_ventilation_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_ventilation_Region[0]
del Percent_of_Means_of_ventilation_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Means of ventilation']
Percent_of_Means_of_ventilation_Region.columns= labels_of_col[1:]
Percent_of_Means_of_ventilation_Region.index= labels_of_col1[1:]
Percent_of_Means_of_ventilation_Region.columns.names= [labels_of_col[0]]
Percent_of_Means_of_ventilation_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203C_3'], data['Q203C_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Means_of_ventilation_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Means_of_ventilation_Region

                   Means of ventilation
Region
Tigray                             95.0
Afar                               53.0
Amhara                             86.0
Oromia                             81.0
Somali                             85.0
Benishangul-Gumuz                  95.0
SNNP                               84.0
Gambella                           85.0
Harari                            100.0
Addis Ababa                        93.0
Dire Dawa                         100.0
National                           84.0

In [532]:
my_tab = pd.crosstab(data['Q005'], data['Q203E_3'])
Percent_of_Means_of_heating_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_heating_Region[0]
del Percent_of_Means_of_heating_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Means of heating']
Percent_of_Means_of_heating_Region.columns= labels_of_col[1:]
Percent_of_Means_of_heating_Region.index= labels_of_col1[1:]
Percent_of_Means_of_heating_Region.columns.names= [labels_of_col[0]]
Percent_of_Means_of_heating_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203E_3'], data['Q203E_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Means_of_heating_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Means_of_heating_Region

                   Means of heating
Region
Tigray                         35.0
Afar                           29.0
Amhara                         30.0
Oromia                         26.0
Somali                         20.0
Benishangul-Gumuz              67.0
SNNP                           28.0
Gambella                       22.0
Harari                         60.0
Addis Ababa                    78.0
Dire Dawa                      62.0
National                       31.0

In [533]:
my_tab = pd.crosstab(data['Q005'], data['Q203F_3'])
Percent_of_Functional_fan_or_air_conditioning_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functional_fan_or_air_conditioning_Region[0]
del Percent_of_Functional_fan_or_air_conditioning_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Functional fan or air conditioning']
Percent_of_Functional_fan_or_air_conditioning_Region.columns= labels_of_col[1:]
Percent_of_Functional_fan_or_air_conditioning_Region.index= labels_of_col1[1:]
Percent_of_Functional_fan_or_air_conditioning_Region.columns.names= [labels_of_col[0]]
Percent_of_Functional_fan_or_air_conditioning_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203F_3'], data['Q203F_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Functional_fan_or_air_conditioning_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Functional_fan_or_air_conditioning_Region

                   Functional fan or air conditioning
Region
Tigray                                           10.0
Afar                                             35.0
Amhara                                           14.0
Oromia                                            8.0
Somali                                           15.0
Benishangul-Gumuz                                28.0
SNNP                                              9.0
Gambella                                         15.0
Harari                                           20.0
Addis Ababa                                      26.0
Dire Dawa                                        86.0
National                                         12.0

In [534]:
my_tab = pd.crosstab(data['Q005'], data['Q203D_3'])
Percent_of_Functioning_toilet_for_client_use_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functioning_toilet_for_client_use_Region[0]
del Percent_of_Functioning_toilet_for_client_use_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Functioning toilet for client use']
Percent_of_Functioning_toilet_for_client_use_Region.columns= labels_of_col[1:]
Percent_of_Functioning_toilet_for_client_use_Region.index= labels_of_col1[1:]
Percent_of_Functioning_toilet_for_client_use_Region.columns.names= [labels_of_col[0]]
Percent_of_Functioning_toilet_for_client_use_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203D_3'], data['Q203D_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Percent_of_Functioning_toilet_for_client_use_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Percent_of_Functioning_toilet_for_client_use_Region

                   Functioning toilet for client use
Region
Tigray                                          81.0
Afar                                            79.0
Amhara                                          73.0
Oromia                                          79.0
Somali                                          88.0
Benishangul-Gumuz                              100.0
SNNP                                            81.0
Gambella                                        70.0
Harari                                          87.0
Addis Ababa                                     95.0
Dire Dawa                                       95.0
National                                        80.0

In [535]:
my_tab = pd.crosstab(data['Q005'], data['Q203I_3'])
Per_Functioning_toilet_for_visitors_and_family_use_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functioning_toilet_for_visitors_and_family_use_Region[0]
del Per_Functioning_toilet_for_visitors_and_family_use_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Functioning toilet for client use']
Per_Functioning_toilet_for_visitors_and_family_use_Region.columns= labels_of_col[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Region.index= labels_of_col1[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Region.columns.names= [labels_of_col[0]]
Per_Functioning_toilet_for_visitors_and_family_use_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203I_3'], data['Q203I_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Per_Functioning_toilet_for_visitors_and_family_use_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Per_Functioning_toilet_for_visitors_and_family_use_Region

                   Functioning toilet for client use
Region
Tigray                                          73.0
Afar                                            83.0
Amhara                                          75.0
Oromia                                          82.0
Somali                                          81.0
Benishangul-Gumuz                              100.0
SNNP                                            77.0
Gambella                                        56.0
Harari                                          87.0
Addis Ababa                                     82.0
Dire Dawa                                       90.0
National                                        79.0

In [536]:
my_tab = pd.crosstab(data['Q005'], data['Q203H_3'])
Per_Waiting_area_for_visitors_and_family_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Waiting_area_for_visitors_and_family_Region[0]
del Per_Waiting_area_for_visitors_and_family_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Waiting area for visitors and family']
Per_Waiting_area_for_visitors_and_family_Region.columns= labels_of_col[1:]
Per_Waiting_area_for_visitors_and_family_Region.index= labels_of_col1[1:]
Per_Waiting_area_for_visitors_and_family_Region.columns.names= [labels_of_col[0]]
Per_Waiting_area_for_visitors_and_family_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203H_3'], data['Q203H_3'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
#dd = pd.DataFrame(columns = 'National', cc)
Per_Waiting_area_for_visitors_and_family_Region.loc['National'] = cc
#Percent_of_Sufficient_light_during_the_day_Region
Per_Waiting_area_for_visitors_and_family_Region

                   Waiting area for visitors and family
Region
Tigray                                             80.0
Afar                                               77.0
Amhara                                             78.0
Oromia                                             80.0
Somali                                             82.0
Benishangul-Gumuz                                 100.0
SNNP                                               76.0
Gambella                                           81.0
Harari                                             80.0
Addis Ababa                                        89.0
Dire Dawa                                         100.0
National                                           79.0

In [537]:
Percent_of_facilities_with_the_indicated_infrastructure=(Percent_of_Sufficient_light_during_the_day_Region, Percent_of_Sufficient_light_at_night_Region, Percent_of_Means_of_ventilation_Region,Percent_of_Means_of_heating_Region,Percent_of_Functional_fan_or_air_conditioning_Region,Percent_of_Functioning_toilet_for_client_use_Region,Per_Functioning_toilet_for_visitors_and_family_use_Region,Per_Waiting_area_for_visitors_and_family_Region)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_0=pd.concat(Percent_of_facilities_with_the_indicated_infrastructure, axis=1, sort=False)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_0

,Sufficient light during the day,Sufficient light at night,Means of ventilation,Means of heating,Functional fan or air conditioning,Functioning toilet for client use,Functioning toilet for client use,Waiting area for visitors and family
Region,,,,,,,,
Tigray,97.0,90.0,95.0,35.0,10.0,81.0,73.0,80.0
Afar,96.0,69.0,53.0,29.0,35.0,79.0,83.0,77.0
Amhara,93.0,62.0,86.0,30.0,14.0,73.0,75.0,78.0
Oromia,95.0,59.0,81.0,26.0,8.0,79.0,82.0,80.0
Somali,96.0,68.0,85.0,20.0,15.0,88.0,81.0,82.0
Benishangul-Gumuz,93.0,77.0,95.0,67.0,28.0,100.0,100.0,100.0
SNNP,95.0,71.0,84.0,28.0,9.0,81.0,77.0,76.0
Gambella,100.0,33.0,85.0,22.0,15.0,70.0,56.0,81.0
Harari,100.0,93.0,100.0,60.0,20.0,87.0,87.0,80.0
Addis Ababa,98.0,94.0,93.0,78.0,26.0,95.0,82.0,89.0
Dire Dawa,100.0,95.0,100.0,62.0,86.0,95.0,90.0,100.0
National,95.0,67.0,84.0,31.0,12.0,80.0,79.0,79.0

In [538]:
my_tab = pd.crosstab(data['FT7'], data['Q203A_3'])
Percent_of_Sufficient_light_during_the_day_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_during_the_day_Facility[0]
del Percent_of_Sufficient_light_during_the_day_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sufficient light during the day']
Percent_of_Sufficient_light_during_the_day_Facility.columns= labels_of_col[1:]
Percent_of_Sufficient_light_during_the_day_Facility.index= labels_of_col1[1:]
Percent_of_Sufficient_light_during_the_day_Facility.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_during_the_day_Facility.index.names= [labels_of_col1[0]]
Percent_of_Sufficient_light_during_the_day_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203B_3'])
Percent_of_Sufficient_light_at_night_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_at_night_Facility[0]
del Percent_of_Sufficient_light_at_night_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sufficient light at night']
Percent_of_Sufficient_light_at_night_Facility.columns= labels_of_col[1:]
Percent_of_Sufficient_light_at_night_Facility.index= labels_of_col1[1:]
Percent_of_Sufficient_light_at_night_Facility.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_at_night_Facility.index.names= [labels_of_col1[0]]
Percent_of_Sufficient_light_at_night_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203C_3'])
Percent_of_Means_of_ventilation_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_ventilation_Facility[0]
del Percent_of_Means_of_ventilation_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Means of ventilation']
Percent_of_Means_of_ventilation_Facility.columns= labels_of_col[1:]
Percent_of_Means_of_ventilation_Facility.index= labels_of_col1[1:]
Percent_of_Means_of_ventilation_Facility.columns.names= [labels_of_col[0]]
Percent_of_Means_of_ventilation_Facility.index.names= [labels_of_col1[0]]
Percent_of_Means_of_ventilation_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203E_3'])
Percent_of_Means_of_heating_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_heating_Facility[0]
del Percent_of_Means_of_heating_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Means of heating']
Percent_of_Means_of_heating_Facility.columns= labels_of_col[1:]
Percent_of_Means_of_heating_Facility.index= labels_of_col1[1:]
Percent_of_Means_of_heating_Facility.columns.names= [labels_of_col[0]]
Percent_of_Means_of_heating_Facility.index.names= [labels_of_col1[0]]
Percent_of_Means_of_heating_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203F_3'])
Percent_of_Functional_fan_or_air_conditioning_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functional_fan_or_air_conditioning_Facility[0]
del Percent_of_Functional_fan_or_air_conditioning_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Functional fan or air conditioning']
Percent_of_Functional_fan_or_air_conditioning_Facility.columns= labels_of_col[1:]
Percent_of_Functional_fan_or_air_conditioning_Facility.index= labels_of_col1[1:]
Percent_of_Functional_fan_or_air_conditioning_Facility.columns.names= [labels_of_col[0]]
Percent_of_Functional_fan_or_air_conditioning_Facility.index.names= [labels_of_col1[0]]
Percent_of_Functional_fan_or_air_conditioning_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203D_3'])
Percent_of_Functioning_toilet_for_client_use_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functioning_toilet_for_client_use_Facility[0]
del Percent_of_Functioning_toilet_for_client_use_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Functioning toilet for client use']
Percent_of_Functioning_toilet_for_client_use_Facility.columns= labels_of_col[1:]
Percent_of_Functioning_toilet_for_client_use_Facility.index= labels_of_col1[1:]
Percent_of_Functioning_toilet_for_client_use_Facility.columns.names= [labels_of_col[0]]
Percent_of_Functioning_toilet_for_client_use_Facility.index.names= [labels_of_col1[0]]
Percent_of_Functioning_toilet_for_client_use_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203I_3'])
Per_Functioning_toilet_for_visitors_and_family_use_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functioning_toilet_for_visitors_and_family_use_Facility[0]
del Per_Functioning_toilet_for_visitors_and_family_use_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Functioning toilet for client use']
Per_Functioning_toilet_for_visitors_and_family_use_Facility.columns= labels_of_col[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.index= labels_of_col1[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.columns.names= [labels_of_col[0]]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.index.names= [labels_of_col1[0]]
Per_Functioning_toilet_for_visitors_and_family_use_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203H_3'])
Per_Waiting_area_for_visitors_and_family_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Waiting_area_for_visitors_and_family_Facility[0]
del Per_Waiting_area_for_visitors_and_family_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Waiting area for visitors and family']
Per_Waiting_area_for_visitors_and_family_Facility.columns= labels_of_col[1:]
Per_Waiting_area_for_visitors_and_family_Facility.index= labels_of_col1[1:]
Per_Waiting_area_for_visitors_and_family_Facility.columns.names= [labels_of_col[0]]
Per_Waiting_area_for_visitors_and_family_Facility.index.names= [labels_of_col1[0]]
Per_Waiting_area_for_visitors_and_family_FacilityPercent_of_facilities_with_the_indicated_infrastructure_1=(Percent_of_Sufficient_light_during_the_day_Facility, Percent_of_Sufficient_light_at_night_Facility, Percent_of_Means_of_ventilation_Facility,Percent_of_Means_of_heating_Facility,Percent_of_Functional_fan_or_air_conditioning_Facility,Percent_of_Functioning_toilet_for_client_use_Facility,Per_Functioning_toilet_for_visitors_and_family_use_Facility,Per_Waiting_area_for_visitors_and_family_Facility)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_1=pd.concat(Per_Waiting_area_for_visitors_and_family_FacilityPercent_of_facilities_with_the_indicated_infrastructure_1, axis=1, sort=False)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_1

,Sufficient light during the day,Sufficient light at night,Means of ventilation,Means of heating,Functional fan or air conditioning,Functioning toilet for client use,Functioning toilet for client use,Waiting area for visitors and family
Facility,,,,,,,,
Referral/specialized,100.0,90.0,90.0,80.0,50.0,90.0,83.0,90.0
General hospitals,100.0,98.0,95.0,80.0,43.0,91.0,89.0,85.0
Primary hospitals,95.0,89.0,89.0,66.0,27.0,88.0,86.0,91.0
MCH specialty centres,96.0,96.0,96.0,96.0,48.0,100.0,91.0,100.0
Health centres,95.0,64.0,83.0,26.0,10.0,79.0,78.0,78.0
MCH specialty clinics,100.0,100.0,94.0,62.0,31.0,100.0,94.0,100.0
Higher clinics,92.0,100.0,85.0,62.0,8.0,92.0,85.0,77.0

In [539]:
my_tab = pd.crosstab(data['Q009'], data['Q203A_3'])
Percent_of_Sufficient_light_during_the_day_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_during_the_day_Facility[0]
del Percent_of_Sufficient_light_during_the_day_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Sufficient light during the day']
Percent_of_Sufficient_light_during_the_day_Facility.columns= labels_of_col[1:]
Percent_of_Sufficient_light_during_the_day_Facility.index= labels_of_col1[1:]
Percent_of_Sufficient_light_during_the_day_Facility.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_during_the_day_Facility.index.names= [labels_of_col1[0]]
Percent_of_Sufficient_light_during_the_day_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203B_3'])
Percent_of_Sufficient_light_at_night_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Sufficient_light_at_night_Facility[0]
del Percent_of_Sufficient_light_at_night_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Sufficient light at night']
Percent_of_Sufficient_light_at_night_Facility.columns= labels_of_col[1:]
Percent_of_Sufficient_light_at_night_Facility.index= labels_of_col1[1:]
Percent_of_Sufficient_light_at_night_Facility.columns.names= [labels_of_col[0]]
Percent_of_Sufficient_light_at_night_Facility.index.names= [labels_of_col1[0]]
Percent_of_Sufficient_light_at_night_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203C_3'])
Percent_of_Means_of_ventilation_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_ventilation_Facility[0]
del Percent_of_Means_of_ventilation_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Means of ventilation']
Percent_of_Means_of_ventilation_Facility.columns= labels_of_col[1:]
Percent_of_Means_of_ventilation_Facility.index= labels_of_col1[1:]
Percent_of_Means_of_ventilation_Facility.columns.names= [labels_of_col[0]]
Percent_of_Means_of_ventilation_Facility.index.names= [labels_of_col1[0]]
Percent_of_Means_of_ventilation_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203E_3'])
Percent_of_Means_of_heating_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Means_of_heating_Facility[0]
del Percent_of_Means_of_heating_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Means of heating']
Percent_of_Means_of_heating_Facility.columns= labels_of_col[1:]
Percent_of_Means_of_heating_Facility.index= labels_of_col1[1:]
Percent_of_Means_of_heating_Facility.columns.names= [labels_of_col[0]]
Percent_of_Means_of_heating_Facility.index.names= [labels_of_col1[0]]
Percent_of_Means_of_heating_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203F_3'])
Percent_of_Functional_fan_or_air_conditioning_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functional_fan_or_air_conditioning_Facility[0]
del Percent_of_Functional_fan_or_air_conditioning_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Functional fan or air conditioning']
Percent_of_Functional_fan_or_air_conditioning_Facility.columns= labels_of_col[1:]
Percent_of_Functional_fan_or_air_conditioning_Facility.index= labels_of_col1[1:]
Percent_of_Functional_fan_or_air_conditioning_Facility.columns.names= [labels_of_col[0]]
Percent_of_Functional_fan_or_air_conditioning_Facility.index.names= [labels_of_col1[0]]
Percent_of_Functional_fan_or_air_conditioning_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203D_3'])
Percent_of_Functioning_toilet_for_client_use_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_Functioning_toilet_for_client_use_Facility[0]
del Percent_of_Functioning_toilet_for_client_use_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Functioning toilet for client use']
Percent_of_Functioning_toilet_for_client_use_Facility.columns= labels_of_col[1:]
Percent_of_Functioning_toilet_for_client_use_Facility.index= labels_of_col1[1:]
Percent_of_Functioning_toilet_for_client_use_Facility.columns.names= [labels_of_col[0]]
Percent_of_Functioning_toilet_for_client_use_Facility.index.names= [labels_of_col1[0]]
Percent_of_Functioning_toilet_for_client_use_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203I_3'])
Per_Functioning_toilet_for_visitors_and_family_use_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functioning_toilet_for_visitors_and_family_use_Facility[0]
del Per_Functioning_toilet_for_visitors_and_family_use_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Functioning toilet for client use']
Per_Functioning_toilet_for_visitors_and_family_use_Facility.columns= labels_of_col[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.index= labels_of_col1[1:]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.columns.names= [labels_of_col[0]]
Per_Functioning_toilet_for_visitors_and_family_use_Facility.index.names= [labels_of_col1[0]]
Per_Functioning_toilet_for_visitors_and_family_use_Facility
my_tab = pd.crosstab(data['Q009'], data['Q203H_3'])
Per_Waiting_area_for_visitors_and_family_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Waiting_area_for_visitors_and_family_Facility[0]
del Per_Waiting_area_for_visitors_and_family_Facility[-999]
labels_of_col1 =["Facility","Urban" , "Rural"]
labels_of_col = ["",'Waiting area for visitors and family']
Per_Waiting_area_for_visitors_and_family_Facility.columns= labels_of_col[1:]
Per_Waiting_area_for_visitors_and_family_Facility.index= labels_of_col1[1:]
Per_Waiting_area_for_visitors_and_family_Facility.columns.names= [labels_of_col[0]]
Per_Waiting_area_for_visitors_and_family_Facility.index.names= [labels_of_col1[0]]
Per_Waiting_area_for_visitors_and_family_FacilityPercent_of_facilities_with_the_indicated_infrastructure_2=(Percent_of_Sufficient_light_during_the_day_Facility, Percent_of_Sufficient_light_at_night_Facility, Percent_of_Means_of_ventilation_Facility,Percent_of_Means_of_heating_Facility,Percent_of_Functional_fan_or_air_conditioning_Facility,Percent_of_Functioning_toilet_for_client_use_Facility,Per_Functioning_toilet_for_visitors_and_family_use_Facility,Per_Waiting_area_for_visitors_and_family_Facility)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_2=pd.concat(Per_Waiting_area_for_visitors_and_family_FacilityPercent_of_facilities_with_the_indicated_infrastructure_2, axis=1, sort=False)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_2

,Sufficient light during the day,Sufficient light at night,Means of ventilation,Means of heating,Functional fan or air conditioning,Functioning toilet for client use,Functioning toilet for client use,Waiting area for visitors and family
Facility,,,,,,,,
Urban,96.0,82.0,87.0,47.0,18.0,83.0,80.0,84.0
Rural,94.0,56.0,82.0,20.0,8.0,78.0,78.0,77.0

In [540]:
Percent_of_facilities_with_the_indicated_infrastructure_2=(Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_0, Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_1,Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_the_indicated_infrastructure_in_the_labour_and_delivery_area_2)
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_thse_indicated_infrastructure_in_the_labour_and_delivery_area_2=pd.concat(Percent_of_facilities_with_the_indicated_infrastructure_2, keys=['Regional', 'Facility type','Location'])
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_thse_indicated_infrastructure_in_the_labour_and_delivery_area_2

                                      Sufficient light during the day  \
Regional      Tigray                                             97.0
              Afar                                               96.0
              Amhara                                             93.0
              Oromia                                             95.0
              Somali                                             96.0
              Benishangul-Gumuz                                  93.0
              SNNP                                               95.0
              Gambella                                          100.0
              Harari                                            100.0
              Addis Ababa                                        98.0
              Dire Dawa                                         100.0
              National                                           95.0
Facility type Referral/specialized                              100.0
              General hospitals                                 100.0
              Primary hospitals                                  95.0
              MCH specialty centres                              96.0
              Health centres                                     95.0
              MCH specialty clinics                             100.0
              Higher clinics                                     92.0
Location      Urban                                              96.0
              Rural                                              94.0

                                      Sufficient light at night  \
Regional      Tigray                                       90.0
              Afar                                         69.0
              Amhara                                       62.0
              Oromia                                       59.0
              Somali                                       68.0
              Benishangul-Gumuz                            77.0
              SNNP                                         71.0
              Gambella                                     33.0
              Harari                                       93.0
              Addis Ababa                                  94.0
              Dire Dawa                                    95.0
              National                                     67.0
Facility type Referral/specialized                         90.0
              General hospitals                            98.0
              Primary hospitals                            89.0
              MCH specialty centres                        96.0
              Health centres                               64.0
              MCH specialty clinics                       100.0
              Higher clinics                              100.0
Location      Urban                                        82.0
              Rural                                        56.0

                                      Means of ventilation  Means of heating  \
Regional      Tigray                                  95.0              35.0
              Afar                                    53.0              29.0
              Amhara                                  86.0              30.0
              Oromia                                  81.0              26.0
              Somali                                  85.0              20.0
              Benishangul-Gumuz                       95.0              67.0
              SNNP                                    84.0              28.0
              Gambella                                85.0              22.0
              Harari                                 100.0              60.0
              Addis Ababa                             93.0              78.0
              Dire Dawa                              100.0              62.0
              National                                84.0              31.0
Facility type Referral/specialized                    90.0              80.0
              General hospitals                       95.0              80.0
              Primary hospitals                       89.0              66.0
              MCH specialty centres                   96.0              96.0
              Health centres                          83.0              26.0
              MCH specialty clinics                   94.0              62.0
              Higher clinics                          85.0              62.0
Location      Urban                                   87.0              47.0
              Rural                                   82.0              20.0

                                      Functional fan or air conditioning  \
Regional      Tigray                                                10.0
              Afar                                                  35.0
              Amhara                                                14.0
              Oromia                                                 8.0
              Somali                                                15.0
              Benishangul-Gumuz                                     28.0
              SNNP                                                   9.0
              Gambella                                              15.0
              Harari                                                20.0
              Addis Ababa                                           26.0
              Dire Dawa                                             86.0
              National                                              12.0
Facility type Referral/specialized                                  50.0
              General hospitals                                     43.0
              Primary hospitals                                     27.0
              MCH specialty centres                                 48.0
              Health centres                                        10.0
              MCH specialty clinics                                 31.0
              Higher clinics                                         8.0
Location      Urban                                                 18.0
              Rural                                                  8.0

                                      Functioning toilet for client use  \
Regional      Tigray                                               81.0
              Afar                                                 79.0
              Amhara                                               73.0
              Oromia                                               79.0
              Somali                                               88.0
              Benishangul-Gumuz                                   100.0
              SNNP                                                 81.0
              Gambella                                             70.0
              Harari                                               87.0
              Addis Ababa                                          95.0
              Dire Dawa                                            95.0
              National                                             80.0
Facility type Referral/specialized                                 90.0
              General hospitals                                    91.0
              Primary hospitals                                    88.0
              MCH specialty centres                               100.0
              Health centres                                       79.0
              MCH specialty clinics                               100.0
              Higher clinics                                       92.0
Location      Urban                                                83.0
              Rural                                                78.0

                                      Functioning toilet for client use  \
Regional      Tigray                                               73.0
              Afar                                                 83.0
              Amhara                                               75.0
              Oromia                                               82.0
              Somali                                               81.0
              Benishangul-Gumuz                                   100.0
              SNNP                                                 77.0
              Gambella                                             56.0
              Harari                                               87.0
              Addis Ababa                                          82.0
              Dire Dawa                                            90.0
              National                                             79.0
Facility type Referral/specialized                                 83.0
              General hospitals                                    89.0
              Primary hospitals                                    86.0
              MCH specialty centres                                91.0
              Health centres                                       78.0
              MCH specialty clinics                                94.0
              Higher clinics                                       85.0
Location      Urban                                                80.0
              Rural                                                78.0

                                      Waiting area for visitors and family
Regional      Tigray                                                  80.0
              Afar                                                    77.0
              Amhara                                                  78.0
              Oromia                                                  80.0
              Somali                                                  82.0
              Benishangul-Gumuz                                      100.0
              SNNP                                                    76.0
              Gambella                                                81.0
              Harari                                                  80.0
              Addis Ababa                                             89.0
              Dire Dawa                                              100.0
              National                                                79.0
Facility type Referral/specialized                                    90.0
              General hospitals                                       85.0
              Primary hospitals                                       91.0
              MCH specialty centres                                  100.0
              Health centres                                          78.0
              MCH specialty clinics                                  100.0
              Higher clinics                                          77.0
Location      Urban                                                   84.0
              Rural                                                   77.0

In [541]:
Percent_of_facilities_with_the_indicated_infrastructure_Percent_of_facilities_with_thse_indicated_infrastructure_in_the_labour_and_delivery_area_2.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Physical infrastructure/  Percent of facilities with the indicated infrastructure in the labour and delivery areas.csv")

# Availability of electricity, water and toilets

In [542]:
my_tab = pd.crosstab(data['Q005'], data['elecsource']!=0)
Per_Has_a_source_of_electricity_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_a_source_of_electricity_Region[0]
#del Per_Has_a_source_of_electricity_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Has a source of electricity']
Per_Has_a_source_of_electricity_Region.columns= labels_of_col[1:]
Per_Has_a_source_of_electricity_Region.index= labels_of_col1[1:]
Per_Has_a_source_of_electricity_Region.columns.names= [labels_of_col[0]]
Per_Has_a_source_of_electricity_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['elecsource']!=0, data['elecsource']!=0)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Has_a_source_of_electricity_Region.loc['National'] = cc
Per_Has_a_source_of_electricity_Region

                   Has a source of electricity
Region
Tigray                                    96.0
Afar                                      88.0
Amhara                                    87.0
Oromia                                    87.0
Somali                                    84.0
Benishangul-Gumuz                         98.0
SNNP                                      87.0
Gambella                                  93.0
Harari                                   100.0
Addis Ababa                              100.0
Dire Dawa                                100.0
National                                  88.0

In [543]:
my_tab = pd.crosstab(data['Q005'], data['Q203_1'])
Per_Has_electricity_from_the_grid_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_electricity_from_the_grid_Region[0]
#del Per_Has_electricity_from_the_grid_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Has a source of electricity']
Per_Has_electricity_from_the_grid_Region.columns= labels_of_col[1:]
Per_Has_electricity_from_the_grid_Region.index= labels_of_col1[1:]
Per_Has_electricity_from_the_grid_Region.columns.names= [labels_of_col[0]]
Per_Has_electricity_from_the_grid_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203_1'], data['Q203_1'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Has_electricity_from_the_grid_Region.loc['National'] = cc
Per_Has_electricity_from_the_grid_Region

                   Has a source of electricity
Region
Tigray                                    81.0
Afar                                      60.0
Amhara                                    61.0
Oromia                                    61.0
Somali                                    37.0
Benishangul-Gumuz                         60.0
SNNP                                      62.0
Gambella                                  44.0
Harari                                   100.0
Addis Ababa                              100.0
Dire Dawa                                 76.0
National                                  63.0

In [544]:
my_tab = pd.crosstab(data['Q005'], data['Q206A_1'])
Per_Generator_fueloperated_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_fueloperated_Region[0]
del Per_Generator_fueloperated_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Generator fuel operated']
Per_Generator_fueloperated_Region.columns= labels_of_col[1:]
Per_Generator_fueloperated_Region.index= labels_of_col1[1:]
Per_Generator_fueloperated_Region.columns.names= [labels_of_col[0]]
Per_Generator_fueloperated_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q206A_1'], data['Q206A_1'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Generator_fueloperated_Region.loc['National'] = cc
Per_Generator_fueloperated_Region

                   Generator fuel operated
Region
Tigray                                19.0
Afar                                  21.0
Amhara                                46.0
Oromia                                33.0
Somali                                47.0
Benishangul-Gumuz                     65.0
SNNP                                  29.0
Gambella                              22.0
Harari                                73.0
Addis Ababa                           83.0
Dire Dawa                             86.0
National                              37.0

In [545]:
my_tab = pd.crosstab(data['Q005'], data['Q206B_1'])
Per_Generator_battery_operated_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_battery_operated_Region[0]
del Per_Generator_battery_operated_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Generator fuel operated']
Per_Generator_battery_operated_Region.columns= labels_of_col[1:]
Per_Generator_battery_operated_Region.index= labels_of_col1[1:]
Per_Generator_battery_operated_Region.columns.names= [labels_of_col[0]]
Per_Generator_battery_operated_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q206B_1'], data['Q206B_1'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Generator_battery_operated_Region.loc['National'] = cc
Per_Generator_battery_operated_Region

                   Generator fuel operated
Region
Tigray                                 1.0
Afar                                   0.0
Amhara                                 1.0
Oromia                                 1.0
Somali                                 9.0
Benishangul-Gumuz                      2.0
SNNP                                   2.0
Gambella                               0.0
Harari                                 0.0
Addis Ababa                            7.0
Dire Dawa                              5.0
National                               2.0

In [546]:
my_tab = pd.crosstab(data['Q005'], data['Q206C_1'])
Per_Solar_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Solar_Region[0]
del Per_Solar_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Solar']
Per_Solar_Region.columns= labels_of_col[1:]
Per_Solar_Region.index= labels_of_col1[1:]
Per_Solar_Region.columns.names= [labels_of_col[0]]
Per_Solar_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q206C_1'], data['Q206C_1'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Solar_Region.loc['National'] = cc
Per_Solar_Region

                   Solar
Region
Tigray              30.0
Afar                43.0
Amhara              28.0
Oromia              30.0
Somali              55.0
Benishangul-Gumuz   23.0
SNNP                39.0
Gambella            70.0
Harari               7.0
Addis Ababa          5.0
Dire Dawa           24.0
National            31.0

In [547]:
my_tab = pd.crosstab(data['Q005'], data['Q207_1'])
Per_Functional_on_day_of_survey_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functional_on_day_of_survey_Region[0]
del Per_Functional_on_day_of_survey_Region[8]
del Per_Functional_on_day_of_survey_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Functional on day of survey']
Per_Functional_on_day_of_survey_Region.columns= labels_of_col[1:]
Per_Functional_on_day_of_survey_Region.index= labels_of_col1[1:]
Per_Functional_on_day_of_survey_Region.columns.names= [labels_of_col[0]]
Per_Functional_on_day_of_survey_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q207_1'], data['Q207_1'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Functional_on_day_of_survey_Region.loc['National'] = cc
Per_Functional_on_day_of_survey_Region

                   Functional on day of survey
Region
Tigray                                    18.0
Afar                                      19.0
Amhara                                    39.0
Oromia                                    27.0
Somali                                    43.0
Benishangul-Gumuz                         60.0
SNNP                                      25.0
Gambella                                  22.0
Harari                                    53.0
Addis Ababa                               79.0
Dire Dawa                                 76.0
National                                  32.0

In [548]:
my_tab = pd.crosstab(data['Q005'], data['Q208_1'])
Per_Comes_on_automatically_when_needed_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Region[0]
del Per_Comes_on_automatically_when_needed_Region[8]
del Per_Comes_on_automatically_when_needed_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Comes on automatically when needed']
Per_Comes_on_automatically_when_needed_Region.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Region.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Region.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q208_1']!=0, data['Q208_1']!=0)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Comes_on_automatically_when_needed_Region.loc['National'] = cc
Per_Comes_on_automatically_when_needed_Region

                   Comes on automatically when needed
Region
Tigray                                            3.0
Afar                                              1.0
Amhara                                            8.0
Oromia                                            4.0
Somali                                            4.0
Benishangul-Gumuz                                 5.0
SNNP                                              4.0
Gambella                                          4.0
Harari                                           27.0
Addis Ababa                                      46.0
Dire Dawa                                        14.0
National                                         69.0

In [549]:
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_2=(Per_Has_a_source_of_electricity_Region, Per_Has_electricity_from_the_grid_Region, Per_Generator_fueloperated_Region,Per_Generator_battery_operated_Region,Per_Solar_Region,Per_Functional_on_day_of_survey_Region,Per_Comes_on_automatically_when_needed_Region)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Region=pd.concat(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_2, axis=1, sort=False)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Region

,Has a source of electricity,Has a source of electricity,Generator fuel operated,Generator fuel operated,Solar,Functional on day of survey,Comes on automatically when needed
Region,,,,,,,
Tigray,96.0,81.0,19.0,1.0,30.0,18.0,3.0
Afar,88.0,60.0,21.0,0.0,43.0,19.0,1.0
Amhara,87.0,61.0,46.0,1.0,28.0,39.0,8.0
Oromia,87.0,61.0,33.0,1.0,30.0,27.0,4.0
Somali,84.0,37.0,47.0,9.0,55.0,43.0,4.0
Benishangul-Gumuz,98.0,60.0,65.0,2.0,23.0,60.0,5.0
SNNP,87.0,62.0,29.0,2.0,39.0,25.0,4.0
Gambella,93.0,44.0,22.0,0.0,70.0,22.0,4.0
Harari,100.0,100.0,73.0,0.0,7.0,53.0,27.0
Addis Ababa,100.0,100.0,83.0,7.0,5.0,79.0,46.0
Dire Dawa,100.0,76.0,86.0,5.0,24.0,76.0,14.0
National,88.0,63.0,37.0,2.0,31.0,32.0,69.0

In [550]:
my_tab = pd.crosstab(data['FT7'], data['elecsource']!=0)
Per_Has_a_source_of_electricity_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_a_source_of_electricity_Facility[0]
#del Per_Has_a_source_of_electricity_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has a source of electricity']
Per_Has_a_source_of_electricity_Facility.columns= labels_of_col[1:]
Per_Has_a_source_of_electricity_Facility.index= labels_of_col1[1:]
Per_Has_a_source_of_electricity_Facility.columns.names= [labels_of_col[0]]
Per_Has_a_source_of_electricity_Facility.index.names= [labels_of_col1[0]]
Per_Has_a_source_of_electricity_Facility
my_tab = pd.crosstab(data['FT7'], data['Q203_1'])
Per_Has_electricity_from_the_grid_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_electricity_from_the_grid_Facility[0]
#del Per_Has_electricity_from_the_grid_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has a source of electricity']
Per_Has_electricity_from_the_grid_Facility.columns= labels_of_col[1:]
Per_Has_electricity_from_the_grid_Facility.index= labels_of_col1[1:]
Per_Has_electricity_from_the_grid_Facility.columns.names= [labels_of_col[0]]
Per_Has_electricity_from_the_grid_Facility.index.names= [labels_of_col1[0]]
Per_Has_electricity_from_the_grid_Facility
my_tab = pd.crosstab(data['FT7'], data['Q206A_1'])
Per_Generator_fueloperated_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_fueloperated_Facility[0]
del Per_Generator_fueloperated_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Generator fuel operated']
Per_Generator_fueloperated_Facility.columns= labels_of_col[1:]
Per_Generator_fueloperated_Facility.index= labels_of_col1[1:]
Per_Generator_fueloperated_Facility.columns.names= [labels_of_col[0]]
Per_Generator_fueloperated_Facility.index.names= [labels_of_col1[0]]
Per_Generator_fueloperated_Facility
my_tab = pd.crosstab(data['FT7'], data['Q206B_1'])
Per_Generator_battery_operated_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_battery_operated_Facility[0]
del Per_Generator_battery_operated_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Generator fuel operated']
Per_Generator_battery_operated_Facility.columns= labels_of_col[1:]
Per_Generator_battery_operated_Facility.index= labels_of_col1[1:]
Per_Generator_battery_operated_Facility.columns.names= [labels_of_col[0]]
Per_Generator_battery_operated_Facility.index.names= [labels_of_col1[0]]
Per_Generator_battery_operated_Facility
my_tab = pd.crosstab(data['FT7'], data['Q206C_1'])
Per_Solar_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Solar_Facility[0]
del Per_Solar_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Solar']
Per_Solar_Facility.columns= labels_of_col[1:]
Per_Solar_Facility.index= labels_of_col1[1:]
Per_Solar_Facility.columns.names= [labels_of_col[0]]
Per_Solar_Facility.index.names= [labels_of_col1[0]]
Per_Solar_Facility
my_tab = pd.crosstab(data['FT7'], data['Q207_1'])
Per_Functional_on_day_of_survey_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functional_on_day_of_survey_Facility[0]
del Per_Functional_on_day_of_survey_Facility[8]
del Per_Functional_on_day_of_survey_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Functional on day of survey']
Per_Functional_on_day_of_survey_Facility.columns= labels_of_col[1:]
Per_Functional_on_day_of_survey_Facility.index= labels_of_col1[1:]
Per_Functional_on_day_of_survey_Facility.columns.names= [labels_of_col[0]]
Per_Functional_on_day_of_survey_Facility.index.names= [labels_of_col1[0]]
Per_Functional_on_day_of_survey_Facility
my_tab = pd.crosstab(data['FT7'], data['Q208_1'])
Per_Comes_on_automatically_when_needed_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Facility[0]
del Per_Comes_on_automatically_when_needed_Facility[8]
del Per_Comes_on_automatically_when_needed_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Comes on automatically when needed']
Per_Comes_on_automatically_when_needed_Facility.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Facility.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Facility.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Facility.index.names= [labels_of_col1[0]]
Per_Comes_on_automatically_when_needed_Facility
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4=(Per_Has_a_source_of_electricity_Facility, Per_Has_electricity_from_the_grid_Facility, Per_Generator_fueloperated_Facility,Per_Generator_battery_operated_Facility,Per_Solar_Facility,Per_Functional_on_day_of_survey_Facility,Per_Comes_on_automatically_when_needed_Facility)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Facility=pd.concat(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4, axis=1, sort=False)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Facility

,Has a source of electricity,Has a source of electricity,Generator fuel operated,Generator fuel operated,Solar,Functional on day of survey,Comes on automatically when needed
Facility,,,,,,,
Referral/specialized,100.0,100.0,100.0,7.0,7.0,100.0,80.0
General hospitals,100.0,98.0,95.0,13.0,7.0,94.0,50.0
Primary hospitals,99.0,94.0,92.0,4.0,10.0,90.0,36.0
MCH specialty centres,100.0,100.0,100.0,4.0,9.0,96.0,65.0
Health centres,87.0,60.0,32.0,1.0,34.0,26.0,3.0
MCH specialty clinics,100.0,100.0,88.0,0.0,12.0,88.0,31.0
Higher clinics,100.0,92.0,85.0,23.0,23.0,92.0,31.0

In [551]:
my_tab = pd.crosstab(data['MA3'], data['elecsource']!=0)
Per_Has_a_source_of_electricity_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_a_source_of_electricity_Managing_authority[0]
#del Per_Has_a_source_of_electricity_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Has a source of electricity']
Per_Has_a_source_of_electricity_Managing_authority.columns= labels_of_col[1:]
Per_Has_a_source_of_electricity_Managing_authority.index= labels_of_col1[1:]
Per_Has_a_source_of_electricity_Managing_authority.columns.names= [labels_of_col[0]]
Per_Has_a_source_of_electricity_Managing_authority.index.names= [labels_of_col1[0]]
Per_Has_a_source_of_electricity_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q203_1'])
Per_Has_electricity_from_the_grid_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_electricity_from_the_grid_Managing_authority[0]
#del Per_Has_electricity_from_the_grid_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Has a source of electricity']
Per_Has_electricity_from_the_grid_Managing_authority.columns= labels_of_col[1:]
Per_Has_electricity_from_the_grid_Managing_authority.index= labels_of_col1[1:]
Per_Has_electricity_from_the_grid_Managing_authority.columns.names= [labels_of_col[0]]
Per_Has_electricity_from_the_grid_Managing_authority.index.names= [labels_of_col1[0]]
Per_Has_electricity_from_the_grid_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q206A_1'])
Per_Generator_fueloperated_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_fueloperated_Managing_authority[0]
del Per_Generator_fueloperated_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Generator fuel operated']
Per_Generator_fueloperated_Managing_authority.columns= labels_of_col[1:]
Per_Generator_fueloperated_Managing_authority.index= labels_of_col1[1:]
Per_Generator_fueloperated_Managing_authority.columns.names= [labels_of_col[0]]
Per_Generator_fueloperated_Managing_authority.index.names= [labels_of_col1[0]]
Per_Generator_fueloperated_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q206B_1'])
Per_Generator_battery_operated_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_battery_operated_Managing_authority[0]
del Per_Generator_battery_operated_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Generator fuel operated']
Per_Generator_battery_operated_Managing_authority.columns= labels_of_col[1:]
Per_Generator_battery_operated_Managing_authority.index= labels_of_col1[1:]
Per_Generator_battery_operated_Managing_authority.columns.names= [labels_of_col[0]]
Per_Generator_battery_operated_Managing_authority.index.names= [labels_of_col1[0]]
Per_Generator_battery_operated_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q206C_1'])
Per_Solar_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Solar_Managing_authority[0]
del Per_Solar_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Solar']
Per_Solar_Managing_authority.columns= labels_of_col[1:]
Per_Solar_Managing_authority.index= labels_of_col1[1:]
Per_Solar_Managing_authority.columns.names= [labels_of_col[0]]
Per_Solar_Managing_authority.index.names= [labels_of_col1[0]]
Per_Solar_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q207_1'])
Per_Functional_on_day_of_survey_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functional_on_day_of_survey_Managing_authority[0]
del Per_Functional_on_day_of_survey_Managing_authority[8]
del Per_Functional_on_day_of_survey_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Functional on day of survey']
Per_Functional_on_day_of_survey_Managing_authority.columns= labels_of_col[1:]
Per_Functional_on_day_of_survey_Managing_authority.index= labels_of_col1[1:]
Per_Functional_on_day_of_survey_Managing_authority.columns.names= [labels_of_col[0]]
Per_Functional_on_day_of_survey_Managing_authority.index.names= [labels_of_col1[0]]
Per_Functional_on_day_of_survey_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q208_1'])
Per_Comes_on_automatically_when_needed_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Managing_authority[0]
del Per_Comes_on_automatically_when_needed_Managing_authority[8]
del Per_Comes_on_automatically_when_needed_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Comes on automatically when needed']
Per_Comes_on_automatically_when_needed_Managing_authority.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Managing_authority.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Managing_authority.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Managing_authority.index.names= [labels_of_col1[0]]
Per_Comes_on_automatically_when_needed_Managing_authority
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4=(Per_Has_a_source_of_electricity_Managing_authority, Per_Has_electricity_from_the_grid_Managing_authority, Per_Generator_fueloperated_Managing_authority,Per_Generator_battery_operated_Managing_authority,Per_Solar_Managing_authority,Per_Functional_on_day_of_survey_Managing_authority,Per_Comes_on_automatically_when_needed_Managing_authority)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Managing_Authority=pd.concat(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4, axis=1, sort=False)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Managing_Authority

,Has a source of electricity,Has a source of electricity,Generator fuel operated,Generator fuel operated,Solar,Functional on day of survey,Comes on automatically when needed
Managing_authority,,,,,,,
Public/government,88.0,62.0,35.0,2.0,32.0,30.0,5.0
Private-for-profit,100.0,98.0,95.0,8.0,4.0,96.0,52.0
Private-not-for-profit,95.0,90.0,80.0,10.0,27.0,80.0,41.0

In [552]:
my_tab = pd.crosstab(data['Q009'], data['elecsource']!=0)
Per_Has_a_source_of_electricity_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_a_source_of_electricity_Location[0]
#del Per_Has_a_source_of_electricity_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Has a source of electricity']
Per_Has_a_source_of_electricity_Location.columns= labels_of_col[1:]
Per_Has_a_source_of_electricity_Location.index= labels_of_col1[1:]
Per_Has_a_source_of_electricity_Location.columns.names= [labels_of_col[0]]
Per_Has_a_source_of_electricity_Location.index.names= [labels_of_col1[0]]
Per_Has_a_source_of_electricity_Location
my_tab = pd.crosstab(data['Q009'], data['Q203_1'])
Per_Has_electricity_from_the_grid_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Has_electricity_from_the_grid_Location[0]
#del Per_Has_electricity_from_the_grid_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Has a source of electricity']
Per_Has_electricity_from_the_grid_Location.columns= labels_of_col[1:]
Per_Has_electricity_from_the_grid_Location.index= labels_of_col1[1:]
Per_Has_electricity_from_the_grid_Location.columns.names= [labels_of_col[0]]
Per_Has_electricity_from_the_grid_Location.index.names= [labels_of_col1[0]]
Per_Has_electricity_from_the_grid_Location
my_tab = pd.crosstab(data['Q009'], data['Q206A_1'])
Per_Generator_fueloperated_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_fueloperated_Location[0]
del Per_Generator_fueloperated_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Generator fuel operated']
Per_Generator_fueloperated_Location.columns= labels_of_col[1:]
Per_Generator_fueloperated_Location.index= labels_of_col1[1:]
Per_Generator_fueloperated_Location.columns.names= [labels_of_col[0]]
Per_Generator_fueloperated_Location.index.names= [labels_of_col1[0]]
Per_Generator_fueloperated_Location
my_tab = pd.crosstab(data['Q009'], data['Q206B_1'])
Per_Generator_battery_operated_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Generator_battery_operated_Location[0]
del Per_Generator_battery_operated_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Generator fuel operated']
Per_Generator_battery_operated_Location.columns= labels_of_col[1:]
Per_Generator_battery_operated_Location.index= labels_of_col1[1:]
Per_Generator_battery_operated_Location.columns.names= [labels_of_col[0]]
Per_Generator_battery_operated_Location.index.names= [labels_of_col1[0]]
Per_Generator_battery_operated_Location
my_tab = pd.crosstab(data['Q009'], data['Q206C_1'])
Per_Solar_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Solar_Location[0]
del Per_Solar_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Solar']
Per_Solar_Location.columns= labels_of_col[1:]
Per_Solar_Location.index= labels_of_col1[1:]
Per_Solar_Location.columns.names= [labels_of_col[0]]
Per_Solar_Location.index.names= [labels_of_col1[0]]
Per_Solar_Location
my_tab = pd.crosstab(data['Q009'], data['Q207_1'])
Per_Functional_on_day_of_survey_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Functional_on_day_of_survey_Location[0]
del Per_Functional_on_day_of_survey_Location[8]
del Per_Functional_on_day_of_survey_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Functional on day of survey']
Per_Functional_on_day_of_survey_Location.columns= labels_of_col[1:]
Per_Functional_on_day_of_survey_Location.index= labels_of_col1[1:]
Per_Functional_on_day_of_survey_Location.columns.names= [labels_of_col[0]]
Per_Functional_on_day_of_survey_Location.index.names= [labels_of_col1[0]]
Per_Functional_on_day_of_survey_Location
my_tab = pd.crosstab(data['Q009'], data['Q208_1'])
Per_Comes_on_automatically_when_needed_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Location[0]
del Per_Comes_on_automatically_when_needed_Location[8]
del Per_Comes_on_automatically_when_needed_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Comes on automatically when needed']
Per_Comes_on_automatically_when_needed_Location.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Location.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Location.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Location.index.names= [labels_of_col1[0]]
Per_Comes_on_automatically_when_needed_Location
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4=(Per_Has_a_source_of_electricity_Location, Per_Has_electricity_from_the_grid_Location, Per_Generator_fueloperated_Location,Per_Generator_battery_operated_Location,Per_Solar_Location,Per_Functional_on_day_of_survey_Location,Per_Comes_on_automatically_when_needed_Location)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Location1=pd.concat(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_4, axis=1, sort=False)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Location1

,Has a source of electricity,Has a source of electricity,Generator fuel operated,Generator fuel operated,Solar,Functional on day of survey,Comes on automatically when needed
Location,,,,,,,
Urban,97.0,88.0,58.0,3.0,19.0,51.0,15.0
Rural,82.0,46.0,24.0,1.0,39.0,20.0,1.0

In [553]:
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Location_1=(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Region, Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Facility,Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Managing_Authority,Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Location1)
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator=pd.concat(Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator_Location_1, keys=['Regional', 'Facility type','Managing Authority','Location'])
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator

                                            Has a source of electricity  \
Regional           Tigray                                          96.0
                   Afar                                            88.0
                   Amhara                                          87.0
                   Oromia                                          87.0
                   Somali                                          84.0
                   Benishangul-Gumuz                               98.0
                   SNNP                                            87.0
                   Gambella                                        93.0
                   Harari                                         100.0
                   Addis Ababa                                    100.0
                   Dire Dawa                                      100.0
                   National                                        88.0
Facility type      Referral/specialized                           100.0
                   General hospitals                              100.0
                   Primary hospitals                               99.0
                   MCH specialty centres                          100.0
                   Health centres                                  87.0
                   MCH specialty clinics                          100.0
                   Higher clinics                                 100.0
Managing Authority Public/government                               88.0
                   Private-for-profit                             100.0
                   Private-not-for-profit                          95.0
Location           Urban                                           97.0
                   Rural                                           82.0

                                            Has a source of electricity  \
Regional           Tigray                                          81.0
                   Afar                                            60.0
                   Amhara                                          61.0
                   Oromia                                          61.0
                   Somali                                          37.0
                   Benishangul-Gumuz                               60.0
                   SNNP                                            62.0
                   Gambella                                        44.0
                   Harari                                         100.0
                   Addis Ababa                                    100.0
                   Dire Dawa                                       76.0
                   National                                        63.0
Facility type      Referral/specialized                           100.0
                   General hospitals                               98.0
                   Primary hospitals                               94.0
                   MCH specialty centres                          100.0
                   Health centres                                  60.0
                   MCH specialty clinics                          100.0
                   Higher clinics                                  92.0
Managing Authority Public/government                               62.0
                   Private-for-profit                              98.0
                   Private-not-for-profit                          90.0
Location           Urban                                           88.0
                   Rural                                           46.0

                                            Generator fuel operated  \
Regional           Tigray                                      19.0
                   Afar                                        21.0
                   Amhara                                      46.0
                   Oromia                                      33.0
                   Somali                                      47.0
                   Benishangul-Gumuz                           65.0
                   SNNP                                        29.0
                   Gambella                                    22.0
                   Harari                                      73.0
                   Addis Ababa                                 83.0
                   Dire Dawa                                   86.0
                   National                                    37.0
Facility type      Referral/specialized                       100.0
                   General hospitals                           95.0
                   Primary hospitals                           92.0
                   MCH specialty centres                      100.0
                   Health centres                              32.0
                   MCH specialty clinics                       88.0
                   Higher clinics                              85.0
Managing Authority Public/government                           35.0
                   Private-for-profit                          95.0
                   Private-not-for-profit                      80.0
Location           Urban                                       58.0
                   Rural                                       24.0

                                            Generator fuel operated  Solar  \
Regional           Tigray                                       1.0   30.0
                   Afar                                         0.0   43.0
                   Amhara                                       1.0   28.0
                   Oromia                                       1.0   30.0
                   Somali                                       9.0   55.0
                   Benishangul-Gumuz                            2.0   23.0
                   SNNP                                         2.0   39.0
                   Gambella                                     0.0   70.0
                   Harari                                       0.0    7.0
                   Addis Ababa                                  7.0    5.0
                   Dire Dawa                                    5.0   24.0
                   National                                     2.0   31.0
Facility type      Referral/specialized                         7.0    7.0
                   General hospitals                           13.0    7.0
                   Primary hospitals                            4.0   10.0
                   MCH specialty centres                        4.0    9.0
                   Health centres                               1.0   34.0
                   MCH specialty clinics                        0.0   12.0
                   Higher clinics                              23.0   23.0
Managing Authority Public/government                            2.0   32.0
                   Private-for-profit                           8.0    4.0
                   Private-not-for-profit                      10.0   27.0
Location           Urban                                        3.0   19.0
                   Rural                                        1.0   39.0

                                            Functional on day of survey  \
Regional           Tigray                                          18.0
                   Afar                                            19.0
                   Amhara                                          39.0
                   Oromia                                          27.0
                   Somali                                          43.0
                   Benishangul-Gumuz                               60.0
                   SNNP                                            25.0
                   Gambella                                        22.0
                   Harari                                          53.0
                   Addis Ababa                                     79.0
                   Dire Dawa                                       76.0
                   National                                        32.0
Facility type      Referral/specialized                           100.0
                   General hospitals                               94.0
                   Primary hospitals                               90.0
                   MCH specialty centres                           96.0
                   Health centres                                  26.0
                   MCH specialty clinics                           88.0
                   Higher clinics                                  92.0
Managing Authority Public/government                               30.0
                   Private-for-profit                              96.0
                   Private-not-for-profit                          80.0
Location           Urban                                           51.0
                   Rural                                           20.0

                                            Comes on automatically when needed
Regional           Tigray                                                  3.0
                   Afar                                                    1.0
                   Amhara                                                  8.0
                   Oromia                                                  4.0
                   Somali                                                  4.0
                   Benishangul-Gumuz                                       5.0
                   SNNP                                                    4.0
                   Gambella                                                4.0
                   Harari                                                 27.0
                   Addis Ababa                                            46.0
                   Dire Dawa                                              14.0
                   National                                               69.0
Facility type      Referral/specialized                                   80.0
                   General hospitals                                      50.0
                   Primary hospitals                                      36.0
                   MCH specialty centres                                  65.0
                   Health centres                                          3.0
                   MCH specialty clinics                                  31.0
                   Higher clinics                                         31.0
Managing Authority Public/government                                       5.0
                   Private-for-profit                                     52.0
                   Private-not-for-profit                                 41.0
Location           Urban                                                  15.0
                   Rural                                                   1.0

In [554]:
Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_functionality_of_generator.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of electricity, water and toilets/Percent_of_facilities_with_any_source_of_electricity_and_among_those_percent_with_power_from_grid_backup_source_and_function_of_generator.csv")

# Percent distribution of facilities according to their primary source of water,

In [555]:
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_N=data.loc[(data['watersource'] == 0)]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_D=data.loc[(data['watersource'])]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_1=(len(  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_N)/len( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_D)*100)
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water=round(( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_1),0)
print( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water)

22.0

In [556]:
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_N=data.loc[(data['watersource'] == 1)]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_D=data.loc[(data['watersource'])]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_1=(len(  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_N)/len( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_D)*100)
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water=round(( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water_1),0)
print( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_No_water)

53.0

In [557]:
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_N=data.loc[(data['watersource'] == 2)]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_D=data.loc[(data['watersource'])]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_1=(len(  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_N)/len( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_D)*100)
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water=round(( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water_1),0)
print( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Piped_water)

10.0

In [558]:
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_N=data.loc[(data['watersource'] == 3)]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_D=data.loc[(data['watersource'])]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_1=(len(  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_N)/len( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_D)*100)
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump=round(( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump_1),0)
print( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Hand_pump )

5.0

In [559]:
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_N=data.loc[(data['watersource'] == 4)]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_D=data.loc[(data['watersource'])]
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_1=(len(  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_N)/len( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_D)*100)
 Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well=round(( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well_1),0)
print( Percent_distribution_of_facilities_according_to_their_primary_source_of_water_Well )

6.0

In [560]:
my_tab = pd.crosstab(data['Q005'], data['Q212_1'])
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'No water source','No shortage ','Shortage']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region

                   No water source  No shortage   Shortage
Region
Tigray                        18.0          47.0      35.0
Afar                          51.0          25.0      25.0
Amhara                        29.0          40.0      31.0
Oromia                        20.0          30.0      50.0
Somali                        24.0          48.0      28.0
Benishangul-Gumuz              5.0          67.0      28.0
SNNP                          20.0          43.0      37.0
Gambella                      22.0          41.0      37.0
Harari                        13.0          67.0      20.0
Addis Ababa                    0.0          68.0      32.0
Dire Dawa                     19.0          48.0      33.0

In [561]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of electricity, water and toilets/Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.csv")

# Percent distribution of facilities with a water source according to proximity of water source, and percent of facilities with shortage ≥24 hours in the past 3 months

In [562]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region = pd.crosstab(data['Q005'], data['Q209_1'])
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[8]
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q209_1'], data['Q209_1'])
b = 1
my_tab1 = ((my_tab1[1][1])/b)
cc= round((my_tab1),0)
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.loc['National'] = cc
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region.loc['National'] = my_tab1
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region

                   Number of facilities with a water source
Region
Tigray                                                209.0
Afar                                                   38.0
Amhara                                                621.0
Oromia                                               1121.0
Somali                                                122.0
Benishangul-Gumuz                                      41.0
SNNP                                                  613.0
Gambella                                               21.0
Harari                                                 13.0
Addis Ababa                                           151.0
Dire Dawa                                              17.0
National                                             2967.0

In [563]:
my_tab = pd.crosstab(data['Q005'], (data['Q211_1']))
del my_tab[-999]
del my_tab[6]
Percent_Within_500_meters_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Percent_Within_500_meters_Region[-999]
#del Percent_Within_500_meters_Region[6]
#del Percent_Within_500_meters_Region[8]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'On-site/ within compound','Within 500 meters','Beyond 500meters']
Percent_Within_500_meters_Region.columns= labels_of_col[1:]
Percent_Within_500_meters_Region.index= labels_of_col1[1:]
Percent_Within_500_meters_Region.columns.names= [labels_of_col[0]]
Percent_Within_500_meters_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q211_1'], data['Q211_1'])
b = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region['Number of facilities with a water source'][11]
my_tab11 = ((my_tab1[1][1])/b)*100
my_tab12 = ((my_tab1[2][2])/b)*100
my_tab13 = ((my_tab1[3][3])/b)*100
cc= round((my_tab11),0)
cc1= round((my_tab12),0)
cc2= round((my_tab13),0)
Percent_Within_500_meters_Region.loc['National'] = cc
Percent_Within_500_meters_Region.loc['National'][1] = cc1
Percent_Within_500_meters_Region.loc['National'][2] = cc2
Percent_Within_500_meters_Region

,On-site/ within compound,Within 500 meters,Beyond 500meters
Region,,,
Tigray,75.0,7.0,18.0
Afar,92.0,8.0,0.0
Amhara,75.0,9.0,16.0
Oromia,80.0,4.0,17.0
Somali,59.0,8.0,33.0
Benishangul-Gumuz,54.0,22.0,24.0
SNNP,70.0,10.0,20.0
Gambella,71.0,24.0,5.0
Harari,92.0,0.0,8.0
Addis Ababa,99.0,0.0,1.0
Dire Dawa,100.0,0.0,0.0
National,76.0,7.0,17.0

In [564]:
my_tab1 = pd.crosstab(data['Q005'], (data['Q211_1']))
Total = ((my_tab1/my_tab1)*100)
del Total[-999]
del Total[6]
del Total[3]
del Total[2]
#del Total[8]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Proximity_of_water_source_Total']
Total.columns= labels_of_col[1:]
Total.index= labels_of_col1[1:]
Total.columns.names= [labels_of_col[0]]
Total.index.names= [labels_of_col1[0]]
my_tab1 = 2967
my_tab11 = ((my_tab1/my_tab1)*100)
Total.loc['National'] = my_tab11
Total

                   Proximity_of_water_source_Total
Region
Tigray                                       100.0
Afar                                         100.0
Amhara                                       100.0
Oromia                                       100.0
Somali                                       100.0
Benishangul-Gumuz                            100.0
SNNP                                         100.0
Gambella                                     100.0
Harari                                       100.0
Addis Ababa                                  100.0
Dire Dawa                                    100.0
National                                     100.0

In [565]:
my_tab = pd.crosstab(data['Q005'], (data['Q212_1']))
Shortage_for_24_hours_in_past_3_months_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Shortage_for_24_hours_in_past_3_months_Region[0]
del Shortage_for_24_hours_in_past_3_months_Region[-999]
#del Shortage_for_24_hours_in_past_3_months_Region[9]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Shortage for ≥24 hours in past 3 months']
Shortage_for_24_hours_in_past_3_months_Region.columns= labels_of_col[1:]
Shortage_for_24_hours_in_past_3_months_Region.index= labels_of_col1[1:]
Shortage_for_24_hours_in_past_3_months_Region.columns.names= [labels_of_col[0]]
Shortage_for_24_hours_in_past_3_months_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q212_1'], data['Q212_1'])
b = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region['Number of facilities with a water source'][11]
my_tab11 = ((my_tab1[1][1])/b)*100
cc= round((my_tab11),0)
Shortage_for_24_hours_in_past_3_months_Region.loc['National'] = cc
Shortage_for_24_hours_in_past_3_months_Region

                   Shortage for ≥24 hours in past 3 months
Region
Tigray                                                35.0
Afar                                                  25.0
Amhara                                                31.0
Oromia                                                50.0
Somali                                                28.0
Benishangul-Gumuz                                     28.0
SNNP                                                  37.0
Gambella                                              37.0
Harari                                                20.0
Addis Ababa                                           32.0
Dire Dawa                                             33.0
National                                              50.0

In [566]:
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Region_4=(Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region, Proximity_of_water_source_Region,Total,Shortage_for_24_hours_in_past_3_months_Region)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Region=pd.concat(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Region_4, axis=1, sort=False)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Region

,Number of facilities with a water source,On-site/ within compound,Within 500 meters,Beyond 500meters,Proximity_of_water_source_Total,Shortage for ≥24 hours in past 3 months
Region,,,,,,
Tigray,209.0,75.0,7.0,18.0,100.0,35.0
Afar,38.0,92.0,8.0,0.0,100.0,25.0
Amhara,621.0,75.0,9.0,16.0,100.0,31.0
Oromia,1121.0,80.0,4.0,17.0,100.0,50.0
Somali,122.0,59.0,8.0,33.0,100.0,28.0
Benishangul-Gumuz,41.0,54.0,22.0,24.0,100.0,28.0
SNNP,613.0,70.0,10.0,20.0,100.0,37.0
Gambella,21.0,71.0,24.0,5.0,100.0,37.0
Harari,13.0,92.0,0.0,8.0,100.0,20.0
Addis Ababa,151.0,99.0,0.0,1.0,100.0,32.0
Dire Dawa,17.0,100.0,0.0,0.0,100.0,33.0
National,2967.0,76.0,7.0,17.0,100.0,50.0

In [567]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type = pd.crosstab(data['FT7'], data['Q209_1'])
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type[8]
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type
my_tab = pd.crosstab(data['FT7'], (data['Q211_1']))
del my_tab[-999]
del my_tab[6]
Proximity_of_water_source_Facility_type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Proximity_of_water_source_Facility_type[-999]
#del Proximity_of_water_source_Facility_type[6]
#del Proximity_of_water_source_Facility_type[8]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'On-site/ within compound','Within 500 meters','Beyond 500meters']
Proximity_of_water_source_Facility_type.columns= labels_of_col[1:]
Proximity_of_water_source_Facility_type.index= labels_of_col1[1:]
Proximity_of_water_source_Facility_type.columns.names= [labels_of_col[0]]
Proximity_of_water_source_Facility_type.index.names= [labels_of_col1[0]]
Proximity_of_water_source_Facility_type
my_tab1 = pd.crosstab(data['FT7'], (data['Q211_1']))
Total = ((my_tab1/my_tab1)*100)
del Total[-999]
del Total[6]
del Total[3]
del Total[2]
#del Total[8]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Proximity_of_water_source_Total']
Total.columns= labels_of_col[1:]
Total.index= labels_of_col1[1:]
Total.columns.names= [labels_of_col[0]]
Total.index.names= [labels_of_col1[0]]
Total
my_tab = pd.crosstab(data['FT7'], (data['Q212_1']))
Shortage_for_24_hours_in_past_3_months_Facility_type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Shortage_for_24_hours_in_past_3_months_Facility_type[0]
del Shortage_for_24_hours_in_past_3_months_Facility_type[-999]
#del Shortage_for_24_hours_in_past_3_months_Facility_type[9]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Shortage for ≥24 hours in past 3 months']
Shortage_for_24_hours_in_past_3_months_Facility_type.columns= labels_of_col[1:]
Shortage_for_24_hours_in_past_3_months_Facility_type.index= labels_of_col1[1:]
Shortage_for_24_hours_in_past_3_months_Facility_type.columns.names= [labels_of_col[0]]
Shortage_for_24_hours_in_past_3_months_Facility_type.index.names= [labels_of_col1[0]]
Shortage_for_24_hours_in_past_3_months_Facility_type
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Facility_type_4=(Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility_type, Proximity_of_water_source_Facility_type, Total,Shortage_for_24_hours_in_past_3_months_Facility_type)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Facility_type=pd.concat(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Facility_type_4, axis=1, sort=False)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Facility_type

,Number of facilities with a water source,On-site/ within compound,Within 500 meters,Beyond 500meters,Proximity_of_water_source_Total,Shortage for ≥24 hours in past 3 months
Facility,,,,,,
Referral/specialized,30,100.0,0.0,0.0,100.0,30.0
General hospitals,99,95.0,1.0,4.0,100.0,37.0
Primary hospitals,152,96.0,1.0,3.0,100.0,49.0
MCH specialty centres,23,100.0,0.0,0.0,100.0,26.0
Health centres,2635,74.0,8.0,18.0,100.0,39.0
MCH specialty clinics,16,100.0,0.0,0.0,100.0,25.0
Higher clinics,12,83.0,0.0,17.0,100.0,23.0

In [568]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority = pd.crosstab(data['MA3'], data['Q209_1'])
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority[8]
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority
my_tab = pd.crosstab(data['MA3'], (data['Q211_1']))
del my_tab[-999]
del my_tab[6]
Proximity_of_water_source_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Proximity_of_water_source_Managing_authority[-999]
#del Proximity_of_water_source_Managing_authority[6]
#del Proximity_of_water_source_Managing_authority[8]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'On-site/ within compound','Within 500 meters','Beyond 500meters']
Proximity_of_water_source_Managing_authority.columns= labels_of_col[1:]
Proximity_of_water_source_Managing_authority.index= labels_of_col1[1:]
Proximity_of_water_source_Managing_authority.columns.names= [labels_of_col[0]]
Proximity_of_water_source_Managing_authority.index.names= [labels_of_col1[0]]
Proximity_of_water_source_Managing_authority
my_tab1 = pd.crosstab(data['MA3'], (data['Q211_1']))
Total = ((my_tab1/my_tab1)*100)
del Total[-999]
del Total[6]
del Total[3]
del Total[2]
#del Total[8]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Proximity_of_water_source_Total']
Total.columns= labels_of_col[1:]
Total.index= labels_of_col1[1:]
Total.columns.names= [labels_of_col[0]]
Total.index.names= [labels_of_col1[0]]
Total
my_tab = pd.crosstab(data['MA3'], (data['Q212_1']))
Shortage_for_24_hours_in_past_3_months_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Shortage_for_24_hours_in_past_3_months_Managing_authority[0]
del Shortage_for_24_hours_in_past_3_months_Managing_authority[-999]
#del Shortage_for_24_hours_in_past_3_months_Managing_authority[9]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Shortage for ≥24 hours in past 3 months']
Shortage_for_24_hours_in_past_3_months_Managing_authority.columns= labels_of_col[1:]
Shortage_for_24_hours_in_past_3_months_Managing_authority.index= labels_of_col1[1:]
Shortage_for_24_hours_in_past_3_months_Managing_authority.columns.names= [labels_of_col[0]]
Shortage_for_24_hours_in_past_3_months_Managing_authority.index.names= [labels_of_col1[0]]
Shortage_for_24_hours_in_past_3_months_Managing_authority
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Managing_authority_4=(Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Managing_authority, Proximity_of_water_source_Managing_authority, Total,Shortage_for_24_hours_in_past_3_months_Managing_authority)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Managing_authority=pd.concat(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Managing_authority_4, axis=1, sort=False)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Managing_authority

,Number of facilities with a water source,On-site/ within compound,Within 500 meters,Beyond 500meters,Proximity_of_water_source_Total,Shortage for ≥24 hours in past 3 months
Managing_authority,,,,,,
Public/government,2830,76.0,7.0,17.0,100.0,40.0
Private-for-profit,79,97.0,0.0,3.0,100.0,33.0
Private-not-for-profit,58,88.0,5.0,7.0,100.0,37.0

In [569]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location = pd.crosstab(data['Q009'], data['Q209_1'])
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location[8]
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location
my_tab = pd.crosstab(data['Q009'], (data['Q211_1']))
del my_tab[-999]
del my_tab[6]
Proximity_of_water_source_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Proximity_of_water_source_Location[-999]
#del Proximity_of_water_source_Location[6]
#del Proximity_of_water_source_Location[8]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'On-site/ within compound','Within 500 meters','Beyond 500meters']
Proximity_of_water_source_Location.columns= labels_of_col[1:]
Proximity_of_water_source_Location.index= labels_of_col1[1:]
Proximity_of_water_source_Location.columns.names= [labels_of_col[0]]
Proximity_of_water_source_Location.index.names= [labels_of_col1[0]]
Proximity_of_water_source_Location
my_tab1 = pd.crosstab(data['Q009'], (data['Q211_1']))
Total = ((my_tab1/my_tab1)*100)
del Total[-999]
del Total[6]
del Total[3]
del Total[2]
#del Total[8]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Proximity_of_water_source_Total']
Total.columns= labels_of_col[1:]
Total.index= labels_of_col1[1:]
Total.columns.names= [labels_of_col[0]]
Total.index.names= [labels_of_col1[0]]
Total
my_tab = pd.crosstab(data['Q009'], (data['Q212_1']))
Shortage_for_24_hours_in_past_3_months_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Shortage_for_24_hours_in_past_3_months_Location[0]
del Shortage_for_24_hours_in_past_3_months_Location[-999]
#del Shortage_for_24_hours_in_past_3_months_Location[9]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Shortage for ≥24 hours in past 3 months']
Shortage_for_24_hours_in_past_3_months_Location.columns= labels_of_col[1:]
Shortage_for_24_hours_in_past_3_months_Location.index= labels_of_col1[1:]
Shortage_for_24_hours_in_past_3_months_Location.columns.names= [labels_of_col[0]]
Shortage_for_24_hours_in_past_3_months_Location.index.names= [labels_of_col1[0]]
Shortage_for_24_hours_in_past_3_months_Location
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Location_4=(Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Location, Proximity_of_water_source_Location, Total,Shortage_for_24_hours_in_past_3_months_Location)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Location=pd.concat(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Location_4, axis=1, sort=False)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Location

,Number of facilities with a water source,On-site/ within compound,Within 500 meters,Beyond 500meters,Proximity_of_water_source_Total,Shortage for ≥24 hours in past 3 months
Location,,,,,,
Urban,1382,87.0,4.0,9.0,100.0,47.0
Rural,1585,67.0,9.0,24.0,100.0,34.0

In [570]:
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_1=(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Region,Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Facility_type,Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Managing_authority,Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_of_water_source_Location)
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity=pd.concat(Percent_distribution_of_facilities_with_a_water_source_according_to_proximity_1, keys=['Regional', 'Facility type','Managing Authority','Location'])
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity

                                            Number of facilities with a water source  \
Regional           Tigray                                                      209.0
                   Afar                                                         38.0
                   Amhara                                                      621.0
                   Oromia                                                     1121.0
                   Somali                                                      122.0
                   Benishangul-Gumuz                                            41.0
                   SNNP                                                        613.0
                   Gambella                                                     21.0
                   Harari                                                       13.0
                   Addis Ababa                                                 151.0
                   Dire Dawa                                                    17.0
                   National                                                   2967.0
Facility type      Referral/specialized                                         30.0
                   General hospitals                                            99.0
                   Primary hospitals                                           152.0
                   MCH specialty centres                                        23.0
                   Health centres                                             2635.0
                   MCH specialty clinics                                        16.0
                   Higher clinics                                               12.0
Managing Authority Public/government                                          2830.0
                   Private-for-profit                                           79.0
                   Private-not-for-profit                                       58.0
Location           Urban                                                      1382.0
                   Rural                                                      1585.0

                                            On-site/ within compound  \
Regional           Tigray                                       75.0
                   Afar                                         92.0
                   Amhara                                       75.0
                   Oromia                                       80.0
                   Somali                                       59.0
                   Benishangul-Gumuz                            54.0
                   SNNP                                         70.0
                   Gambella                                     71.0
                   Harari                                       92.0
                   Addis Ababa                                  99.0
                   Dire Dawa                                   100.0
                   National                                     76.0
Facility type      Referral/specialized                        100.0
                   General hospitals                            95.0
                   Primary hospitals                            96.0
                   MCH specialty centres                       100.0
                   Health centres                               74.0
                   MCH specialty clinics                       100.0
                   Higher clinics                               83.0
Managing Authority Public/government                            76.0
                   Private-for-profit                           97.0
                   Private-not-for-profit                       88.0
Location           Urban                                        87.0
                   Rural                                        67.0

                                            Within 500 meters  \
Regional           Tigray                                 7.0
                   Afar                                   8.0
                   Amhara                                 9.0
                   Oromia                                 4.0
                   Somali                                 8.0
                   Benishangul-Gumuz                     22.0
                   SNNP                                  10.0
                   Gambella                              24.0
                   Harari                                 0.0
                   Addis Ababa                            0.0
                   Dire Dawa                              0.0
                   National                               7.0
Facility type      Referral/specialized                   0.0
                   General hospitals                      1.0
                   Primary hospitals                      1.0
                   MCH specialty centres                  0.0
                   Health centres                         8.0
                   MCH specialty clinics                  0.0
                   Higher clinics                         0.0
Managing Authority Public/government                      7.0
                   Private-for-profit                     0.0
                   Private-not-for-profit                 5.0
Location           Urban                                  4.0
                   Rural                                  9.0

                                            Beyond 500meters  \
Regional           Tigray                               18.0
                   Afar                                  0.0
                   Amhara                               16.0
                   Oromia                               17.0
                   Somali                               33.0
                   Benishangul-Gumuz                    24.0
                   SNNP                                 20.0
                   Gambella                              5.0
                   Harari                                8.0
                   Addis Ababa                           1.0
                   Dire Dawa                             0.0
                   National                             17.0
Facility type      Referral/specialized                  0.0
                   General hospitals                     4.0
                   Primary hospitals                     3.0
                   MCH specialty centres                 0.0
                   Health centres                       18.0
                   MCH specialty clinics                 0.0
                   Higher clinics                       17.0
Managing Authority Public/government                    17.0
                   Private-for-profit                    3.0
                   Private-not-for-profit                7.0
Location           Urban                                 9.0
                   Rural                                24.0

                                            Proximity_of_water_source_Total  \
Regional           Tigray                                             100.0
                   Afar                                               100.0
                   Amhara                                             100.0
                   Oromia                                             100.0
                   Somali                                             100.0
                   Benishangul-Gumuz                                  100.0
                   SNNP                                               100.0
                   Gambella                                           100.0
                   Harari                                             100.0
                   Addis Ababa                                        100.0
                   Dire Dawa                                          100.0
                   National                                           100.0
Facility type      Referral/specialized                               100.0
                   General hospitals                                  100.0
                   Primary hospitals                                  100.0
                   MCH specialty centres                              100.0
                   Health centres                                     100.0
                   MCH specialty clinics                              100.0
                   Higher clinics                                     100.0
Managing Authority Public/government                                  100.0
                   Private-for-profit                                 100.0
                   Private-not-for-profit                             100.0
Location           Urban                                              100.0
                   Rural                                              100.0

                                            Shortage for ≥24 hours in past 3 months
Regional           Tigray                                                      35.0
                   Afar                                                        25.0
                   Amhara                                                      31.0
                   Oromia                                                      50.0
                   Somali                                                      28.0
                   Benishangul-Gumuz                                           28.0
                   SNNP                                                        37.0
                   Gambella                                                    37.0
                   Harari                                                      20.0
                   Addis Ababa                                                 32.0
                   Dire Dawa                                                   33.0
                   National                                                    50.0
Facility type      Referral/specialized                                        30.0
                   General hospitals                                           37.0
                   Primary hospitals                                           49.0
                   MCH specialty centres                                       26.0
                   Health centres                                              39.0
                   MCH specialty clinics                                       25.0
                   Higher clinics                                              23.0
Managing Authority Public/government                                           40.0
                   Private-for-profit                                          33.0
                   Private-not-for-profit                                      37.0
Location           Urban                                                       47.0
                   Rural                                                       34.0

In [571]:
Percent_distribution_of_facilities_with_a_water_source_according_to_proximity.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of electricity, water and toilets/Percent distribution of facilities with a water source according to proximity of water source, and percent of facilities with shortage ≥24 hours in the past 3 months.csv")

# Availability of modes of communication

In [572]:
my_tab = pd.crosstab(data['Q005'], data['anycom'])
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[0]
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[8]
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Percent of facilities with at least 1 mode of functional communication on-site']
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.columns= labels_of_col[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.index= labels_of_col1[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.columns.names= [labels_of_col[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.index.names= [labels_of_col1[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region

                   Percent of facilities with at least 1 mode of functional communication on-site
Region
Tigray                                                          34.0
Afar                                                            19.0
Amhara                                                          36.0
Oromia                                                          40.0
Somali                                                          19.0
Benishangul-Gumuz                                               35.0
SNNP                                                            22.0
Gambella                                                         7.0
Harari                                                          40.0
Addis Ababa                                                     97.0
Dire Dawa                                                       57.0

In [573]:
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of modes of communication/Percent of facilities with at least 1 mode of functional communication_by_Region.csv")

In [574]:
my_tab = pd.crosstab(data['Q005'], data['Q407_11'])
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[0]
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[8]
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'No cell phone signal','Very dependable signal','Somewhat dependable signal','Not very dependable signal']
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.columns= labels_of_col[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.index= labels_of_col1[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.columns.names= [labels_of_col[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q407_11'], data['Q407_11'])
b = len(data.loc[((data['Q005']))])
my_tab11 = ((my_tab1[0][0])/b)*100
my_tab12 = ((my_tab1[1][1])/b)*100
my_tab13 = ((my_tab1[2][2])/b)*100
my_tab14 = ((my_tab1[3][3])/b)*100
cc1= round((my_tab11),0)
cc2= round((my_tab12),0)
cc3= round((my_tab13),0)
cc4= round((my_tab14),0)
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.loc['National']= cc1
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.loc['National'][1] = cc2
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.loc['National'][2] = cc3
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region.loc['National'][3] = cc4
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal
Region,,,,
Tigray,3.0,46.0,40.0,11.0
Afar,48.0,19.0,27.0,5.0
Amhara,7.0,36.0,37.0,20.0
Oromia,12.0,36.0,34.0,19.0
Somali,27.0,53.0,14.0,6.0
Benishangul-Gumuz,33.0,40.0,23.0,5.0
SNNP,4.0,26.0,41.0,29.0
Gambella,30.0,30.0,37.0,4.0
Harari,13.0,73.0,13.0,0.0
Addis Ababa,5.0,45.0,19.0,31.0
Dire Dawa,5.0,76.0,14.0,5.0
National,10.0,36.0,35.0,20.0

In [575]:
my_tab = pd.crosstab(data['Q005'], (data['Q404_11']))
per_Staff_have_their_own_cell_phone_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_have_their_own_cell_phone_Region[0]
#del  per_Staff_have_their_own_cell_phone_Region[8]
del  per_Staff_have_their_own_cell_phone_Region[-999]
#del  per_Staff_have_their_own_cell_phone_Region[2]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Staff have their own cell phone']
per_Staff_have_their_own_cell_phone_Region.columns= labels_of_col[1:]
per_Staff_have_their_own_cell_phone_Region.index= labels_of_col1[1:]
per_Staff_have_their_own_cell_phone_Region.columns.names= [labels_of_col[0]]
per_Staff_have_their_own_cell_phone_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q404_11'], data['Q404_11'])
b = len(data.loc[((data['Q404_11']!=1))])
my_tab11 = ((my_tab1[0][0])/b)*100
cc1= round((my_tab11),0)
per_Staff_have_their_own_cell_phone_Region.loc['National']= cc1
per_Staff_have_their_own_cell_phone_Region

                   Staff have their own cell phone
Region
Tigray                                        97.0
Afar                                          40.0
Amhara                                        94.0
Oromia                                        90.0
Somali                                        91.0
Benishangul-Gumuz                             84.0
SNNP                                          97.0
Gambella                                      96.0
Harari                                        47.0
Addis Ababa                                   88.0
Dire Dawa                                     67.0
National                                      98.0

In [576]:
my_tab = pd.crosstab(data['Q005'], (data['Q408_11']))
per_Staff_use_their_personal_phone_for_workrelated_calls_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Region[0]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Region[8]
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Region[-999]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Region[2]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Staff_use_their_personal_phone_for_workrelated_calls_Region.columns= labels_of_col[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Region.index= labels_of_col1[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Region.columns.names= [labels_of_col[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q408_11'], data['Q408_11'])
b = len(data.loc[((data['Q005']))])
my_tab11 = ((my_tab1[0][0])/b)*100
cc2= round((my_tab11),0)
per_Staff_use_their_personal_phone_for_workrelated_calls_Region.loc['National']= cc2
per_Staff_use_their_personal_phone_for_workrelated_calls_Region

                   Staff use their personal phone for workrelated calls
Region
Tigray                                                          95.0
Afar                                                            48.0
Amhara                                                          81.0
Oromia                                                          82.0
Somali                                                          64.0
Benishangul-Gumuz                                               60.0
SNNP                                                            93.0
Gambella                                                        67.0
Harari                                                          40.0
Addis Ababa                                                     73.0
Dire Dawa                                                       62.0
National                                                         7.0

In [577]:
my_tab = pd.crosstab(data['Q005'], (data['Q409_11']))
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region[0]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region[8]
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region[-999]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region[2]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region.columns= labels_of_col[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region.index= labels_of_col1[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region.columns.names= [labels_of_col[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q409_11'], data['Q409_11'])
b = len(data.loc[((data['Q005']))])
my_tab11 = ((my_tab1[0][0])/b)*100
cc2= round((my_tab11),0)
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region.loc['National']= cc2
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region

                   Staff use their personal phone for workrelated calls
Region
Tigray                                                           8.0
Afar                                                             9.0
Amhara                                                           3.0
Oromia                                                           8.0
Somali                                                           9.0
Benishangul-Gumuz                                                7.0
SNNP                                                             7.0
Gambella                                                         4.0
Harari                                                           0.0
Addis Ababa                                                     11.0
Dire Dawa                                                        5.0
National                                                        76.0

In [578]:
Per_Among_facilities_with_cell_phone_signal_4=(per_Staff_have_their_own_cell_phone_Region,per_Staff_use_their_personal_phone_for_workrelated_calls_Region,per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Region)
Per_Among_facilities_with_cell_phone_signal=pd.concat(Per_Among_facilities_with_cell_phone_signal_4, axis=1, sort=False)
Per_Among_facilities_with_cell_phone_signal

,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Region,,,
Tigray,97.0,95.0,8.0
Afar,40.0,48.0,9.0
Amhara,94.0,81.0,3.0
Oromia,90.0,82.0,8.0
Somali,91.0,64.0,9.0
Benishangul-Gumuz,84.0,60.0,7.0
SNNP,97.0,93.0,7.0
Gambella,96.0,67.0,4.0
Harari,47.0,40.0,0.0
Addis Ababa,88.0,73.0,11.0
Dire Dawa,67.0,62.0,5.0
National,98.0,7.0,76.0

In [579]:
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Region_4=(Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Region,Per_Among_facilities_with_cell_phone_signal)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Region=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Region_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Region

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Region,,,,,,,
Tigray,3.0,46.0,40.0,11.0,97.0,95.0,8.0
Afar,48.0,19.0,27.0,5.0,40.0,48.0,9.0
Amhara,7.0,36.0,37.0,20.0,94.0,81.0,3.0
Oromia,12.0,36.0,34.0,19.0,90.0,82.0,8.0
Somali,27.0,53.0,14.0,6.0,91.0,64.0,9.0
Benishangul-Gumuz,33.0,40.0,23.0,5.0,84.0,60.0,7.0
SNNP,4.0,26.0,41.0,29.0,97.0,93.0,7.0
Gambella,30.0,30.0,37.0,4.0,96.0,67.0,4.0
Harari,13.0,73.0,13.0,0.0,47.0,40.0,0.0
Addis Ababa,5.0,45.0,19.0,31.0,88.0,73.0,11.0
Dire Dawa,5.0,76.0,14.0,5.0,67.0,62.0,5.0
National,10.0,36.0,35.0,20.0,98.0,7.0,76.0

In [580]:
my_tab = pd.crosstab(data['FT7'], data['Q407_11'])
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[0]
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[8]
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'No cell phone signal','Very dependable signal','Somewhat dependable signal','Not very dependable signal']
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns= labels_of_col[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index= labels_of_col1[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns.names= [labels_of_col[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index.names= [labels_of_col1[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal
Facility,,,,
Referral/specialized,0.0,37.0,30.0,33.0
General hospitals,7.0,44.0,27.0,22.0
Primary hospitals,6.0,35.0,31.0,28.0
MCH specialty centres,9.0,39.0,30.0,22.0
Health centres,10.0,35.0,35.0,19.0
MCH specialty clinics,0.0,25.0,50.0,25.0
Higher clinics,8.0,46.0,8.0,38.0

In [581]:
my_tab = pd.crosstab(data['FT7'], (data['Q404_11']))
per_Staff_have_their_own_cell_phone_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_have_their_own_cell_phone_Facility[0]
#del  per_Staff_have_their_own_cell_phone_Facility[8]
del  per_Staff_have_their_own_cell_phone_Facility[-999]
#del  per_Staff_have_their_own_cell_phone_Facility[2]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Staff have their own cell phone']
per_Staff_have_their_own_cell_phone_Facility.columns= labels_of_col[1:]
per_Staff_have_their_own_cell_phone_Facility.index= labels_of_col1[1:]
per_Staff_have_their_own_cell_phone_Facility.columns.names= [labels_of_col[0]]
per_Staff_have_their_own_cell_phone_Facility.index.names= [labels_of_col1[0]]
per_Staff_have_their_own_cell_phone_Facility
my_tab = pd.crosstab(data['FT7'], (data['Q408_11']))
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[0]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[8]
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[-999]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[2]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns= labels_of_col[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index= labels_of_col1[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns.names= [labels_of_col[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index.names= [labels_of_col1[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility
my_tab = pd.crosstab(data['FT7'], (data['Q409_11']))
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[0]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[8]
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[-999]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[2]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns= labels_of_col[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index= labels_of_col1[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns.names= [labels_of_col[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index.names= [labels_of_col1[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility_4=(per_Staff_have_their_own_cell_phone_Facility,per_Staff_use_their_personal_phone_for_workrelated_calls_Facility,per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility

,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Facility,,,
Referral/specialized,77.0,90.0,17.0
General hospitals,81.0,78.0,14.0
Primary hospitals,90.0,88.0,8.0
MCH specialty centres,78.0,74.0,22.0
Health centres,92.0,83.0,6.0
MCH specialty clinics,88.0,69.0,12.0
Higher clinics,77.0,85.0,8.0

In [582]:
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility_4=(Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Facility,,,,,,,
Referral/specialized,0.0,37.0,30.0,33.0,77.0,90.0,17.0
General hospitals,7.0,44.0,27.0,22.0,81.0,78.0,14.0
Primary hospitals,6.0,35.0,31.0,28.0,90.0,88.0,8.0
MCH specialty centres,9.0,39.0,30.0,22.0,78.0,74.0,22.0
Health centres,10.0,35.0,35.0,19.0,92.0,83.0,6.0
MCH specialty clinics,0.0,25.0,50.0,25.0,88.0,69.0,12.0
Higher clinics,8.0,46.0,8.0,38.0,77.0,85.0,8.0

In [583]:
my_tab = pd.crosstab(data['MA3'], data['Q407_11'])
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[0]
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[8]
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'No cell phone signal','Very dependable signal','Somewhat dependable signal','Not very dependable signal']
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns= labels_of_col[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index= labels_of_col1[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns.names= [labels_of_col[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index.names= [labels_of_col1[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal
Managing_authority,,,,
Public/government,10.0,36.0,35.0,19.0
Private-for-profit,7.0,41.0,25.0,27.0
Private-not-for-profit,7.0,29.0,29.0,36.0

In [584]:
my_tab = pd.crosstab(data['MA3'], (data['Q404_11']))
per_Staff_have_their_own_cell_phone_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_have_their_own_cell_phone_Facility[0]
#del  per_Staff_have_their_own_cell_phone_Facility[8]
del  per_Staff_have_their_own_cell_phone_Facility[-999]
#del  per_Staff_have_their_own_cell_phone_Facility[2]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Staff have their own cell phone']
per_Staff_have_their_own_cell_phone_Facility.columns= labels_of_col[1:]
per_Staff_have_their_own_cell_phone_Facility.index= labels_of_col1[1:]
per_Staff_have_their_own_cell_phone_Facility.columns.names= [labels_of_col[0]]
per_Staff_have_their_own_cell_phone_Facility.index.names= [labels_of_col1[0]]
per_Staff_have_their_own_cell_phone_Facility
my_tab = pd.crosstab(data['MA3'], (data['Q408_11']))
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[0]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[8]
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[-999]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[2]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns= labels_of_col[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index= labels_of_col1[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns.names= [labels_of_col[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index.names= [labels_of_col1[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility
my_tab = pd.crosstab(data['MA3'], (data['Q409_11']))
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[0]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[8]
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[-999]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[2]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns= labels_of_col[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index= labels_of_col1[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns.names= [labels_of_col[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index.names= [labels_of_col1[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority_4=(per_Staff_have_their_own_cell_phone_Facility,per_Staff_use_their_personal_phone_for_workrelated_calls_Facility,per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority

,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Managing_authority,,,
Public/government,92.0,83.0,6.0
Private-for-profit,77.0,67.0,13.0
Private-not-for-profit,90.0,83.0,17.0

In [585]:
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority_4=(Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Managing_authority,,,,,,,
Public/government,10.0,36.0,35.0,19.0,92.0,83.0,6.0
Private-for-profit,7.0,41.0,25.0,27.0,77.0,67.0,13.0
Private-not-for-profit,7.0,29.0,29.0,36.0,90.0,83.0,17.0

In [586]:
my_tab = pd.crosstab(data['Q009'], data['Q407_11'])
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[0]
#del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[8]
del  Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'No cell phone signal','Very dependable signal','Somewhat dependable signal','Not very dependable signal']
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns= labels_of_col[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index= labels_of_col1[1:]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.columns.names= [labels_of_col[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility.index.names= [labels_of_col1[0]]
Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal
Location,,,,
Urban,6.0,35.0,34.0,24.0
Rural,12.0,36.0,35.0,17.0

In [587]:
my_tab = pd.crosstab(data['Q009'], (data['Q404_11']))
per_Staff_have_their_own_cell_phone_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_have_their_own_cell_phone_Facility[0]
#del  per_Staff_have_their_own_cell_phone_Facility[8]
del  per_Staff_have_their_own_cell_phone_Facility[-999]
#del  per_Staff_have_their_own_cell_phone_Facility[2]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Staff have their own cell phone']
per_Staff_have_their_own_cell_phone_Facility.columns= labels_of_col[1:]
per_Staff_have_their_own_cell_phone_Facility.index= labels_of_col1[1:]
per_Staff_have_their_own_cell_phone_Facility.columns.names= [labels_of_col[0]]
per_Staff_have_their_own_cell_phone_Facility.index.names= [labels_of_col1[0]]
per_Staff_have_their_own_cell_phone_Facility
my_tab = pd.crosstab(data['Q009'], (data['Q408_11']))
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[0]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[8]
del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[-999]
#del  per_Staff_use_their_personal_phone_for_workrelated_calls_Facility[2]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns= labels_of_col[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index= labels_of_col1[1:]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.columns.names= [labels_of_col[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility.index.names= [labels_of_col1[0]]
per_Staff_use_their_personal_phone_for_workrelated_calls_Facility
my_tab = pd.crosstab(data['Q009'], (data['Q409_11']))
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[0]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[8]
del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[-999]
#del  per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility[2]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Staff use their personal phone for workrelated calls']
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns= labels_of_col[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index= labels_of_col1[1:]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.columns.names= [labels_of_col[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility.index.names= [labels_of_col1[0]]
per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location_4=(per_Staff_have_their_own_cell_phone_Facility,per_Staff_use_their_personal_phone_for_workrelated_calls_Facility,per_Facility_has_policy_to_reimburse_staff_for_use_of_air_time_for_work_Facility)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location

,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Location,,,
Urban,91.0,85.0,8.0
Rural,92.0,81.0,6.0

In [588]:
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location_4=(Per_of_facilities_with_at_least_1_mode_of_functional_communication_on_site_Facility,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location_4, axis=1, sort=False)
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location

,No cell phone signal,Very dependable signal,Somewhat dependable signal,Not very dependable signal,Staff have their own cell phone,Staff use their personal phone for workrelated calls,Staff use their personal phone for workrelated calls
Location,,,,,,,
Urban,6.0,35.0,34.0,24.0,91.0,85.0,8.0
Rural,12.0,36.0,35.0,17.0,92.0,81.0,6.0

In [589]:
Per_distribution_of_facilities_according_to_strength_of_cell_phone_signal_at_facility_and_among_facilities_with_a_signal_Location_1=(Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Region,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Facility,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Managing_authority,Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_at_facility_by_Location)
Per_distribution_of_facilities_according_to_strength_of_cell_phone_signal_at_facility_and_among_facilities_with_a_signal=pd.concat(Per_distribution_of_facilities_according_to_strength_of_cell_phone_signal_at_facility_and_among_facilities_with_a_signal_Location_1, keys=['Regional', 'Facility type','Managing Authority','Location'])
Per_distribution_of_facilities_according_to_strength_of_cell_phone_signal_at_facility_and_among_facilities_with_a_signal

                                            No cell phone signal  \
Regional           Tigray                                    3.0
                   Afar                                     48.0
                   Amhara                                    7.0
                   Oromia                                   12.0
                   Somali                                   27.0
                   Benishangul-Gumuz                        33.0
                   SNNP                                      4.0
                   Gambella                                 30.0
                   Harari                                   13.0
                   Addis Ababa                               5.0
                   Dire Dawa                                 5.0
                   National                                 10.0
Facility type      Referral/specialized                      0.0
                   General hospitals                         7.0
                   Primary hospitals                         6.0
                   MCH specialty centres                     9.0
                   Health centres                           10.0
                   MCH specialty clinics                     0.0
                   Higher clinics                            8.0
Managing Authority Public/government                        10.0
                   Private-for-profit                        7.0
                   Private-not-for-profit                    7.0
Location           Urban                                     6.0
                   Rural                                    12.0

                                            Very dependable signal  \
Regional           Tigray                                     46.0
                   Afar                                       19.0
                   Amhara                                     36.0
                   Oromia                                     36.0
                   Somali                                     53.0
                   Benishangul-Gumuz                          40.0
                   SNNP                                       26.0
                   Gambella                                   30.0
                   Harari                                     73.0
                   Addis Ababa                                45.0
                   Dire Dawa                                  76.0
                   National                                   36.0
Facility type      Referral/specialized                       37.0
                   General hospitals                          44.0
                   Primary hospitals                          35.0
                   MCH specialty centres                      39.0
                   Health centres                             35.0
                   MCH specialty clinics                      25.0
                   Higher clinics                             46.0
Managing Authority Public/government                          36.0
                   Private-for-profit                         41.0
                   Private-not-for-profit                     29.0
Location           Urban                                      35.0
                   Rural                                      36.0

                                            Somewhat dependable signal  \
Regional           Tigray                                         40.0
                   Afar                                           27.0
                   Amhara                                         37.0
                   Oromia                                         34.0
                   Somali                                         14.0
                   Benishangul-Gumuz                              23.0
                   SNNP                                           41.0
                   Gambella                                       37.0
                   Harari                                         13.0
                   Addis Ababa                                    19.0
                   Dire Dawa                                      14.0
                   National                                       35.0
Facility type      Referral/specialized                           30.0
                   General hospitals                              27.0
                   Primary hospitals                              31.0
                   MCH specialty centres                          30.0
                   Health centres                                 35.0
                   MCH specialty clinics                          50.0
                   Higher clinics                                  8.0
Managing Authority Public/government                              35.0
                   Private-for-profit                             25.0
                   Private-not-for-profit                         29.0
Location           Urban                                          34.0
                   Rural                                          35.0

                                            Not very dependable signal  \
Regional           Tigray                                         11.0
                   Afar                                            5.0
                   Amhara                                         20.0
                   Oromia                                         19.0
                   Somali                                          6.0
                   Benishangul-Gumuz                               5.0
                   SNNP                                           29.0
                   Gambella                                        4.0
                   Harari                                          0.0
                   Addis Ababa                                    31.0
                   Dire Dawa                                       5.0
                   National                                       20.0
Facility type      Referral/specialized                           33.0
                   General hospitals                              22.0
                   Primary hospitals                              28.0
                   MCH specialty centres                          22.0
                   Health centres                                 19.0
                   MCH specialty clinics                          25.0
                   Higher clinics                                 38.0
Managing Authority Public/government                              19.0
                   Private-for-profit                             27.0
                   Private-not-for-profit                         36.0
Location           Urban                                          24.0
                   Rural                                          17.0

                                            Staff have their own cell phone  \
Regional           Tigray                                              97.0
                   Afar                                                40.0
                   Amhara                                              94.0
                   Oromia                                              90.0
                   Somali                                              91.0
                   Benishangul-Gumuz                                   84.0
                   SNNP                                                97.0
                   Gambella                                            96.0
                   Harari                                              47.0
                   Addis Ababa                                         88.0
                   Dire Dawa                                           67.0
                   National                                            98.0
Facility type      Referral/specialized                                77.0
                   General hospitals                                   81.0
                   Primary hospitals                                   90.0
                   MCH specialty centres                               78.0
                   Health centres                                      92.0
                   MCH specialty clinics                               88.0
                   Higher clinics                                      77.0
Managing Authority Public/government                                   92.0
                   Private-for-profit                                  77.0
                   Private-not-for-profit                              90.0
Location           Urban                                               91.0
                   Rural                                               92.0

                                            Staff use their personal phone for workrelated calls  \
Regional           Tigray                                                                95.0
                   Afar                                                                  48.0
                   Amhara                                                                81.0
                   Oromia                                                                82.0
                   Somali                                                                64.0
                   Benishangul-Gumuz                                                     60.0
                   SNNP                                                                  93.0
                   Gambella                                                              67.0
                   Harari                                                                40.0
                   Addis Ababa                                                           73.0
                   Dire Dawa                                                             62.0
                   National                                                               7.0
Facility type      Referral/specialized                                                  90.0
                   General hospitals                                                     78.0
                   Primary hospitals                                                     88.0
                   MCH specialty centres                                                 74.0
                   Health centres                                                        83.0
                   MCH specialty clinics                                                 69.0
                   Higher clinics                                                        85.0
Managing Authority Public/government                                                     83.0
                   Private-for-profit                                                    67.0
                   Private-not-for-profit                                                83.0
Location           Urban                                                                 85.0
                   Rural                                                                 81.0

                                            Staff use their personal phone for workrelated calls
Regional           Tigray                                                                 8.0
                   Afar                                                                   9.0
                   Amhara                                                                 3.0
                   Oromia                                                                 8.0
                   Somali                                                                 9.0
                   Benishangul-Gumuz                                                      7.0
                   SNNP                                                                   7.0
                   Gambella                                                               4.0
                   Harari                                                                 0.0
                   Addis Ababa                                                           11.0
                   Dire Dawa                                                              5.0
                   National                                                              76.0
Facility type      Referral/specialized                                                  17.0
                   General hospitals                                                     14.0
                   Primary hospitals                                                      8.0
                   MCH specialty centres                                                 22.0
                   Health centres                                                         6.0
                   MCH specialty clinics                                                 12.0
                   Higher clinics                                                         8.0
Managing Authority Public/government                                                      6.0
                   Private-for-profit                                                    13.0
                   Private-not-for-profit                                                17.0
Location           Urban                                                                  8.0
                   Rural                                                                  6.0

In [590]:
Per_distribution_of_facilities_according_to_strength_of_cell_phone_signal_at_facility_and_among_facilities_with_a_signal.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of modes of communication/Percent distribution of facilities according to strength of cell phone signal.csv")

# Regulatory policies and practice on front line

In [922]:
my_tab = pd.crosstab(data['FT2'], data['Q116_3']!=0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Antibiotics']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics

                                 Antibiotics

Hospitals/MCH specialty centres        100.0
Health centres/clinics                 100.0

In [923]:
my_tab = pd.crosstab(data['FT2'], data['Q103_5']!=0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Uterotonics']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics

                                 Uterotonics

Hospitals/MCH specialty centres         95.0
Health centres/clinics                  93.0

In [925]:
my_tab = pd.crosstab(data['FT2'], data['Q118_3']!=0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Anticonvulsantts']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants

                                 Anticonvulsantts

Hospitals/MCH specialty centres              98.0
Health centres/clinics                       86.0

In [955]:
my_tab = pd.crosstab(data['FT2'], data['Q201F_6A'])
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC[0]
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Manual Removal Placenta']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta

                                 Manual Removal Placenta

Hospitals/MCH specialty centres                     79.0
Health centres/clinics                              65.0

In [1021]:
my_tab = pd.crosstab(data['FT2'], data['Q254A_3'])
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA[9]
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'MVA']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA

                                  MVA

Hospitals/MCH specialty centres  91.0
Health centres/clinics           55.0

In [1049]:
my_tab = pd.crosstab(data['FT2'], data['Q118D_5']==0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Dilatation and curettage (D&C) or Evacuation and Curettage (E&C)']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC

                                 Dilatation and curettage (D&C) or Evacuation and Curettage (E&C)

Hospitals/MCH specialty centres                                               49.0
Health centres/clinics                                                        62.0

In [1126]:
my_tab = pd.crosstab(data['FT2'], data['Q108D_5']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Medical abortion']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion

                                 Medical abortion

Hospitals/MCH specialty centres              44.0
Health centres/clinics                       87.0

In [1129]:
my_tab = pd.crosstab(data['FT2'], data['Q116K_9B_1']==0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Vacuume Extraction']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction

                                 Vacuume Extraction

Hospitals/MCH specialty centres                57.0
Health centres/clinics                         92.0

In [1146]:
my_tab = pd.crosstab(data['FT2'], data['Q252B_3']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Forceps']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps

                                 Forceps

Hospitals/MCH specialty centres     11.0
Health centres/clinics              83.0

In [1182]:
my_tab = pd.crosstab(data['FT2'], data['Q301_1_12']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Caesarean_Delivery']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery

                                 Caesarean_Delivery

Hospitals/MCH specialty centres                15.0
Health centres/clinics                         99.0

In [1231]:
my_tab = pd.crosstab(data['FT2'], data['Q301_1_13']==0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[9]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_D&C_or_E$C[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Blood_Transfusiony']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony

                                 Blood_Transfusiony

Hospitals/MCH specialty centres                78.0
Health centres/clinics                          1.0

In [1232]:
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmONC_signal_functions_4=(Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_antibiotics,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Uterotonics,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Anticonvulsants,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Manual_Removal_placenta,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_MVA,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_DC_or_EC,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Medical_abortion,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Vacuume_Extraction,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Forceps,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Caesarean_Delivery,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmONC_Blood_Transfusiony)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmONC_signal_functions=pd.concat( Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmONC_signal_functions_4, axis=1, sort=False)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmONC_signal_functions

,Antibiotics,Uterotonics,Anticonvulsantts,Manual Removal Placenta,MVA,Vacuume Extraction,Medical abortion,Forceps,Forceps,Caesarean_Delivery,Blood_Transfusiony
,,,,,,,,,,,
Hospitals/MCH specialty centres,100.0,98.0,79.0,91.0,49.0,57.0,44.0,11.0,85.0,78.0,78.0
Health centres/clinics,100.0,86.0,65.0,55.0,62.0,92.0,87.0,83.0,100.0,1.0,1.0

In [1233]:
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmONC_signal_functions.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of Human Resources/Percent of facilities with at least one health worker on staff who could perform each of the EmONC signal functions.csv")

In [1528]:
my_tab = pd.crosstab(data['FT2'], data['Q302_3']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Newborn resuscitation with bagand mask']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask

                                 Newborn resuscitation with bagand mask

Hospitals/MCH specialty centres                                   100.0
Health centres/clinics                                            100.0

In [1529]:
my_tab = pd.crosstab(data['FT2'], data['Q212_2_6']==0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Antenatal corticosteroids']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids

                                 Antenatal corticosteroids

Hospitals/MCH specialty centres                       69.0
Health centres/clinics                                81.0

In [1530]:
my_tab = pd.crosstab(data['FT2'], data['Q101_5']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Antibiotics_for_pPROM']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM

                                 Antibiotics_for_pPROM

Hospitals/MCH specialty centres                   96.0
Health centres/clinics                            79.0

In [1531]:
my_tab = pd.crosstab(data['FT2'], data['Q311A_6A']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Antibiotics for neonatal sepsis']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis

                                 Antibiotics for neonatal sepsis

Hospitals/MCH specialty centres                             82.0
Health centres/clinics                                      71.0

In [1532]:
#Not match with report
my_tab = pd.crosstab(data['FT2'], data['Q207G_3']!=0)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'KMC for small babies']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies

                                 KMC for small babies

Hospitals/MCH specialty centres                  62.0
Health centres/clinics                           46.0

In [1533]:
#Not match with report
my_tab = pd.crosstab(data['FT2'], data['Q305P_3']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'Safe administration of oxygen']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen

                                 Safe administration of oxygen

Hospitals/MCH specialty centres                           90.0
Health centres/clinics                                     9.0

In [1534]:
#Not match with report
my_tab = pd.crosstab(data['FT2'], data['Q220_5']==1)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids[0]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[1]
#del Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_ EmONC[-999]
labels_of_col1 =["","Hospitals/MCH specialty centres",'Health centres/clinics']
labels_of_col = ["",'IV fluids']
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids.columns= labels_of_col[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids.index= labels_of_col1[1:]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids

                                 IV fluids

Hospitals/MCH specialty centres       63.0
Health centres/clinics                 7.0

In [1537]:
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmNeC_signal_functions_4=(Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Newborn_resuscitation_with_bagand_mask,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antenatal_corticosteroids,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_pPROM,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Antibiotics_for_neonatal_sepsis,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_KMC_for_small_babies,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_Safe_administration_of_oxygen,Percent_of_facilities_with_at_least_one_health_worker_on_staff_by_EmNeC_IV_fluids)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmNeC_signal_functions=pd.concat( Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmNeC_signal_functions_4, axis=1, sort=False)
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmNeC_signal_functions

,Newborn resuscitation with bagand mask,Antenatal corticosteroids,Antibiotics_for_pPROM,Antibiotics for neonatal sepsis,KMC for small babies,Safe administration of oxygen,IV fluids
,,,,,,,
Hospitals/MCH specialty centres,100.0,69.0,96.0,82.0,62.0,90.0,63.0
Health centres/clinics,100.0,81.0,79.0,71.0,46.0,9.0,7.0

In [1538]:
Percent_of_facilities_with_at_least_one_health_worker_on_staff_who_could_perform_each_of_the_EmNeC_signal_functions.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of Human Resources/Percent of facilities with at least one health worker on staff who could perform each of the EmNeC signal functions.csv")

In [1647]:
fata = [['Tigray', 5151000], ['Afar', 1768000], ['Amhara', 20771000], ['Oromia', 34575000], ['Somali', 5599000], ['Benishangul_Gumuz', 1035000], ['SNNP', 18720000], ['Gambella', 422000], ['Harari', 238000], ['Addis Ababa', 3353000], ['Dire Dawa', 453000],['National', 92085000]]
df = pd.DataFrame(fata, columns = ['Region', 'Population'])

In [1684]:
fata1 = [[5151000], [1768000], [20771000], [34575000], [5599000], [1035000], [18720000], [422000], [238000], [3353000], [453000],[92085000]]
df = pd.DataFrame(fata1, columns = ['Population'])

In [1661]:
fata1 = [[5151000], [1768000], [20771000], [34575000], [5599000], [1035000], [18720000], [422000], [238000], [3353000], [453000],[92085000]]
df = pd.DataFrame(fata1, columns = ['Population'])
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa','National']
#labels_of_col = ["ddd",'Number of deliveries in facilities','']
#df.columns= labels_of_col[1:]
df.index= labels_of_col1[1:]
df.index.names= [labels_of_col1[0]]
df

                   Population
Region
Tigray                5151000
Afar                  1768000
Amhara               20771000
Oromia               34575000
Somali                5599000
Benishangul-Gumuz     1035000
SNNP                 18720000
Gambella               422000
Harari                 238000
Addis Ababa           3353000
Dire Dawa              453000
National             92085000

In [1662]:
dfsd = pd.DataFrame(data, columns = ['Q005', 'totdeliveries'])
sss=dfsd.groupby(['Q005']).sum()
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of deliveries in facilities']
sss.columns= labels_of_col[1:]
sss.index= labels_of_col1[1:]
sss.columns.names= [labels_of_col[0]]
sss.index.names= [labels_of_col1[0]]
my_tab1= data['totdeliveries'].sum()
sss.loc['National'] = my_tab1
sss

                   Number of deliveries in facilities
Region
Tigray                                         113425
Afar                                             7678
Amhara                                         386131
Oromia                                         844287
Somali                                          22036
Benishangul-Gumuz                               12288
SNNP                                           417697
Gambella                                         3383
Harari                                           7579
Addis Ababa                                    101401
Dire Dawa                                        8425
National                                      1924330

In [1663]:
dfsd1 = pd.DataFrame(data, columns = ['Q005', 'midwives_all'])
dfsd1['midwives_all']=np.where(dfsd1['midwives_all'] == -999,  0, dfsd1['midwives_all'])
ssss=dfsd1.groupby(['Q005']).sum()
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number_of_midwives_in_facilities']
ssss.columns= labels_of_col[1:]
ssss.index= labels_of_col1[1:]
ssss.columns.names= [labels_of_col[0]]
ssss.index.names= [labels_of_col1[0]]
my_tab1= data['midwives_all'].sum()
ssss.loc['National'] = my_tab1
ssss

                   Number_of_midwives_in_facilities
Region
Tigray                                          911
Afar                                            188
Amhara                                         2610
Oromia                                         3619
Somali                                          741
Benishangul-Gumuz                               213
SNNP                                           2327
Gambella                                         39
Harari                                           78
Addis Ababa                                    1345
Dire Dawa                                        82
National                                      12153

In [1670]:
Number_of_midwives_per_1000_institutional_deliveries_by_region_4=(df,sss,ssss)
Number_of_midwives_per_1000_institutional_deliveries_by_region=pd.concat(Number_of_midwives_per_1000_institutional_deliveries_by_region_4, axis=1, sort=False)
Number_of_midwives_per_1000_institutional_deliveries_by_region

,Population,Number of deliveries in facilities,Number_of_midwives_in_facilities
Region,,,
Tigray,5151000,113425,911
Afar,1768000,7678,188
Amhara,20771000,386131,2610
Oromia,34575000,844287,3619
Somali,5599000,22036,741
Benishangul-Gumuz,1035000,12288,213
SNNP,18720000,417697,2327
Gambella,422000,3383,39
Harari,238000,7579,78
Addis Ababa,3353000,101401,1345
Dire Dawa,453000,8425,82
National,92085000,1924330,12153

In [1673]:
Number_of_midwives_per_1000_institutional_deliveries_by_region["Number of midwives per 1,000 institutional deliveries"] = (Number_of_midwives_per_1000_institutional_deliveries_by_region["Number_of_midwives_in_facilities"]/Percent_distribution_offacilities_according_to_strength["Number of deliveries in facilities"])*1000
Number_of_midwives_per_1000_institutional_deliveries_by_region_1=round((Number_of_midwives_per_1000_institutional_deliveries_by_region),0)
Number_of_midwives_per_1000_institutional_deliveries_by_region_1

,Population,Number of deliveries in facilities,Number_of_midwives_in_facilities,"Number of midwives per 1,000 institutional deliveries"
Region,,,,
Tigray,5151000,113425,911,8.0
Afar,1768000,7678,188,24.0
Amhara,20771000,386131,2610,7.0
Oromia,34575000,844287,3619,4.0
Somali,5599000,22036,741,34.0
Benishangul-Gumuz,1035000,12288,213,17.0
SNNP,18720000,417697,2327,6.0
Gambella,422000,3383,39,12.0
Harari,238000,7579,78,10.0
Addis Ababa,3353000,101401,1345,13.0
Dire Dawa,453000,8425,82,10.0
National,92085000,1924330,12153,6.0

In [1683]:
Number_of_midwives_per_1000_institutional_deliveries_by_region["Number of midwives per 5,000 population"] = (Number_of_midwives_per_1000_institutional_deliveries_by_region["Number_of_midwives_in_facilities"]/Number_of_midwives_per_1000_institutional_deliveries_by_region["Population"])*5000
Number_of_midwives_per_5000_population_by_region_1=round((Number_of_midwives_per_1000_institutional_deliveries_by_region),2)
Number_of_midwives_per_5000_population_by_region_1

,Population,Number of deliveries in facilities,Number_of_midwives_in_facilities,"Number of midwives per 1,000 institutional deliveries","Number of midwives per 5,000 population"
Region,,,,,
Tigray,5151000,113425,911,8.03,0.88
Afar,1768000,7678,188,24.49,0.53
Amhara,20771000,386131,2610,6.76,0.63
Oromia,34575000,844287,3619,4.29,0.52
Somali,5599000,22036,741,33.63,0.66
Benishangul-Gumuz,1035000,12288,213,17.33,1.03
SNNP,18720000,417697,2327,5.57,0.62
Gambella,422000,3383,39,11.53,0.46
Harari,238000,7579,78,10.29,1.64
Addis Ababa,3353000,101401,1345,13.26,2.01
Dire Dawa,453000,8425,82,9.73,0.91
National,92085000,1924330,12153,6.32,0.66

In [1685]:
Number_of_midwives_per_5000_population_by_region_1.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of Human Resources/Number of midwives per 1,000 institutional deliveries and per 5,000 population.csv")

In [421]:
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']==0)
gggggggg=(Number_of_women_with_major_DOC_National1).sum()
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']!=-999)
gggggggg1=(Number_of_women_with_major_DOC_National1).sum()
gggggggg2=(gggggggg/gggggggg1)*100
gggggggg3= round((gggggggg2),0)
fata0 = ([["never received on-the-job training at MNH", gggggggg3]])
df = pd.DataFrame(fata0, columns = ['','Total'])
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']==1)
gggggggg=(Number_of_women_with_major_DOC_National1).sum()
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']!=-999)
gggggggg1=(Number_of_women_with_major_DOC_National1).sum()
gggggggg2=(gggggggg/gggggggg1)*100
gggggggg3= round((gggggggg2),0)
fata00 = ([["received on-the-job training at MNH In last 6 months", gggggggg3]])
df1 = pd.DataFrame(fata00, columns = ['','Total'])
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']==2)
gggggggg=(Number_of_women_with_major_DOC_National1).sum()
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']!=-999)
gggggggg1=(Number_of_women_with_major_DOC_National1).sum()
gggggggg2=(gggggggg/gggggggg1)*100
gggggggg3= round((gggggggg2),0)
fata000 = ([["received on-the-job training at MNH In last year", gggggggg3]])
df2 = pd.DataFrame(fata000, columns = ['','Total'])
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']==3)
gggggggg=(Number_of_women_with_major_DOC_National1).sum()
Number_of_women_with_major_DOC_National1 = (data['Q407_6A']!=-999)
gggggggg1=(Number_of_women_with_major_DOC_National1).sum()
gggggggg2=(gggggggg/gggggggg1)*100
gggggggg3= round((gggggggg2),0)
fata0000 = ([["received on-the-job training at MNH In last yearMore than a year ago", gggggggg3]])
df3 = pd.DataFrame(fata0000, columns = ["",'Total'])

In [579]:
Neve_received_on_the_job_training1=data.loc[(data['profqual_cat']==2) & (data['Q407_6A']==0)]
Neve_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==2)]
Neve_received_on_the_job_training_in_MNH_In_Midwives=(len(Neve_received_on_the_job_training1)/(len(Neve_received_on_the_job_training)))*100
Neve_received_on_the_job_training_in_MNH_In_Midwives_1=round((Neve_received_on_the_job_training_in_MNH_In_Midwives),0)
Neve_received_on_the_job_training_in_MNH_In_Midwives_1
fata1 = ([["never received on-the-job training at MNH", Neve_received_on_the_job_training_in_MNH_In_Midwives_1]])
df11 = pd.DataFrame(fata1, columns = ["",'Midwives'])
In_last_6_months_received_on_the_job_training1=data.loc[(data['profqual_cat']==2) & (data['Q407_6A']==1)]
In_last_6_months_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==2)]
In_last_6_months_received_on_the_job_training_in_MNH_In_Midwives=(len(In_last_6_months_received_on_the_job_training1)/(len(In_last_6_months_received_on_the_job_training)))*100
In_last_6_months_received_on_the_job_training_in_MNH_In_Midwives_1=round((In_last_6_months_received_on_the_job_training_in_MNH_In_Midwives),0)
In_last_6_months_received_on_the_job_training_in_MNH_In_Midwives_1
fata11 = ([["received on-the-job training at MNH In last 6 months", In_last_6_months_received_on_the_job_training_in_MNH_In_Midwives_1]])
df12 = pd.DataFrame(fata11, columns = ["",'Midwives'])
In_last_year_received_on_the_job_training1=data.loc[(data['profqual_cat']==2) & (data['Q407_6A']==2)]
In_last_year_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==2)]
In_last_year_received_on_the_job_training_in_MNH_In_Midwives=(len(In_last_year_received_on_the_job_training1)/(len(In_last_year_received_on_the_job_training)))*100
In_last_year_received_on_the_job_training_in_MNH_In_Midwives_1=round((In_last_year_received_on_the_job_training_in_MNH_In_Midwives),0)
In_last_year_received_on_the_job_training_in_MNH_In_Midwives_1
fata111 = ([["received on-the-job training at MNH In last year", In_last_year_received_on_the_job_training_in_MNH_In_Midwives_1]])
df13 = pd.DataFrame(fata111, columns = ["",'Midwives'])
More_than_year_ago_on_the_job_training1=data.loc[(data['profqual_cat']==2) & (data['Q407_6A']==3)]
More_than_year_ago_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==2)]
More_than_year_ago_on_the_job_training_in_MNH_In_Midwives=(len(More_than_year_ago_on_the_job_training1)/(len(More_than_year_ago_on_the_job_training)))*100
More_than_year_ago_on_the_job_training_in_MNH_In_Midwives_1=round((More_than_year_ago_on_the_job_training_in_MNH_In_Midwives),0)
More_than_year_ago_on_the_job_training_in_MNH_In_Midwives_1
fata1111 = ([["received on-the-job training at MNH In last yearMore than a year ago", More_than_year_ago_on_the_job_training_in_MNH_In_Midwives_1]])
df14 = pd.DataFrame(fata1111, columns = ["",'Midwives'])
Last_received_on_the_job_training_in_MNH_In_Midwives_4=(df11,df12,df13,df14)
Last_received_on_the_job_training_in_MNH_In_Midwives=pd.concat( Last_received_on_the_job_training_in_MNH_In_Midwives_4, axis=0)

In [578]:
Neve_received_on_the_job_training1=data.loc[(data['profqual_cat']==3) & (data['Q407_6A']==0)]
Neve_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==3)]
Neve_received_on_the_job_training_in_MNH_In_Nurses=(len(Neve_received_on_the_job_training1)/(len(Neve_received_on_the_job_training)))*100
Neve_received_on_the_job_training_in_MNH_In_Nurses_1=round((Neve_received_on_the_job_training_in_MNH_In_Nurses),0)
Neve_received_on_the_job_training_in_MNH_In_Nurses_1
fata2 = ([["never received on-the-job training at MNH", Neve_received_on_the_job_training_in_MNH_In_Nurses_1]])
df11 = pd.DataFrame(fata2, columns = ["",'Nurses'])
In_last_6_months_received_on_the_job_training1=data.loc[(data['profqual_cat']==3) & (data['Q407_6A']==1)]
In_last_6_months_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==3)]
In_last_6_months_received_on_the_job_training_in_MNH_In_Nurses=(len(In_last_6_months_received_on_the_job_training1)/(len(In_last_6_months_received_on_the_job_training)))*100
In_last_6_months_received_on_the_job_training_in_MNH_In_Nurses_1=round((In_last_6_months_received_on_the_job_training_in_MNH_In_Nurses),0)
In_last_6_months_received_on_the_job_training_in_MNH_In_Nurses_1
fata22 = ([["received on-the-job training at MNH In last 6 months", In_last_6_months_received_on_the_job_training_in_MNH_In_Nurses_1]])
df12 = pd.DataFrame(fata22, columns = ["",'Nurses'])
In_last_year_received_on_the_job_training1=data.loc[(data['profqual_cat']==3) & (data['Q407_6A']==2)]
In_last_year_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==3)]
In_last_year_received_on_the_job_training_in_MNH_In_Nurses=(len(In_last_year_received_on_the_job_training1)/(len(In_last_year_received_on_the_job_training)))*100
In_last_year_received_on_the_job_training_in_MNH_In_Nurses_1=round((In_last_year_received_on_the_job_training_in_MNH_In_Nurses),0)
In_last_year_received_on_the_job_training_in_MNH_In_Nurses_1
fata222 = ([["received on-the-job training at MNH In last year", In_last_year_received_on_the_job_training_in_MNH_In_Nurses_1]])
df13 = pd.DataFrame(fata222, columns = ["",'Nurses'])
More_than_year_ago_on_the_job_training1=data.loc[(data['profqual_cat']==3) & (data['Q407_6A']==3)]
More_than_year_ago_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==3)]
More_than_year_ago_on_the_job_training_in_MNH_In_Nurses=(len(More_than_year_ago_on_the_job_training1)/(len(More_than_year_ago_on_the_job_training)))*100
More_than_year_ago_on_the_job_training_in_MNH_In_Nurses_1=round((More_than_year_ago_on_the_job_training_in_MNH_In_Nurses),0)
More_than_year_ago_on_the_job_training_in_MNH_In_Nurses_1
fata2222 = ([["received on-the-job training at MNH In last yearMore than a year ago", More_than_year_ago_on_the_job_training_in_MNH_In_Nurses_1]])
df14 = pd.DataFrame(fata2222, columns = ['','Nurses'])
Last_received_on_the_job_training_in_MNH_In_Nurses_4=(df11,df12,df13,df14)
Last_received_on_the_job_training_in_MNH_In_Nurses=pd.concat( Last_received_on_the_job_training_in_MNH_In_Nurses_4, axis=0)

In [577]:
Neve_received_on_the_job_training1=data.loc[(data['profqual_cat']==1) & (data['Q407_6A']==0)]
Neve_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==1)]
Neve_received_on_the_job_training_in_MNH_In_Health_officers=(len(Neve_received_on_the_job_training1)/(len(Neve_received_on_the_job_training)))*100
Neve_received_on_the_job_training_in_MNH_In_Health_officers_1=round((Neve_received_on_the_job_training_in_MNH_In_Health_officers),0)
Neve_received_on_the_job_training_in_MNH_In_Health_officers_1
fata3 = ([["never received on-the-job training at MNH", Neve_received_on_the_job_training_in_MNH_In_Health_officers_1]])
df11 = pd.DataFrame(fata3, columns = ["",'Health officers'])
In_last_6_months_received_on_the_job_training1=data.loc[(data['profqual_cat']==1) & (data['Q407_6A']==1)]
In_last_6_months_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==1)]
In_last_6_months_received_on_the_job_training_in_MNH_In_Health_officers=(len(In_last_6_months_received_on_the_job_training1)/(len(In_last_6_months_received_on_the_job_training)))*100
In_last_6_months_received_on_the_job_training_in_MNH_In_Health_officers_1=round((In_last_6_months_received_on_the_job_training_in_MNH_In_Health_officers),0)
In_last_6_months_received_on_the_job_training_in_MNH_In_Health_officers_1
fata33 = ([["received on-the-job training at MNH In last 6 months", In_last_6_months_received_on_the_job_training_in_MNH_In_Health_officers_1]])
df12 = pd.DataFrame(fata33, columns = ["",'Health officers'])
In_last_year_received_on_the_job_training1=data.loc[(data['profqual_cat']==1) & (data['Q407_6A']==2)]
In_last_year_received_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==1)]
In_last_year_received_on_the_job_training_in_MNH_In_Health_officers=(len(In_last_year_received_on_the_job_training1)/(len(In_last_year_received_on_the_job_training)))*100
In_last_year_received_on_the_job_training_in_MNH_In_Health_officers_1=round((In_last_year_received_on_the_job_training_in_MNH_In_Health_officers),0)
In_last_year_received_on_the_job_training_in_MNH_In_Health_officers_1
fata333 =([["received on-the-job training at MNH In last year", In_last_year_received_on_the_job_training_in_MNH_In_Health_officers_1]])
df13 = pd.DataFrame(fata333, columns = ["",'Health officers'])
More_than_year_ago_on_the_job_training1=data.loc[(data['profqual_cat']==1) & (data['Q407_6A']==3)]
More_than_year_ago_on_the_job_training = Number_facility=data.loc[(data['profqual_cat']==1)]
More_than_year_ago_on_the_job_training_in_MNH_In_Health_officers=(len(More_than_year_ago_on_the_job_training1)/(len(More_than_year_ago_on_the_job_training)))*100
More_than_year_ago_on_the_job_training_in_MNH_In_Health_officers_1=round((More_than_year_ago_on_the_job_training_in_MNH_In_Health_officers),0)
More_than_year_ago_on_the_job_training_in_MNH_In_Health_officers_1
fata3333 =([["received on-the-job training at MNH In last yearMore than a year ago", More_than_year_ago_on_the_job_training_in_MNH_In_Health_officers_1]])
df14 = pd.DataFrame(fata3333, columns = ["",'Health officers'])
Last_received_on_the_job_training_in_MNH_In_Health_officers_4=(df11,df12,df13,df14)
Last_received_on_the_job_training_in_MNH_In_Health_officers=pd.concat( Last_received_on_the_job_training_in_MNH_In_Health_officers_4, axis=0)

In [428]:
Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_4=(Last_received_on_the_job_training_in_MNH,Last_received_on_the_job_training_in_MNH_In_Midwives,Last_received_on_the_job_training_in_MNH_In_Nurses,Last_received_on_the_job_training_in_MNH_In_Health_officers)
Percent_distribution_offacilities_according_to_strength_of_cell=pd.concat( Percent_distribution_offacilities_according_to_strength_of_cell_phone_signal_4,axis=1)
Percent_distribution_offacilities_according_to_strength_of_cell

,,Total,,Midwives,,Nurses,,Health officers
0,never received on-the-job training at MNH,21.0,never received on-the-job training at MNH,17.0,never received on-the-job training at MNH,41.0,never received on-the-job training at MNH,45.0
0,received on-the-job training at MNH In last 6 ...,43.0,received on-the-job training at MNH In last 6 ...,45.0,received on-the-job training at MNH In last 6 ...,30.0,received on-the-job training at MNH In last 6 ...,36.0
0,received on-the-job training at MNH In last year,17.0,received on-the-job training at MNH In last year,18.0,received on-the-job training at MNH In last year,14.0,received on-the-job training at MNH In last year,11.0
0,received on-the-job training at MNH In last ye...,19.0,received on-the-job training at MNH In last ye...,20.0,received on-the-job training at MNH In last ye...,14.0,received on-the-job training at MNH In last ye...,8.0

In [430]:
Percent_distribution_offacilities_according_to_strength_of_cell.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of Human Resources/Last received on the job training in MNH.csv")

# Availability of Drugs, Equipment, and Supplies

In [615]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['pharm_meds'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Has_pharmacy_supply_of_medicines_National  = pd.DataFrame(fata1, columns =['Has pharmacy/supply of medicines'])
labels_of_col1 = ["Facility	",'National']
Has_pharmacy_supply_of_medicines_National .index= labels_of_col1[1:]
Has_pharmacy_supply_of_medicines_National .index.names= [labels_of_col1[0]]

In [616]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q104_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Has_drug_inventory_register_National = pd.DataFrame(fata1, columns = ['Has drug inventory register'])
labels_of_col1 = ["Facility	",'National']
Has_drug_inventory_register_National.index= labels_of_col1[1:]
Has_drug_inventory_register_National.index.names= [labels_of_col1[0]]

In [617]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q105_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Drug_inventory_register_up_to_data_National = pd.DataFrame(fata1, columns = ['Drug inventory register up-to-date'])
labels_of_col1 = ["Facility	",'National']
Drug_inventory_register_up_to_data_National.index= labels_of_col1[1:]
Drug_inventory_register_up_to_data_National.index.names= [labels_of_col1[0]]

In [645]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=(Has_pharmacy_supply_of_medicines_National,Has_drug_inventory_register_National,Drug_inventory_register_up_to_data_National)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines1=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=1, sort=False)
#Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines1

In [646]:
my_tab = pd.crosstab(data['FT7'], data['pharm_meds'])
Has_pharmacy_supply_of_medicines_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Has_pharmacy_supply_of_medicines_Facility_Type[0]
#del Has_pharmacy_supply_of_medicines_Facility_Type[8]
del Has_pharmacy_supply_of_medicines_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has pharmacy/supply of medicines']
Has_pharmacy_supply_of_medicines_Facility_Type.columns= labels_of_col[1:]
Has_pharmacy_supply_of_medicines_Facility_Type.index= labels_of_col1[1:]
Has_pharmacy_supply_of_medicines_Facility_Type.columns.names= [labels_of_col[0]]
Has_pharmacy_supply_of_medicines_Facility_Type.index.names= [labels_of_col1[0]]

In [647]:
my_tab = pd.crosstab(data['FT7'], data['Q104_3'])
Has_drug_inventory_register_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Has_drug_inventory_register_Facility_Type[0]
#del Has_drug_inventory_register_Facility_Type[8]
del Has_drug_inventory_register_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has drug inventory register']
Has_drug_inventory_register_Facility_Type.columns= labels_of_col[1:]
Has_drug_inventory_register_Facility_Type.index= labels_of_col1[1:]
Has_drug_inventory_register_Facility_Type.columns.names= [labels_of_col[0]]
Has_drug_inventory_register_Facility_Type.index.names= [labels_of_col1[0]]
Has_drug_inventory_register_Facility_Type

                        Has drug inventory register
Facility
Referral/specialized                           87.0
General hospitals                              93.0
Primary hospitals                              86.0
MCH specialty centres                          83.0
Health centres                                 56.0
MCH specialty clinics                          25.0
Higher clinics                                 38.0

In [664]:
my_tab = pd.crosstab(data['FT7'], data['Q105_3'])
Has_drug_inventory_register_up_to_date_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Has_drug_inventory_register_up_to_date_Facility_Type[0]
#del Has_drug_inventory_register_up_to_date _Facility_Type[8]
del Has_drug_inventory_register_up_to_date_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Drug inventory register up-to-date']
Has_drug_inventory_register_up_to_date_Facility_Type.columns= labels_of_col[1:]
Has_drug_inventory_register_up_to_date_Facility_Type.index= labels_of_col1[1:]
Has_drug_inventory_register_up_to_date_Facility_Type.columns.names= [labels_of_col[0]]
Has_drug_inventory_register_up_to_date_Facility_Type.index.names= [labels_of_col1[0]]

In [649]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=((Has_pharmacy_supply_of_medicines_Facility_Type,Has_drug_inventory_register_Facility_Type,Has_drug_inventory_register_up_to_date_Facility_Type))
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=1, sort=False)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines

,Has pharmacy/supply of medicines,Has drug inventory register,Drug inventory register up-to-date
Facility,,,
Referral/specialized,100.0,87.0,83.0
General hospitals,100.0,93.0,84.0
Primary hospitals,99.0,86.0,72.0
MCH specialty centres,91.0,83.0,61.0
Health centres,100.0,56.0,41.0
MCH specialty clinics,38.0,25.0,25.0
Higher clinics,62.0,38.0,31.0

In [650]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent of facilities with a pharmacy or supply of medicines, with a drug inventory register, and whose register is up-to-date.csv")

In [719]:
my_tab = pd.crosstab(data['FT7'], data['Q106_3'])
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type[0]
#del Has_drug_inventory_register_up_to_date _Facility_Type[8]
del Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type[-999]
labels_of_col1 =["","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["Facility","Weekly/monthly/quarterly","Every 6 or 12 months",'Whenever stock reaches reorder level','Whenever stock runs out','Never order drugs (sent through kits)','Other']
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.columns= labels_of_col[1:]
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.index= labels_of_col1[1:]
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q106_3'], data['Q106_3'])
b = 3780
my_tab11 = ((my_tab1[1][1])/b)*100
my_tab12 = ((my_tab1[2][2])/b)*100
my_tab13 = ((my_tab1[3][3])/b)*100
my_tab14 = ((my_tab1[4][4])/b)*100
my_tab15 = ((my_tab1[5][5])/b)*100
my_tab16 = ((my_tab1[96][96])/b)*100
cc= round((my_tab11),0)
cc1= round((my_tab12),0)
cc2= round((my_tab13),0)
cc3= round((my_tab14),0)
cc4= round((my_tab15),0)
cc5= round((my_tab16),0)
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'] = cc
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'][1] = cc1
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'][2] = cc2
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'][3] = cc3
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'][4] = cc4
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.loc['National'][5] = cc5
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type

Facility,Weekly/monthly/quarterly,Every 6 or 12 months,Whenever stock reaches reorder level,Whenever stock runs out,Never order drugs (sent through kits),Other
,,,,,,
Referral/specialized,83.0,0.0,10.0,3.0,0.0,3.0
General hospitals,79.0,2.0,12.0,6.0,2.0,0.0
Primary hospitals,81.0,5.0,6.0,6.0,1.0,0.0
MCH specialty centres,43.0,4.0,35.0,9.0,0.0,0.0
Health centres,66.0,26.0,4.0,3.0,1.0,0.0
MCH specialty clinics,19.0,12.0,0.0,6.0,0.0,0.0
Higher clinics,38.0,0.0,8.0,15.0,0.0,0.0
National,67.0,24.0,4.0,4.0,1.0,0.0

In [722]:
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_Facility_Type.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent distribution of facilities with a pharmacy or supply of medicines according to schedule for ordering drugs.csv")

In [750]:
my_tab = pd.crosstab(data['FT7'], data['Q108_3'])
Has_drug_inventory_register_up_to_date_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
#del Has_drug_inventory_register_up_to_date_Facility_Type[0]
#del Has_drug_inventory_register_up_to_date _Facility_Type[8]
del Has_drug_inventory_register_up_to_date_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col =  ["","Inadequate transport","Administrative difficulties",'Financial problems','Stock out at central store','Other','No delay']
Has_drug_inventory_register_up_to_date_Facility_Type.columns= labels_of_col[1:]
Has_drug_inventory_register_up_to_date_Facility_Type.index= labels_of_col1[1:]
Has_drug_inventory_register_up_to_date_Facility_Type.columns.names= [labels_of_col[0]]
Has_drug_inventory_register_up_to_date_Facility_Type.index.names= [labels_of_col1[0]]
Has_drug_inventory_register_up_to_date_Facility_Type

,Inadequate transport,Administrative difficulties,Financial problems,Stock out at central store,Other,No delay
Facility,,,,,,
Referral/specialized,0.0,13.0,3.0,67.0,13.0,3.0
General hospitals,6.0,16.0,6.0,62.0,10.0,1.0
Primary hospitals,14.0,15.0,11.0,52.0,8.0,0.0
MCH specialty centres,4.0,35.0,4.0,48.0,0.0,0.0
Health centres,23.0,21.0,10.0,40.0,5.0,0.0
MCH specialty clinics,0.0,6.0,0.0,31.0,0.0,0.0
Higher clinics,0.0,8.0,15.0,31.0,8.0,0.0

In [731]:
Percent_distribution_of_facilities_with_a_pharmacy_or_supply_of_medicines_according_to_reasons_Facility_Type.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent distribution of facilities with a pharmacy or supply of medicines according to reasons for delays refilling stock.csv")

In [761]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141C_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Ketamine  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Ketamine']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Ketamine .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Ketamine .index.names= [labels_of_col1[0]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Ketamine

            pharmacy or supply of medicines that reported a stock out of selected drugs
Facility\t
Ketamine                                                 57.0

In [766]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141B_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Magnesium_sulphate  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Magnesium_sulphate']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Magnesium_sulphate .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Magnesium_sulphate .index.names= [labels_of_col1[0]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Magnesium_sulphate

                    pharmacy or supply of medicines that reported a stock out of selected drugs
Facility\t
Magnesium_sulphate                                               52.0

In [769]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141D_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Dexamethasone  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Dexamethasone']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Dexamethasone .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Dexamethasone .index.names= [labels_of_col1[0]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Dexamethasone

               pharmacy or supply of medicines that reported a stock out of selected drugs
Facility\t
Dexamethasone                                               49.0

In [771]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141A_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Gentamicin_injection  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Gentamicin_injection']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Gentamicin_injection .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Gentamicin_injection .index.names= [labels_of_col1[0]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Gentamicin_injection

                      pharmacy or supply of medicines that reported a stock out of selected drugs
Facility\t
Gentamicin_injection                                               46.0

In [773]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141E_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Antiretrovirals  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Antiretrovirals']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Antiretrovirals .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Antiretrovirals .index.names= [labels_of_col1[0]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Antiretrovirals

                 pharmacy or supply of medicines that reported a stock out of selected drugs
Facility\t
Antiretrovirals                                               39.0

In [944]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q141F_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Oxytocin  = pd.DataFrame(fata1, columns =['pharmacy or supply of medicines that reported a stock out of selected drugs'])
labels_of_col1 = ["Facility	",'Oxytocin']
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Oxytocin .index= labels_of_col1[1:]
pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Oxytocin .index.names= [labels_of_col1[0]]
#pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Oxytocin

In [943]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_4=(pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Ketamine,pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Magnesium_sulphate,pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Dexamethasone,pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Gentamicin_injection,pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Antiretrovirals,pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_National_Oxytocin)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs_4, axis=0, sort=False)
#Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs

In [778]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_that_reported_a_stock_out_of_selected_drugs.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent of facilities with a pharmacy or supply of medicines that reported a stock out of selected drugs in the last 3 months.csv")

In [942]:
my_tab = pd.crosstab(data['FT7'], data['Q109_3'])
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),2)
del Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type[0]
#del Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type[8]
del Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pharmacy present and accessible 24 hours a day']
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.columns= labels_of_col[1:]
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.index= labels_of_col1[1:]
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q109_3'], data['Q109_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.loc['National'] = cc
#Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type.transpose()

In [941]:
my_tab = pd.crosstab(data['FT7'], data['QE1_3'])
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),2)
del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type[0]
#del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type[8]
del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pharmacy has adequate lighting to perform duties During the day']
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.columns= labels_of_col[1:]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.index= labels_of_col1[1:]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.columns.names= [labels_of_col[0]]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['QE1_3'], data['QE1_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.loc['National'] = cc
#Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type.transpose()

In [940]:
my_tab = pd.crosstab(data['FT7'], data['QE2_3'])
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),2)
del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type[0]
del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type[2]
del Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pharmacy has adequate lighting to perform duties During the night (among facilities with 24 hour pharmacy service) ']
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.columns= labels_of_col[1:]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.index= labels_of_col1[1:]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.columns.names= [labels_of_col[0]]
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['QE2_3'], data['QE2_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.loc['National'] = cc
#Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type.transpose()

In [939]:
my_tab = pd.crosstab(data['FT7'], data['Q110_3'])
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),2)
del Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed[0]
#del Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed[2]
del Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Regularly used mechanism to ensure that expired drugs are not distributed']
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.columns= labels_of_col[1:]
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.index= labels_of_col1[1:]
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.columns.names= [labels_of_col[0]]
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q110_3'], data['Q110_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.loc['National'] = cc
#Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed.transpose()

In [938]:
my_tab = pd.crosstab(data['FT7'], data['Q111_3'])
First_in_first_out_system_is_in_use_for_gentamicin_observation = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del First_in_first_out_system_is_in_use_for_gentamicin_observation[0]
del First_in_first_out_system_is_in_use_for_gentamicin_observation[2]
del First_in_first_out_system_is_in_use_for_gentamicin_observation[-999]
del First_in_first_out_system_is_in_use_for_gentamicin_observation[3]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'First-in-first-out" system is in use for gentamicin (observation) ']
First_in_first_out_system_is_in_use_for_gentamicin_observation.columns= labels_of_col[1:]
First_in_first_out_system_is_in_use_for_gentamicin_observation.index= labels_of_col1[1:]
First_in_first_out_system_is_in_use_for_gentamicin_observation.columns.names= [labels_of_col[0]]
First_in_first_out_system_is_in_use_for_gentamicin_observation.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q111_3'], data['Q111_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
First_in_first_out_system_is_in_use_for_gentamicin_observation.loc['National'] = cc
#First_in_first_out_system_is_in_use_for_gentamicin_observation.transpose()

In [937]:
my_tab = pd.crosstab(data['FT7'], data['Q112_3'])
Drugs_are_protected_from_moisture_heat_or_infestation_observation = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Drugs_are_protected_from_moisture_heat_or_infestation_observation[0]
del Drugs_are_protected_from_moisture_heat_or_infestation_observation[2]
del Drugs_are_protected_from_moisture_heat_or_infestation_observation[-999]
#del Drugs_are_protected_from_moisture_heat_or_infestation_observation[3]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Drugs are protected from moisture,heat, or infestation (observation)']
Drugs_are_protected_from_moisture_heat_or_infestation_observation.columns= labels_of_col[1:]
Drugs_are_protected_from_moisture_heat_or_infestation_observation.index= labels_of_col1[1:]
Drugs_are_protected_from_moisture_heat_or_infestation_observation.columns.names= [labels_of_col[0]]
Drugs_are_protected_from_moisture_heat_or_infestation_observation.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q112_3'], data['Q112_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Drugs_are_protected_from_moisture_heat_or_infestation_observation.loc['National'] = cc
#Drugs_are_protected_from_moisture_heat_or_infestation_observation.transpose()

In [936]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=(Percent_of_facilities_with_pharmacy_or_supply_of_medicines_reporting_Facility_Type,Pharmacy_has_adequate_lighting_to_perform_duties_During_the_day_Facility_Type,Pharmacy_has_adequate_lighting_to_perform_duties_During_the_night_among_facilities_with_24_hour_pharmacy_service_Facility_Type,Regularly_used_mechanism_to_ensure_that_expired_drugs_are_not_distributed,First_in_first_out_system_is_in_use_for_gentamicin_observation,Drugs_are_protected_from_moisture_heat_or_infestation_observation)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=1, sort=False)
#Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines.transpose()

In [935]:
my_tab = pd.crosstab(data['FT7'], data['Q113_3'])
Oxytocin_refrigerated_and_temperature_monitored_daily = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),2)
#del Oxytocin_refrigerated_and_temperature_monitored_daily[0]
#del Oxytocin_refrigerated_and_temperature_monitored_daily[2]
#del Oxytocin_refrigerated_and_temperature_monitored_daily[-999]
#del Oxytocin_refrigerated_and_temperature_monitored_daily[3]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Yes, refrigerated and monitored ','Yes, refrigerated but not monitored','No, oxytocin not refrigerated','No oxytocin in stock','Did not observe ','Drop']
Oxytocin_refrigerated_and_temperature_monitored_daily.columns= labels_of_col[1:]
Oxytocin_refrigerated_and_temperature_monitored_daily.index= labels_of_col1[1:]
Oxytocin_refrigerated_and_temperature_monitored_daily.columns.names= [labels_of_col[0]]
Oxytocin_refrigerated_and_temperature_monitored_daily.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q113_3'], data['Q113_3'])
b = len(data.loc[((data['FT7']))])
my_tab11 = ((my_tab1[0][0])/b)*100
my_tab12 = ((my_tab1[1][1])/b)*100
my_tab13 = ((my_tab1[2][2])/b)*100
my_tab14 = ((my_tab1[3][3])/b)*100
my_tab15 = ((my_tab1[8][8])/b)*100
cc= round((my_tab11),0)
cc1= round((my_tab12),0)
cc2= round((my_tab13),0)
cc3= round((my_tab14),0)
cc4= round((my_tab15),0)
Oxytocin_refrigerated_and_temperature_monitored_daily.loc['National'] = cc
Oxytocin_refrigerated_and_temperature_monitored_daily.loc['National'][1] = cc1
Oxytocin_refrigerated_and_temperature_monitored_daily.loc['National'][2] = cc2
Oxytocin_refrigerated_and_temperature_monitored_daily.loc['National'][3] = cc3
Oxytocin_refrigerated_and_temperature_monitored_daily.loc['National'][4] = cc4
del Oxytocin_refrigerated_and_temperature_monitored_daily['Drop']
#Oxytocin_refrigerated_and_temperature_monitored_daily.transpose()

In [934]:
my_tab = pd.crosstab(data['FT7'], data['Q114_3'])
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI[0]
#del Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI[2]
del Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI[-999]
#del Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI[3]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has functioning electric/gas refrigerator other than one for EPI']
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.columns= labels_of_col[1:]
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.index= labels_of_col1[1:]
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.columns.names= [labels_of_col[0]]
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q114_3'], data['Q114_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.loc['National'] = cc
#Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI.transpose()

In [933]:
my_tab = pd.crosstab(data['FT7'], data['Q115_3'])
Has_functioning_Solar_refrigerator_other_than_one_for_EPI = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Has_functioning_Solar_refrigerator_other_than_one_for_EPI[0]
#del Has_functioning_Solar_refrigerator_other_than_one_for_EPI[2]
del Has_functioning_Solar_refrigerator_other_than_one_for_EPI[-999]
#del Has_functioning_Solar_refrigerator_other_than_one_for_EPI[3]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has functioning solar refrigerator other than one for EPI']
Has_functioning_Solar_refrigerator_other_than_one_for_EPI.columns= labels_of_col[1:]
Has_functioning_Solar_refrigerator_other_than_one_for_EPI.index= labels_of_col1[1:]
Has_functioning_Solar_refrigerator_other_than_one_for_EPI.columns.names= [labels_of_col[0]]
Has_functioning_Solar_refrigerator_other_than_one_for_EPI.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q112_3'], data['Q112_3'])
b = len(data.loc[((data['FT7']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Has_functioning_Solar_refrigerator_other_than_one_for_EPI.loc['National'] = cc
#Has_functioning_Solar_refrigerator_other_than_one_for_EPI.transpose()

In [947]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines,Oxytocin_refrigerated_and_temperature_monitored_daily,Has_functioning_electric_gas_refrigerator_other_than_one_for_EPI,Has_functioning_Solar_refrigerator_other_than_one_for_EPI)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines22=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=1)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines22.transpose()

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Pharmacy present and accessible 24 hours a day,96.67,84.47,94.38,65.22,86.21,0.00,23.08,86.0
Pharmacy has adequate lighting to perform duties During the day,100.00,99.03,99.38,86.96,93.76,37.50,61.54,94.0
Pharmacy has adequate lighting to perform duties During the night (among facilities with 24 hour pharmacy service),100.00,93.20,89.38,73.91,58.49,18.75,61.54,61.0
Regularly used mechanism to ensure that expired drugs are not distributed,100.00,96.12,96.88,91.30,89.77,31.25,53.85,90.0
"First-in-first-out"" system is in use for gentamicin (observation)",73.00,83.00,87.00,65.00,67.00,12.00,62.00,68.0
"Drugs are protected from moisture,heat, or infestation (observation)",97.00,93.00,96.00,91.00,83.00,31.00,54.00,83.0
"Yes, refrigerated and monitored",0.00,0.00,0.62,8.70,0.17,62.50,38.46,3.0
"Yes, refrigerated but not monitored",3.33,1.94,3.12,0.00,3.47,0.00,0.00,71.0
"No, oxytocin not refrigerated",80.00,77.67,75.00,69.57,70.37,31.25,38.46,20.0
No oxytocin in stock,13.33,14.56,20.00,13.04,20.61,0.00,23.08,5.0
Did not observe,3.33,5.83,1.25,8.70,4.63,6.25,0.00,1.0
Has functioning electric/gas refrigerator other than one for EPI,90.00,89.00,81.00,78.00,56.00,31.00,38.00,58.0
Has functioning solar refrigerator other than one for EPI,13.00,17.00,11.00,13.00,21.00,12.00,15.00,83.0

In [1047]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines22.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent of facilities with a pharmacy or supply of medicines reporting on pharmacy medicine-related items.csv")

In [1048]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines22.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and stock outs of drugs/Percent of facilities with a pharmacy or supply of medicines reporting on pharmacy medicine-related items.csv")

In [1049]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q116_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the signal functions and emergencies'])
labels_of_col1 = ["Facility	",'Antibiotics']
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions

             Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Antibiotics                                               99.0

In [1050]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q124_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_emergencies  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the signal functions and emergencies'])
labels_of_col1 = ["Facility	",'Drugs used in emergencies']
Percent_of_facilities_that_had_drugs_related_to_the_emergencies .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_emergencies .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_emergencies

                           Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Drugs used in emergencies                                               97.0

In [1051]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q122_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Oxytocics_and_prostaglandins  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the signal functions and emergencies'])
labels_of_col1 = ["Facility	",'Oxytocics and prostaglandins']
Percent_of_facilities_that_had_drugs_related_to_the_Oxytocics_and_prostaglandins .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Oxytocics_and_prostaglandins .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Oxytocics_and_prostaglandins

                              Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Oxytocics and prostaglandins                                               94.0

In [1052]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q120_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Antihypertensives  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the signal functions and emergencies'])
labels_of_col1 = ["Facility	",'Antihypertensives']
Percent_of_facilities_that_had_drugs_related_to_the_Antihypertensives .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Antihypertensives .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Antihypertensives

                   Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Antihypertensives                                               92.0

In [1053]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q118_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Anticonvulsants  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the signal functions and emergencies'])
labels_of_col1 = ["Facility	",'Anticonvulsants']
Percent_of_facilities_that_had_drugs_related_to_the_Anticonvulsants .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Anticonvulsants .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Anticonvulsants

                 Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Anticonvulsants                                               87.0

In [1054]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=(Percent_of_facilities_that_had_drugs_related_to_the_signal_functions,Percent_of_facilities_that_had_drugs_related_to_the_emergencies,Percent_of_facilities_that_had_drugs_related_to_the_Oxytocics_and_prostaglandins,Percent_of_facilities_that_had_drugs_related_to_the_Antihypertensives,Percent_of_facilities_that_had_drugs_related_to_the_Anticonvulsants)
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions_and_emergencies=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=0)
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions_and_emergencies

                              Percent of facilities that had drugs related to the signal functions and emergencies
Facility\t
Antibiotics                                                                99.0
Drugs used in emergencies                                                  97.0
Oxytocics and prostaglandins                                               94.0
Antihypertensives                                                          92.0
Anticonvulsants                                                            87.0

In [1055]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q132_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_IV_fluids  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'IV_fluids']
Percent_of_facilities_that_had_drugs_related_to_the_IV_fluids .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_IV_fluids .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_IV_fluids

            Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
IV_fluids                                                98.0

In [1056]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q128_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Analgesics  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'Analgesics']
Percent_of_facilities_that_had_drugs_related_to_the_Analgesics .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Analgesics .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Analgesics

            Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
Analgesics                                               97.0

In [1057]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q134_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Antimalarials  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'Antimalarials']
Percent_of_facilities_that_had_drugs_related_to_the_Antimalarials .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Antimalarials .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Antimalarials

               Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
Antimalarials                                               88.0

In [1058]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q130_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Steroids  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'Steroids']
Percent_of_facilities_that_had_drugs_related_to_the_Steroids .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Steroids .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Steroids

            Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
Steroids                                                 83.0

In [1059]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q126_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Anaesthetics  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'Anaesthetics']
Percent_of_facilities_that_had_drugs_related_to_the_Anaesthetics .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Anaesthetics .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Anaesthetics

              Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
Anaesthetics                                               79.0

In [1060]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q126_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_had_drugs_related_to_the_Antiretrovirals  = pd.DataFrame(fata1, columns =['Percent of facilities that had drugs related to the anaesthetics and other drugs'])
labels_of_col1 = ["Facility	",'Antiretrovirals']
Percent_of_facilities_that_had_drugs_related_to_the_Antiretrovirals .index= labels_of_col1[1:]
Percent_of_facilities_that_had_drugs_related_to_the_Antiretrovirals .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_had_drugs_related_to_the_Antiretrovirals

                 Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
Antiretrovirals                                               79.0

In [1061]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4=(Percent_of_facilities_that_had_drugs_related_to_the_IV_fluids,Percent_of_facilities_that_had_drugs_related_to_the_Analgesics,Percent_of_facilities_that_had_drugs_related_to_the_Antimalarials,Percent_of_facilities_that_had_drugs_related_to_the_Steroids,Percent_of_facilities_that_had_drugs_related_to_the_Anaesthetics,Percent_of_facilities_that_had_drugs_related_to_the_Antiretrovirals)
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions_and_emergencies=pd.concat( Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines_4, axis=0)
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions_and_emergencies

                 Percent of facilities that had drugs related to the anaesthetics and other drugs
Facility\t
IV_fluids                                                     98.0
Analgesics                                                    97.0
Antimalarials                                                 88.0
Steroids                                                      83.0
Anaesthetics                                                  79.0
Antiretrovirals                                               79.0

In [1062]:
Percent_of_facilities_that_had_drugs_related_to_the_signal_functions_and_emergencies.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Essential drugs/Percent of facilities that had drugs related to the anaesthetics and other drugs.csv")

In [1063]:
my_tab = pd.crosstab(data['FT7'], data['Q138_3'])
Percent_of_facilities_that_Contraceptives_any = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Contraceptives_any[0]
#del  Percent_of_facilities_that_Contraceptives_any[8]
del  Percent_of_facilities_that_Contraceptives_any[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Any Contraceptives use']
Percent_of_facilities_that_Contraceptives_any.columns= labels_of_col[1:]
Percent_of_facilities_that_Contraceptives_any.index= labels_of_col1[1:]
Percent_of_facilities_that_Contraceptives_any.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Contraceptives_any.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q138_3']==1, data['Q138_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Contraceptives_any.loc['National'] = cc
Percent_of_facilities_that_Contraceptives_any

                        Any Contraceptives use
Facility
Referral/specialized                      97.0
General hospitals                         97.0
Primary hospitals                         97.0
MCH specialty centres                     91.0
Health centres                            98.0
MCH specialty clinics                     31.0
Higher clinics                            54.0
National                                  97.0

In [1069]:
my_tab = pd.crosstab(data['FT7'], data['Q139A_3'])
Percent_of_facilities_that_had_contraceptives = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_contraceptives[0]
#del  Percent_of_facilities_that_had_contraceptives[8]
del  Percent_of_facilities_that_had_contraceptives[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Combined oral contraceptives']
Percent_of_facilities_that_had_contraceptives.columns= labels_of_col[1:]
Percent_of_facilities_that_had_contraceptives.index= labels_of_col1[1:]
Percent_of_facilities_that_had_contraceptives.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_contraceptives.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139A_3']==1, data['Q139A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_contraceptives.loc['National'] = cc
Percent_of_facilities_that_had_contraceptives

                        Combined oral contraceptives
Facility
Referral/specialized                            90.0
General hospitals                               91.0
Primary hospitals                               91.0
MCH specialty centres                           87.0
Health centres                                  88.0
MCH specialty clinics                           31.0
Higher clinics                                  54.0
National                                        88.0

In [1065]:
my_tab = pd.crosstab(data['FT7'], data['Q139B_3'])
Percent_of_facilities_that_Progestin_only_pills = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Progestin_only_pills[0]
#del  Percent_of_facilities_that_Progestin_only_pills[8]
del  Percent_of_facilities_that_Progestin_only_pills[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Progestin only pills']
Percent_of_facilities_that_Progestin_only_pills.columns= labels_of_col[1:]
Percent_of_facilities_that_Progestin_only_pills.index= labels_of_col1[1:]
Percent_of_facilities_that_Progestin_only_pills.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Progestin_only_pills.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139B_3']==1, data['Q139B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Progestin_only_pills.loc['National'] = cc
Percent_of_facilities_that_Progestin_only_pills

                        Progestin only pills
Facility
Referral/specialized                    93.0
General hospitals                       80.0
Primary hospitals                       68.0
MCH specialty centres                   78.0
Health centres                          71.0
MCH specialty clinics                   25.0
Higher clinics                          31.0
National                                71.0

In [1066]:
my_tab = pd.crosstab(data['FT7'], data['Q139C_3'])
Percent_of_facilities_that_Implants = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Implants[0]
del  Percent_of_facilities_that_Implants[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Implants']
Percent_of_facilities_that_Implants.columns= labels_of_col[1:]
Percent_of_facilities_that_Implants.index= labels_of_col1[1:]
Percent_of_facilities_that_Implants.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Implants.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139C_3']==1, data['Q139C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Implants.loc['National'] = cc
Percent_of_facilities_that_Implants

                        Implants
Facility
Referral/specialized        90.0
General hospitals           87.0
Primary hospitals           89.0
MCH specialty centres       83.0
Health centres              89.0
MCH specialty clinics       25.0
Higher clinics              46.0
National                    88.0

In [1067]:
my_tab = pd.crosstab(data['FT7'], data['Q139D_3'])
Percent_of_facilities_that_3_month_injectables = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_3_month_injectables[0]
del  Percent_of_facilities_that_3_month_injectables[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'3 month injectables']
Percent_of_facilities_that_3_month_injectables.columns= labels_of_col[1:]
Percent_of_facilities_that_3_month_injectables.index= labels_of_col1[1:]
Percent_of_facilities_that_3_month_injectables.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_3_month_injectables.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139D_3']==1, data['Q139D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_3_month_injectables.loc['National'] = cc
Percent_of_facilities_that_3_month_injectables

                        3 month injectables
Facility
Referral/specialized                   97.0
General hospitals                      84.0
Primary hospitals                      92.0
MCH specialty centres                  91.0
Health centres                         92.0
MCH specialty clinics                  31.0
Higher clinics                         46.0
National                               91.0

In [1068]:
my_tab = pd.crosstab(data['FT7'], data['Q139E_3'])
Percent_of_facilities_that_Intrauterine_IUDs = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Intrauterine_IUDs[0]
del  Percent_of_facilities_that_Intrauterine_IUDs[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Intrauterine IUDs']
Percent_of_facilities_that_Intrauterine_IUDs.columns= labels_of_col[1:]
Percent_of_facilities_that_Intrauterine_IUDs.index= labels_of_col1[1:]
Percent_of_facilities_that_Intrauterine_IUDs.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Intrauterine_IUDs.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139E_3']==1, data['Q139E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),2)
Percent_of_facilities_that_Intrauterine_IUDs.loc['National'] = cc
Percent_of_facilities_that_Intrauterine_IUDs

                        Intrauterine IUDs
Facility
Referral/specialized                97.00
General hospitals                   84.00
Primary hospitals                   83.00
MCH specialty centres               87.00
Health centres                      75.00
MCH specialty clinics               25.00
Higher clinics                      23.00
National                            75.89

In [1070]:
my_tab = pd.crosstab(data['FT7'], data['Q139F_3'])
Percent_of_facilities_that_Male_condoms = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Male_condoms[0]
del  Percent_of_facilities_that_Male_condoms[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Male condoms']
Percent_of_facilities_that_Male_condoms.columns= labels_of_col[1:]
Percent_of_facilities_that_Male_condoms.index= labels_of_col1[1:]
Percent_of_facilities_that_Male_condoms.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Male_condoms.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139F_3']==1, data['Q139F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Male_condoms.loc['National'] = cc
Percent_of_facilities_that_Male_condoms

                        Male condoms
Facility
Referral/specialized            97.0
General hospitals               88.0
Primary hospitals               92.0
MCH specialty centres           78.0
Health centres                  94.0
MCH specialty clinics           19.0
Higher clinics                  38.0
National                        93.0

In [1071]:
my_tab = pd.crosstab(data['FT7'], data['Q139G_3'])
Percent_of_facilities_that_Female_condoms = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Female_condoms[0]
del  Percent_of_facilities_that_Female_condoms[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Female condoms']
Percent_of_facilities_that_Female_condoms.columns= labels_of_col[1:]
Percent_of_facilities_that_Female_condoms.index= labels_of_col1[1:]
Percent_of_facilities_that_Female_condoms.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Female_condoms.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139G_3']==1, data['Q139G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Female_condoms.loc['National'] = cc
Percent_of_facilities_that_Female_condoms

                        Female condoms
Facility
Referral/specialized               3.0
General hospitals                  5.0
Primary hospitals                  3.0
MCH specialty centres             22.0
Health centres                     3.0
MCH specialty clinics              0.0
Higher clinics                     8.0
National                           3.0

In [1072]:
my_tab = pd.crosstab(data['FT7'], data['Q139H_3'])
Percent_of_facilities_that_Emergency_contraception = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_Emergency_contraception[0]
del  Percent_of_facilities_that_Emergency_contraception[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Emergency contraception']
Percent_of_facilities_that_Emergency_contraception.columns= labels_of_col[1:]
Percent_of_facilities_that_Emergency_contraception.index= labels_of_col1[1:]
Percent_of_facilities_that_Emergency_contraception.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_Emergency_contraception.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q139H_3']==1, data['Q139H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_Emergency_contraception.loc['National'] = cc
Percent_of_facilities_that_Emergency_contraception

                        Emergency contraception
Facility
Referral/specialized                       93.0
General hospitals                          83.0
Primary hospitals                          88.0
MCH specialty centres                      70.0
Health centres                             78.0
MCH specialty clinics                      25.0
Higher clinics                             46.0
National                                   78.0

In [1073]:
Percent_of_facilities_that_had_contraceptives_and_other_drugs_4=(Percent_of_facilities_that_Contraceptives_any,Percent_of_facilities_that_had_contraceptives,Percent_of_facilities_that_Progestin_only_pills,Percent_of_facilities_that_Implants,Percent_of_facilities_that_3_month_injectables,Percent_of_facilities_that_Intrauterine_IUDs,Percent_of_facilities_that_Male_condoms,Percent_of_facilities_that_Female_condoms,Percent_of_facilities_that_Emergency_contraception)
Percent_of_facilities_that_had_contraceptives_and_other_drugs=pd.concat( Percent_of_facilities_that_had_contraceptives_and_other_drugs_4, axis=1, sort=False)
Percent_of_facilities_that_had_contraceptives_and_other_drugs

,Any Contraceptives use,Combined oral contraceptives,Progestin only pills,Implants,3 month injectables,Intrauterine IUDs,Male condoms,Female condoms,Emergency contraception
Facility,,,,,,,,,
Referral/specialized,97.0,90.0,93.0,90.0,97.0,97.00,97.0,3.0,93.0
General hospitals,97.0,91.0,80.0,87.0,84.0,84.00,88.0,5.0,83.0
Primary hospitals,97.0,91.0,68.0,89.0,92.0,83.00,92.0,3.0,88.0
MCH specialty centres,91.0,87.0,78.0,83.0,91.0,87.00,78.0,22.0,70.0
Health centres,98.0,88.0,71.0,89.0,92.0,75.00,94.0,3.0,78.0
MCH specialty clinics,31.0,31.0,25.0,25.0,31.0,25.00,19.0,0.0,25.0
Higher clinics,54.0,54.0,31.0,46.0,46.0,23.00,38.0,8.0,46.0
National,97.0,88.0,71.0,88.0,91.0,75.89,93.0,3.0,78.0

In [1075]:
my_tab = pd.crosstab(data['FT7'], data['Q140A_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vitamin K (for newborn)']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140A_3']==1, data['Q140A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn

                        Vitamin K (for newborn)
Facility
Referral/specialized                      100.0
General hospitals                          93.0
Primary hospitals                          91.0
MCH specialty centres                      91.0
Health centres                             81.0
MCH specialty clinics                      25.0
Higher clinics                             46.0
National                                   82.0

In [1076]:
my_tab = pd.crosstab(data['FT7'], data['Q140C_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Nystatin (oral, for newborn) ']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140C_3']==1, data['Q140C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn

                        Nystatin (oral, for newborn)
Facility
Referral/specialized                             20.0
General hospitals                                22.0
Primary hospitals                                15.0
MCH specialty centres                             9.0
Health centres                                    4.0
MCH specialty clinics                             6.0
Higher clinics                                    8.0
National                                          5.0

In [1077]:
my_tab = pd.crosstab(data['FT7'], data['Q140D_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Oral rehydration solution ']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140D_3']==1, data['Q140D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution

                        Oral rehydration solution
Facility
Referral/specialized                          93.0
General hospitals                             97.0
Primary hospitals                             93.0
MCH specialty centres                         87.0
Health centres                                83.0
MCH specialty clinics                         25.0
Higher clinics                                62.0
National                                      83.0

In [1078]:
my_tab = pd.crosstab(data['FT7'], data['Q140E_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Gentian violet paint']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140E_3']==1, data['Q140E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint

                        Gentian violet paint
Facility
Referral/specialized                    87.0
General hospitals                       85.0
Primary hospitals                       79.0
MCH specialty centres                   87.0
Health centres                          75.0
MCH specialty clinics                   31.0
Higher clinics                          54.0
National                                75.0

In [1080]:
my_tab = pd.crosstab(data['FT7'], data['Q140F_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ferrous sulphate or fumarate']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140F_3']==1, data['Q140F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate

                        Ferrous sulphate or fumarate
Facility
Referral/specialized                            47.0
General hospitals                               69.0
Primary hospitals                               61.0
MCH specialty centres                           52.0
Health centres                                  54.0
MCH specialty clinics                           12.0
Higher clinics                                  38.0
National                                        55.0

In [1082]:
my_tab = pd.crosstab(data['FT7'], data['Q140G_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Folic acid']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140G_3']==1, data['Q140G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid

                        Folic acid
Facility
Referral/specialized          57.0
General hospitals             65.0
Primary hospitals             64.0
MCH specialty centres         61.0
Health centres                40.0
MCH specialty clinics         12.0
Higher clinics                31.0
National                      41.0

In [1084]:
my_tab = pd.crosstab(data['FT7'], data['Q140R_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ferrous sulphate with folic acid']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140R_3']==1, data['Q140R_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid

                        Ferrous sulphate with folic acid
Facility
Referral/specialized                                80.0
General hospitals                                   85.0
Primary hospitals                                   85.0
MCH specialty centres                               87.0
Health centres                                      78.0
MCH specialty clinics                               25.0
Higher clinics                                      62.0
National                                            78.0

In [1085]:
my_tab = pd.crosstab(data['FT7'], data['Q140H_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Heparin']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140H_3']==1, data['Q140H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin

                        Heparin
Facility
Referral/specialized       77.0
General hospitals          63.0
Primary hospitals          20.0
MCH specialty centres      22.0
Health centres              2.0
MCH specialty clinics       0.0
Higher clinics             15.0
National                    5.0

In [1086]:
my_tab = pd.crosstab(data['FT7'], data['Q140I_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Magnesium trisilicate']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140I_3']==1, data['Q140I_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate

                        Magnesium trisilicate
Facility
Referral/specialized                     90.0
General hospitals                        78.0
Primary hospitals                        82.0
MCH specialty centres                    61.0
Health centres                           76.0
MCH specialty clinics                    19.0
Higher clinics                           31.0
National                                 76.0

In [1087]:
my_tab = pd.crosstab(data['FT7'], data['Q140J_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Polio 0']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140J_3']==1, data['Q140J_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0

                        Polio 0
Facility
Referral/specialized       90.0
General hospitals          69.0
Primary hospitals          75.0
MCH specialty centres      83.0
Health centres             87.0
MCH specialty clinics      19.0
Higher clinics             23.0
National                   86.0

In [1088]:
my_tab = pd.crosstab(data['FT7'], data['Q140K_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'BCG vaccine']
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140K_3']==1, data['Q140K_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine

                        BCG vaccine
Facility
Referral/specialized           97.0
General hospitals              77.0
Primary hospitals              81.0
MCH specialty centres          78.0
Health centres                 95.0
MCH specialty clinics          25.0
Higher clinics                 38.0
National                       93.0

In [1089]:
my_tab = pd.crosstab(data['FT7'], data['Q140L_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Anti-tetanus serum/TAT ']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140L_3']==1, data['Q140L_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT

                        Anti-tetanus serum/TAT
Facility
Referral/specialized                       87.0
General hospitals                          80.0
Primary hospitals                          74.0
MCH specialty centres                      65.0
Health centres                             57.0
MCH specialty clinics                       6.0
Higher clinics                             46.0
National                                   58.0

In [1090]:
my_tab = pd.crosstab(data['FT7'], data['Q140M_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Tetanus toxoid vaccine']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140M_3']==1, data['Q140M_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine

                        Tetanus toxoid vaccine
Facility
Referral/specialized                      97.0
General hospitals                         79.0
Primary hospitals                         78.0
MCH specialty centres                     78.0
Health centres                            90.0
MCH specialty clinics                     25.0
Higher clinics                            38.0
National                                  89.0

In [1091]:
my_tab = pd.crosstab(data['FT7'], data['Q14ON_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Anti-rho (D) immune globulin']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q14ON_3']==1, data['Q14ON_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin

                        Anti-rho (D) immune globulin
Facility
Referral/specialized                            77.0
General hospitals                               43.0
Primary hospitals                               24.0
MCH specialty centres                           39.0
Health centres                                   7.0
MCH specialty clinics                           12.0
Higher clinics                                   8.0
National                                         9.0

In [1092]:
my_tab = pd.crosstab(data['FT7'], data['Q140O_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Insecticide-treated bednets(ITN)']
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140O_3']==1, data['Q140O_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs

                        Insecticide-treated bednets(ITN)
Facility
Referral/specialized                                17.0
General hospitals                                   21.0
Primary hospitals                                   35.0
MCH specialty centres                                4.0
Health centres                                      38.0
MCH specialty clinics                                0.0
Higher clinics                                      31.0
National                                            37.0

In [1096]:
my_tab = pd.crosstab(data['FT7'], data['Q140P_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Mebendazole']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140P_3']==1, data['Q140P_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole

                        Mebendazole
Facility
Referral/specialized           93.0
General hospitals              97.0
Primary hospitals              98.0
MCH specialty centres          87.0
Health centres                 95.0
MCH specialty clinics          25.0
Higher clinics                 62.0
National                       95.0

In [1097]:
my_tab = pd.crosstab(data['FT7'], data['Q140Q_3'])
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide[0]
del  Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Metoclopramide']
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide.columns= labels_of_col[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide.index= labels_of_col1[1:]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q140Q_3']==1, data['Q140Q_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide.loc['National'] = cc
Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide

                        Metoclopramide
Facility
Referral/specialized             100.0
General hospitals                 99.0
Primary hospitals                 96.0
MCH specialty centres             78.0
Health centres                    78.0
MCH specialty clinics             25.0
Higher clinics                    62.0
National                          79.0

In [1104]:
Percent_of_facilities_that_had_other_drugs_supply_4=(Percent_of_facilities_that_had_Other_drugs_and_supplies_Vitamin_K_for_newborn,Percent_of_facilities_that_had_Other_drugs_and_supplies_Nystatin_oral_for_newborn,Percent_of_facilities_that_had_Other_drugs_and_supplies_Oral_rehydration_solution,Percent_of_facilities_that_had_Other_drugs_and_supplies_Gentian_violet_paint,Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_or_fumarate,Percent_of_facilities_that_had_Other_drugs_and_supplies_Folic_acid,Percent_of_facilities_that_had_Other_drugs_and_supplies_Ferrous_sulphate_with_folic_acid,Percent_of_facilities_that_had_Other_drugs_and_supplies_Heparin,Percent_of_facilities_that_had_Other_drugs_and_supplies_Magnesium_trisilicate,Percent_of_facilities_that_had_Other_drugs_and_supplies_Polio_0,Percent_of_facilities_that_had_Other_drugs_and_supplies_BCG_vaccine,Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_tetanus_serum_TAT,Percent_of_facilities_that_had_Other_drugs_and_supplies_Tetanus_toxoid_vaccine,Percent_of_facilities_that_had_Other_drugs_and_supplies_Anti_rho_D_immune_globulin,Percent_of_facilities_that_had_Other_drugs_and_supplies_ITNs,Percent_of_facilities_that_had_Other_drugs_and_supplies_Mebendazole,Percent_of_facilities_that_had_Other_drugs_and_supplies_Metoclopramide)
Percent_of_facilities_that_had_other_drugs_supply=pd.concat(  Percent_of_facilities_that_had_other_drugs_supply_4, axis=1, sort=False)
Percent_of_facilities_that_had_other_drugs_supply.transpose()

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Vitamin K (for newborn),100.0,93.0,91.0,91.0,81.0,25.0,46.0,82.0
"Nystatin (oral, for newborn)",20.0,22.0,15.0,9.0,4.0,6.0,8.0,5.0
Oral rehydration solution,93.0,97.0,93.0,87.0,83.0,25.0,62.0,83.0
Gentian violet paint,87.0,85.0,79.0,87.0,75.0,31.0,54.0,75.0
Ferrous sulphate or fumarate,47.0,69.0,61.0,52.0,54.0,12.0,38.0,55.0
Folic acid,57.0,65.0,64.0,61.0,40.0,12.0,31.0,41.0
Ferrous sulphate with folic acid,80.0,85.0,85.0,87.0,78.0,25.0,62.0,78.0
Heparin,77.0,63.0,20.0,22.0,2.0,0.0,15.0,5.0
Magnesium trisilicate,90.0,78.0,82.0,61.0,76.0,19.0,31.0,76.0
Polio 0,90.0,69.0,75.0,83.0,87.0,19.0,23.0,86.0
BCG vaccine,97.0,77.0,81.0,78.0,95.0,25.0,38.0,93.0
Anti-tetanus serum/TAT,87.0,80.0,74.0,65.0,57.0,6.0,46.0,58.0
Tetanus toxoid vaccine,97.0,79.0,78.0,78.0,90.0,25.0,38.0,89.0
Anti-rho (D) immune globulin,77.0,43.0,24.0,39.0,7.0,12.0,8.0,9.0
Insecticide-treated bednets(ITN),17.0,21.0,35.0,4.0,38.0,0.0,31.0,37.0
Mebendazole,93.0,97.0,98.0,87.0,95.0,25.0,62.0,95.0
Metoclopramide,100.0,99.0,96.0,78.0,78.0,25.0,62.0,79.0

In [1105]:
Percent_of_facilities_that_had_other_drugs_supply_1=(Percent_of_facilities_that_had_contraceptives_and_other_drugs.transpose(),Percent_of_facilities_that_had_other_drugs_supply.transpose())
Percent_of_facilities_that_had_other_drugs_supply=pd.concat(Percent_of_facilities_that_had_other_drugs_supply_1, keys=['Contraceptives', 'Other drugs and supplies'])
Percent_of_facilities_that_had_other_drugs_supply

Facility                                                   Referral/specialized  \

Contraceptives           Any Contraceptives use                            97.0
                         Combined oral contraceptives                      90.0
                         Progestin only pills                              93.0
                         Implants                                          90.0
                         3 month injectables                               97.0
                         Intrauterine IUDs                                 97.0
                         Male condoms                                      97.0
                         Female condoms                                     3.0
                         Emergency contraception                           93.0
Other drugs and supplies Vitamin K (for newborn)                          100.0
                         Nystatin (oral, for newborn)                      20.0
                         Oral rehydration solution                         93.0
                         Gentian violet paint                              87.0
                         Ferrous sulphate or fumarate                      47.0
                         Folic acid                                        57.0
                         Ferrous sulphate with folic acid                  80.0
                         Heparin                                           77.0
                         Magnesium trisilicate                             90.0
                         Polio 0                                           90.0
                         BCG vaccine                                       97.0
                         Anti-tetanus serum/TAT                            87.0
                         Tetanus toxoid vaccine                            97.0
                         Anti-rho (D) immune globulin                      77.0
                         Insecticide-treated bednets(ITN)                  17.0
                         Mebendazole                                       93.0
                         Metoclopramide                                   100.0

Facility                                                   General hospitals  \

Contraceptives           Any Contraceptives use                         97.0
                         Combined oral contraceptives                   91.0
                         Progestin only pills                           80.0
                         Implants                                       87.0
                         3 month injectables                            84.0
                         Intrauterine IUDs                              84.0
                         Male condoms                                   88.0
                         Female condoms                                  5.0
                         Emergency contraception                        83.0
Other drugs and supplies Vitamin K (for newborn)                        93.0
                         Nystatin (oral, for newborn)                   22.0
                         Oral rehydration solution                      97.0
                         Gentian violet paint                           85.0
                         Ferrous sulphate or fumarate                   69.0
                         Folic acid                                     65.0
                         Ferrous sulphate with folic acid               85.0
                         Heparin                                        63.0
                         Magnesium trisilicate                          78.0
                         Polio 0                                        69.0
                         BCG vaccine                                    77.0
                         Anti-tetanus serum/TAT                         80.0
                         Tetanus toxoid vaccine                         79.0
                         Anti-rho (D) immune globulin                   43.0
                         Insecticide-treated bednets(ITN)               21.0
                         Mebendazole                                    97.0
                         Metoclopramide                                 99.0

Facility                                                   Primary hospitals   \

Contraceptives           Any Contraceptives use                          97.0
                         Combined oral contraceptives                    91.0
                         Progestin only pills                            68.0
                         Implants                                        89.0
                         3 month injectables                             92.0
                         Intrauterine IUDs                               83.0
                         Male condoms                                    92.0
                         Female condoms                                   3.0
                         Emergency contraception                         88.0
Other drugs and supplies Vitamin K (for newborn)                         91.0
                         Nystatin (oral, for newborn)                    15.0
                         Oral rehydration solution                       93.0
                         Gentian violet paint                            79.0
                         Ferrous sulphate or fumarate                    61.0
                         Folic acid                                      64.0
                         Ferrous sulphate with folic acid                85.0
                         Heparin                                         20.0
                         Magnesium trisilicate                           82.0
                         Polio 0                                         75.0
                         BCG vaccine                                     81.0
                         Anti-tetanus serum/TAT                          74.0
                         Tetanus toxoid vaccine                          78.0
                         Anti-rho (D) immune globulin                    24.0
                         Insecticide-treated bednets(ITN)                35.0
                         Mebendazole                                     98.0
                         Metoclopramide                                  96.0

Facility                                                   MCH specialty centres   \

Contraceptives           Any Contraceptives use                              91.0
                         Combined oral contraceptives                        87.0
                         Progestin only pills                                78.0
                         Implants                                            83.0
                         3 month injectables                                 91.0
                         Intrauterine IUDs                                   87.0
                         Male condoms                                        78.0
                         Female condoms                                      22.0
                         Emergency contraception                             70.0
Other drugs and supplies Vitamin K (for newborn)                             91.0
                         Nystatin (oral, for newborn)                         9.0
                         Oral rehydration solution                           87.0
                         Gentian violet paint                                87.0
                         Ferrous sulphate or fumarate                        52.0
                         Folic acid                                          61.0
                         Ferrous sulphate with folic acid                    87.0
                         Heparin                                             22.0
                         Magnesium trisilicate                               61.0
                         Polio 0                                             83.0
                         BCG vaccine                                         78.0
                         Anti-tetanus serum/TAT                              65.0
                         Tetanus toxoid vaccine                              78.0
                         Anti-rho (D) immune globulin                        39.0
                         Insecticide-treated bednets(ITN)                     4.0
                         Mebendazole                                         87.0
                         Metoclopramide                                      78.0

Facility                                                   Health centres  \

Contraceptives           Any Contraceptives use                      98.0
                         Combined oral contraceptives                88.0
                         Progestin only pills                        71.0
                         Implants                                    89.0
                         3 month injectables                         92.0
                         Intrauterine IUDs                           75.0
                         Male condoms                                94.0
                         Female condoms                               3.0
                         Emergency contraception                     78.0
Other drugs and supplies Vitamin K (for newborn)                     81.0
                         Nystatin (oral, for newborn)                 4.0
                         Oral rehydration solution                   83.0
                         Gentian violet paint                        75.0
                         Ferrous sulphate or fumarate                54.0
                         Folic acid                                  40.0
                         Ferrous sulphate with folic acid            78.0
                         Heparin                                      2.0
                         Magnesium trisilicate                       76.0
                         Polio 0                                     87.0
                         BCG vaccine                                 95.0
                         Anti-tetanus serum/TAT                      57.0
                         Tetanus toxoid vaccine                      90.0
                         Anti-rho (D) immune globulin                 7.0
                         Insecticide-treated bednets(ITN)            38.0
                         Mebendazole                                 95.0
                         Metoclopramide                              78.0

Facility                                                   MCH specialty clinics  \

Contraceptives           Any Contraceptives use                             31.0
                         Combined oral contraceptives                       31.0
                         Progestin only pills                               25.0
                         Implants                                           25.0
                         3 month injectables                                31.0
                         Intrauterine IUDs                                  25.0
                         Male condoms                                       19.0
                         Female condoms                                      0.0
                         Emergency contraception                            25.0
Other drugs and supplies Vitamin K (for newborn)                            25.0
                         Nystatin (oral, for newborn)                        6.0
                         Oral rehydration solution                          25.0
                         Gentian violet paint                               31.0
                         Ferrous sulphate or fumarate                       12.0
                         Folic acid                                         12.0
                         Ferrous sulphate with folic acid                   25.0
                         Heparin                                             0.0
                         Magnesium trisilicate                              19.0
                         Polio 0                                            19.0
                         BCG vaccine                                        25.0
                         Anti-tetanus serum/TAT                              6.0
                         Tetanus toxoid vaccine                             25.0
                         Anti-rho (D) immune globulin                       12.0
                         Insecticide-treated bednets(ITN)                    0.0
                         Mebendazole                                        25.0
                         Metoclopramide                                     25.0

Facility                                                   Higher clinics  \

Contraceptives           Any Contraceptives use                      54.0
                         Combined oral contraceptives                54.0
                         Progestin only pills                        31.0
                         Implants                                    46.0
                         3 month injectables                         46.0
                         Intrauterine IUDs                           23.0
                         Male condoms                                38.0
                         Female condoms                               8.0
                         Emergency contraception                     46.0
Other drugs and supplies Vitamin K (for newborn)                     46.0
                         Nystatin (oral, for newborn)                 8.0
                         Oral rehydration solution                   62.0
                         Gentian violet paint                        54.0
                         Ferrous sulphate or fumarate                38.0
                         Folic acid                                  31.0
                         Ferrous sulphate with folic acid            62.0
                         Heparin                                     15.0
                         Magnesium trisilicate                       31.0
                         Polio 0                                     23.0
                         BCG vaccine                                 38.0
                         Anti-tetanus serum/TAT                      46.0
                         Tetanus toxoid vaccine                      38.0
                         Anti-rho (D) immune globulin                 8.0
                         Insecticide-treated bednets(ITN)            31.0
                         Mebendazole                                 62.0
                         Metoclopramide                              62.0

Facility                                                   National

Contraceptives           Any Contraceptives use               97.00
                         Combined oral contraceptives         88.00
                         Progestin only pills                 71.00
                         Implants                             88.00
                         3 month injectables                  91.00
                         Intrauterine IUDs                    75.89
                         Male condoms                         93.00
                         Female condoms                        3.00
                         Emergency contraception              78.00
Other drugs and supplies Vitamin K (for newborn)              82.00
                         Nystatin (oral, for newborn)          5.00
                         Oral rehydration solution            83.00
                         Gentian violet paint                 75.00
                         Ferrous sulphate or fumarate         55.00
                         Folic acid                           41.00
                         Ferrous sulphate with folic acid     78.00
                         Heparin                               5.00
                         Magnesium trisilicate                76.00
                         Polio 0                              86.00
                         BCG vaccine                          93.00
                         Anti-tetanus serum/TAT               58.00
                         Tetanus toxoid vaccine               89.00
                         Anti-rho (D) immune globulin          9.00
                         Insecticide-treated bednets(ITN)     37.00
                         Mebendazole                          95.00
                         Metoclopramide                       79.00

In [1106]:
Percent_of_facilities_that_had_other_drugs_supply.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Essential drugs/Percent of facilities that had contraceptives and other drugs.csv")

In [1109]:
my_tab = pd.crosstab(data['FT7'], data['Q201A_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Soap']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201A_3']==1, data['Q201A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap

                         Soap
Facility
Referral/specialized     97.0
General hospitals        98.0
Primary hospitals        93.0
MCH specialty centres   100.0
Health centres           85.0
MCH specialty clinics    94.0
Higher clinics          100.0
National                 86.0

In [1110]:
my_tab = pd.crosstab(data['FT7'], data['Q201B_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Antiseptics']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201B_3']==1, data['Q201B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics

                        Antiseptics
Facility
Referral/specialized          100.0
General hospitals              99.0
Primary hospitals              99.0
MCH specialty centres          96.0
Health centres                 93.0
MCH specialty clinics         100.0
Higher clinics                100.0
National                       93.0

In [1111]:
my_tab = pd.crosstab(data['FT7'], data['Q201C_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Disposable_latex_examination_gloves']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201C_3']==1, data['Q201C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves

                        Disposable_latex_examination_gloves
Facility
Referral/specialized                                  100.0
General hospitals                                     100.0
Primary hospitals                                      98.0
MCH specialty centres                                 100.0
Health centres                                         97.0
MCH specialty clinics                                 100.0
Higher clinics                                        100.0
National                                               97.0

In [1112]:
my_tab = pd.crosstab(data['FT7'], data['Q201D_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Elbow_length_gloves']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201D_3']==1, data['Q201D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves

                        Elbow_length_gloves
Facility
Referral/specialized                   67.0
General hospitals                      61.0
Primary hospitals                      55.0
MCH specialty centres                  61.0
Health centres                         37.0
MCH specialty clinics                  62.0
Higher clinics                         54.0
National                               39.0

In [1113]:
my_tab = pd.crosstab(data['FT7'], data['Q201E_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Heavy_duty_gloves']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201E_3']==1, data['Q201E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves

                        Heavy_duty_gloves
Facility
Referral/specialized                 97.0
General hospitals                    93.0
Primary hospitals                    94.0
MCH specialty centres                91.0
Health centres                       80.0
MCH specialty clinics               100.0
Higher clinics                       92.0
National                             81.0

In [1114]:
my_tab = pd.crosstab(data['FT7'], data['Q201F_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Eye_shields']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201F_3']==1, data['Q201F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields

                        Eye_shields
Facility
Referral/specialized          100.0
General hospitals              92.0
Primary hospitals              87.0
MCH specialty centres          96.0
Health centres                 64.0
MCH specialty clinics          81.0
Higher clinics                 92.0
National                       66.0

In [1115]:
my_tab = pd.crosstab(data['FT7'], data['Q201G_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Mask']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201G_3']==1, data['Q201G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask

                        Mask
Facility
Referral/specialized    97.0
General hospitals       96.0
Primary hospitals       96.0
MCH specialty centres   96.0
Health centres          74.0
MCH specialty clinics   94.0
Higher clinics          92.0
National                76.0

In [1116]:
my_tab = pd.crosstab(data['FT7'], data['Q201H_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Non_sterile_protective_clothing']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201H_3']==1, data['Q201H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing

                        Non_sterile_protective_clothing
Facility
Referral/specialized                              100.0
General hospitals                                 100.0
Primary hospitals                                  96.0
MCH specialty centres                             100.0
Health centres                                     84.0
MCH specialty clinics                              94.0
Higher clinics                                    100.0
National                                           85.0

In [1117]:
my_tab = pd.crosstab(data['FT7'], data['Q201I_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Decontamination_container']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201I_3']==1, data['Q201I_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container

                        Decontamination_container
Facility
Referral/specialized                        100.0
General hospitals                           100.0
Primary hospitals                            99.0
MCH specialty centres                       100.0
Health centres                               94.0
MCH specialty clinics                       100.0
Higher clinics                              100.0
National                                     95.0

In [1119]:
my_tab = pd.crosstab(data['FT7'], data['Q201J_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Bleach_or_bleaching_powder(chlorine)']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201J_3']==1, data['Q201J_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder

                        Bleach_or_bleaching_powder(chlorine)
Facility
Referral/specialized                                    90.0
General hospitals                                       94.0
Primary hospitals                                       89.0
MCH specialty centres                                  100.0
Health centres                                          84.0
MCH specialty clinics                                   94.0
Higher clinics                                          92.0
National                                                84.0

In [1120]:
my_tab = pd.crosstab(data['FT7'], data['Q201K_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Prepared_disinfection_solution']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201K_3']==1, data['Q201K_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution

                        Prepared_disinfection_solution
Facility
Referral/specialized                             100.0
General hospitals                                 99.0
Primary hospitals                                 98.0
MCH specialty centres                             96.0
Health centres                                    90.0
MCH specialty clinics                             94.0
Higher clinics                                   100.0
National                                          91.0

In [1121]:
my_tab = pd.crosstab(data['FT7'], data['Q201L_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Regular_trash_bin']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201L_3']==1, data['Q201L_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin

                        Regular_trash_bin
Facility
Referral/specialized                 97.0
General hospitals                    97.0
Primary hospitals                    96.0
MCH specialty centres               100.0
Health centres                       84.0
MCH specialty clinics                94.0
Higher clinics                       92.0
National                             85.0

In [1123]:
my_tab = pd.crosstab(data['FT7'], data['Q201M_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Covered_contaminated_waste_trash bin']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201M_3']==1, data['Q201M_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash

                        Covered_contaminated_waste_trash bin
Facility
Referral/specialized                                    93.0
General hospitals                                       93.0
Primary hospitals                                       74.0
MCH specialty centres                                   91.0
Health centres                                          60.0
MCH specialty clinics                                   88.0
Higher clinics                                          54.0
National                                                62.0

In [1124]:
my_tab = pd.crosstab(data['FT7'], data['Q201N_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Puncture_proof_sharps_container']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201N_3']==1, data['Q201N_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container

                        Puncture_proof_sharps_container
Facility
Referral/specialized                               97.0
General hospitals                                  98.0
Primary hospitals                                 100.0
MCH specialty centres                             100.0
Health centres                                     96.0
MCH specialty clinics                              94.0
Higher clinics                                    100.0
National                                           96.0

In [1126]:
my_tab = pd.crosstab(data['FT7'], data['Q201O_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Mayo_stand_table_or_equivalent_to_establish_sterile_field']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201O_3']==1, data['Q201O_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field

                        Mayo_stand_table_or_equivalent_to_establish_sterile_field
Facility
Referral/specialized                                                 90.0
General hospitals                                                    83.0
Primary hospitals                                                    67.0
MCH specialty centres                                                78.0
Health centres                                                       46.0
MCH specialty clinics                                                88.0
Higher clinics                                                       69.0
National                                                             48.0

In [1127]:
my_tab = pd.crosstab(data['FT7'], data['Q201P_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Surgeon_hand_brush_with_nylon_bristles']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201P_3']==1, data['Q201P_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles

                        Surgeon_hand_brush_with_nylon_bristles
Facility
Referral/specialized                                      67.0
General hospitals                                         86.0
Primary hospitals                                         56.0
MCH specialty centres                                     83.0
Health centres                                            21.0
MCH specialty clinics                                     50.0
Higher clinics                                            31.0
National                                                  25.0

In [1128]:
my_tab = pd.crosstab(data['FT7'], data['Q201Q_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Surgeon_boots']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q201Q_3']==1, data['Q201Q_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots

                        Surgeon_boots
Facility
Referral/specialized            100.0
General hospitals                94.0
Primary hospitals                85.0
MCH specialty centres            96.0
Health centres                   55.0
MCH specialty clinics            81.0
Higher clinics                   85.0
National                         58.0

In [1129]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_4=(Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Soap,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Antiseptics,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Disposable_latex_examination_gloves,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Elbow_length_gloves,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Heavy_duty_gloves,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Eye_shields,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mask,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Non_sterile_protective_clothing,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Decontamination_container,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Bleach_or_bleaching_powder,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Prepared_disinfection_solution,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Regular_trash_bin,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Covered_contaminated_waste_trash,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Puncture_proof_sharps_container,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Mayo_stand_table_or_equivalent_to_establish_sterile_field,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_hand_brush_with_nylon_bristles,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Surgeon_boots)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention=pd.concat( Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_4, axis=1, sort=False)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention.transpose()

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Soap,97.0,98.0,93.0,100.0,85.0,94.0,100.0,86.0
Antiseptics,100.0,99.0,99.0,96.0,93.0,100.0,100.0,93.0
Disposable_latex_examination_gloves,100.0,100.0,98.0,100.0,97.0,100.0,100.0,97.0
Elbow_length_gloves,67.0,61.0,55.0,61.0,37.0,62.0,54.0,39.0
Heavy_duty_gloves,97.0,93.0,94.0,91.0,80.0,100.0,92.0,81.0
Eye_shields,100.0,92.0,87.0,96.0,64.0,81.0,92.0,66.0
Mask,97.0,96.0,96.0,96.0,74.0,94.0,92.0,76.0
Non_sterile_protective_clothing,100.0,100.0,96.0,100.0,84.0,94.0,100.0,85.0
Decontamination_container,100.0,100.0,99.0,100.0,94.0,100.0,100.0,95.0
Bleach_or_bleaching_powder(chlorine),90.0,94.0,89.0,100.0,84.0,94.0,92.0,84.0
Prepared_disinfection_solution,100.0,99.0,98.0,96.0,90.0,94.0,100.0,91.0
Regular_trash_bin,97.0,97.0,96.0,100.0,84.0,94.0,92.0,85.0
Covered_contaminated_waste_trash bin,93.0,93.0,74.0,91.0,60.0,88.0,54.0,62.0
Puncture_proof_sharps_container,97.0,98.0,100.0,100.0,96.0,94.0,100.0,96.0
Mayo_stand_table_or_equivalent_to_establish_sterile_field,90.0,83.0,67.0,78.0,46.0,88.0,69.0,48.0
Surgeon_hand_brush_with_nylon_bristles,67.0,86.0,56.0,83.0,21.0,50.0,31.0,25.0
Surgeon_boots,100.0,94.0,85.0,96.0,55.0,81.0,85.0,58.0

In [1136]:
my_tab = pd.crosstab(data['FT7'], data['Q202A_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Chlorhexidine_4Perc_gel']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202A_3']==1, data['Q202A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel

                        Chlorhexidine_4Perc_gel
Facility
Referral/specialized                       13.0
General hospitals                          35.0
Primary hospitals                          18.0
MCH specialty centres                      26.0
Health centres                             14.0
MCH specialty clinics                      12.0
Higher clinics                             23.0
National                                   15.0

In [1138]:
my_tab = pd.crosstab(data['FT7'], data['Q202B_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Chlorhexidine_solution_Savlon']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202B_3']==1, data['Q202B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),2)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon

                        Chlorhexidine_solution_Savlon
Facility
Referral/specialized                            70.00
General hospitals                               91.00
Primary hospitals                               87.00
MCH specialty centres                           91.00
Health centres                                  83.00
MCH specialty clinics                           81.00
Higher clinics                                 100.00
National                                        83.49

In [1139]:
my_tab = pd.crosstab(data['FT7'], data['Q202C_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ethanol_75_percent']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202C_3']==1, data['Q202C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent

                        Ethanol_75_percent
Facility
Referral/specialized                  70.0
General hospitals                     68.0
Primary hospitals                     59.0
MCH specialty centres                 78.0
Health centres                        42.0
MCH specialty clinics                 75.0
Higher clinics                        23.0
National                              44.0

In [1140]:
my_tab = pd.crosstab(data['FT7'], data['Q202D_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ethanol_95_percent']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202D_3']==1, data['Q202D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent

                        Ethanol_95_percent
Facility
Referral/specialized                  37.0
General hospitals                     28.0
Primary hospitals                     28.0
MCH specialty centres                 52.0
Health centres                        13.0
MCH specialty clinics                 38.0
Higher clinics                        23.0
National                              15.0

In [1141]:
my_tab = pd.crosstab(data['FT7'], data['Q202E_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Polyvidone_iodine']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202E_3']==1, data['Q202E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine

                        Polyvidone_iodine
Facility
Referral/specialized                 97.0
General hospitals                    96.0
Primary hospitals                    87.0
MCH specialty centres                96.0
Health centres                       77.0
MCH specialty clinics               100.0
Higher clinics                       92.0
National                             78.0

In [1142]:
my_tab = pd.crosstab(data['FT7'], data['Q202F_3'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub[0]
del  Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Alcohol_based_rub']
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub.columns= labels_of_col[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub.index= labels_of_col1[1:]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub.columns.names= [labels_of_col[0]]
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q202F_3']==1, data['Q202F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub.loc['National'] = cc
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub

                        Alcohol_based_rub
Facility
Referral/specialized                 93.0
General hospitals                    95.0
Primary hospitals                    87.0
MCH specialty centres                74.0
Health centres                       71.0
MCH specialty clinics                88.0
Higher clinics                      100.0
National                             73.0

In [1143]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_4=(Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_4Perc_gel,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Chlorhexidine_solution_Savlon,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_75_percent,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Ethanol_95_percent,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Polyvidone_iodine,Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Alcohol_based_rub,)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity=pd.concat( Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_4, axis=1, sort=False)
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity

,Chlorhexidine_4Perc_gel,Chlorhexidine_solution_Savlon,Ethanol_75_percent,Ethanol_95_percent,Polyvidone_iodine,Alcohol_based_rub
Facility,,,,,,
Referral/specialized,13.0,70.00,70.0,37.0,97.0,93.0
General hospitals,35.0,91.00,68.0,28.0,96.0,95.0
Primary hospitals,18.0,87.00,59.0,28.0,87.0,87.0
MCH specialty centres,26.0,91.00,78.0,52.0,96.0,74.0
Health centres,14.0,83.00,42.0,13.0,77.0,71.0
MCH specialty clinics,12.0,81.00,75.0,38.0,100.0,88.0
Higher clinics,23.0,100.00,23.0,23.0,92.0,100.0
National,15.0,83.49,44.0,15.0,78.0,73.0

In [1145]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Location_1=(Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention.transpose(),Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity.transpose())
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area=pd.concat(Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Location_1, keys=['Basic items', 'Disinfectants and antiseptics'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area

Facility                                                                          Referral/specialized  \

Basic items                   Soap                                                                97.0
                              Antiseptics                                                        100.0
                              Disposable_latex_examination_gloves                                100.0
                              Elbow_length_gloves                                                 67.0
                              Heavy_duty_gloves                                                   97.0
                              Eye_shields                                                        100.0
                              Mask                                                                97.0
                              Non_sterile_protective_clothing                                    100.0
                              Decontamination_container                                          100.0
                              Bleach_or_bleaching_powder(chlorine)                                90.0
                              Prepared_disinfection_solution                                     100.0
                              Regular_trash_bin                                                   97.0
                              Covered_contaminated_waste_trash bin                                93.0
                              Puncture_proof_sharps_container                                     97.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...                  90.0
                              Surgeon_hand_brush_with_nylon_bristles                              67.0
                              Surgeon_boots                                                      100.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                             13.0
                              Chlorhexidine_solution_Savlon                                       70.0
                              Ethanol_75_percent                                                  70.0
                              Ethanol_95_percent                                                  37.0
                              Polyvidone_iodine                                                   97.0
                              Alcohol_based_rub                                                   93.0

Facility                                                                          General hospitals  \

Basic items                   Soap                                                             98.0
                              Antiseptics                                                      99.0
                              Disposable_latex_examination_gloves                             100.0
                              Elbow_length_gloves                                              61.0
                              Heavy_duty_gloves                                                93.0
                              Eye_shields                                                      92.0
                              Mask                                                             96.0
                              Non_sterile_protective_clothing                                 100.0
                              Decontamination_container                                       100.0
                              Bleach_or_bleaching_powder(chlorine)                             94.0
                              Prepared_disinfection_solution                                   99.0
                              Regular_trash_bin                                                97.0
                              Covered_contaminated_waste_trash bin                             93.0
                              Puncture_proof_sharps_container                                  98.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...               83.0
                              Surgeon_hand_brush_with_nylon_bristles                           86.0
                              Surgeon_boots                                                    94.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                          35.0
                              Chlorhexidine_solution_Savlon                                    91.0
                              Ethanol_75_percent                                               68.0
                              Ethanol_95_percent                                               28.0
                              Polyvidone_iodine                                                96.0
                              Alcohol_based_rub                                                95.0

Facility                                                                          Primary hospitals   \

Basic items                   Soap                                                              93.0
                              Antiseptics                                                       99.0
                              Disposable_latex_examination_gloves                               98.0
                              Elbow_length_gloves                                               55.0
                              Heavy_duty_gloves                                                 94.0
                              Eye_shields                                                       87.0
                              Mask                                                              96.0
                              Non_sterile_protective_clothing                                   96.0
                              Decontamination_container                                         99.0
                              Bleach_or_bleaching_powder(chlorine)                              89.0
                              Prepared_disinfection_solution                                    98.0
                              Regular_trash_bin                                                 96.0
                              Covered_contaminated_waste_trash bin                              74.0
                              Puncture_proof_sharps_container                                  100.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...                67.0
                              Surgeon_hand_brush_with_nylon_bristles                            56.0
                              Surgeon_boots                                                     85.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                           18.0
                              Chlorhexidine_solution_Savlon                                     87.0
                              Ethanol_75_percent                                                59.0
                              Ethanol_95_percent                                                28.0
                              Polyvidone_iodine                                                 87.0
                              Alcohol_based_rub                                                 87.0

Facility                                                                          MCH specialty centres   \

Basic items                   Soap                                                                 100.0
                              Antiseptics                                                           96.0
                              Disposable_latex_examination_gloves                                  100.0
                              Elbow_length_gloves                                                   61.0
                              Heavy_duty_gloves                                                     91.0
                              Eye_shields                                                           96.0
                              Mask                                                                  96.0
                              Non_sterile_protective_clothing                                      100.0
                              Decontamination_container                                            100.0
                              Bleach_or_bleaching_powder(chlorine)                                 100.0
                              Prepared_disinfection_solution                                        96.0
                              Regular_trash_bin                                                    100.0
                              Covered_contaminated_waste_trash bin                                  91.0
                              Puncture_proof_sharps_container                                      100.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...                    78.0
                              Surgeon_hand_brush_with_nylon_bristles                                83.0
                              Surgeon_boots                                                         96.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                               26.0
                              Chlorhexidine_solution_Savlon                                         91.0
                              Ethanol_75_percent                                                    78.0
                              Ethanol_95_percent                                                    52.0
                              Polyvidone_iodine                                                     96.0
                              Alcohol_based_rub                                                     74.0

Facility                                                                          Health centres  \

Basic items                   Soap                                                          85.0
                              Antiseptics                                                   93.0
                              Disposable_latex_examination_gloves                           97.0
                              Elbow_length_gloves                                           37.0
                              Heavy_duty_gloves                                             80.0
                              Eye_shields                                                   64.0
                              Mask                                                          74.0
                              Non_sterile_protective_clothing                               84.0
                              Decontamination_container                                     94.0
                              Bleach_or_bleaching_powder(chlorine)                          84.0
                              Prepared_disinfection_solution                                90.0
                              Regular_trash_bin                                             84.0
                              Covered_contaminated_waste_trash bin                          60.0
                              Puncture_proof_sharps_container                               96.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...            46.0
                              Surgeon_hand_brush_with_nylon_bristles                        21.0
                              Surgeon_boots                                                 55.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                       14.0
                              Chlorhexidine_solution_Savlon                                 83.0
                              Ethanol_75_percent                                            42.0
                              Ethanol_95_percent                                            13.0
                              Polyvidone_iodine                                             77.0
                              Alcohol_based_rub                                             71.0

Facility                                                                          MCH specialty clinics  \

Basic items                   Soap                                                                 94.0
                              Antiseptics                                                         100.0
                              Disposable_latex_examination_gloves                                 100.0
                              Elbow_length_gloves                                                  62.0
                              Heavy_duty_gloves                                                   100.0
                              Eye_shields                                                          81.0
                              Mask                                                                 94.0
                              Non_sterile_protective_clothing                                      94.0
                              Decontamination_container                                           100.0
                              Bleach_or_bleaching_powder(chlorine)                                 94.0
                              Prepared_disinfection_solution                                       94.0
                              Regular_trash_bin                                                    94.0
                              Covered_contaminated_waste_trash bin                                 88.0
                              Puncture_proof_sharps_container                                      94.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...                   88.0
                              Surgeon_hand_brush_with_nylon_bristles                               50.0
                              Surgeon_boots                                                        81.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                              12.0
                              Chlorhexidine_solution_Savlon                                        81.0
                              Ethanol_75_percent                                                   75.0
                              Ethanol_95_percent                                                   38.0
                              Polyvidone_iodine                                                   100.0
                              Alcohol_based_rub                                                    88.0

Facility                                                                          Higher clinics  \

Basic items                   Soap                                                         100.0
                              Antiseptics                                                  100.0
                              Disposable_latex_examination_gloves                          100.0
                              Elbow_length_gloves                                           54.0
                              Heavy_duty_gloves                                             92.0
                              Eye_shields                                                   92.0
                              Mask                                                          92.0
                              Non_sterile_protective_clothing                              100.0
                              Decontamination_container                                    100.0
                              Bleach_or_bleaching_powder(chlorine)                          92.0
                              Prepared_disinfection_solution                               100.0
                              Regular_trash_bin                                             92.0
                              Covered_contaminated_waste_trash bin                          54.0
                              Puncture_proof_sharps_container                              100.0
                              Mayo_stand_table_or_equivalent_to_establish_ste...            69.0
                              Surgeon_hand_brush_with_nylon_bristles                        31.0
                              Surgeon_boots                                                 85.0
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                       23.0
                              Chlorhexidine_solution_Savlon                                100.0
                              Ethanol_75_percent                                            23.0
                              Ethanol_95_percent                                            23.0
                              Polyvidone_iodine                                             92.0
                              Alcohol_based_rub                                            100.0

Facility                                                                          National

Basic items                   Soap                                                   86.00
                              Antiseptics                                            93.00
                              Disposable_latex_examination_gloves                    97.00
                              Elbow_length_gloves                                    39.00
                              Heavy_duty_gloves                                      81.00
                              Eye_shields                                            66.00
                              Mask                                                   76.00
                              Non_sterile_protective_clothing                        85.00
                              Decontamination_container                              95.00
                              Bleach_or_bleaching_powder(chlorine)                   84.00
                              Prepared_disinfection_solution                         91.00
                              Regular_trash_bin                                      85.00
                              Covered_contaminated_waste_trash bin                   62.00
                              Puncture_proof_sharps_container                        96.00
                              Mayo_stand_table_or_equivalent_to_establish_ste...     48.00
                              Surgeon_hand_brush_with_nylon_bristles                 25.00
                              Surgeon_boots                                          58.00
Disinfectants and antiseptics Chlorhexidine_4Perc_gel                                15.00
                              Chlorhexidine_solution_Savlon                          83.49
                              Ethanol_75_percent                                     44.00
                              Ethanol_95_percent                                     15.00
                              Polyvidone_iodine                                      78.00
                              Alcohol_based_rub                                      73.00

In [1146]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Infection prevention and autoclave room/Percent of facilities that had the indicated materials for infection prevention in the maternity area.csv")

In [1166]:
my_tab = pd.crosstab(data['FT7'], data['Q258_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave[96]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Has separate equipment and space','Shares with other services','Other']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q258_3']==1, data['Q258_3']==1)
my_tab122 = pd.crosstab(data['Q258_3']==2, data['Q258_3']==2)
my_tab123 = pd.crosstab(data['Q258_3']==3, data['Q258_3']==3)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
my_tab11 = ((my_tab122[1][1])/b)*100
my_tab12 = ((my_tab123[1][1])/b)*100
cc= round((my_tab1),0)
cc1= round((my_tab11),0)
cc2= round((my_tab12),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.loc['National'][1] = cc1
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.loc['National'][2] = cc2
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave

,Has separate equipment and space,Shares with other services,Other
Facility,,,
Referral/specialized,80.0,17.0,3.0
General hospitals,73.0,27.0,0.0
Primary hospitals,64.0,36.0,1.0
MCH specialty centres,83.0,17.0,0.0
Health centres,46.0,51.0,3.0
MCH specialty clinics,69.0,31.0,0.0
Higher clinics,54.0,46.0,0.0
National,48.0,49.0,3.0

In [1169]:
my_tab = pd.crosstab(data['FT7'], data['Q259A_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Autoclave (with temperature and pressure gauges)']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259A_3']==1, data['Q259A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave

                        Autoclave (with temperature and pressure gauges)
Facility
Referral/specialized                                                80.0
General hospitals                                                   87.0
Primary hospitals                                                   77.0
MCH specialty centres                                               83.0
Health centres                                                      48.0
MCH specialty clinics                                               69.0
Higher clinics                                                      77.0
National                                                            51.0

In [1170]:
my_tab = pd.crosstab(data['FT7'], data['Q259B_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Hot air sterilizer (dry oven)']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259B_3']==1, data['Q259B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven

                        Hot air sterilizer (dry oven)
Facility
Referral/specialized                             53.0
General hospitals                                59.0
Primary hospitals                                45.0
MCH specialty centres                            52.0
Health centres                                   21.0
MCH specialty clinics                            19.0
Higher clinics                                   31.0
National                                         23.0

In [1172]:
my_tab = pd.crosstab(data['FT7'], data['Q259C_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Steamm sterilizer']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259C_3']==1, data['Q259C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer

                        Steamm sterilizer
Facility
Referral/specialized                 70.0
General hospitals                    69.0
Primary hospitals                    61.0
MCH specialty centres                65.0
Health centres                       36.0
MCH specialty clinics                62.0
Higher clinics                       46.0
National                             39.0

In [1173]:
my_tab = pd.crosstab(data['FT7'], data['Q259D_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Steam instrument sterilizer/pressure cooker (electric)']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259D_3']==1, data['Q259D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize

                        Steam instrument sterilizer/pressure cooker (electric)
Facility
Referral/specialized                                                 40.0
General hospitals                                                    54.0
Primary hospitals                                                    49.0
MCH specialty centres                                                61.0
Health centres                                                       20.0
MCH specialty clinics                                                50.0
Higher clinics                                                       38.0
National                                                             22.0

In [1175]:
my_tab = pd.crosstab(data['FT7'], data['Q259E_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sterilizer/pressure cooker (kerosene heated)']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259E_3']==1, data['Q259E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer

                        Sterilizer/pressure cooker (kerosene heated)
Facility
Referral/specialized                                            17.0
General hospitals                                               19.0
Primary hospitals                                               18.0
MCH specialty centres                                           22.0
Health centres                                                  47.0
MCH specialty clinics                                           12.0
Higher clinics                                                  15.0
National                                                        45.0

In [1176]:
my_tab = pd.crosstab(data['FT7'], data['Q259F_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sterilization drum ']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259F_3']==1, data['Q259F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum

                        Sterilization drum
Facility
Referral/specialized                   93.0
General hospitals                      96.0
Primary hospitals                      94.0
MCH specialty centres                  96.0
Health centres                         83.0
MCH specialty clinics                  94.0
Higher clinics                         85.0
National                               84.0

In [1177]:
my_tab = pd.crosstab(data['FT7'], data['Q259G_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sterilization drum stand']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q259G_3']==1, data['Q259G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand

                        Sterilization drum stand
Facility
Referral/specialized                        90.0
General hospitals                           91.0
Primary hospitals                           82.0
MCH specialty centres                       87.0
Health centres                              64.0
MCH specialty clinics                       75.0
Higher clinics                              77.0
National                                    66.0

In [1179]:
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_4=(Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Autoclave,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Hot_air_sterilizer_dry_oven,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_sterilizer,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Steam_instrument_sterilize,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilizer,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Sterilization_drum_stand)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area=pd.concat( Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_4, axis=1, sort=False)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area

,Autoclave (with temperature and pressure gauges),Hot air sterilizer (dry oven),Steamm sterilizer,Steam instrument sterilizer/pressure cooker (electric),Sterilizer/pressure cooker (kerosene heated),Sterilization drum,Sterilization drum stand
Facility,,,,,,,
Referral/specialized,80.0,53.0,70.0,40.0,17.0,93.0,90.0
General hospitals,87.0,59.0,69.0,54.0,19.0,96.0,91.0
Primary hospitals,77.0,45.0,61.0,49.0,18.0,94.0,82.0
MCH specialty centres,83.0,52.0,65.0,61.0,22.0,96.0,87.0
Health centres,48.0,21.0,36.0,20.0,47.0,83.0,64.0
MCH specialty clinics,69.0,19.0,62.0,50.0,12.0,94.0,75.0
Higher clinics,77.0,31.0,46.0,38.0,15.0,85.0,77.0
National,51.0,23.0,39.0,22.0,45.0,84.0,66.0

In [1181]:
my_tab = pd.crosstab(data['FT7'], data['Q260_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Functioning incinerator']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q260_3']==1, data['Q260_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator

                        Functioning incinerator
Facility
Referral/specialized                      100.0
General hospitals                          99.0
Primary hospitals                          93.0
MCH specialty centres                      87.0
Health centres                             81.0
MCH specialty clinics                      88.0
Higher clinics                             69.0
National                                   82.0

In [1182]:
my_tab = pd.crosstab(data['FT7'], data['Q261_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Placenta pit']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q261_3']==1, data['Q261_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit

                        Placenta pit
Facility
Referral/specialized           100.0
General hospitals               98.0
Primary hospitals               98.0
MCH specialty centres          100.0
Health centres                  91.0
MCH specialty clinics           94.0
Higher clinics                  85.0
National                        92.0

In [1183]:
my_tab = pd.crosstab(data['FT7'], data['Q262_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Food is provided to clients by facility']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q262_3']==1, data['Q262_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility

                        Food is provided to clients by facility
Facility
Referral/specialized                                       90.0
General hospitals                                          70.0
Primary hospitals                                          42.0
MCH specialty centres                                      13.0
Health centres                                             49.0
MCH specialty clinics                                      12.0
Higher clinics                                              8.0
National                                                   49.0

In [1185]:
my_tab = pd.crosstab(data['FT7'], data['Q263A_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Are empty beds for the next patients in first stage (labor)']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q263A_3']==1, data['Q263A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage

                        Are empty beds for the next patients in first stage (labor)
Facility
Referral/specialized                                                 83.0
General hospitals                                                    92.0
Primary hospitals                                                    94.0
MCH specialty centres                                               100.0
Health centres                                                       73.0
MCH specialty clinics                                                81.0
Higher clinics                                                       92.0
National                                                             75.0

In [1186]:
my_tab = pd.crosstab(data['FT7'], data['Q263B_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Are empty beds for the next patients in Postnatal']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q263B_3']==1, data['Q263B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal

                        Are empty beds for the next patients in Postnatal
Facility
Referral/specialized                                                 87.0
General hospitals                                                    92.0
Primary hospitals                                                    96.0
MCH specialty centres                                               100.0
Health centres                                                       84.0
MCH specialty clinics                                                81.0
Higher clinics                                                       85.0
National                                                             85.0

In [1188]:
my_tab = pd.crosstab(data['FT7'], data['Q263C_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Are empty beds for the next patients in Obstetrics']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q263C_3']==1, data['Q263C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics

                        Are empty beds for the next patients in Obstetrics
Facility
Referral/specialized                                                 87.0
General hospitals                                                    93.0
Primary hospitals                                                    93.0
MCH specialty centres                                                87.0
Health centres                                                       72.0
MCH specialty clinics                                                81.0
Higher clinics                                                       92.0
National                                                             74.0

In [1190]:
my_tab = pd.crosstab(data['FT7'], data['Q264_3'])
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors[0]
#del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors[0]
del  Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Liquid spills or trash observed on floors']
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors.columns= labels_of_col[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors.index= labels_of_col1[1:]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q264_3']==1, data['Q264_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors.loc['National'] = cc
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors

                        Liquid spills or trash observed on floors
Facility
Referral/specialized                                         23.0
General hospitals                                            17.0
Primary hospitals                                            18.0
MCH specialty centres                                        13.0
Health centres                                               21.0
MCH specialty clinics                                         6.0
Higher clinics                                               15.0
National                                                     21.0

In [1191]:
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_Miscellaneous_item_4=(Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_incinerator,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Placenta_pit,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Food_is_provided_to_clients_by_facility,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Empty_bed_available_for_First_stage,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Postnatal,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Obstetrics,Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Sterilization_equipment_Liquid_spills_or_trash_observed_on_floors,)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_Miscellaneous_item=pd.concat( Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_Miscellaneous_item_4, axis=1, sort=False)
Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_Miscellaneous_item

,Functioning incinerator,Placenta pit,Food is provided to clients by facility,Are empty beds for the next patients in first stage (labor),Are empty beds for the next patients in Postnatal,Are empty beds for the next patients in Obstetrics,Liquid spills or trash observed on floors
Facility,,,,,,,
Referral/specialized,100.0,100.0,90.0,83.0,87.0,87.0,23.0
General hospitals,99.0,98.0,70.0,92.0,92.0,93.0,17.0
Primary hospitals,93.0,98.0,42.0,94.0,96.0,93.0,18.0
MCH specialty centres,87.0,100.0,13.0,100.0,100.0,87.0,13.0
Health centres,81.0,91.0,49.0,73.0,84.0,72.0,21.0
MCH specialty clinics,88.0,94.0,12.0,81.0,81.0,81.0,6.0
Higher clinics,69.0,85.0,8.0,92.0,85.0,92.0,15.0
National,82.0,92.0,49.0,75.0,85.0,74.0,21.0

In [1194]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Location_1=(Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area_Physical_space_for_autoclave.transpose(),Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_items_in_the_maternity_area.transpose(),Percent_of_facilities_with_sterilization_equipment_and_other_miscellaneous_Miscellaneous_item.transpose())
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area1=pd.concat(Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area_Location_1, keys=['Physical space for autoclave', 'Sterilization equipment','Miscellaneous items'])
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area1

Facility                                                                         Referral/specialized  \

Physical space for autoclave Has separate equipment and space                                    80.0
                             Shares with other services                                          17.0
                             Other                                                                3.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)                    80.0
                             Hot air sterilizer (dry oven)                                       53.0
                             Steamm sterilizer                                                   70.0
                             Steam instrument sterilizer/pressure cooker (el...                  40.0
                             Sterilizer/pressure cooker (kerosene heated)                        17.0
                             Sterilization drum                                                  93.0
                             Sterilization drum stand                                            90.0
Miscellaneous items          Functioning incinerator                                            100.0
                             Placenta pit                                                       100.0
                             Food is provided to clients by facility                             90.0
                             Are empty beds for the next patients in first s...                  83.0
                             Are empty beds for the next patients in Postnatal                   87.0
                             Are empty beds for the next patients in Obstetrics                  87.0
                             Liquid spills or trash observed on floors                           23.0

Facility                                                                         General hospitals  \

Physical space for autoclave Has separate equipment and space                                 73.0
                             Shares with other services                                       27.0
                             Other                                                             0.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)                 87.0
                             Hot air sterilizer (dry oven)                                    59.0
                             Steamm sterilizer                                                69.0
                             Steam instrument sterilizer/pressure cooker (el...               54.0
                             Sterilizer/pressure cooker (kerosene heated)                     19.0
                             Sterilization drum                                               96.0
                             Sterilization drum stand                                         91.0
Miscellaneous items          Functioning incinerator                                          99.0
                             Placenta pit                                                     98.0
                             Food is provided to clients by facility                          70.0
                             Are empty beds for the next patients in first s...               92.0
                             Are empty beds for the next patients in Postnatal                92.0
                             Are empty beds for the next patients in Obstetrics               93.0
                             Liquid spills or trash observed on floors                        17.0

Facility                                                                         Primary hospitals   \

Physical space for autoclave Has separate equipment and space                                  64.0
                             Shares with other services                                        36.0
                             Other                                                              1.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)                  77.0
                             Hot air sterilizer (dry oven)                                     45.0
                             Steamm sterilizer                                                 61.0
                             Steam instrument sterilizer/pressure cooker (el...                49.0
                             Sterilizer/pressure cooker (kerosene heated)                      18.0
                             Sterilization drum                                                94.0
                             Sterilization drum stand                                          82.0
Miscellaneous items          Functioning incinerator                                           93.0
                             Placenta pit                                                      98.0
                             Food is provided to clients by facility                           42.0
                             Are empty beds for the next patients in first s...                94.0
                             Are empty beds for the next patients in Postnatal                 96.0
                             Are empty beds for the next patients in Obstetrics                93.0
                             Liquid spills or trash observed on floors                         18.0

Facility                                                                         MCH specialty centres   \

Physical space for autoclave Has separate equipment and space                                      83.0
                             Shares with other services                                            17.0
                             Other                                                                  0.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)                      83.0
                             Hot air sterilizer (dry oven)                                         52.0
                             Steamm sterilizer                                                     65.0
                             Steam instrument sterilizer/pressure cooker (el...                    61.0
                             Sterilizer/pressure cooker (kerosene heated)                          22.0
                             Sterilization drum                                                    96.0
                             Sterilization drum stand                                              87.0
Miscellaneous items          Functioning incinerator                                               87.0
                             Placenta pit                                                         100.0
                             Food is provided to clients by facility                               13.0
                             Are empty beds for the next patients in first s...                   100.0
                             Are empty beds for the next patients in Postnatal                    100.0
                             Are empty beds for the next patients in Obstetrics                    87.0
                             Liquid spills or trash observed on floors                             13.0

Facility                                                                         Health centres  \

Physical space for autoclave Has separate equipment and space                              46.0
                             Shares with other services                                    51.0
                             Other                                                          3.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)              48.0
                             Hot air sterilizer (dry oven)                                 21.0
                             Steamm sterilizer                                             36.0
                             Steam instrument sterilizer/pressure cooker (el...            20.0
                             Sterilizer/pressure cooker (kerosene heated)                  47.0
                             Sterilization drum                                            83.0
                             Sterilization drum stand                                      64.0
Miscellaneous items          Functioning incinerator                                       81.0
                             Placenta pit                                                  91.0
                             Food is provided to clients by facility                       49.0
                             Are empty beds for the next patients in first s...            73.0
                             Are empty beds for the next patients in Postnatal             84.0
                             Are empty beds for the next patients in Obstetrics            72.0
                             Liquid spills or trash observed on floors                     21.0

Facility                                                                         MCH specialty clinics  \

Physical space for autoclave Has separate equipment and space                                     69.0
                             Shares with other services                                           31.0
                             Other                                                                 0.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)                     69.0
                             Hot air sterilizer (dry oven)                                        19.0
                             Steamm sterilizer                                                    62.0
                             Steam instrument sterilizer/pressure cooker (el...                   50.0
                             Sterilizer/pressure cooker (kerosene heated)                         12.0
                             Sterilization drum                                                   94.0
                             Sterilization drum stand                                             75.0
Miscellaneous items          Functioning incinerator                                              88.0
                             Placenta pit                                                         94.0
                             Food is provided to clients by facility                              12.0
                             Are empty beds for the next patients in first s...                   81.0
                             Are empty beds for the next patients in Postnatal                    81.0
                             Are empty beds for the next patients in Obstetrics                   81.0
                             Liquid spills or trash observed on floors                             6.0

Facility                                                                         Higher clinics  \

Physical space for autoclave Has separate equipment and space                              54.0
                             Shares with other services                                    46.0
                             Other                                                          0.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)              77.0
                             Hot air sterilizer (dry oven)                                 31.0
                             Steamm sterilizer                                             46.0
                             Steam instrument sterilizer/pressure cooker (el...            38.0
                             Sterilizer/pressure cooker (kerosene heated)                  15.0
                             Sterilization drum                                            85.0
                             Sterilization drum stand                                      77.0
Miscellaneous items          Functioning incinerator                                       69.0
                             Placenta pit                                                  85.0
                             Food is provided to clients by facility                        8.0
                             Are empty beds for the next patients in first s...            92.0
                             Are empty beds for the next patients in Postnatal             85.0
                             Are empty beds for the next patients in Obstetrics            92.0
                             Liquid spills or trash observed on floors                     15.0

Facility                                                                         National

Physical space for autoclave Has separate equipment and space                        48.0
                             Shares with other services                              49.0
                             Other                                                    3.0
Sterilization equipment      Autoclave (with temperature and pressure gauges)        51.0
                             Hot air sterilizer (dry oven)                           23.0
                             Steamm sterilizer                                       39.0
                             Steam instrument sterilizer/pressure cooker (el...      22.0
                             Sterilizer/pressure cooker (kerosene heated)            45.0
                             Sterilization drum                                      84.0
                             Sterilization drum stand                                66.0
Miscellaneous items          Functioning incinerator                                 82.0
                             Placenta pit                                            92.0
                             Food is provided to clients by facility                 49.0
                             Are empty beds for the next patients in first s...      75.0
                             Are empty beds for the next patients in Postnatal       85.0
                             Are empty beds for the next patients in Obstetrics      74.0
                             Liquid spills or trash observed on floors               21.0

In [1195]:
Percent_of_facilities_that_had_the_indicated_materials_for_infection_prevention_in_the_maternity_area1.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Infection prevention and autoclave room/ Percent of facilities with sterilization equipment and other miscellaneous items in the maternity area.csv")

In [83]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207L_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Family_planning  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Family planning']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Family_planning .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Family_planning .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Family_planning

                 Percent of facilities that have the indicated guidelines in the maternity_area
\t
Family planning                                               78.0

In [84]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207I_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_IMNCI  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Treatment of infections in young infants(IMNCI)']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_IMNCI .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_IMNCI .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_IMNCI

                                                 Percent of facilities that have the indicated guidelines in the maternity_area
\t
Treatment of infections in young infants(IMNCI)                                               72.0

In [85]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207H_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Neonatal_resuscitation  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Neonatal resuscitation']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Neonatal_resuscitation .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Neonatal_resuscitation .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Neonatal_resuscitation

                        Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal resuscitation                                               65.0

In [86]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207B_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PMTCT  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Prevention of mother-to child transmission of HIV']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PMTCT .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PMTCT .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PMTCT

                                                   Percent of facilities that have the indicated guidelines in the maternity_area
\t
Prevention of mother-to child transmission of HIV                                               65.0

In [87]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207F_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PCPNC  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Integrated management of pregnancy,childbirth,postpartum and newborn care']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PCPNC .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PCPNC .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PCPNC

                                                    Percent of facilities that have the indicated guidelines in the maternity_area
\t
Integrated management of pregnancy,childbirth,p...                                               57.0

In [88]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207C_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Obstetric_topics  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Obstetric topics']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Obstetric_topics .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Obstetric_topics .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Obstetric_topics

                  Percent of facilities that have the indicated guidelines in the maternity_area
\t
Obstetric topics                                               52.0

In [89]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207D_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Infection_prevention  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Infection prevention']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Infection_prevention .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Infection_prevention .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Infection_prevention

                      Percent of facilities that have the indicated guidelines in the maternity_area
\t
Infection prevention                                               52.0

In [90]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207G_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Preterm_LBW_KMC  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Care for preterm or low birth weight babies, including Kangaroo mother ']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Preterm_LBW_KMC .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Preterm_LBW_KMC .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Preterm_LBW_KMC

                                                    Percent of facilities that have the indicated guidelines in the maternity_area
\t
Care for preterm or low birth weight babies, in...                                               48.0

In [91]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207K_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_HIV_AIDS_infection_prevention  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'HIV/AIDS infection prevention']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_HIV_AIDS_infection_prevention .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_HIV_AIDS_infection_prevention .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_HIV_AIDS_infection_prevention

                               Percent of facilities that have the indicated guidelines in the maternity_area
\t
HIV/AIDS infection prevention                                               41.0

In [92]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207A_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Safe_abortion  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Safe abortion']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Safe_abortion .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Safe_abortion .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Safe_abortion

               Percent of facilities that have the indicated guidelines in the maternity_area
\t
Safe abortion                                               36.0

In [93]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207J_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Referral_and_counter_referral  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Reimbursement']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Referral_and_counter_referral .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Referral_and_counter_referral .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Referral_and_counter_referral

               Percent of facilities that have the indicated guidelines in the maternity_area
\t
Reimbursement                                               26.0

In [94]:
Number_facility_Functioning_as_BEmONC_Location = data.loc[((data['Q207E_3'] ==1))]
Designated_as_BEmONC_Location = data.loc[((data['FT7']))]
Percentage_of_facilaities_Function_as_BEmONC_by_Location=(len(Number_facility_Functioning_as_BEmONC_Location)/(len(Designated_as_BEmONC_Location)))*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((Percentage_of_facilaities_Function_as_BEmONC_by_Location),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Reimbursement  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Safe abortion']
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Reimbursement .index= labels_of_col1[1:]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Reimbursement .index.names= [labels_of_col1[0]]
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Reimbursement

               Percent of facilities that have the indicated guidelines in the maternity_area
\t
Safe abortion                                                9.0

In [95]:
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_4=(Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Family_planning,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_IMNCI,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Neonatal_resuscitation,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PMTCT,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_PCPNC,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Obstetric_topics,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Infection_prevention,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Preterm_LBW_KMC,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_HIV_AIDS_infection_prevention,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Safe_abortion,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Referral_and_counter_referral,Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_Reimbursement)
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area=pd.concat( Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area_4, axis=0, sort=False)
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area

                                                    Percent of facilities that have the indicated guidelines in the maternity_area
\t
Family planning                                                                                  78.0
Treatment of infections in young infants(IMNCI)                                                  72.0
Neonatal resuscitation                                                                           65.0
Prevention of mother-to child transmission of HIV                                                65.0
Integrated management of pregnancy,childbirth,p...                                               57.0
Obstetric topics                                                                                 52.0
Infection prevention                                                                             52.0
Care for preterm or low birth weight babies, in...                                               48.0
HIV/AIDS infection prevention                                                                    41.0
Safe abortion                                                                                    36.0
Reimbursement                                                                                    26.0
Safe abortion                                                                                     9.0

In [96]:
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Guidelines, supplies, and medical equipment in labour and delivery and maternity wards/Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area.csv")

In [59]:
my_tab = pd.crosstab(data['FT7'], data['Q252A_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vacuum extractor with different size cups']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q252A_3']==1, data['Q252A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups

                        Vacuum extractor with different size cups
Facility
Referral/specialized                                         93.0
General hospitals                                            97.0
Primary hospitals                                            89.0
MCH specialty centres                                        96.0
Health centres                                               55.0
MCH specialty clinics                                        62.0
Higher clinics                                               77.0
National                                                     58.0

In [60]:
my_tab = pd.crosstab(data['FT7'], data['Q252B_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Obstetric forceps (outlet)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q252B_3']==1, data['Q252B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet

                        Obstetric forceps (outlet)
Facility
Referral/specialized                          97.0
General hospitals                             93.0
Primary hospitals                             86.0
MCH specialty centres                         83.0
Health centres                                16.0
MCH specialty clinics                         75.0
Higher clinics                                69.0
National                                      23.0

In [61]:
my_tab = pd.crosstab(data['FT7'], data['Q252C_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Obstetric forceps (low)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q252C_3']==1, data['Q252C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low

                        Obstetric forceps (low)
Facility
Referral/specialized                       90.0
General hospitals                          86.0
Primary hospitals                          72.0
MCH specialty centres                      83.0
Health centres                             13.0
MCH specialty clinics                      69.0
Higher clinics                             62.0
National                                   19.0

In [62]:
my_tab = pd.crosstab(data['FT7'], data['Q252D_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Obstetric forceps (breech)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q252D_3']==1, data['Q252D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech

                        Obstetric forceps (breech)
Facility
Referral/specialized                          63.0
General hospitals                             64.0
Primary hospitals                             44.0
MCH specialty centres                         52.0
Health centres                                 9.0
MCH specialty clinics                         44.0
Higher clinics                                31.0
National                                      13.0

In [63]:
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4=(Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Vacuum_extractor_with_different_size_cups,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_extractor_Obstetric_forceps_outlet,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_low,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Obstetric_forceps_breech)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area=pd.concat( Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4, axis=1, sort=False)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area

,Vacuum extractor with different size cups,Obstetric forceps (outlet),Obstetric forceps (low),Obstetric forceps (breech)
Facility,,,,
Referral/specialized,93.0,97.0,90.0,63.0
General hospitals,97.0,93.0,86.0,64.0
Primary hospitals,89.0,86.0,72.0,44.0
MCH specialty centres,96.0,83.0,83.0,52.0
Health centres,55.0,16.0,13.0,9.0
MCH specialty clinics,62.0,75.0,69.0,44.0
Higher clinics,77.0,69.0,62.0,31.0
National,58.0,23.0,19.0,13.0

In [64]:
my_tab = pd.crosstab(data['FT7'], data['Q253A_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Electric vacuum aspiration machine']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253A_3']==1, data['Q253A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine

                        Electric vacuum aspiration machine
Facility
Referral/specialized                                  73.0
General hospitals                                     76.0
Primary hospitals                                     68.0
MCH specialty centres                                 78.0
Health centres                                        10.0
MCH specialty clinics                                 69.0
Higher clinics                                        38.0
National                                              16.0

In [65]:
my_tab = pd.crosstab(data['FT7'], data['Q253B_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vaginal speculum (Sims)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253B_3']==1, data['Q253B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims

                        Vaginal speculum (Sims)
Facility
Referral/specialized                       97.0
General hospitals                          98.0
Primary hospitals                          92.0
MCH specialty centres                      83.0
Health centres                             62.0
MCH specialty clinics                      81.0
Higher clinics                             85.0
National                                   65.0

In [66]:
my_tab = pd.crosstab(data['FT7'], data['Q253C_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (sponge [ring] or uterine packing) ']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253C_3']==1, data['Q253C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing

                        Forceps (sponge [ring] or uterine packing)
Facility
Referral/specialized                                           93.0
General hospitals                                              98.0
Primary hospitals                                              98.0
MCH specialty centres                                          96.0
Health centres                                                 78.0
MCH specialty clinics                                          88.0
Higher clinics                                                 92.0
National                                                       79.0

In [67]:
my_tab = pd.crosstab(data['FT7'], data['Q253D_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette  = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette [0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette [0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette [-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Postpartum curette']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette .columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette .index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette .columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette .index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253D_3']==1, data['Q253D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette .loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette

                        Postpartum curette
Facility
Referral/specialized                  90.0
General hospitals                     89.0
Primary hospitals                     78.0
MCH specialty centres                 78.0
Health centres                        16.0
MCH specialty clinics                 75.0
Higher clinics                        54.0
National                              22.0

In [68]:
my_tab = pd.crosstab(data['FT7'], data['Q253E_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Uterine dilators (French, sizes 13-27)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253E_3']==1, data['Q253E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators

                        Uterine dilators (French, sizes 13-27)
Facility
Referral/specialized                                      80.0
General hospitals                                         90.0
Primary hospitals                                         78.0
MCH specialty centres                                     87.0
Health centres                                            19.0
MCH specialty clinics                                     56.0
Higher clinics                                            77.0
National                                                  25.0

In [69]:
my_tab = pd.crosstab(data['FT7'], data['Q253F_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Uterine curettes (sharp, size 0 or 00)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253F_3']==1, data['Q253F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes

                        Uterine curettes (sharp, size 0 or 00)
Facility
Referral/specialized                                      80.0
General hospitals                                         82.0
Primary hospitals                                         67.0
MCH specialty centres                                     83.0
Health centres                                             9.0
MCH specialty clinics                                     56.0
Higher clinics                                            46.0
National                                                  15.0

In [70]:
my_tab = pd.crosstab(data['FT7'], data['Q253G_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Uterine curettes (blunt, size 0 or 00)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253G_3']==1, data['Q253G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes

                        Uterine curettes (blunt, size 0 or 00)
Facility
Referral/specialized                                      80.0
General hospitals                                         83.0
Primary hospitals                                         66.0
MCH specialty centres                                     83.0
Health centres                                            10.0
MCH specialty clinics                                     62.0
Higher clinics                                            46.0
National                                                  15.0

In [71]:
my_tab = pd.crosstab(data['FT7'], data['Q253H_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Uterine sound']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q253H_3']==1, data['Q253H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound

                        Uterine sound
Facility
Referral/specialized             97.0
General hospitals                93.0
Primary hospitals                80.0
MCH specialty centres           100.0
Health centres                   48.0
MCH specialty clinics            81.0
Higher clinics                   62.0
National                         52.0

In [72]:
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4=(Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Electric_vacuum_aspiration_machine,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vaginal_speculum_Sims,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Forceps_sponge_ring_or_uterine_packing,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Postpartum_curette,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_dilators,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_curettes,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Uterine_sound)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area1=pd.concat( Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4, axis=1, sort=False)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area1

,Electric vacuum aspiration machine,Vaginal speculum (Sims),Forceps (sponge [ring] or uterine packing),Postpartum curette,"Uterine dilators (French, sizes 13-27)","Uterine curettes (blunt, size 0 or 00)","Uterine curettes (blunt, size 0 or 00)",Uterine sound
Facility,,,,,,,,
Referral/specialized,73.0,97.0,93.0,90.0,80.0,80.0,80.0,97.0
General hospitals,76.0,98.0,98.0,89.0,90.0,83.0,83.0,93.0
Primary hospitals,68.0,92.0,98.0,78.0,78.0,66.0,66.0,80.0
MCH specialty centres,78.0,83.0,96.0,78.0,87.0,83.0,83.0,100.0
Health centres,10.0,62.0,78.0,16.0,19.0,10.0,10.0,48.0
MCH specialty clinics,69.0,81.0,88.0,75.0,56.0,62.0,62.0,81.0
Higher clinics,38.0,85.0,92.0,54.0,77.0,46.0,46.0,62.0
National,16.0,65.0,79.0,22.0,25.0,15.0,15.0,52.0

In [73]:
my_tab = pd.crosstab(data['FT7'], data['Q254A_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Complete manual vacuum aspiration set']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254A_3']==1, data['Q254A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual

                        Complete manual vacuum aspiration set
Facility
Referral/specialized                                     93.0
General hospitals                                        95.0
Primary hospitals                                        86.0
MCH specialty centres                                   100.0
Health centres                                           54.0
MCH specialty clinics                                    81.0
Higher clinics                                           85.0
National                                                 58.0

In [74]:
my_tab = pd.crosstab(data['FT7'], data['Q254B_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vacuum aspirators/syringes']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254B_3']==1, data['Q254B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators

                        Vacuum aspirators/syringes
Facility
Referral/specialized                          97.0
General hospitals                             91.0
Primary hospitals                             88.0
MCH specialty centres                        100.0
Health centres                                52.0
MCH specialty clinics                         81.0
Higher clinics                                77.0
National                                      56.0

In [75]:
my_tab = pd.crosstab(data['FT7'], data['Q254C_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Silicone lubricant (for lubricating Oring)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254C_3']==1, data['Q254C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant

                        Silicone lubricant (for lubricating Oring)
Facility
Referral/specialized                                          83.0
General hospitals                                             84.0
Primary hospitals                                             74.0
MCH specialty centres                                         91.0
Health centres                                                36.0
MCH specialty clinics                                         75.0
Higher clinics                                                69.0
National                                                      40.0

In [76]:
my_tab = pd.crosstab(data['FT7'], data['Q254D_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Other oil (for lubricating O-ring)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254D_3']==1, data['Q254D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil

                        Other oil (for lubricating O-ring)
Facility
Referral/specialized                                  53.0
General hospitals                                     47.0
Primary hospitals                                     33.0
MCH specialty centres                                 52.0
Health centres                                        16.0
MCH specialty clinics                                 44.0
Higher clinics                                        38.0
National                                              18.0

In [77]:
my_tab = pd.crosstab(data['FT7'], data['Q254E_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Flexible cannulae (4-6mm)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254E_3']==1, data['Q254E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae

                        Flexible cannulae (4-6mm)
Facility
Referral/specialized                        100.0
General hospitals                            87.0
Primary hospitals                            81.0
MCH specialty centres                        96.0
Health centres                               48.0
MCH specialty clinics                        69.0
Higher clinics                               85.0
National                                     52.0

In [78]:
my_tab = pd.crosstab(data['FT7'], data['Q254F_3'])
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula[0]
#del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula[0]
del  Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Flexible cannulae (7-12mm)']
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula.columns= labels_of_col[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula.index= labels_of_col1[1:]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q254F_3']==1, data['Q254F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula.loc['National'] = cc
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula

                        Flexible cannulae (7-12mm)
Facility
Referral/specialized                          93.0
General hospitals                             89.0
Primary hospitals                             79.0
MCH specialty centres                         87.0
Health centres                                47.0
MCH specialty clinics                         69.0
Higher clinics                                85.0
National                                      50.0

In [79]:
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4=(Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Complete_manual,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Vacuum_aspirators,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Silicone_lubricant,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Other_oil,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannulae,Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_Flexible_cannula,)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area2=pd.concat( Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area_4, axis=1, sort=False)
Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area2

,Complete manual vacuum aspiration set,Vacuum aspirators/syringes,Silicone lubricant (for lubricating Oring),Other oil (for lubricating O-ring),Flexible cannulae (4-6mm),Flexible cannulae (7-12mm)
Facility,,,,,,
Referral/specialized,93.0,97.0,83.0,53.0,100.0,93.0
General hospitals,95.0,91.0,84.0,47.0,87.0,89.0
Primary hospitals,86.0,88.0,74.0,33.0,81.0,79.0
MCH specialty centres,100.0,100.0,91.0,52.0,96.0,87.0
Health centres,54.0,52.0,36.0,16.0,48.0,47.0
MCH specialty clinics,81.0,81.0,75.0,44.0,69.0,69.0
Higher clinics,85.0,77.0,69.0,38.0,85.0,85.0
National,58.0,56.0,40.0,18.0,52.0,50.0

In [80]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area.transpose(),Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area1.transpose(),Percent_of_facilities_with_equipment_for_procedures_in_the_maternity_area2.transpose())
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Vacuum extraction/forceps delivery', 'Uterine evacuation','Manual vacuum aspiration'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12

Facility                                                                        Referral/specialized  \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups                    93.0
                                   Obstetric forceps (outlet)                                   97.0
                                   Obstetric forceps (low)                                      90.0
                                   Obstetric forceps (breech)                                   63.0
Uterine evacuation                 Electric vacuum aspiration machine                           73.0
                                   Vaginal speculum (Sims)                                      97.0
                                   Forceps (sponge [ring] or uterine packing)                   93.0
                                   Postpartum curette                                           90.0
                                   Uterine dilators (French, sizes 13-27)                       80.0
                                   Uterine curettes (blunt, size 0 or 00)                       80.0
                                   Uterine curettes (blunt, size 0 or 00)                       80.0
                                   Uterine sound                                                97.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                        93.0
                                   Vacuum aspirators/syringes                                   97.0
                                   Silicone lubricant (for lubricating Oring)                   83.0
                                   Other oil (for lubricating O-ring)                           53.0
                                   Flexible cannulae (4-6mm)                                   100.0
                                   Flexible cannulae (7-12mm)                                   93.0

Facility                                                                        General hospitals  \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups                 97.0
                                   Obstetric forceps (outlet)                                93.0
                                   Obstetric forceps (low)                                   86.0
                                   Obstetric forceps (breech)                                64.0
Uterine evacuation                 Electric vacuum aspiration machine                        76.0
                                   Vaginal speculum (Sims)                                   98.0
                                   Forceps (sponge [ring] or uterine packing)                98.0
                                   Postpartum curette                                        89.0
                                   Uterine dilators (French, sizes 13-27)                    90.0
                                   Uterine curettes (blunt, size 0 or 00)                    83.0
                                   Uterine curettes (blunt, size 0 or 00)                    83.0
                                   Uterine sound                                             93.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                     95.0
                                   Vacuum aspirators/syringes                                91.0
                                   Silicone lubricant (for lubricating Oring)                84.0
                                   Other oil (for lubricating O-ring)                        47.0
                                   Flexible cannulae (4-6mm)                                 87.0
                                   Flexible cannulae (7-12mm)                                89.0

Facility                                                                        Primary hospitals   \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups                  89.0
                                   Obstetric forceps (outlet)                                 86.0
                                   Obstetric forceps (low)                                    72.0
                                   Obstetric forceps (breech)                                 44.0
Uterine evacuation                 Electric vacuum aspiration machine                         68.0
                                   Vaginal speculum (Sims)                                    92.0
                                   Forceps (sponge [ring] or uterine packing)                 98.0
                                   Postpartum curette                                         78.0
                                   Uterine dilators (French, sizes 13-27)                     78.0
                                   Uterine curettes (blunt, size 0 or 00)                     66.0
                                   Uterine curettes (blunt, size 0 or 00)                     66.0
                                   Uterine sound                                              80.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                      86.0
                                   Vacuum aspirators/syringes                                 88.0
                                   Silicone lubricant (for lubricating Oring)                 74.0
                                   Other oil (for lubricating O-ring)                         33.0
                                   Flexible cannulae (4-6mm)                                  81.0
                                   Flexible cannulae (7-12mm)                                 79.0

Facility                                                                        MCH specialty centres   \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups                      96.0
                                   Obstetric forceps (outlet)                                     83.0
                                   Obstetric forceps (low)                                        83.0
                                   Obstetric forceps (breech)                                     52.0
Uterine evacuation                 Electric vacuum aspiration machine                             78.0
                                   Vaginal speculum (Sims)                                        83.0
                                   Forceps (sponge [ring] or uterine packing)                     96.0
                                   Postpartum curette                                             78.0
                                   Uterine dilators (French, sizes 13-27)                         87.0
                                   Uterine curettes (blunt, size 0 or 00)                         83.0
                                   Uterine curettes (blunt, size 0 or 00)                         83.0
                                   Uterine sound                                                 100.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                         100.0
                                   Vacuum aspirators/syringes                                    100.0
                                   Silicone lubricant (for lubricating Oring)                     91.0
                                   Other oil (for lubricating O-ring)                             52.0
                                   Flexible cannulae (4-6mm)                                      96.0
                                   Flexible cannulae (7-12mm)                                     87.0

Facility                                                                        Health centres  \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups              55.0
                                   Obstetric forceps (outlet)                             16.0
                                   Obstetric forceps (low)                                13.0
                                   Obstetric forceps (breech)                              9.0
Uterine evacuation                 Electric vacuum aspiration machine                     10.0
                                   Vaginal speculum (Sims)                                62.0
                                   Forceps (sponge [ring] or uterine packing)             78.0
                                   Postpartum curette                                     16.0
                                   Uterine dilators (French, sizes 13-27)                 19.0
                                   Uterine curettes (blunt, size 0 or 00)                 10.0
                                   Uterine curettes (blunt, size 0 or 00)                 10.0
                                   Uterine sound                                          48.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                  54.0
                                   Vacuum aspirators/syringes                             52.0
                                   Silicone lubricant (for lubricating Oring)             36.0
                                   Other oil (for lubricating O-ring)                     16.0
                                   Flexible cannulae (4-6mm)                              48.0
                                   Flexible cannulae (7-12mm)                             47.0

Facility                                                                        MCH specialty clinics  \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups                     62.0
                                   Obstetric forceps (outlet)                                    75.0
                                   Obstetric forceps (low)                                       69.0
                                   Obstetric forceps (breech)                                    44.0
Uterine evacuation                 Electric vacuum aspiration machine                            69.0
                                   Vaginal speculum (Sims)                                       81.0
                                   Forceps (sponge [ring] or uterine packing)                    88.0
                                   Postpartum curette                                            75.0
                                   Uterine dilators (French, sizes 13-27)                        56.0
                                   Uterine curettes (blunt, size 0 or 00)                        62.0
                                   Uterine curettes (blunt, size 0 or 00)                        62.0
                                   Uterine sound                                                 81.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                         81.0
                                   Vacuum aspirators/syringes                                    81.0
                                   Silicone lubricant (for lubricating Oring)                    75.0
                                   Other oil (for lubricating O-ring)                            44.0
                                   Flexible cannulae (4-6mm)                                     69.0
                                   Flexible cannulae (7-12mm)                                    69.0

Facility                                                                        Higher clinics  \

Vacuum extraction/forceps delivery Vacuum extractor with different size cups              77.0
                                   Obstetric forceps (outlet)                             69.0
                                   Obstetric forceps (low)                                62.0
                                   Obstetric forceps (breech)                             31.0
Uterine evacuation                 Electric vacuum aspiration machine                     38.0
                                   Vaginal speculum (Sims)                                85.0
                                   Forceps (sponge [ring] or uterine packing)             92.0
                                   Postpartum curette                                     54.0
                                   Uterine dilators (French, sizes 13-27)                 77.0
                                   Uterine curettes (blunt, size 0 or 00)                 46.0
                                   Uterine curettes (blunt, size 0 or 00)                 46.0
                                   Uterine sound                                          62.0
Manual vacuum aspiration           Complete manual vacuum aspiration set                  85.0
                                   Vacuum aspirators/syringes                             77.0
                                   Silicone lubricant (for lubricating Oring)             69.0
                                   Other oil (for lubricating O-ring)                     38.0
                                   Flexible cannulae (4-6mm)                              85.0
                                   Flexible cannulae (7-12mm)                             85.0

Facility                                                                        National

Vacuum extraction/forceps delivery Vacuum extractor with different size cups        58.0
                                   Obstetric forceps (outlet)                       23.0
                                   Obstetric forceps (low)                          19.0
                                   Obstetric forceps (breech)                       13.0
Uterine evacuation                 Electric vacuum aspiration machine               16.0
                                   Vaginal speculum (Sims)                          65.0
                                   Forceps (sponge [ring] or uterine packing)       79.0
                                   Postpartum curette                               22.0
                                   Uterine dilators (French, sizes 13-27)           25.0
                                   Uterine curettes (blunt, size 0 or 00)           15.0
                                   Uterine curettes (blunt, size 0 or 00)           15.0
                                   Uterine sound                                    52.0
Manual vacuum aspiration           Complete manual vacuum aspiration set            58.0
                                   Vacuum aspirators/syringes                       56.0
                                   Silicone lubricant (for lubricating Oring)       40.0
                                   Other oil (for lubricating O-ring)               18.0
                                   Flexible cannulae (4-6mm)                        52.0
                                   Flexible cannulae (7-12mm)                       50.0

In [97]:
Percent_of_facilities_that_have_the_indicated_guidelines_in_the_maternity_area.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Guidelines, supplies, and medical equipment in labour and delivery and maternity wards/Percent of facilities with equipment for procedures in the maternity area.csv")

In [100]:
my_tab = pd.crosstab(data['FT7'], data['Q250C_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Disposable latex gloves (short)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q250C_3']==1, data['Q250C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex

                        Disposable latex gloves (short)
Facility
Referral/specialized                              100.0
General hospitals                                 100.0
Primary hospitals                                  99.0
MCH specialty centres                             100.0
Health centres                                     96.0
MCH specialty clinics                             100.0
Higher clinics                                    100.0
National                                           96.0

In [101]:
my_tab = pd.crosstab(data['FT7'], data['Q250D_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Disposable latex gloves (long)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q250D_3']!=0, data['Q250D_3']!=0)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1

                        Disposable latex gloves (long)
Facility
Referral/specialized                              80.0
General hospitals                                 74.0
Primary hospitals                                 63.0
MCH specialty centres                             61.0
Health centres                                    53.0
MCH specialty clinics                             88.0
Higher clinics                                    69.0
National                                          55.0

In [102]:
my_tab = pd.crosstab(data['FT7'], data['Q250E_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Plastic sheeting']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q250E_3']==1, data['Q250E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting

                        Plastic sheeting
Facility
Referral/specialized               100.0
General hospitals                   98.0
Primary hospitals                   94.0
MCH specialty centres              100.0
Health centres                      74.0
MCH specialty clinics               94.0
Higher clinics                     100.0
National                            76.0

In [104]:
my_tab = pd.crosstab(data['FT7'], data['Q250F_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Gauze swabs']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q250F_3']==1, data['Q250F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs

                        Gauze swabs
Facility
Referral/specialized          100.0
General hospitals             100.0
Primary hospitals              99.0
MCH specialty centres         100.0
Health centres                 97.0
MCH specialty clinics         100.0
Higher clinics                100.0
National                       97.0

In [106]:
my_tab = pd.crosstab(data['FT7'], data['Q250G_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Cloths or towels']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q250G_3']==1, data['Q250G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels

                        Cloths or towels
Facility
Referral/specialized                73.0
General hospitals                   74.0
Primary hospitals                   56.0
MCH specialty centres               78.0
Health centres                      29.0
MCH specialty clinics               81.0
Higher clinics                      38.0
National                            33.0

In [107]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Disposable_latex1,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Plastic_sheeting,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gauze_swabs,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cloths_or_towels)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological

,Disposable latex gloves (short),Disposable latex gloves (long),Plastic sheeting,Gauze swabs,Cloths or towels
Facility,,,,,
Referral/specialized,100.0,80.0,100.0,100.0,73.0
General hospitals,100.0,74.0,98.0,100.0,74.0
Primary hospitals,99.0,63.0,94.0,99.0,56.0
MCH specialty centres,100.0,61.0,100.0,100.0,78.0
Health centres,96.0,53.0,74.0,97.0,29.0
MCH specialty clinics,100.0,88.0,94.0,100.0,81.0
Higher clinics,100.0,69.0,100.0,100.0,38.0
National,96.0,55.0,76.0,97.0,33.0

In [108]:
my_tab = pd.crosstab(data['FT7'], data['Q255A_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Gallipot bowl or jar (s/s)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255A_3']==1, data['Q255A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl

                        Gallipot bowl or jar (s/s)
Facility
Referral/specialized                          93.0
General hospitals                             96.0
Primary hospitals                             91.0
MCH specialty centres                         96.0
Health centres                                81.0
MCH specialty clinics                         88.0
Higher clinics                                92.0
National                                      82.0

In [109]:
my_tab = pd.crosstab(data['FT7'], data['Q255C_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Needle holder (Mayo Hegar, 180mm, s/s']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255C_3']==1, data['Q255C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder

                        Needle holder (Mayo Hegar, 180mm, s/s
Facility
Referral/specialized                                    100.0
General hospitals                                       100.0
Primary hospitals                                        96.0
MCH specialty centres                                   100.0
Health centres                                           88.0
MCH specialty clinics                                    94.0
Higher clinics                                          100.0
National                                                 89.0

In [110]:
my_tab = pd.crosstab(data['FT7'], data['Q255D_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scissors (sharp straight, 120mm, s/s)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255D_3']==1, data['Q255D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight

                        Scissors (sharp straight, 120mm, s/s)
Facility
Referral/specialized                                    100.0
General hospitals                                        99.0
Primary hospitals                                        95.0
MCH specialty centres                                   100.0
Health centres                                           89.0
MCH specialty clinics                                    94.0
Higher clinics                                          100.0
National                                                 89.0

In [111]:
my_tab = pd.crosstab(data['FT7'], data['Q255E_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scissors (flat curved, 180mm, s/s']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255E_3']==1, data['Q255E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved

                        Scissors (flat curved, 180mm, s/s
Facility
Referral/specialized                                 93.0
General hospitals                                    97.0
Primary hospitals                                    94.0
MCH specialty centres                               100.0
Health centres                                       83.0
MCH specialty clinics                                94.0
Higher clinics                                      100.0
National                                             84.0

In [113]:
my_tab = pd.crosstab(data['FT7'], data['Q255H_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scissors (other types)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255H_3']==1, data['Q255H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types

                        Scissors (other types)
Facility
Referral/specialized                      63.0
General hospitals                         52.0
Primary hospitals                         51.0
MCH specialty centres                     48.0
Health centres                            30.0
MCH specialty clinics                     62.0
Higher clinics                            15.0
National                                  32.0

In [114]:
my_tab = pd.crosstab(data['FT7'], data['Q255B_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (dissecting, Lane 1x2 teeth, 140mm)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255B_3']==1, data['Q255B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting

                        Forceps (dissecting, Lane 1x2 teeth, 140mm)
Facility
Referral/specialized                                           80.0
General hospitals                                              91.0
Primary hospitals                                              88.0
MCH specialty centres                                         100.0
Health centres                                                 66.0
MCH specialty clinics                                          88.0
Higher clinics                                                100.0
National                                                       68.0

In [116]:
my_tab = pd.crosstab(data['FT7'], data['Q255F_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (sponge [ring])']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255F_3']==1, data['Q255F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring

                        Forceps (sponge [ring])
Facility
Referral/specialized                       97.0
General hospitals                          96.0
Primary hospitals                          96.0
MCH specialty centres                     100.0
Health centres                             87.0
MCH specialty clinics                      94.0
Higher clinics                            100.0
National                                   88.0

In [117]:
my_tab = pd.crosstab(data['FT7'], data['Q255G_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery  = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery [0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery [0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery [-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (artery, mosquito straight, 130mm, s/s)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery .columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery .index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery .columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery .index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255G_3']==1, data['Q255G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery .loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery

                        Forceps (artery, mosquito straight, 130mm, s/s)
Facility
Referral/specialized                                               93.0
General hospitals                                                 100.0
Primary hospitals                                                  98.0
MCH specialty centres                                             100.0
Health centres                                                     82.0
MCH specialty clinics                                              88.0
Higher clinics                                                    100.0
National                                                           84.0

In [118]:
my_tab = pd.crosstab(data['FT7'], data['Q255I_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (other types)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q255I_3']==1, data['Q255I_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types

                        Forceps (other types)
Facility
Referral/specialized                     60.0
General hospitals                        53.0
Primary hospitals                        45.0
MCH specialty centres                    35.0
Health centres                           26.0
MCH specialty clinics                    56.0
Higher clinics                            8.0
National                                 28.0

In [119]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Gallipot_bowl,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Needle_holder,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp_straight,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_flat_curved,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_other_types,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_dissecting,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_sponge_ring,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_artery,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Forceps_other_types)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological1

,Gallipot bowl or jar (s/s),"Needle holder (Mayo Hegar, 180mm, s/s","Scissors (sharp straight, 120mm, s/s)","Scissors (flat curved, 180mm, s/s",Scissors (other types),"Forceps (dissecting, Lane 1x2 teeth, 140mm)",Forceps (sponge [ring]),"Forceps (artery, mosquito straight, 130mm, s/s)",Forceps (other types)
Facility,,,,,,,,,
Referral/specialized,93.0,100.0,100.0,93.0,63.0,80.0,97.0,93.0,60.0
General hospitals,96.0,100.0,99.0,97.0,52.0,91.0,96.0,100.0,53.0
Primary hospitals,91.0,96.0,95.0,94.0,51.0,88.0,96.0,98.0,45.0
MCH specialty centres,96.0,100.0,100.0,100.0,48.0,100.0,100.0,100.0,35.0
Health centres,81.0,88.0,89.0,83.0,30.0,66.0,87.0,82.0,26.0
MCH specialty clinics,88.0,94.0,94.0,94.0,62.0,88.0,94.0,88.0,56.0
Higher clinics,92.0,100.0,100.0,100.0,15.0,100.0,100.0,100.0,8.0
National,82.0,89.0,89.0,84.0,32.0,68.0,88.0,84.0,28.0

In [121]:
my_tab = pd.crosstab(data['FT7'], data['Q256A_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vaginal speculum (Sims)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256A_3']==1, data['Q256A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum

                        Vaginal speculum (Sims)
Facility
Referral/specialized                       97.0
General hospitals                          98.0
Primary hospitals                          91.0
MCH specialty centres                      83.0
Health centres                             65.0
MCH specialty clinics                      94.0
Higher clinics                             85.0
National                                   68.0

In [122]:
my_tab = pd.crosstab(data['FT7'], data['Q256B_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Vaginal speculum (Cusco, virgin size 75x17mm)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256B_3']==1, data['Q256B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco

                        Vaginal speculum (Cusco, virgin size 75x17mm)
Facility
Referral/specialized                                             80.0
General hospitals                                                86.0
Primary hospitals                                                72.0
MCH specialty centres                                            74.0
Health centres                                                   44.0
MCH specialty clinics                                            75.0
Higher clinics                                                   85.0
National                                                         47.0

In [124]:
my_tab = pd.crosstab(data['FT7'], data['Q256C_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Cusco speculum (Cusco, adult size) ']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256C_3']==1, data['Q256C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco

                        Cusco speculum (Cusco, adult size)
Facility
Referral/specialized                                   97.0
General hospitals                                      98.0
Primary hospitals                                      91.0
MCH specialty centres                                  91.0
Health centres                                         69.0
MCH specialty clinics                                  88.0
Higher clinics                                         85.0
National                                               71.0

In [125]:
my_tab = pd.crosstab(data['FT7'], data['Q256D_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Forceps (other types)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256D_3']==1, data['Q256D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated

                        Forceps (other types)
Facility
Referral/specialized                     97.0
General hospitals                        93.0
Primary hospitals                        76.0
MCH specialty centres                   100.0
Health centres                           47.0
MCH specialty clinics                    75.0
Higher clinics                           77.0
National                                 50.0

In [126]:
my_tab = pd.crosstab(data['FT7'], data['Q256E_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Tenaculum (single-tooth/multi-teeth)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256E_3']==1, data['Q256E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single

                        Tenaculum (single-tooth/multi-teeth)
Facility
Referral/specialized                                   100.0
General hospitals                                      100.0
Primary hospitals                                       96.0
MCH specialty centres                                  100.0
Health centres                                          66.0
MCH specialty clinics                                   88.0
Higher clinics                                          85.0
National                                                69.0

In [127]:
my_tab = pd.crosstab(data['FT7'], data['Q256F_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scissors (sharp straight, 145mm, s/s)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q256F_3']==1, data['Q256F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp

                        Scissors (sharp straight, 145mm, s/s)
Facility
Referral/specialized                                    100.0
General hospitals                                       100.0
Primary hospitals                                        97.0
MCH specialty centres                                   100.0
Health centres                                           77.0
MCH specialty clinics                                    88.0
Higher clinics                                          100.0
National                                                 79.0

In [129]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Vaginal_speculum_Cusco,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Cusco_speculum_Cusco,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Uterine_sound_graduated,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Tenaculum_single,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Scissors_sharp)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological2

,Vaginal speculum (Sims),"Vaginal speculum (Cusco, virgin size 75x17mm)","Cusco speculum (Cusco, adult size)",Forceps (other types),Tenaculum (single-tooth/multi-teeth),"Scissors (sharp straight, 145mm, s/s)"
Facility,,,,,,
Referral/specialized,97.0,80.0,97.0,97.0,100.0,100.0
General hospitals,98.0,86.0,98.0,93.0,100.0,100.0
Primary hospitals,91.0,72.0,91.0,76.0,96.0,97.0
MCH specialty centres,83.0,74.0,91.0,100.0,100.0,100.0
Health centres,65.0,44.0,69.0,47.0,66.0,77.0
MCH specialty clinics,94.0,75.0,88.0,75.0,88.0,88.0
Higher clinics,85.0,85.0,85.0,77.0,85.0,100.0
National,68.0,47.0,71.0,50.0,69.0,79.0

In [130]:
my_tab = pd.crosstab(data['FT7'], data['Q257A_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Decapitation hook']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q257A_3']==1, data['Q257A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook

                        Decapitation hook
Facility
Referral/specialized                 83.0
General hospitals                    68.0
Primary hospitals                    49.0
MCH specialty centres                61.0
Health centres                        2.0
MCH specialty clinics                31.0
Higher clinics                       31.0
National                              7.0

In [131]:
my_tab = pd.crosstab(data['FT7'], data['Q257B_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scissors (sharp straight, 145mm, s/s)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q257B_3']==1, data['Q257B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps

                        Scissors (sharp straight, 145mm, s/s)
Facility
Referral/specialized                                     77.0
General hospitals                                        73.0
Primary hospitals                                        52.0
MCH specialty centres                                    61.0
Health centres                                            2.0
MCH specialty clinics                                    25.0
Higher clinics                                           31.0
National                                                  7.0

In [132]:
my_tab = pd.crosstab(data['FT7'], data['Q257C_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Embryotomy scissors']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q257C_3']==1, data['Q257C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors

                        Embryotomy scissors
Facility
Referral/specialized                   73.0
General hospitals                      65.0
Primary hospitals                      47.0
MCH specialty centres                  61.0
Health centres                          2.0
MCH specialty clinics                  25.0
Higher clinics                         31.0
National                                7.0

In [133]:
my_tab = pd.crosstab(data['FT7'], data['Q257D_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Perforator']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q257D_3']==1, data['Q257D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator

                        Perforator
Facility
Referral/specialized          90.0
General hospitals             72.0
Primary hospitals             52.0
MCH specialty centres         57.0
Health centres                 2.0
MCH specialty clinics         25.0
Higher clinics                23.0
National                       7.0

In [134]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Decapitation_hook,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Craniotomy_forceps,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Embryotomy_scissors,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Perforator)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3

,Decapitation hook,"Scissors (sharp straight, 145mm, s/s)",Embryotomy scissors,Perforator
Facility,,,,
Referral/specialized,83.0,77.0,73.0,90.0
General hospitals,68.0,73.0,65.0,72.0
Primary hospitals,49.0,52.0,47.0,52.0
MCH specialty centres,61.0,61.0,61.0,57.0
Health centres,2.0,2.0,2.0,2.0
MCH specialty clinics,31.0,25.0,25.0,25.0
Higher clinics,31.0,31.0,31.0,23.0
National,7.0,7.0,7.0,7.0

In [135]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological.transpose(),Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological1.transpose(),Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological2.transpose(),Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3.transpose())
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines123=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Supplies for delivery', 'Dressing instrument set','Gynaecological equipment','Craniotomy equipment'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines123

Facility                                                                  Referral/specialized  \

Supplies for delivery    Disposable latex gloves (short)                                 100.0
                         Disposable latex gloves (long)                                   80.0
                         Plastic sheeting                                                100.0
                         Gauze swabs                                                     100.0
                         Cloths or towels                                                 73.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                       93.0
                         Needle holder (Mayo Hegar, 180mm, s/s                           100.0
                         Scissors (sharp straight, 120mm, s/s)                           100.0
                         Scissors (flat curved, 180mm, s/s                                93.0
                         Scissors (other types)                                           63.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                      80.0
                         Forceps (sponge [ring])                                          97.0
                         Forceps (artery, mosquito straight, 130mm, s/s)                  93.0
                         Forceps (other types)                                            60.0
Gynaecological equipment Vaginal speculum (Sims)                                          97.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)                    80.0
                         Cusco speculum (Cusco, adult size)                               97.0
                         Forceps (other types)                                            97.0
                         Tenaculum (single-tooth/multi-teeth)                            100.0
                         Scissors (sharp straight, 145mm, s/s)                           100.0
Craniotomy equipment     Decapitation hook                                                83.0
                         Scissors (sharp straight, 145mm, s/s)                            77.0
                         Embryotomy scissors                                              73.0
                         Perforator                                                       90.0

Facility                                                                  General hospitals  \

Supplies for delivery    Disposable latex gloves (short)                              100.0
                         Disposable latex gloves (long)                                74.0
                         Plastic sheeting                                              98.0
                         Gauze swabs                                                  100.0
                         Cloths or towels                                              74.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                    96.0
                         Needle holder (Mayo Hegar, 180mm, s/s                        100.0
                         Scissors (sharp straight, 120mm, s/s)                         99.0
                         Scissors (flat curved, 180mm, s/s                             97.0
                         Scissors (other types)                                        52.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                   91.0
                         Forceps (sponge [ring])                                       96.0
                         Forceps (artery, mosquito straight, 130mm, s/s)              100.0
                         Forceps (other types)                                         53.0
Gynaecological equipment Vaginal speculum (Sims)                                       98.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)                 86.0
                         Cusco speculum (Cusco, adult size)                            98.0
                         Forceps (other types)                                         93.0
                         Tenaculum (single-tooth/multi-teeth)                         100.0
                         Scissors (sharp straight, 145mm, s/s)                        100.0
Craniotomy equipment     Decapitation hook                                             68.0
                         Scissors (sharp straight, 145mm, s/s)                         73.0
                         Embryotomy scissors                                           65.0
                         Perforator                                                    72.0

Facility                                                                  Primary hospitals   \

Supplies for delivery    Disposable latex gloves (short)                                99.0
                         Disposable latex gloves (long)                                 63.0
                         Plastic sheeting                                               94.0
                         Gauze swabs                                                    99.0
                         Cloths or towels                                               56.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                     91.0
                         Needle holder (Mayo Hegar, 180mm, s/s                          96.0
                         Scissors (sharp straight, 120mm, s/s)                          95.0
                         Scissors (flat curved, 180mm, s/s                              94.0
                         Scissors (other types)                                         51.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                    88.0
                         Forceps (sponge [ring])                                        96.0
                         Forceps (artery, mosquito straight, 130mm, s/s)                98.0
                         Forceps (other types)                                          45.0
Gynaecological equipment Vaginal speculum (Sims)                                        91.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)                  72.0
                         Cusco speculum (Cusco, adult size)                             91.0
                         Forceps (other types)                                          76.0
                         Tenaculum (single-tooth/multi-teeth)                           96.0
                         Scissors (sharp straight, 145mm, s/s)                          97.0
Craniotomy equipment     Decapitation hook                                              49.0
                         Scissors (sharp straight, 145mm, s/s)                          52.0
                         Embryotomy scissors                                            47.0
                         Perforator                                                     52.0

Facility                                                                  MCH specialty centres   \

Supplies for delivery    Disposable latex gloves (short)                                   100.0
                         Disposable latex gloves (long)                                     61.0
                         Plastic sheeting                                                  100.0
                         Gauze swabs                                                       100.0
                         Cloths or towels                                                   78.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                         96.0
                         Needle holder (Mayo Hegar, 180mm, s/s                             100.0
                         Scissors (sharp straight, 120mm, s/s)                             100.0
                         Scissors (flat curved, 180mm, s/s                                 100.0
                         Scissors (other types)                                             48.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                       100.0
                         Forceps (sponge [ring])                                           100.0
                         Forceps (artery, mosquito straight, 130mm, s/s)                   100.0
                         Forceps (other types)                                              35.0
Gynaecological equipment Vaginal speculum (Sims)                                            83.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)                      74.0
                         Cusco speculum (Cusco, adult size)                                 91.0
                         Forceps (other types)                                             100.0
                         Tenaculum (single-tooth/multi-teeth)                              100.0
                         Scissors (sharp straight, 145mm, s/s)                             100.0
Craniotomy equipment     Decapitation hook                                                  61.0
                         Scissors (sharp straight, 145mm, s/s)                              61.0
                         Embryotomy scissors                                                61.0
                         Perforator                                                         57.0

Facility                                                                  Health centres  \

Supplies for delivery    Disposable latex gloves (short)                            96.0
                         Disposable latex gloves (long)                             53.0
                         Plastic sheeting                                           74.0
                         Gauze swabs                                                97.0
                         Cloths or towels                                           29.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                 81.0
                         Needle holder (Mayo Hegar, 180mm, s/s                      88.0
                         Scissors (sharp straight, 120mm, s/s)                      89.0
                         Scissors (flat curved, 180mm, s/s                          83.0
                         Scissors (other types)                                     30.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                66.0
                         Forceps (sponge [ring])                                    87.0
                         Forceps (artery, mosquito straight, 130mm, s/s)            82.0
                         Forceps (other types)                                      26.0
Gynaecological equipment Vaginal speculum (Sims)                                    65.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)              44.0
                         Cusco speculum (Cusco, adult size)                         69.0
                         Forceps (other types)                                      47.0
                         Tenaculum (single-tooth/multi-teeth)                       66.0
                         Scissors (sharp straight, 145mm, s/s)                      77.0
Craniotomy equipment     Decapitation hook                                           2.0
                         Scissors (sharp straight, 145mm, s/s)                       2.0
                         Embryotomy scissors                                         2.0
                         Perforator                                                  2.0

Facility                                                                  MCH specialty clinics  \

Supplies for delivery    Disposable latex gloves (short)                                  100.0
                         Disposable latex gloves (long)                                    88.0
                         Plastic sheeting                                                  94.0
                         Gauze swabs                                                      100.0
                         Cloths or towels                                                  81.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                        88.0
                         Needle holder (Mayo Hegar, 180mm, s/s                             94.0
                         Scissors (sharp straight, 120mm, s/s)                             94.0
                         Scissors (flat curved, 180mm, s/s                                 94.0
                         Scissors (other types)                                            62.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)                       88.0
                         Forceps (sponge [ring])                                           94.0
                         Forceps (artery, mosquito straight, 130mm, s/s)                   88.0
                         Forceps (other types)                                             56.0
Gynaecological equipment Vaginal speculum (Sims)                                           94.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)                     75.0
                         Cusco speculum (Cusco, adult size)                                88.0
                         Forceps (other types)                                             75.0
                         Tenaculum (single-tooth/multi-teeth)                              88.0
                         Scissors (sharp straight, 145mm, s/s)                             88.0
Craniotomy equipment     Decapitation hook                                                 31.0
                         Scissors (sharp straight, 145mm, s/s)                             25.0
                         Embryotomy scissors                                               25.0
                         Perforator                                                        25.0

Facility                                                                  Higher clinics  \

Supplies for delivery    Disposable latex gloves (short)                           100.0
                         Disposable latex gloves (long)                             69.0
                         Plastic sheeting                                          100.0
                         Gauze swabs                                               100.0
                         Cloths or towels                                           38.0
Dressing instrument set  Gallipot bowl or jar (s/s)                                 92.0
                         Needle holder (Mayo Hegar, 180mm, s/s                     100.0
                         Scissors (sharp straight, 120mm, s/s)                     100.0
                         Scissors (flat curved, 180mm, s/s                         100.0
                         Scissors (other types)                                     15.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)               100.0
                         Forceps (sponge [ring])                                   100.0
                         Forceps (artery, mosquito straight, 130mm, s/s)           100.0
                         Forceps (other types)                                       8.0
Gynaecological equipment Vaginal speculum (Sims)                                    85.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)              85.0
                         Cusco speculum (Cusco, adult size)                         85.0
                         Forceps (other types)                                      77.0
                         Tenaculum (single-tooth/multi-teeth)                       85.0
                         Scissors (sharp straight, 145mm, s/s)                     100.0
Craniotomy equipment     Decapitation hook                                          31.0
                         Scissors (sharp straight, 145mm, s/s)                      31.0
                         Embryotomy scissors                                        31.0
                         Perforator                                                 23.0

Facility                                                                  National

Supplies for delivery    Disposable latex gloves (short)                      96.0
                         Disposable latex gloves (long)                       55.0
                         Plastic sheeting                                     76.0
                         Gauze swabs                                          97.0
                         Cloths or towels                                     33.0
Dressing instrument set  Gallipot bowl or jar (s/s)                           82.0
                         Needle holder (Mayo Hegar, 180mm, s/s                89.0
                         Scissors (sharp straight, 120mm, s/s)                89.0
                         Scissors (flat curved, 180mm, s/s                    84.0
                         Scissors (other types)                               32.0
                         Forceps (dissecting, Lane 1x2 teeth, 140mm)          68.0
                         Forceps (sponge [ring])                              88.0
                         Forceps (artery, mosquito straight, 130mm, s/s)      84.0
                         Forceps (other types)                                28.0
Gynaecological equipment Vaginal speculum (Sims)                              68.0
                         Vaginal speculum (Cusco, virgin size 75x17mm)        47.0
                         Cusco speculum (Cusco, adult size)                   71.0
                         Forceps (other types)                                50.0
                         Tenaculum (single-tooth/multi-teeth)                 69.0
                         Scissors (sharp straight, 145mm, s/s)                79.0
Craniotomy equipment     Decapitation hook                                     7.0
                         Scissors (sharp straight, 145mm, s/s)                 7.0
                         Embryotomy scissors                                   7.0
                         Perforator                                            7.0

In [136]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines123.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Guidelines, supplies, and medical equipment in labour and delivery and maternity wards/Percent of facilities with delivery sets, dressing instrument sets, and gynaecological and craniotomy equipment in the maternity area.csv")

In [138]:
my_tab = pd.crosstab(data['FT7'], data['Q243_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Instrument trolley']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q243_3']==1, data['Q243_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr

                        Instrument trolley
Facility
Referral/specialized                 100.0
General hospitals                     98.0
Primary hospitals                     92.0
MCH specialty centres                100.0
Health centres                        77.0
MCH specialty clinics                 94.0
Higher clinics                        85.0
National                              79.0

In [139]:
my_tab = pd.crosstab(data['FT7'], data['Q244_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Instrument tray']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q244_3']==1, data['Q244_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray

                        Instrument tray
Facility
Referral/specialized               93.0
General hospitals                  96.0
Primary hospitals                  87.0
MCH specialty centres              87.0
Health centres                     72.0
MCH specialty clinics              88.0
Higher clinics                     92.0
National                           73.0

In [140]:
my_tab = pd.crosstab(data['FT7'], data['Q245_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Beds']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q245_3']==1, data['Q245_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds

                         Beds
Facility
Referral/specialized    100.0
General hospitals        99.0
Primary hospitals       100.0
MCH specialty centres   100.0
Health centres           96.0
MCH specialty clinics    94.0
Higher clinics          100.0
National                 97.0

In [141]:
my_tab = pd.crosstab(data['FT7'], data['Q246_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Linens']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q246_3']==1, data['Q246_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens

                        Linens
Facility
Referral/specialized      93.0
General hospitals         94.0
Primary hospitals         90.0
MCH specialty centres     96.0
Health centres            68.0
MCH specialty clinics    100.0
Higher clinics            85.0
National                  70.0

In [142]:
my_tab = pd.crosstab(data['FT7'], data['Q247_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Blankets for cold weather']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q247_3']==1, data['Q247_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather

                        Blankets for cold weather
Facility
Referral/specialized                         97.0
General hospitals                            90.0
Primary hospitals                            90.0
MCH specialty centres                        96.0
Health centres                               72.0
MCH specialty clinics                       100.0
Higher clinics                               77.0
National                                     73.0

In [143]:
my_tab = pd.crosstab(data['FT7'], data['Q248_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Water filter (or other means to make potable water available to clients/staff)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q248_3']==1, data['Q248_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter

                        Water filter (or other means to make potable water available to clients/staff)
Facility
Referral/specialized                                                 40.0
General hospitals                                                    27.0
Primary hospitals                                                    16.0
MCH specialty centres                                                70.0
Health centres                                                       10.0
MCH specialty clinics                                                56.0
Higher clinics                                                       23.0
National                                                             12.0

In [144]:
my_tab = pd.crosstab(data['FT7'], data['Q230_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Wheelchair']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q230_3']==1, data['Q230_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair

                        Wheelchair
Facility
Referral/specialized         100.0
General hospitals             98.0
Primary hospitals             88.0
MCH specialty centres         96.0
Health centres                66.0
MCH specialty clinics         75.0
Higher clinics                77.0
National                      68.0

In [145]:
my_tab = pd.crosstab(data['FT7'], data['Q231_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Stretcher with trolley']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q231_3']==1, data['Q231_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley

                        Stretcher with trolley
Facility
Referral/specialized                      93.0
General hospitals                         97.0
Primary hospitals                         86.0
MCH specialty centres                     91.0
Health centres                            62.0
MCH specialty clinics                     69.0
Higher clinics                            77.0
National                                  64.0

In [146]:
my_tab = pd.crosstab(data['FT7'], data['Q232_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Examination table']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q232_3']==1, data['Q232_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table

                        Examination table
Facility
Referral/specialized                 97.0
General hospitals                    98.0
Primary hospitals                    99.0
MCH specialty centres               100.0
Health centres                       96.0
MCH specialty clinics               100.0
Higher clinics                       85.0
National                             97.0

In [147]:
my_tab = pd.crosstab(data['FT7'], data['Q233_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Labour/delivery table (with stirrups)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q233_3']==1, data['Q233_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery

                        Labour/delivery table (with stirrups)
Facility
Referral/specialized                                     93.0
General hospitals                                        92.0
Primary hospitals                                        90.0
MCH specialty centres                                   100.0
Health centres                                           75.0
MCH specialty clinics                                    94.0
Higher clinics                                           77.0
National                                                 76.0

In [148]:
my_tab = pd.crosstab(data['FT7'], data['Q234_3'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1[0]
#del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1[0]
del  Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Labour/delivery table (without stirrups)']
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1.columns= labels_of_col[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1.index= labels_of_col1[1:]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q234_3']==1, data['Q234_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1

                        Labour/delivery table (without stirrups)
Facility
Referral/specialized                                        80.0
General hospitals                                           62.0
Primary hospitals                                           56.0
MCH specialty centres                                       52.0
Health centres                                              62.0
MCH specialty clinics                                       69.0
Higher clinics                                              31.0
National                                                    62.0

In [149]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_trolleyr,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Instrument_tray,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Beds,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Linens,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Blankets_for_cold_weather,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Water_filter,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Wheelchair,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Stretcher_with_trolley,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Examination_table,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221

,Instrument trolley,Instrument tray,Beds,Linens,Blankets for cold weather,Water filter (or other means to make potable water available to clients/staff),Wheelchair,Stretcher with trolley,Examination table,Labour/delivery table (with stirrups),Labour/delivery table (without stirrups)
Facility,,,,,,,,,,,
Referral/specialized,100.0,93.0,100.0,93.0,97.0,40.0,100.0,93.0,97.0,93.0,80.0
General hospitals,98.0,96.0,99.0,94.0,90.0,27.0,98.0,97.0,98.0,92.0,62.0
Primary hospitals,92.0,87.0,100.0,90.0,90.0,16.0,88.0,86.0,99.0,90.0,56.0
MCH specialty centres,100.0,87.0,100.0,96.0,96.0,70.0,96.0,91.0,100.0,100.0,52.0
Health centres,77.0,72.0,96.0,68.0,72.0,10.0,66.0,62.0,96.0,75.0,62.0
MCH specialty clinics,94.0,88.0,94.0,100.0,100.0,56.0,75.0,69.0,100.0,94.0,69.0
Higher clinics,85.0,92.0,100.0,85.0,77.0,23.0,77.0,77.0,85.0,77.0,31.0
National,79.0,73.0,97.0,70.0,73.0,12.0,68.0,64.0,97.0,76.0,62.0

In [151]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Guidelines, supplies, and medical equipment in labour and delivery and maternity wards/Percent of facilities with selected furnishings and amenities in the maternity area.csv")

In [166]:
my_tab121 = pd.crosstab(data['Q302E_3']==1, data['Q302E_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_size_ambu  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Neonatal size ambu (ventilatory bag)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_size_ambu .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_size_ambu .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_size_ambu

                                      Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal size ambu (ventilatory bag)                                               94.0

In [167]:
my_tab121 = pd.crosstab(data['Q302B_3']==1, data['Q302B_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_extractor  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Mucus extractor/simple suction']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_extractor .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_extractor .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_extractor

                                Percent of facilities that have the indicated guidelines in the maternity_area
\t
Mucus extractor/simple suction                                               89.0

In [168]:
my_tab121 = pd.crosstab(data['Q302A_3']==1, data['Q302A_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_resuscitating  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Neonatal resuscitating table']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_resuscitating .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_resuscitating .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_resuscitating

                              Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal resuscitating table                                               81.0

In [169]:
my_tab121 = pd.crosstab(data['Q302D_3']==1, data['Q302D_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Neonatal face masks (size 1)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks

                              Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal face masks (size 1)                                               74.0

In [170]:
my_tab121 = pd.crosstab(data['Q302C_3']==1, data['Q302C_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Neonatal face masks (size 0)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks

                              Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal face masks (size 0)                                               74.0

In [171]:
my_tab121 = pd.crosstab(data['Q302K_3']==1, data['Q302K_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_trap_for_suction  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Mucus trap for suction']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_trap_for_suction .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_trap_for_suction .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_trap_for_suction

                        Percent of facilities that have the indicated guidelines in the maternity_area
\t
Mucus trap for suction                                               49.0

In [172]:
my_tab121 = pd.crosstab(data['Q302F_3']==1, data['Q302F_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_catheter  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Suction catheter (10, 12Ch)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_catheter .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_catheter .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_catheter

                             Percent of facilities that have the indicated guidelines in the maternity_area
\t
Suction catheter (10, 12Ch)                                               32.0

In [173]:
my_tab121 = pd.crosstab(data['Q302J_3']==1, data['Q302J_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_apparatus  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Suction apparatus (foot- or electrically-operated)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_apparatus .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_apparatus .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_apparatus

                                                    Percent of facilities that have the indicated guidelines in the maternity_area
\t
Suction apparatus (foot- or electrically-operated)                                               21.0

In [174]:
my_tab121 = pd.crosstab(data['Q302L_3']==1, data['Q302L_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Newborn_anatomical_model  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Newborn anatomical model (for practice)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Newborn_anatomical_model .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Newborn_anatomical_model .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Newborn_anatomical_model

                                         Percent of facilities that have the indicated guidelines in the maternity_area
\t
Newborn anatomical model (for practice)                                               11.0

In [175]:
my_tab121 = pd.crosstab(data['Q302H_3']==1, data['Q302H_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Endotracheal_tubes  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Endotracheal tubes (3.5, 3.0, 2.5mm)']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Endotracheal_tubes .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Endotracheal_tubes .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Endotracheal_tubes

                                      Percent of facilities that have the indicated guidelines in the maternity_area
\t
Endotracheal tubes (3.5, 3.0, 2.5mm)                                                7.0

In [176]:
my_tab121 = pd.crosstab(data['Q302G_3']==1, data['Q302G_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Infant_laryngoscope  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Infant laryngoscope with spare bulb and batteries']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Infant_laryngoscope .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Infant_laryngoscope .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Infant_laryngoscope

                                                   Percent of facilities that have the indicated guidelines in the maternity_area
\t
Infant laryngoscope with spare bulb and batteries                                                7.0

In [177]:
my_tab121 = pd.crosstab(data['Q302I_3']==1, data['Q302I_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1= ((my_tab121[1][1])/b)*100
Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural=round((my_tab1),0)
fata1 = [[Percentage_of_facilaities_Function_as_BEmONC_by_Location_Rural]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Disposable_uncuffed  = pd.DataFrame(fata1, columns =['Percent of facilities that have the indicated guidelines in the maternity_area'])
labels_of_col1 = ["	",'Disposable uncuffed tracheal tubes (sizes 2.0-3.5']
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Disposable_uncuffed .index= labels_of_col1[1:]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Disposable_uncuffed .index.names= [labels_of_col1[0]]
Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Disposable_uncuffed

                                                   Percent of facilities that have the indicated guidelines in the maternity_area
\t
Disposable uncuffed tracheal tubes (sizes 2.0-3.5                                                5.0

In [183]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_size_ambu,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_extractor,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_resuscitating,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Neonatal_face_masks,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Mucus_trap_for_suction,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_catheter,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Suction_apparatus,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Newborn_anatomical_model,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Endotracheal_tubes,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Infant_laryngoscope,Percent_of_facilities_with_selected_items_from_neonatal_resuscitation_pack_Disposable_uncuffed)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12213=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12213

                                                    Percent of facilities that have the indicated guidelines in the maternity_area
\t
Neonatal size ambu (ventilatory bag)                                                             94.0
Mucus extractor/simple suction                                                                   89.0
Neonatal resuscitating table                                                                     81.0
Neonatal face masks (size 0)                                                                     74.0
Neonatal face masks (size 0)                                                                     74.0
Mucus trap for suction                                                                           49.0
Suction catheter (10, 12Ch)                                                                      32.0
Suction apparatus (foot- or electrically-operated)                                               21.0
Newborn anatomical model (for practice)                                                          11.0
Endotracheal tubes (3.5, 3.0, 2.5mm)                                                              7.0
Infant laryngoscope with spare bulb and batteries                                                 7.0
Disposable uncuffed tracheal tubes (sizes 2.0-3.5                                                 5.0

In [184]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12213.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Newborn care equipment and supplies/Percent of facilities with selected items from neonatal resuscitation pack.csv")

In [187]:
my_tab = pd.crosstab(data['FT7'], data['Q401_3'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre[0]
del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Facility has an operating theatre (OT)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre

                        Facility has an operating theatre (OT)
Facility
Referral/specialized                                     100.0
General hospitals                                         98.0
Primary hospitals                                         78.0
MCH specialty centres                                     74.0
Health centres                                             0.0
MCH specialty clinics                                     12.0
Higher clinics                                            15.0

In [190]:
my_tab = pd.crosstab(data['FT7'], data['Q402_3'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1[0]
del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Facility has separate OT for obstetric clients']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1

                        Facility has separate OT for obstetric clients
Facility
Referral/specialized                                              77.0
General hospitals                                                 59.0
Primary hospitals                                                 34.0
MCH specialty centres                                             61.0
Health centres                                                     0.0
MCH specialty clinics                                              6.0
Higher clinics                                                     8.0

In [197]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre,Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre1)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery13313=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery13313

,Facility has an operating theatre (OT),Facility has separate OT for obstetric clients
Facility,,
Referral/specialized,77.0,77.0
General hospitals,59.0,59.0
Primary hospitals,34.0,34.0
MCH specialty centres,61.0,61.0
Health centres,0.0,0.0
MCH specialty clinics,6.0,6.0
Higher clinics,8.0,8.0

In [198]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12213.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Operating theatre and equipment/Percent of hospitals and MCH specialty centres with an operating theatre for allclients and for obstetric clients.csv")

In [379]:
my_tab = pd.crosstab(data['FT7'], data['Q403A_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Operating table']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table
Percent_of_hospitals_and_MCH_specialty_centres=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Operating_table.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres

                                      Operating table
Facility
Referral/specialized                            100.0
General hospitals                               100.0
Primary hospitals                               100.0
MCH specialized centres                         100.0
All hospitals/ MCH specialty centres            100.0

In [380]:
my_tab = pd.crosstab(data['FT7'], data['Q403B_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Light (adjustable, shadowless) ']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres1=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Light.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres1

                                      Light (adjustable, shadowless)
Facility
Referral/specialized                                            100.0
General hospitals                                                97.0
Primary hospitals                                                92.0
MCH specialized centres                                         100.0
All hospitals/ MCH specialty centres                            100.0

In [381]:
my_tab = pd.crosstab(data['FT7'], data['Q403C_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Surgical drapes']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres2=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Surgical_drapes.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres2

                                      Surgical drapes
Facility
Referral/specialized                            100.0
General hospitals                               100.0
Primary hospitals                               100.0
MCH specialized centres                         100.0
All hospitals/ MCH specialty centres            100.0

In [382]:
my_tab = pd.crosstab(data['FT7'], data['Q403D_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Syringes (5ml)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres3=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_5ml.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres3

                                      Syringes (5ml)
Facility
Referral/specialized                           100.0
General hospitals                               98.0
Primary hospitals                              100.0
MCH specialized centres                        100.0
All hospitals/ MCH specialty centres           100.0

In [383]:
my_tab = pd.crosstab(data['FT7'], data['Q403E_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Syringes (10ml)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres4=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_10ml.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres4

                                      Syringes (10ml)
Facility
Referral/specialized                            100.0
General hospitals                                99.0
Primary hospitals                                99.0
MCH specialized centres                         100.0
All hospitals/ MCH specialty centres            100.0

In [384]:
my_tab = pd.crosstab(data['FT7'], data['Q403F_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Syringes (20ml)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres5=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Syringes_20ml.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres5

                                      Syringes (20ml)
Facility
Referral/specialized                             90.0
General hospitals                                89.0
Primary hospitals                                78.0
MCH specialized centres                          91.0
All hospitals/ MCH specialty centres            100.0

In [385]:
my_tab = pd.crosstab(data['FT7'], data['Q403G_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Needles']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres6=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Needles.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres6

                                      Needles
Facility
Referral/specialized                     80.0
General hospitals                        90.0
Primary hospitals                        82.0
MCH specialized centres                 100.0
All hospitals/ MCH specialty centres    100.0

In [386]:
my_tab = pd.crosstab(data['FT7'], data['Q403H_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Adequate light to provide surgery during the day']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7

                                      Adequate light to provide surgery during the day
Facility
Referral/specialized                                                             100.0
General hospitals                                                                 98.0
Primary hospitals                                                                 96.0
MCH specialized centres                                                          100.0
All hospitals/ MCH specialty centres                                             100.0

In [387]:
my_tab = pd.crosstab(data['FT7'], data['Q403I_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Adequate light to provide surgery at night']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres8=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres8

                                      Adequate light to provide surgery at night
Facility
Referral/specialized                                                        97.0
General hospitals                                                           99.0
Primary hospitals                                                           93.0
MCH specialized centres                                                    100.0
All hospitals/ MCH specialty centres                                       100.0

In [388]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1222_4=(Percent_of_hospitals_and_MCH_specialty_centres.transpose(),Percent_of_hospitals_and_MCH_specialty_centres1.transpose(),Percent_of_hospitals_and_MCH_specialty_centres2.transpose(),Percent_of_hospitals_and_MCH_specialty_centres3.transpose(),Percent_of_hospitals_and_MCH_specialty_centres4.transpose(),Percent_of_hospitals_and_MCH_specialty_centres5.transpose(),Percent_of_hospitals_and_MCH_specialty_centres6.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7.transpose(),Percent_of_hospitals_and_MCH_specialty_centres8.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12201=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1222_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12201

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialized centres,All hospitals/ MCH specialty centres
,,,,,
Operating table,100.0,100.0,100.0,100.0,100.0
"Light (adjustable, shadowless)",100.0,97.0,92.0,100.0,100.0
Surgical drapes,100.0,100.0,100.0,100.0,100.0
Syringes (5ml),100.0,98.0,100.0,100.0,100.0
Syringes (10ml),100.0,99.0,99.0,100.0,100.0
Syringes (20ml),90.0,89.0,78.0,91.0,100.0
Needles,80.0,90.0,82.0,100.0,100.0
Adequate light to provide surgery during the day,100.0,98.0,96.0,100.0,100.0
Adequate light to provide surgery at night,97.0,99.0,93.0,100.0,100.0

In [389]:
my_tab = pd.crosstab(data['FT7'], data['Q404A_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Instrument tray with cover (stainless steel)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres71=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres71

                                      Instrument tray with cover (stainless steel)
Facility
Referral/specialized                                                          97.0
General hospitals                                                             97.0
Primary hospitals                                                             95.0
MCH specialized centres                                                      100.0
All hospitals/ MCH specialty centres                                         100.0

In [390]:
my_tab = pd.crosstab(data['FT7'], data['Q404B_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Towel clips']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres72=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres72

                                      Towel clips
Facility
Referral/specialized                        100.0
General hospitals                           100.0
Primary hospitals                            98.0
MCH specialized centres                     100.0
All hospitals/ MCH specialty centres        100.0

In [391]:
my_tab = pd.crosstab(data['FT7'], data['Q404C_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Forceps (sponge, 22.5cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres73=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres73

                                      Forceps (sponge, 22.5cm)
Facility
Referral/specialized                                     100.0
General hospitals                                         99.0
Primary hospitals                                         99.0
MCH specialized centres                                  100.0
All hospitals/ MCH specialty centres                     100.0

In [392]:
my_tab = pd.crosstab(data['FT7'], data['Q404D_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Forceps (straight artery, 16cm) ']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres74=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres74

                                      Forceps (straight artery, 16cm)
Facility
Referral/specialized                                             100.0
General hospitals                                                 99.0
Primary hospitals                                                100.0
MCH specialized centres                                          100.0
All hospitals/ MCH specialty centres                             100.0

In [393]:
my_tab = pd.crosstab(data['FT7'], data['Q404E_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Forceps (uterine haemostasis, 20cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres75=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres75

                                      Forceps (uterine haemostasis, 20cm)
Facility
Referral/specialized                                                 97.0
General hospitals                                                    91.0
Primary hospitals                                                    90.0
MCH specialized centres                                              96.0
All hospitals/ MCH specialty centres                                100.0

In [394]:
my_tab = pd.crosstab(data['FT7'], data['Q404F_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Needle holder']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres76=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres76

                                      Needle holder
Facility
Referral/specialized                          100.0
General hospitals                             100.0
Primary hospitals                              99.0
MCH specialized centres                       100.0
All hospitals/ MCH specialty centres          100.0

In [395]:
my_tab = pd.crosstab(data['FT7'], data['Q404G_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Surgical knife handle (#3)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres77=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres77

                                      Surgical knife handle (#3)
Facility
Referral/specialized                                        97.0
General hospitals                                           99.0
Primary hospitals                                           96.0
MCH specialized centres                                    100.0
All hospitals/ MCH specialty centres                       100.0

In [396]:
my_tab = pd.crosstab(data['FT7'], data['Q404H_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Surgical knife handle (#4)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres78=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres78

                                      Surgical knife handle (#4)
Facility
Referral/specialized                                       100.0
General hospitals                                           99.0
Primary hospitals                                           98.0
MCH specialized centres                                    100.0
All hospitals/ MCH specialty centres                       100.0

In [397]:
my_tab = pd.crosstab(data['FT7'], data['Q404I_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Surgical knife blades']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres79=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres79

                                      Surgical knife blades
Facility
Referral/specialized                                  100.0
General hospitals                                     100.0
Primary hospitals                                      98.0
MCH specialized centres                               100.0
All hospitals/ MCH specialty centres                  100.0

In [398]:
my_tab = pd.crosstab(data['FT7'], data['Q404J_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Needles (triangular point suture, 7.3cm, size 6)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres721=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres721

                                      Needles (triangular point suture, 7.3cm, size 6)
Facility
Referral/specialized                                                              83.0
General hospitals                                                                 87.0
Primary hospitals                                                                 89.0
MCH specialized centres                                                           96.0
All hospitals/ MCH specialty centres                                             100.0

In [399]:
my_tab = pd.crosstab(data['FT7'], data['Q404K_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Needles (round-bodied, #12, size 6) ']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres722=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres722

                                      Needles (round-bodied, #12, size 6)
Facility
Referral/specialized                                                  93.0
General hospitals                                                     96.0
Primary hospitals                                                     91.0
MCH specialized centres                                              100.0
All hospitals/ MCH specialty centres                                 100.0

In [400]:
my_tab = pd.crosstab(data['FT7'], data['Q404L_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Abdominal retractor (size 3) ']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres723=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres723

                                      Abdominal retractor (size 3)
Facility
Referral/specialized                                          100.0
General hospitals                                              97.0
Primary hospitals                                              98.0
MCH specialized centres                                        91.0
All hospitals/ MCH specialty centres                          100.0

In [401]:
my_tab = pd.crosstab(data['FT7'], data['Q404M_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Abdominal retractor (double-ended, Richardson)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres724=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres724

                                      Abdominal retractor (double-ended, Richardson)
Facility
Referral/specialized                                                            97.0
General hospitals                                                               93.0
Primary hospitals                                                               92.0
MCH specialized centres                                                        100.0
All hospitals/ MCH specialty centres                                           100.0

In [402]:
my_tab = pd.crosstab(data['FT7'], data['Q404N_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Scissors (curved operating, blunt pointed, Mayo, 17cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres725=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres725

                                      Scissors (curved operating, blunt pointed, Mayo, 17cm)
Facility
Referral/specialized                                                              100.0
General hospitals                                                                  98.0
Primary hospitals                                                                  99.0
MCH specialized centres                                                           100.0
All hospitals/ MCH specialty centres                                              100.0

In [403]:
my_tab = pd.crosstab(data['FT7'], data['Q404O_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Scissors (straight operating, blunt pointed, Mayo, 17cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres726=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres726

                                      Scissors (straight operating, blunt pointed, Mayo, 17cm)
Facility
Referral/specialized                                                              100.0
General hospitals                                                                  97.0
Primary hospitals                                                                  99.0
MCH specialized centres                                                           100.0
All hospitals/ MCH specialty centres                                              100.0

In [404]:
my_tab = pd.crosstab(data['FT7'], data['Q404P_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Scissors (straight, 23cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres727=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres727

                                      Scissors (straight, 23cm)
Facility
Referral/specialized                                       97.0
General hospitals                                          98.0
Primary hospitals                                          98.0
MCH specialized centres                                   100.0
All hospitals/ MCH specialty centres                      100.0

In [405]:
my_tab = pd.crosstab(data['FT7'], data['Q404Q_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Suction nozzle']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres728=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres728

                                      Suction nozzle
Facility
Referral/specialized                            97.0
General hospitals                               96.0
Primary hospitals                               93.0
MCH specialized centres                        100.0
All hospitals/ MCH specialty centres           100.0

In [406]:
my_tab = pd.crosstab(data['FT7'], data['Q404R_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Suction tube (22.5cm, 23 French gauge)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres729=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres729

                                      Suction tube (22.5cm, 23 French gauge)
Facility
Referral/specialized                                                    97.0
General hospitals                                                       97.0
Primary hospitals                                                       97.0
MCH specialized centres                                                100.0
All hospitals/ MCH specialty centres                                   100.0

In [407]:
my_tab = pd.crosstab(data['FT7'], data['Q404S_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Intestinal clamps (curved, 22.5cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7291=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7291

                                      Intestinal clamps (curved, 22.5cm)
Facility
Referral/specialized                                                97.0
General hospitals                                                   96.0
Primary hospitals                                                   95.0
MCH specialized centres                                             91.0
All hospitals/ MCH specialty centres                               100.0

In [408]:
my_tab = pd.crosstab(data['FT7'], data['Q404T_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Intestinal clamps (straight, 22.5cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7292=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7292

                                      Intestinal clamps (straight, 22.5cm)
Facility
Referral/specialized                                                  97.0
General hospitals                                                     97.0
Primary hospitals                                                     92.0
MCH specialized centres                                               96.0
All hospitals/ MCH specialty centres                                 100.0

In [409]:
my_tab = pd.crosstab(data['FT7'], data['Q404U_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Dressing (non-toothed tissue) forceps (15cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7293=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7293

                                      Dressing (non-toothed tissue) forceps (15cm)
Facility
Referral/specialized                                                          97.0
General hospitals                                                             99.0
Primary hospitals                                                             99.0
MCH specialized centres                                                      100.0
All hospitals/ MCH specialty centres                                         100.0

In [410]:
my_tab = pd.crosstab(data['FT7'], data['Q404V_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Dressing (non-toothed tissue) forceps (25cm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7294=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7294

                                      Dressing (non-toothed tissue) forceps (25cm)
Facility
Referral/specialized                                                          97.0
General hospitals                                                            100.0
Primary hospitals                                                             98.0
MCH specialized centres                                                       96.0
All hospitals/ MCH specialty centres                                         100.0

In [411]:
my_tab = pd.crosstab(data['FT7'], data['Q404W_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Sutures (different sizes and types)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7295=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7295

                                      Sutures (different sizes and types)
Facility
Referral/specialized                                                 97.0
General hospitals                                                    99.0
Primary hospitals                                                   100.0
MCH specialized centres                                             100.0
All hospitals/ MCH specialty centres                                100.0

In [412]:
my_tab = pd.crosstab(data['FT7'], data['Q404X_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Mini-laparotomy kit (for female sterilization)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres7296=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres7296

                                      Mini-laparotomy kit (for female sterilization)
Facility
Referral/specialized                                                            87.0
General hospitals                                                               84.0
Primary hospitals                                                               77.0
MCH specialized centres                                                         96.0
All hospitals/ MCH specialty centres                                           100.0

In [413]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_hospitals_and_MCH_specialty_centres71.transpose(),Percent_of_hospitals_and_MCH_specialty_centres72.transpose(),Percent_of_hospitals_and_MCH_specialty_centres73.transpose(),Percent_of_hospitals_and_MCH_specialty_centres74.transpose(),Percent_of_hospitals_and_MCH_specialty_centres75.transpose(),Percent_of_hospitals_and_MCH_specialty_centres76.transpose(),Percent_of_hospitals_and_MCH_specialty_centres77.transpose(),Percent_of_hospitals_and_MCH_specialty_centres78.transpose(),Percent_of_hospitals_and_MCH_specialty_centres79.transpose(),Percent_of_hospitals_and_MCH_specialty_centres721.transpose(),Percent_of_hospitals_and_MCH_specialty_centres722.transpose(),Percent_of_hospitals_and_MCH_specialty_centres723.transpose(),Percent_of_hospitals_and_MCH_specialty_centres724.transpose(),Percent_of_hospitals_and_MCH_specialty_centres725.transpose(),Percent_of_hospitals_and_MCH_specialty_centres726.transpose(),Percent_of_hospitals_and_MCH_specialty_centres727.transpose(),Percent_of_hospitals_and_MCH_specialty_centres728.transpose(),Percent_of_hospitals_and_MCH_specialty_centres729.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7291.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7292.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7293.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7294.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7295.transpose(),Percent_of_hospitals_and_MCH_specialty_centres7296.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12211=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12211

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialized centres,All hospitals/ MCH specialty centres
,,,,,
Instrument tray with cover (stainless steel),97.0,97.0,95.0,100.0,100.0
Towel clips,100.0,100.0,98.0,100.0,100.0
"Forceps (sponge, 22.5cm)",100.0,99.0,99.0,100.0,100.0
"Forceps (straight artery, 16cm)",100.0,99.0,100.0,100.0,100.0
"Forceps (uterine haemostasis, 20cm)",97.0,91.0,90.0,96.0,100.0
Needle holder,100.0,100.0,99.0,100.0,100.0
Surgical knife handle (#3),97.0,99.0,96.0,100.0,100.0
Surgical knife handle (#4),100.0,99.0,98.0,100.0,100.0
Surgical knife blades,100.0,100.0,98.0,100.0,100.0
"Needles (triangular point suture, 7.3cm, size 6)",83.0,87.0,89.0,96.0,100.0
"Needles (round-bodied, #12, size 6)",93.0,96.0,91.0,100.0,100.0
Abdominal retractor (size 3),100.0,97.0,98.0,91.0,100.0
"Abdominal retractor (double-ended, Richardson)",97.0,93.0,92.0,100.0,100.0
"Scissors (curved operating, blunt pointed, Mayo, 17cm)",100.0,98.0,99.0,100.0,100.0
"Scissors (straight operating, blunt pointed, Mayo, 17cm)",100.0,97.0,99.0,100.0,100.0
"Scissors (straight, 23cm)",97.0,98.0,98.0,100.0,100.0
Suction nozzle,97.0,96.0,93.0,100.0,100.0
"Suction tube (22.5cm, 23 French gauge)",97.0,97.0,97.0,100.0,100.0
"Intestinal clamps (curved, 22.5cm)",97.0,96.0,95.0,91.0,100.0
"Intestinal clamps (straight, 22.5cm)",97.0,97.0,92.0,96.0,100.0
Dressing (non-toothed tissue) forceps (15cm),97.0,99.0,99.0,100.0,100.0
Dressing (non-toothed tissue) forceps (25cm),97.0,100.0,98.0,96.0,100.0
Sutures (different sizes and types),97.0,99.0,100.0,100.0,100.0
Mini-laparotomy kit (for female sterilization),87.0,84.0,77.0,96.0,100.0

In [414]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12201,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12211)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines1230=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Basic items', 'Obstetric laparotomy/caesarean delivery pack'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines1230

Facility                                                                                         Referral/specialized  \

Basic items                                  Operating table                                                    100.0
                                             Light (adjustable, shadowless)                                     100.0
                                             Surgical drapes                                                    100.0
                                             Syringes (5ml)                                                     100.0
                                             Syringes (10ml)                                                    100.0
                                             Syringes (20ml)                                                     90.0
                                             Needles                                                             80.0
                                             Adequate light to provide surgery during the day                   100.0
                                             Adequate light to provide surgery at night                          97.0
Obstetric laparotomy/caesarean delivery pack Instrument tray with cover (stainless steel)                        97.0
                                             Towel clips                                                        100.0
                                             Forceps (sponge, 22.5cm)                                           100.0
                                             Forceps (straight artery, 16cm)                                    100.0
                                             Forceps (uterine haemostasis, 20cm)                                 97.0
                                             Needle holder                                                      100.0
                                             Surgical knife handle (#3)                                          97.0
                                             Surgical knife handle (#4)                                         100.0
                                             Surgical knife blades                                              100.0
                                             Needles (triangular point suture, 7.3cm, size 6)                    83.0
                                             Needles (round-bodied, #12, size 6)                                 93.0
                                             Abdominal retractor (size 3)                                       100.0
                                             Abdominal retractor (double-ended, Richardson)                      97.0
                                             Scissors (curved operating, blunt pointed, Mayo...                 100.0
                                             Scissors (straight operating, blunt pointed, Ma...                 100.0
                                             Scissors (straight, 23cm)                                           97.0
                                             Suction nozzle                                                      97.0
                                             Suction tube (22.5cm, 23 French gauge)                              97.0
                                             Intestinal clamps (curved, 22.5cm)                                  97.0
                                             Intestinal clamps (straight, 22.5cm)                                97.0
                                             Dressing (non-toothed tissue) forceps (15cm)                        97.0
                                             Dressing (non-toothed tissue) forceps (25cm)                        97.0
                                             Sutures (different sizes and types)                                 97.0
                                             Mini-laparotomy kit (for female sterilization)                      87.0

Facility                                                                                         General hospitals  \

Basic items                                  Operating table                                                 100.0
                                             Light (adjustable, shadowless)                                   97.0
                                             Surgical drapes                                                 100.0
                                             Syringes (5ml)                                                   98.0
                                             Syringes (10ml)                                                  99.0
                                             Syringes (20ml)                                                  89.0
                                             Needles                                                          90.0
                                             Adequate light to provide surgery during the day                 98.0
                                             Adequate light to provide surgery at night                       99.0
Obstetric laparotomy/caesarean delivery pack Instrument tray with cover (stainless steel)                     97.0
                                             Towel clips                                                     100.0
                                             Forceps (sponge, 22.5cm)                                         99.0
                                             Forceps (straight artery, 16cm)                                  99.0
                                             Forceps (uterine haemostasis, 20cm)                              91.0
                                             Needle holder                                                   100.0
                                             Surgical knife handle (#3)                                       99.0
                                             Surgical knife handle (#4)                                       99.0
                                             Surgical knife blades                                           100.0
                                             Needles (triangular point suture, 7.3cm, size 6)                 87.0
                                             Needles (round-bodied, #12, size 6)                              96.0
                                             Abdominal retractor (size 3)                                     97.0
                                             Abdominal retractor (double-ended, Richardson)                   93.0
                                             Scissors (curved operating, blunt pointed, Mayo...               98.0
                                             Scissors (straight operating, blunt pointed, Ma...               97.0
                                             Scissors (straight, 23cm)                                        98.0
                                             Suction nozzle                                                   96.0
                                             Suction tube (22.5cm, 23 French gauge)                           97.0
                                             Intestinal clamps (curved, 22.5cm)                               96.0
                                             Intestinal clamps (straight, 22.5cm)                             97.0
                                             Dressing (non-toothed tissue) forceps (15cm)                     99.0
                                             Dressing (non-toothed tissue) forceps (25cm)                    100.0
                                             Sutures (different sizes and types)                              99.0
                                             Mini-laparotomy kit (for female sterilization)                   84.0

Facility                                                                                         Primary hospitals   \

Basic items                                  Operating table                                                  100.0
                                             Light (adjustable, shadowless)                                    92.0
                                             Surgical drapes                                                  100.0
                                             Syringes (5ml)                                                   100.0
                                             Syringes (10ml)                                                   99.0
                                             Syringes (20ml)                                                   78.0
                                             Needles                                                           82.0
                                             Adequate light to provide surgery during the day                  96.0
                                             Adequate light to provide surgery at night                        93.0
Obstetric laparotomy/caesarean delivery pack Instrument tray with cover (stainless steel)                      95.0
                                             Towel clips                                                       98.0
                                             Forceps (sponge, 22.5cm)                                          99.0
                                             Forceps (straight artery, 16cm)                                  100.0
                                             Forceps (uterine haemostasis, 20cm)                               90.0
                                             Needle holder                                                     99.0
                                             Surgical knife handle (#3)                                        96.0
                                             Surgical knife handle (#4)                                        98.0
                                             Surgical knife blades                                             98.0
                                             Needles (triangular point suture, 7.3cm, size 6)                  89.0
                                             Needles (round-bodied, #12, size 6)                               91.0
                                             Abdominal retractor (size 3)                                      98.0
                                             Abdominal retractor (double-ended, Richardson)                    92.0
                                             Scissors (curved operating, blunt pointed, Mayo...                99.0
                                             Scissors (straight operating, blunt pointed, Ma...                99.0
                                             Scissors (straight, 23cm)                                         98.0
                                             Suction nozzle                                                    93.0
                                             Suction tube (22.5cm, 23 French gauge)                            97.0
                                             Intestinal clamps (curved, 22.5cm)                                95.0
                                             Intestinal clamps (straight, 22.5cm)                              92.0
                                             Dressing (non-toothed tissue) forceps (15cm)                      99.0
                                             Dressing (non-toothed tissue) forceps (25cm)                      98.0
                                             Sutures (different sizes and types)                              100.0
                                             Mini-laparotomy kit (for female sterilization)                    77.0

Facility                                                                                         MCH specialized centres   \

Basic items                                  Operating table                                                        100.0
                                             Light (adjustable, shadowless)                                         100.0
                                             Surgical drapes                                                        100.0
                                             Syringes (5ml)                                                         100.0
                                             Syringes (10ml)                                                        100.0
                                             Syringes (20ml)                                                         91.0
                                             Needles                                                                100.0
                                             Adequate light to provide surgery during the day                       100.0
                                             Adequate light to provide surgery at night                             100.0
Obstetric laparotomy/caesarean delivery pack Instrument tray with cover (stainless steel)                           100.0
                                             Towel clips                                                            100.0
                                             Forceps (sponge, 22.5cm)                                               100.0
                                             Forceps (straight artery, 16cm)                                        100.0
                                             Forceps (uterine haemostasis, 20cm)                                     96.0
                                             Needle holder                                                          100.0
                                             Surgical knife handle (#3)                                             100.0
                                             Surgical knife handle (#4)                                             100.0
                                             Surgical knife blades                                                  100.0
                                             Needles (triangular point suture, 7.3cm, size 6)                        96.0
                                             Needles (round-bodied, #12, size 6)                                    100.0
                                             Abdominal retractor (size 3)                                            91.0
                                             Abdominal retractor (double-ended, Richardson)                         100.0
                                             Scissors (curved operating, blunt pointed, Mayo...                     100.0
                                             Scissors (straight operating, blunt pointed, Ma...                     100.0
                                             Scissors (straight, 23cm)                                              100.0
                                             Suction nozzle                                                         100.0
                                             Suction tube (22.5cm, 23 French gauge)                                 100.0
                                             Intestinal clamps (curved, 22.5cm)                                      91.0
                                             Intestinal clamps (straight, 22.5cm)                                    96.0
                                             Dressing (non-toothed tissue) forceps (15cm)                           100.0
                                             Dressing (non-toothed tissue) forceps (25cm)                            96.0
                                             Sutures (different sizes and types)                                    100.0
                                             Mini-laparotomy kit (for female sterilization)                          96.0

Facility                                                                                         All hospitals/ MCH specialty centres

Basic items                                  Operating table                                                                    100.0
                                             Light (adjustable, shadowless)                                                     100.0
                                             Surgical drapes                                                                    100.0
                                             Syringes (5ml)                                                                     100.0
                                             Syringes (10ml)                                                                    100.0
                                             Syringes (20ml)                                                                    100.0
                                             Needles                                                                            100.0
                                             Adequate light to provide surgery during the day                                   100.0
                                             Adequate light to provide surgery at night                                         100.0
Obstetric laparotomy/caesarean delivery pack Instrument tray with cover (stainless steel)                                       100.0
                                             Towel clips                                                                        100.0
                                             Forceps (sponge, 22.5cm)                                                           100.0
                                             Forceps (straight artery, 16cm)                                                    100.0
                                             Forceps (uterine haemostasis, 20cm)                                                100.0
                                             Needle holder                                                                      100.0
                                             Surgical knife handle (#3)                                                         100.0
                                             Surgical knife handle (#4)                                                         100.0
                                             Surgical knife blades                                                              100.0
                                             Needles (triangular point suture, 7.3cm, size 6)                                   100.0
                                             Needles (round-bodied, #12, size 6)                                                100.0
                                             Abdominal retractor (size 3)                                                       100.0
                                             Abdominal retractor (double-ended, Richardson)                                     100.0
                                             Scissors (curved operating, blunt pointed, Mayo...                                 100.0
                                             Scissors (straight operating, blunt pointed, Ma...                                 100.0
                                             Scissors (straight, 23cm)                                                          100.0
                                             Suction nozzle                                                                     100.0
                                             Suction tube (22.5cm, 23 French gauge)                                             100.0
                                             Intestinal clamps (curved, 22.5cm)                                                 100.0

In [374]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines1230.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Operating theatre and equipment/Percent of hospitals and MCH specialty centres with an operating theatre that haveselect equipment and supplies.csv")

In [460]:
my_tab = pd.crosstab(data['Q007'], data['Q405A_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
#del  Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Anaesthetic face masks']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia

                                      Anaesthetic face masks
Facility
Referral/specialized                                   100.0
General hospitals                                       98.0
Primary hospitals                                       99.0
MCH specialized centres                                100.0
All hospitals/ MCH specialty centres                   100.0

In [461]:
my_tab = pd.crosstab(data['FT7'], data['Q405A_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Anaesthetic face masks']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia1=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia1

                                      Anaesthetic face masks
Facility
Referral/specialized                                   100.0
General hospitals                                       98.0
Primary hospitals                                       99.0
MCH specialized centres                                100.0
All hospitals/ MCH specialty centres                   100.0

In [462]:
my_tab = pd.crosstab(data['FT7'], data['Q405C_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Oropharyngeal airways']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal

                                      Oropharyngeal airways
Facility
Referral/specialized                                  100.0
General hospitals                                      95.0
Primary hospitals                                      96.0
MCH specialized centres                                96.0
All hospitals/ MCH specialty centres                  100.0

In [463]:
my_tab = pd.crosstab(data['FT7'], data['Q405D_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Endotracheal tubes with cuffs (8mm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes

                                      Endotracheal tubes with cuffs (8mm)
Facility
Referral/specialized                                                100.0
General hospitals                                                    98.0
Primary hospitals                                                    94.0
MCH specialized centres                                              96.0
All hospitals/ MCH specialty centres                                 94.0

In [464]:
my_tab = pd.crosstab(data['FT7'], data['Q405E_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Endotracheal tubes with cuffs (10mm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes1=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes1

                                      Endotracheal tubes with cuffs (10mm)
Facility
Referral/specialized                                                  90.0
General hospitals                                                     93.0
Primary hospitals                                                     89.0
MCH specialized centres                                               96.0
All hospitals/ MCH specialty centres                                  94.0

In [465]:
my_tab = pd.crosstab(data['FT7'], data['Q405F_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Endotracheal tubes with cuffs (2.5-3.5mm)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes_with_cuff=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes_with_cuff

                                      Endotracheal tubes with cuffs (2.5-3.5mm)
Facility
Referral/specialized                                                       90.0
General hospitals                                                          93.0
Primary hospitals                                                          88.0
MCH specialized centres                                                    91.0
All hospitals/ MCH specialty centres                                      100.0

In [466]:
my_tab = pd.crosstab(data['FT7'], data['Q405G_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Intubating forceps']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal2=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal2

                                      Intubating forceps
Facility
Referral/specialized                                87.0
General hospitals                                   83.0
Primary hospitals                                   78.0
MCH specialized centres                             96.0
All hospitals/ MCH specialty centres               100.0

In [467]:
my_tab = pd.crosstab(data['FT7'], data['Q405H_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Endotracheal tube connectors (15mm plastic, connect directly to breathing valve, three for each tube size)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tube_connectors=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tube_connectors

                                      Endotracheal tube connectors (15mm plastic, connect directly to breathing valve, three for each tube size)
Facility
Referral/specialized                                                               97.0
General hospitals                                                                  88.0
Primary hospitals                                                                  91.0
MCH specialized centres                                                            96.0
All hospitals/ MCH specialty centres                                              100.0

In [468]:
my_tab = pd.crosstab(data['FT7'], data['Q405I_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Spinal needles (18-25 gauge)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Spinal_needles=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Spinal_needles

                                      Spinal needles (18-25 gauge)
Facility
Referral/specialized                                          90.0
General hospitals                                             93.0
Primary hospitals                                             94.0
MCH specialized centres                                      100.0
All hospitals/ MCH specialty centres                         100.0

In [469]:
my_tab = pd.crosstab(data['FT7'], data['Q405J_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Suction aspirator (foot-operated)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator

                                      Suction aspirator (foot-operated)
Facility
Referral/specialized                                               70.0
General hospitals                                                  76.0
Primary hospitals                                                  74.0
MCH specialized centres                                            83.0
All hospitals/ MCH specialty centres                               88.0

In [470]:
my_tab = pd.crosstab(data['FT7'], data['Q405K_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Suction aspirator (electric)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator_electric=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator_electric

                                      Suction aspirator (electric)
Facility
Referral/specialized                                         100.0
General hospitals                                             95.0
Primary hospitals                                             96.0
MCH specialized centres                                      100.0
All hospitals/ MCH specialty centres                         100.0

In [471]:
my_tab = pd.crosstab(data['FT7'], data['Q405L_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Anaesthetic vaporizers (draw-over system)']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Anaesthetic_vaporizers=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Anaesthetic_vaporizers

                                      Anaesthetic vaporizers (draw-over system)
Facility
Referral/specialized                                                       97.0
General hospitals                                                          88.0
Primary hospitals                                                          86.0
MCH specialized centres                                                    96.0
All hospitals/ MCH specialty centres                                       94.0

In [472]:
my_tab = pd.crosstab(data['FT7'], data['Q405M_3']!=0)
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres ','Health centres','All hospitals/ MCH specialty centres','Higher clinics']
labels_of_col = ["",'Oxygen cylinders with manometer and flowmeter (low flow) tubes and connectors']
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns= labels_of_col[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index= labels_of_col1[1:]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.columns.names= [labels_of_col[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.index.names= [labels_of_col1[0]]
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oxygen_cylinders_with_manometer=Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_select_equipment_and_supplies_Adequate_light_to_provide.drop(['Higher clinics', 'Health centres'])
Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oxygen_cylinders_with_manometer

                                      Oxygen cylinders with manometer and flowmeter (low flow) tubes and connectors
Facility
Referral/specialized                                                              100.0
General hospitals                                                                  98.0
Primary hospitals                                                                  98.0
MCH specialized centres                                                           100.0
All hospitals/ MCH specialty centres                                              100.0

In [474]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes1.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tubes_with_cuff.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oropharyngeal2.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Endotracheal_tube_connectors.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Spinal_needles.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Suction_aspirator_electric.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Anaesthetic_vaporizers.transpose(),Percent_of_hospitals_and_MCH_specialty_centres_with_an_operating_theatre_that_have_anaesthesia_Oxygen_cylinders_with_manometer.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122100=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122100

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialized centres,All hospitals/ MCH specialty centres
,,,,,
Anaesthetic face masks,100.0,98.0,99.0,100.0,100.0
Anaesthetic face masks,100.0,98.0,99.0,100.0,100.0
Oropharyngeal airways,100.0,95.0,96.0,96.0,100.0
Endotracheal tubes with cuffs (8mm),100.0,98.0,94.0,96.0,94.0
Endotracheal tubes with cuffs (10mm),90.0,93.0,89.0,96.0,94.0
Endotracheal tubes with cuffs (2.5-3.5mm),90.0,93.0,88.0,91.0,100.0
Intubating forceps,87.0,83.0,78.0,96.0,100.0
"Endotracheal tube connectors (15mm plastic, connect directly to breathing valve, three for each tube size)",97.0,88.0,91.0,96.0,100.0
Spinal needles (18-25 gauge),90.0,93.0,94.0,100.0,100.0
Suction aspirator (foot-operated),70.0,76.0,74.0,83.0,88.0
Suction aspirator (electric),100.0,95.0,96.0,100.0,100.0
Anaesthetic vaporizers (draw-over system),97.0,88.0,86.0,96.0,94.0
Oxygen cylinders with manometer and flowmeter (low flow) tubes and connectors,100.0,98.0,98.0,100.0,100.0

In [475]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122100.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Operating theatre and equipment/ Percent of hospitals and MCH specialty centres with an operating theatre that have anaesthesia equipment and supplies.csv")

In [623]:
my_tab = pd.crosstab(data['FT7'], data['Q501_3'])
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12[0]
del  Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Facility has a laboratory']
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q501_3']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12

                        Facility has a laboratory
Facility
Referral/specialized                        100.0
General hospitals                           100.0
Primary hospitals                            99.0
MCH specialty centres                       100.0
Health centres                               78.0
MCH specialty clinics                       100.0
Higher clinics                              100.0
National                                     80.0

In [624]:
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q502_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Facility has set of guidelines for laborator']
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q502_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1

                        Facility has set of guidelines for laborator
Facility
Referral/specialized                                           100.0
General hospitals                                               94.0
Primary hospitals                                               83.0
MCH specialty centres                                           74.0
Health centres                                                  62.0
MCH specialty clinics                                           81.0
Higher clinics                                                  69.0
National                                                        65.0

In [625]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503A_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Refrigerator for blood bank']
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503A_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1

                        Refrigerator for blood bank
Facility
Referral/specialized                           97.0
General hospitals                              82.0
Primary hospitals                              57.0
MCH specialty centres                          70.0
Health centres                                  4.0
MCH specialty clinics                          12.0
Higher clinics                                 31.0
National                                       11.0

In [626]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503B_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Test tubes (various sizes)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503B_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1

                        Test tubes (various sizes)
Facility
Referral/specialized                         100.0
General hospitals                             95.0
Primary hospitals                             82.0
MCH specialty centres                        100.0
Health centres                                66.0
MCH specialty clinics                         94.0
Higher clinics                                92.0
National                                      69.0

In [627]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503C_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Microscope slides']
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503C_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1

                        Microscope slides
Facility
Referral/specialized                100.0
General hospitals                    99.0
Primary hospitals                    97.0
MCH specialty centres               100.0
Health centres                       86.0
MCH specialty clinics                94.0
Higher clinics                       92.0
National                             88.0

In [628]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503D_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Compound microscope for crossmatching']
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503D_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1

                        Compound microscope for crossmatching
Facility
Referral/specialized                                     83.0
General hospitals                                        76.0
Primary hospitals                                        63.0
MCH specialty centres                                    74.0
Health centres                                           29.0
MCH specialty clinics                                    50.0
Higher clinics                                           54.0
National                                                 34.0

In [629]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503E_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Microscope illuminator']
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503E_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1

                        Microscope illuminator
Facility
Referral/specialized                      70.0
General hospitals                         59.0
Primary hospitals                         54.0
MCH specialty centres                     52.0
Health centres                            38.0
MCH specialty clinics                     62.0
Higher clinics                            54.0
National                                  40.0

In [630]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503F_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Blood lancets']
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503F_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1

                        Blood lancets
Facility
Referral/specialized             97.0
General hospitals                97.0
Primary hospitals                92.0
MCH specialty centres           100.0
Health centres                   85.0
MCH specialty clinics            94.0
Higher clinics                   85.0
National                         86.0

In [631]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503G_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Cotton wool']
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503G_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1

                        Cotton wool
Facility
Referral/specialized          100.0
General hospitals              99.0
Primary hospitals              96.0
MCH specialty centres         100.0
Health centres                 88.0
MCH specialty clinics          94.0
Higher clinics                 85.0
National                       89.0

In [632]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503H_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Rack[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Rack),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Rack']
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503H_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1

                         Rack
Facility
Referral/specialized    100.0
General hospitals        98.0
Primary hospitals        94.0
MCH specialty centres   100.0
Health centres           77.0
MCH specialty clinics    94.0
Higher clinics           92.0
National                 80.0

In [633]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503I_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sodium chloride solution (8.5g/l)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503I_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1

                        Sodium chloride solution (8.5g/l)
Facility
Referral/specialized                                 93.0
General hospitals                                    87.0
Primary hospitals                                    71.0
MCH specialty centres                                78.0
Health centres                                       52.0
MCH specialty clinics                                69.0
Higher clinics                                       77.0
National                                             55.0

In [634]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503J_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Bovine albumin (20%)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503J_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1

                        Bovine albumin (20%)
Facility
Referral/specialized                    20.0
General hospitals                       25.0
Primary hospitals                       13.0
MCH specialty centres                   26.0
Health centres                           5.0
MCH specialty clinics                   25.0
Higher clinics                          15.0
National                                 6.0

In [635]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503K_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Centrifuge (electric)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503K_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1

                        Centrifuge (electric)
Facility
Referral/specialized                    100.0
General hospitals                        97.0
Primary hospitals                        93.0
MCH specialty centres                   100.0
Health centres                           71.0
MCH specialty clinics                    81.0
Higher clinics                           85.0
National                                 74.0

In [636]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503L_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Centrifuge (hand driven)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503L_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1

                        Centrifuge (hand driven)
Facility
Referral/specialized                        20.0
General hospitals                           27.0
Primary hospitals                           32.0
MCH specialty centres                       13.0
Health centres                              43.0
MCH specialty clinics                       38.0
Higher clinics                              23.0
National                                    41.0

In [637]:
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503M_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'37o water bath (or incubator)']
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503M_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1

                        37o water bath (or incubator)
Facility
Referral/specialized                             77.0
General hospitals                                47.0
Primary hospitals                                23.0
MCH specialty centres                            57.0
Health centres                                    6.0
MCH specialty clinics                            38.0
Higher clinics                                   38.0
National                                         10.0

In [638]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503N_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pipettes (volumetric, various sizes)']
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503N_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1

                        Pipettes (volumetric, various sizes)
Facility
Referral/specialized                                    97.0
General hospitals                                       93.0
Primary hospitals                                       86.0
MCH specialty centres                                   96.0
Health centres                                          52.0
MCH specialty clinics                                   81.0
Higher clinics                                          77.0
National                                                56.0

In [639]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503O_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Blood typing and cross-matching reagents']
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503O_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1

                        Blood typing and cross-matching reagents
Facility
Referral/specialized                                       100.0
General hospitals                                           98.0
Primary hospitals                                           86.0
MCH specialty centres                                       96.0
Health centres                                              53.0
MCH specialty clinics                                       75.0
Higher clinics                                              85.0
National                                                    57.0

In [640]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q503P_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Bags for collecting blood']
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q503P_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1

                        Bags for collecting blood
Facility
Referral/specialized                         40.0
General hospitals                            39.0
Primary hospitals                            18.0
MCH specialty centres                        35.0
Health centres                                2.0
MCH specialty clinics                        19.0
Higher clinics                                8.0
National                                      5.0

In [641]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory12.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_laboratory1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Refrigerator_for_blood_bank1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Test_tubes_various_sizes1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_slides1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Compound_microscope1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Microscope_illuminator1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Blood_lancets1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Cotton_wool1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Rack1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Sodium_chloride_solution1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Bovine_albumin1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_electric1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Centrifuge_hand_driven1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_37o_water_bath_or_incubator1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Pipettes_volumetric_various1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Bloo_typing_and_cross1.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood1.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Facility has a laboratory,100.0,100.0,99.0,100.0,78.0,100.0,100.0,80.0
Facility has set of guidelines for laborator,100.0,94.0,83.0,74.0,62.0,81.0,69.0,65.0
Refrigerator for blood bank,97.0,82.0,57.0,70.0,4.0,12.0,31.0,11.0
Test tubes (various sizes),100.0,95.0,82.0,100.0,66.0,94.0,92.0,69.0
Microscope slides,100.0,99.0,97.0,100.0,86.0,94.0,92.0,88.0
Compound microscope for crossmatching,83.0,76.0,63.0,74.0,29.0,50.0,54.0,34.0
Microscope illuminator,70.0,59.0,54.0,52.0,38.0,62.0,54.0,40.0
Blood lancets,97.0,97.0,92.0,100.0,85.0,94.0,85.0,86.0
Cotton wool,100.0,99.0,96.0,100.0,88.0,94.0,85.0,89.0
Rack,100.0,98.0,94.0,100.0,77.0,94.0,92.0,80.0
Sodium chloride solution (8.5g/l),93.0,87.0,71.0,78.0,52.0,69.0,77.0,55.0
Bovine albumin (20%),20.0,25.0,13.0,26.0,5.0,25.0,15.0,6.0
Centrifuge (electric),100.0,97.0,93.0,100.0,71.0,81.0,85.0,74.0
Centrifuge (hand driven),20.0,27.0,32.0,13.0,43.0,38.0,23.0,41.0
37o water bath (or incubator),77.0,47.0,23.0,57.0,6.0,38.0,38.0,10.0
"Pipettes (volumetric, various sizes)",97.0,93.0,86.0,96.0,52.0,81.0,77.0,56.0
Blood typing and cross-matching reagents,100.0,98.0,86.0,96.0,53.0,75.0,85.0,57.0
Bags for collecting blood,40.0,39.0,18.0,35.0,2.0,19.0,8.0,5.0

In [642]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504A_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Airway needle for collecting blood']
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504A_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood

                        Airway needle for collecting blood
Facility
Referral/specialized                                  67.0
General hospitals                                     65.0
Primary hospitals                                     36.0
MCH specialty centres                                 48.0
Health centres                                         9.0
MCH specialty clinics                                 25.0
Higher clinics                                        23.0
National                                              13.0

In [643]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504B_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Airway needle for collecting blood']
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504B_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps

                        Airway needle for collecting blood
Facility
Referral/specialized                                  57.0
General hospitals                                     53.0
Primary hospitals                                     38.0
MCH specialty centres                                 48.0
Health centres                                        26.0
MCH specialty clinics                                 50.0
Higher clinics                                        54.0
National                                              28.0

In [644]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504C_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Anticoagulant bottles']
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504C_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles

                        Anticoagulant bottles
Facility
Referral/specialized                     70.0
General hospitals                        76.0
Primary hospitals                        54.0
MCH specialty centres                    78.0
Health centres                           25.0
MCH specialty clinics                    62.0
Higher clinics                           54.0
National                                 29.0

In [645]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504D_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Scale for blood collection']
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504D_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection

                        Scale for blood collection
Facility
Referral/specialized                          37.0
General hospitals                             44.0
Primary hospitals                             22.0
MCH specialty centres                         43.0
Health centres                                 8.0
MCH specialty clinics                         19.0
Higher clinics                                31.0
National                                      11.0

In [646]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Guidelines_and_equipment_and_supplies_for_blood_collection_Airway_needle_for_collecting_blood.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Artery_forceps.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Anticoagulant_bottles.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Scale_for_blood_collection.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122133=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122133

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Airway needle for collecting blood,67.0,65.0,36.0,48.0,9.0,25.0,23.0,13.0
Airway needle for collecting blood,57.0,53.0,38.0,48.0,26.0,50.0,54.0,28.0
Anticoagulant bottles,70.0,76.0,54.0,78.0,25.0,62.0,54.0,29.0
Scale for blood collection,37.0,44.0,22.0,43.0,8.0,19.0,31.0,11.0

In [647]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504E_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Hepatitis B test']
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504E_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test

                        Hepatitis B test
Facility
Referral/specialized               100.0
General hospitals                   97.0
Primary hospitals                   87.0
MCH specialty centres               96.0
Health centres                      39.0
MCH specialty clinics               81.0
Higher clinics                      85.0
National                            45.0

In [648]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504F_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Hepatitis C test']
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504F_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test

                        Hepatitis C test
Facility
Referral/specialized                87.0
General hospitals                   85.0
Primary hospitals                   66.0
MCH specialty centres               87.0
Health centres                      11.0
MCH specialty clinics               62.0
Higher clinics                      85.0
National                            19.0

In [649]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504G_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'HIV Rapid Diagnostic test(RDT) kit']
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504G_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit

                        HIV Rapid Diagnostic test(RDT) kit
Facility
Referral/specialized                                  90.0
General hospitals                                     82.0
Primary hospitals                                     74.0
MCH specialty centres                                 74.0
Health centres                                        68.0
MCH specialty clinics                                 62.0
Higher clinics                                        77.0
National                                              69.0

In [650]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504H_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Syphilis test']
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504H_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test

                        Syphilis test
Facility
Referral/specialized             97.0
General hospitals                91.0
Primary hospitals                86.0
MCH specialty centres            96.0
Health centres                   61.0
MCH specialty clinics            88.0
Higher clinics                   92.0
National                         64.0

In [651]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504I_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'TB microscopy (slides, stain)']
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504I_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy

                        TB microscopy (slides, stain)
Facility
Referral/specialized                            100.0
General hospitals                                95.0
Primary hospitals                                90.0
MCH specialty centres                            74.0
Health centres                                   86.0
MCH specialty clinics                            81.0
Higher clinics                                   85.0
National                                         87.0

In [652]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504J_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Malaria RDT kit']
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504J_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit

                        Malaria RDT kit
Facility
Referral/specialized               27.0
General hospitals                  30.0
Primary hospitals                  27.0
MCH specialty centres              52.0
Health centres                     58.0
MCH specialty clinics              31.0
Higher clinics                     62.0
National                           55.0

In [653]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q504K_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pregnancy test']
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.columns= labels_of_col[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.index= labels_of_col1[1:]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.columns.names= [labels_of_col[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q504K_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.loc['National'] = cc
Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test

                        Pregnancy test
Facility
Referral/specialized              97.0
General hospitals                 91.0
Primary hospitals                 92.0
MCH specialty centres             96.0
Health centres                    80.0
MCH specialty clinics             88.0
Higher clinics                   100.0
National                          81.0

In [654]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_B_test.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Hepatitis_C_test.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_HIV_RDT_kit.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Syphilis_test.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_TB_microscopy.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Malaria_RDT_kit.transpose(),Guidelines_and_equipment_and_supplies_for_blood_collection_Pregnancy_test.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122144=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122144

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Hepatitis B test,100.0,97.0,87.0,96.0,39.0,81.0,85.0,45.0
Hepatitis C test,87.0,85.0,66.0,87.0,11.0,62.0,85.0,19.0
HIV Rapid Diagnostic test(RDT) kit,90.0,82.0,74.0,74.0,68.0,62.0,77.0,69.0
Syphilis test,97.0,91.0,86.0,96.0,61.0,88.0,92.0,64.0
"TB microscopy (slides, stain)",100.0,95.0,90.0,74.0,86.0,81.0,85.0,87.0
Malaria RDT kit,27.0,30.0,27.0,52.0,58.0,31.0,62.0,55.0
Pregnancy test,97.0,91.0,92.0,96.0,80.0,88.0,100.0,81.0

In [657]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122133,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122144)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12uuu=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Equipment and supplies for donor blood transfusion', 'Blood collection equipment','Blood screening equipment and supplies'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12uuu

Facility                                                                                         Referral/specialized  \

Equipment and supplies for donor blood transfusion Facility has a laboratory                                    100.0
                                                   Facility has set of guidelines for laborator                 100.0
                                                   Refrigerator for blood bank                                   97.0
                                                   Test tubes (various sizes)                                   100.0
                                                   Microscope slides                                            100.0
                                                   Compound microscope for crossmatching                         83.0
                                                   Microscope illuminator                                        70.0
                                                   Blood lancets                                                 97.0
                                                   Cotton wool                                                  100.0
                                                   Rack                                                         100.0
                                                   Sodium chloride solution (8.5g/l)                             93.0
                                                   Bovine albumin (20%)                                          20.0
                                                   Centrifuge (electric)                                        100.0
                                                   Centrifuge (hand driven)                                      20.0
                                                   37o water bath (or incubator)                                 77.0
                                                   Pipettes (volumetric, various sizes)                          97.0
                                                   Blood typing and cross-matching reagents                     100.0
                                                   Bags for collecting blood                                     40.0
Blood collection equipment                         Airway needle for collecting blood                            67.0
                                                   Airway needle for collecting blood                            57.0
                                                   Anticoagulant bottles                                         70.0
                                                   Scale for blood collection                                    37.0
Blood screening equipment and supplies             Hepatitis B test                                             100.0
                                                   Hepatitis C test                                              87.0
                                                   HIV Rapid Diagnostic test(RDT) kit                            90.0
                                                   Syphilis test                                                 97.0
                                                   TB microscopy (slides, stain)                                100.0
                                                   Malaria RDT kit                                               27.0
                                                   Pregnancy test                                                97.0

Facility                                                                                         General hospitals  \

Equipment and supplies for donor blood transfusion Facility has a laboratory                                 100.0
                                                   Facility has set of guidelines for laborator               94.0
                                                   Refrigerator for blood bank                                82.0
                                                   Test tubes (various sizes)                                 95.0
                                                   Microscope slides                                          99.0
                                                   Compound microscope for crossmatching                      76.0
                                                   Microscope illuminator                                     59.0
                                                   Blood lancets                                              97.0
                                                   Cotton wool                                                99.0
                                                   Rack                                                       98.0
                                                   Sodium chloride solution (8.5g/l)                          87.0
                                                   Bovine albumin (20%)                                       25.0
                                                   Centrifuge (electric)                                      97.0
                                                   Centrifuge (hand driven)                                   27.0
                                                   37o water bath (or incubator)                              47.0
                                                   Pipettes (volumetric, various sizes)                       93.0
                                                   Blood typing and cross-matching reagents                   98.0
                                                   Bags for collecting blood                                  39.0
Blood collection equipment                         Airway needle for collecting blood                         65.0
                                                   Airway needle for collecting blood                         53.0
                                                   Anticoagulant bottles                                      76.0
                                                   Scale for blood collection                                 44.0
Blood screening equipment and supplies             Hepatitis B test                                           97.0
                                                   Hepatitis C test                                           85.0
                                                   HIV Rapid Diagnostic test(RDT) kit                         82.0
                                                   Syphilis test                                              91.0
                                                   TB microscopy (slides, stain)                              95.0
                                                   Malaria RDT kit                                            30.0
                                                   Pregnancy test                                             91.0

Facility                                                                                         Primary hospitals   \

Equipment and supplies for donor blood transfusion Facility has a laboratory                                   99.0
                                                   Facility has set of guidelines for laborator                83.0
                                                   Refrigerator for blood bank                                 57.0
                                                   Test tubes (various sizes)                                  82.0
                                                   Microscope slides                                           97.0
                                                   Compound microscope for crossmatching                       63.0
                                                   Microscope illuminator                                      54.0
                                                   Blood lancets                                               92.0
                                                   Cotton wool                                                 96.0
                                                   Rack                                                        94.0
                                                   Sodium chloride solution (8.5g/l)                           71.0
                                                   Bovine albumin (20%)                                        13.0
                                                   Centrifuge (electric)                                       93.0
                                                   Centrifuge (hand driven)                                    32.0
                                                   37o water bath (or incubator)                               23.0
                                                   Pipettes (volumetric, various sizes)                        86.0
                                                   Blood typing and cross-matching reagents                    86.0
                                                   Bags for collecting blood                                   18.0
Blood collection equipment                         Airway needle for collecting blood                          36.0
                                                   Airway needle for collecting blood                          38.0
                                                   Anticoagulant bottles                                       54.0
                                                   Scale for blood collection                                  22.0
Blood screening equipment and supplies             Hepatitis B test                                            87.0
                                                   Hepatitis C test                                            66.0
                                                   HIV Rapid Diagnostic test(RDT) kit                          74.0
                                                   Syphilis test                                               86.0
                                                   TB microscopy (slides, stain)                               90.0
                                                   Malaria RDT kit                                             27.0
                                                   Pregnancy test                                              92.0

Facility                                                                                         MCH specialty centres   \

Equipment and supplies for donor blood transfusion Facility has a laboratory                                      100.0
                                                   Facility has set of guidelines for laborator                    74.0
                                                   Refrigerator for blood bank                                     70.0
                                                   Test tubes (various sizes)                                     100.0
                                                   Microscope slides                                              100.0
                                                   Compound microscope for crossmatching                           74.0
                                                   Microscope illuminator                                          52.0
                                                   Blood lancets                                                  100.0
                                                   Cotton wool                                                    100.0
                                                   Rack                                                           100.0
                                                   Sodium chloride solution (8.5g/l)                               78.0
                                                   Bovine albumin (20%)                                            26.0
                                                   Centrifuge (electric)                                          100.0
                                                   Centrifuge (hand driven)                                        13.0
                                                   37o water bath (or incubator)                                   57.0
                                                   Pipettes (volumetric, various sizes)                            96.0
                                                   Blood typing and cross-matching reagents                        96.0
                                                   Bags for collecting blood                                       35.0
Blood collection equipment                         Airway needle for collecting blood                              48.0
                                                   Airway needle for collecting blood                              48.0
                                                   Anticoagulant bottles                                           78.0
                                                   Scale for blood collection                                      43.0
Blood screening equipment and supplies             Hepatitis B test                                                96.0
                                                   Hepatitis C test                                                87.0
                                                   HIV Rapid Diagnostic test(RDT) kit                              74.0
                                                   Syphilis test                                                   96.0
                                                   TB microscopy (slides, stain)                                   74.0
                                                   Malaria RDT kit                                                 52.0
                                                   Pregnancy test                                                  96.0

Facility                                                                                         Health centres  \

Equipment and supplies for donor blood transfusion Facility has a laboratory                               78.0
                                                   Facility has set of guidelines for laborator            62.0
                                                   Refrigerator for blood bank                              4.0
                                                   Test tubes (various sizes)                              66.0
                                                   Microscope slides                                       86.0
                                                   Compound microscope for crossmatching                   29.0
                                                   Microscope illuminator                                  38.0
                                                   Blood lancets                                           85.0
                                                   Cotton wool                                             88.0
                                                   Rack                                                    77.0
                                                   Sodium chloride solution (8.5g/l)                       52.0
                                                   Bovine albumin (20%)                                     5.0
                                                   Centrifuge (electric)                                   71.0
                                                   Centrifuge (hand driven)                                43.0
                                                   37o water bath (or incubator)                            6.0
                                                   Pipettes (volumetric, various sizes)                    52.0
                                                   Blood typing and cross-matching reagents                53.0
                                                   Bags for collecting blood                                2.0
Blood collection equipment                         Airway needle for collecting blood                       9.0
                                                   Airway needle for collecting blood                      26.0
                                                   Anticoagulant bottles                                   25.0
                                                   Scale for blood collection                               8.0
Blood screening equipment and supplies             Hepatitis B test                                        39.0
                                                   Hepatitis C test                                        11.0
                                                   HIV Rapid Diagnostic test(RDT) kit                      68.0
                                                   Syphilis test                                           61.0
                                                   TB microscopy (slides, stain)                           86.0
                                                   Malaria RDT kit                                         58.0
                                                   Pregnancy test                                          80.0

Facility                                                                                         MCH specialty clinics  \

Equipment and supplies for donor blood transfusion Facility has a laboratory                                     100.0
                                                   Facility has set of guidelines for laborator                   81.0
                                                   Refrigerator for blood bank                                    12.0
                                                   Test tubes (various sizes)                                     94.0
                                                   Microscope slides                                              94.0
                                                   Compound microscope for crossmatching                          50.0
                                                   Microscope illuminator                                         62.0
                                                   Blood lancets                                                  94.0
                                                   Cotton wool                                                    94.0
                                                   Rack                                                           94.0
                                                   Sodium chloride solution (8.5g/l)                              69.0
                                                   Bovine albumin (20%)                                           25.0
                                                   Centrifuge (electric)                                          81.0
                                                   Centrifuge (hand driven)                                       38.0
                                                   37o water bath (or incubator)                                  38.0
                                                   Pipettes (volumetric, various sizes)                           81.0
                                                   Blood typing and cross-matching reagents                       75.0
                                                   Bags for collecting blood                                      19.0
Blood collection equipment                         Airway needle for collecting blood                             25.0
                                                   Airway needle for collecting blood                             50.0

In [658]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12uuu.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Laboratory equipment and supplies for blood transfusion/Percent of facilities with a laboratory, and among those percent with guidelines and equipment and supplies for blood collection, screening, and transfusion.csv")

In [662]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505A_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Microscope']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505A_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet

                        Microscope
Facility
Referral/specialized         100.0
General hospitals            100.0
Primary hospitals            100.0
MCH specialty centres        100.0
Health centres                99.0
MCH specialty clinics        100.0
Higher clinics               100.0
National                      99.0

In [663]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505B_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Immersion oil']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505B_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil

                        Immersion oil
Facility
Referral/specialized            100.0
General hospitals                99.0
Primary hospitals                99.0
MCH specialty centres            96.0
Health centres                   94.0
MCH specialty clinics            81.0
Higher clinics                   92.0
National                         94.0

In [664]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505C_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Glass rods']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505C_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods

                        Glass rods
Facility
Referral/specialized          73.0
General hospitals             77.0
Primary hospitals             60.0
MCH specialty centres         61.0
Health centres                43.0
MCH specialty clinics         44.0
Higher clinics                77.0
National                      45.0

In [665]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505D_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Sink or staining tank']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505D_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank

                        Sink or staining tank
Facility
Referral/specialized                    100.0
General hospitals                        97.0
Primary hospitals                        92.0
MCH specialty centres                   100.0
Health centres                           84.0
MCH specialty clinics                    94.0
Higher clinics                           92.0
National                                 85.0

In [666]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505E_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Measuring cylinder (various sizes)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505E_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes

                        Measuring cylinder (various sizes)
Facility
Referral/specialized                                 100.0
General hospitals                                     92.0
Primary hospitals                                     87.0
MCH specialty centres                                 78.0
Health centres                                        71.0
MCH specialty clinics                                 62.0
Higher clinics                                        77.0
National                                              73.0

In [667]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505F_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Wash bottle']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505F_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle

                        Wash bottle
Facility
Referral/specialized           97.0
General hospitals              83.0
Primary hospitals              69.0
MCH specialty centres          83.0
Health centres                 49.0
MCH specialty clinics          62.0
Higher clinics                 77.0
National                       52.0

In [668]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505G_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Bottle with buffered water']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505G_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water

                        Bottle with buffered water
Facility
Referral/specialized                          63.0
General hospitals                             59.0
Primary hospitals                             38.0
MCH specialty centres                         78.0
Health centres                                21.0
MCH specialty clinics                         25.0
Higher clinics                                23.0
National                                      24.0

In [669]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505H_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Timer clock with alarm']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505H_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm

                        Timer clock with alarm
Facility
Referral/specialized                      90.0
General hospitals                         88.0
Primary hospitals                         88.0
MCH specialty centres                     96.0
Health centres                            79.0
MCH specialty clinics                     94.0
Higher clinics                            69.0
National                                  80.0

In [670]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505I_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Rack for drying slides']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505I_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides

                        Rack for drying slides
Facility
Referral/specialized                     100.0
General hospitals                         96.0
Primary hospitals                         91.0
MCH specialty centres                     91.0
Health centres                            76.0
MCH specialty clinics                    100.0
Higher clinics                            92.0
National                                  78.0

In [671]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505J_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Giemsa stain']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505J_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain

                        Giemsa stain
Facility
Referral/specialized            93.0
General hospitals               97.0
Primary hospitals               93.0
MCH specialty centres           96.0
Health centres                  83.0
MCH specialty clinics           88.0
Higher clinics                  85.0
National                        84.0

In [672]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505K_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Wright stain']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505K_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain

                        Wright stain
Facility
Referral/specialized            83.0
General hospitals               80.0
Primary hospitals               54.0
MCH specialty centres           78.0
Health centres                  30.0
MCH specialty clinics           69.0
Higher clinics                  85.0
National                        34.0

In [673]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505L_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'May Grunwald stain']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505L_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain

                        May Grunwald stain
Facility
Referral/specialized                  27.0
General hospitals                     15.0
Primary hospitals                     10.0
MCH specialty centres                 22.0
Health centres                         3.0
MCH specialty clinics                 12.0
Higher clinics                         0.0
National                               4.0

In [674]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505M_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Funnel and filter paper']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505M_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper

                        Funnel and filter paper
Facility
Referral/specialized                       97.0
General hospitals                          86.0
Primary hospitals                          79.0
MCH specialty centres                      61.0
Health centres                             64.0
MCH specialty clinics                      44.0
Higher clinics                             69.0
National                                   66.0

In [675]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505N_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Methanol']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505N_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol

                        Methanol
Facility
Referral/specialized        93.0
General hospitals           95.0
Primary hospitals           90.0
MCH specialty centres      100.0
Health centres              70.0
MCH specialty clinics       81.0
Higher clinics              77.0
National                    73.0

In [676]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505O_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Refrigerator for laboratory supplies']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505O_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies

                        Refrigerator for laboratory supplies
Facility
Referral/specialized                                   100.0
General hospitals                                       97.0
Primary hospitals                                       92.0
MCH specialty centres                                  100.0
Health centres                                          60.0
MCH specialty clinics                                   94.0
Higher clinics                                          85.0
National                                                64.0

In [677]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505P_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Glass containers']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505P_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers

                        Glass containers
Facility
Referral/specialized                93.0
General hospitals                   86.0
Primary hospitals                   62.0
MCH specialty centres               83.0
Health centres                      41.0
MCH specialty clinics               62.0
Higher clinics                      62.0
National                            45.0

In [678]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505Q_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Counting chamber (differential counter)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505Q_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter

                        Counting chamber (differential counter)
Facility
Referral/specialized                                      100.0
General hospitals                                          85.0
Primary hospitals                                          68.0
MCH specialty centres                                      83.0
Health centres                                             49.0
MCH specialty clinics                                      75.0
Higher clinics                                            100.0
National                                                   52.0

In [679]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505R_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pipette (5ml)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505R_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml

                        Pipette (5ml)
Facility
Referral/specialized             93.0
General hospitals                83.0
Primary hospitals                65.0
MCH specialty centres            74.0
Health centres                   44.0
MCH specialty clinics            75.0
Higher clinics                   77.0
National                         47.0

In [680]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505S_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pipette (graduated, 1ml)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505S_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml

                        Pipette (graduated, 1ml)
Facility
Referral/specialized                        93.0
General hospitals                           76.0
Primary hospitals                           65.0
MCH specialty centres                       74.0
Health centres                              36.0
MCH specialty clinics                       75.0
Higher clinics                              77.0
National                                    40.0

In [681]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505T_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Pipette (dropping)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505T_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping

                        Pipette (dropping)
Facility
Referral/specialized                  93.0
General hospitals                     89.0
Primary hospitals                     85.0
MCH specialty centres                 96.0
Health centres                        64.0
MCH specialty clinics                 81.0
Higher clinics                        92.0
National                              66.0

In [682]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505U_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Cover slips']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505U_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips

                        Cover slips
Facility
Referral/specialized          100.0
General hospitals              98.0
Primary hospitals              97.0
MCH specialty centres          96.0
Health centres                 92.0
MCH specialty clinics         100.0
Higher clinics                 92.0
National                       92.0

In [683]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505V_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Petri dishes']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505V_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes

                        Petri dishes
Facility
Referral/specialized            93.0
General hospitals               67.0
Primary hospitals               51.0
MCH specialty centres           35.0
Health centres                  33.0
MCH specialty clinics           44.0
Higher clinics                  54.0
National                        36.0

In [684]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505W_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Bowls, kidney dishes (various sizes)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505W_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes

                        Bowls, kidney dishes (various sizes)
Facility
Referral/specialized                                    80.0
General hospitals                                       79.0
Primary hospitals                                       68.0
MCH specialty centres                                   57.0
Health centres                                          61.0
MCH specialty clinics                                   50.0
Higher clinics                                          69.0
National                                                63.0

In [685]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505X_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Turk diluting solution']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505X_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution

                        Turk diluting solution
Facility
Referral/specialized                      77.0
General hospitals                         50.0
Primary hospitals                         33.0
MCH specialty centres                     35.0
Health centres                            18.0
MCH specialty clinics                     25.0
Higher clinics                            31.0
National                                  20.0

In [686]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505Y_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Tally counter']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505Y_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter

                        Tally counter
Facility
Referral/specialized             87.0
General hospitals                78.0
Primary hospitals                64.0
MCH specialty centres            87.0
Health centres                   41.0
MCH specialty clinics            62.0
Higher clinics                   46.0
National                         44.0

In [687]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505Z_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Haemoglobinometer and hydrochloric acid solution']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505Z_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and

                        Haemoglobinometer and hydrochloric acid solution
Facility
Referral/specialized                                                63.0
General hospitals                                                   62.0
Primary hospitals                                                   47.0
MCH specialty centres                                               78.0
Health centres                                                      42.0
MCH specialty clinics                                               88.0
Higher clinics                                                      69.0
National                                                            44.0

In [688]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505AA_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Spectrophotometer']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505AA_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer

                        Spectrophotometer
Facility
Referral/specialized                 80.0
General hospitals                    53.0
Primary hospitals                    28.0
MCH specialty centres                78.0
Health centres                        6.0
MCH specialty clinics                31.0
Higher clinics                       54.0
National                             11.0

In [689]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505BB_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Microhaematocrit centrifuge (manual or electric)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505BB_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge

                        Microhaematocrit centrifuge (manual or electric)
Facility
Referral/specialized                                                83.0
General hospitals                                                   85.0
Primary hospitals                                                   85.0
MCH specialty centres                                              100.0
Health centres                                                      43.0
MCH specialty clinics                                               62.0
Higher clinics                                                      38.0
National                                                            47.0

In [690]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505CC_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Balance for reading results']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505CC_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results

                        Balance for reading results
Facility
Referral/specialized                           83.0
General hospitals                              73.0
Primary hospitals                              61.0
MCH specialty centres                          83.0
Health centres                                 27.0
MCH specialty clinics                          50.0
Higher clinics                                 46.0
National                                       32.0

In [691]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505DD_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Heparinized capillary tubes (75x1.5mm)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505DD_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes

                        Heparinized capillary tubes (75x1.5mm)
Facility
Referral/specialized                                      90.0
General hospitals                                         87.0
Primary hospitals                                         81.0
MCH specialty centres                                     83.0
Health centres                                            52.0
MCH specialty clinics                                     69.0
Higher clinics                                            69.0
National                                                  56.0

In [692]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505EE_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Spirit lamp']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505EE_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp

                        Spirit lamp
Facility
Referral/specialized           93.0
General hospitals              87.0
Primary hospitals              78.0
MCH specialty centres          70.0
Health centres                 66.0
MCH specialty clinics          88.0
Higher clinics                 92.0
National                       68.0

In [693]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505FF_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ethanol']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505FF_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol

                        Ethanol
Facility
Referral/specialized       97.0
General hospitals          91.0
Primary hospitals          75.0
MCH specialty centres      91.0
Health centres             51.0
MCH specialty clinics      81.0
Higher clinics             62.0
National                   55.0

In [694]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505GG_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Test tubes']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505GG_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes

                        Test tubes
Facility
Referral/specialized         100.0
General hospitals             98.0
Primary hospitals             93.0
MCH specialty centres        100.0
Health centres                90.0
MCH specialty clinics        100.0
Higher clinics               100.0
National                      90.0

In [695]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505HH_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Test tube rack']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505HH_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack

                        Test tube rack
Facility
Referral/specialized             100.0
General hospitals                 99.0
Primary hospitals                 95.0
MCH specialty centres            100.0
Health centres                    87.0
MCH specialty clinics            100.0
Higher clinics                   100.0
National                          88.0

In [696]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505II_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Beaker (various sizes)']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505II_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes

                        Beaker (various sizes)
Facility
Referral/specialized                      97.0
General hospitals                         79.0
Primary hospitals                         66.0
MCH specialty centres                     61.0
Health centres                            37.0
MCH specialty clinics                     56.0
Higher clinics                            69.0
National                                  41.0

In [697]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505JJ_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Ammonia']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505JJ_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia

                        Ammonia
Facility
Referral/specialized       20.0
General hospitals          15.0
Primary hospitals           7.0
MCH specialty centres       9.0
Health centres              4.0
MCH specialty clinics      12.0
Higher clinics              0.0
National                    5.0

In [702]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505KK_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Lugols iodine solution ']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505KK_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution

                        Lugols iodine solution
Facility
Referral/specialized                       87.0
General hospitals                          82.0
Primary hospitals                          55.0
MCH specialty centres                      70.0
Health centres                             27.0
MCH specialty clinics                      88.0
Higher clinics                             77.0
National                                   32.0

In [703]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT7'], columns=(data['Q501_3']==1), values=(data['Q505LL_3']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialty centres ','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'CD4 machine']
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.columns= labels_of_col[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.index= labels_of_col1[1:]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.columns.names= [labels_of_col[0]]
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q501_3']==1, data['Q505LL_3']==1)
b = len(data.loc[((data['Q501_3']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.loc['National'] = cc
Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine

                        CD4 machine
Facility
Referral/specialized           97.0
General hospitals              65.0
Primary hospitals              35.0
MCH specialty centres          17.0
Health centres                  4.0
MCH specialty clinics           0.0
Higher clinics                  8.0
National                        8.0

In [706]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microscopet.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Immersion_oil.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_rods.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Sink_or_staining_tank.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Measuring_cylinder_various_sizes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wash_bottle.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bottle_with_buffered_water.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Timer_clock_with_alarm.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Rack_for_drying_slides.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Giemsa_stain.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Wright_stain.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_May_Grunwald_stain.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Funnel_and_filter_paper.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Methanol.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Refrigerator_for_laboratory_supplies.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Glass_containers.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Counting_chamber_differential_counter.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_5ml.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_graduated_1ml.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Pipette_dropping.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Cover_slips.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Petri_dishes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Bowls_kidney_dishes_various_sizes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Turk_diluting_solution.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Tally_counter.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Haemoglobinometer_and.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spectrophotometer.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Microhaematocrit_centrifuge.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Balance_for_reading_results.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Heparinized_capillary_tubes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Spirit_lamp.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ethanol.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tubes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Test_tube_rack.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Beaker_various_sizes.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Ammonia.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_Lugol_iodine_solution.transpose(),Percent_of_facilities_with_laboratory_that_have_basic_laboratory_supplies_CD4_machine.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221waw=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221waw

Facility,Referral/specialized,General hospitals,Primary hospitals,MCH specialty centres,Health centres,MCH specialty clinics,Higher clinics,National
,,,,,,,,
Microscope,100.0,100.0,100.0,100.0,99.0,100.0,100.0,99.0
Immersion oil,100.0,99.0,99.0,96.0,94.0,81.0,92.0,94.0
Glass rods,73.0,77.0,60.0,61.0,43.0,44.0,77.0,45.0
Sink or staining tank,100.0,97.0,92.0,100.0,84.0,94.0,92.0,85.0
Measuring cylinder (various sizes),100.0,92.0,87.0,78.0,71.0,62.0,77.0,73.0
Wash bottle,97.0,83.0,69.0,83.0,49.0,62.0,77.0,52.0
Bottle with buffered water,63.0,59.0,38.0,78.0,21.0,25.0,23.0,24.0
Timer clock with alarm,90.0,88.0,88.0,96.0,79.0,94.0,69.0,80.0
Rack for drying slides,100.0,96.0,91.0,91.0,76.0,100.0,92.0,78.0
Giemsa stain,93.0,97.0,93.0,96.0,83.0,88.0,85.0,84.0
Wright stain,83.0,80.0,54.0,78.0,30.0,69.0,85.0,34.0
May Grunwald stain,27.0,15.0,10.0,22.0,3.0,12.0,0.0,4.0
Funnel and filter paper,97.0,86.0,79.0,61.0,64.0,44.0,69.0,66.0
Methanol,93.0,95.0,90.0,100.0,70.0,81.0,77.0,73.0
Refrigerator for laboratory supplies,100.0,97.0,92.0,100.0,60.0,94.0,85.0,64.0
Glass containers,93.0,86.0,62.0,83.0,41.0,62.0,62.0,45.0
Counting chamber (differential counter),100.0,85.0,68.0,83.0,49.0,75.0,100.0,52.0
Pipette (5ml),93.0,83.0,65.0,74.0,44.0,75.0,77.0,47.0
"Pipette (graduated, 1ml)",93.0,76.0,65.0,74.0,36.0,75.0,77.0,40.0
Pipette (dropping),93.0,89.0,85.0,96.0,64.0,81.0,92.0,66.0
Cover slips,100.0,98.0,97.0,96.0,92.0,100.0,92.0,92.0
Petri dishes,93.0,67.0,51.0,35.0,33.0,44.0,54.0,36.0
"Bowls, kidney dishes (various sizes)",80.0,79.0,68.0,57.0,61.0,50.0,69.0,63.0
Turk diluting solution,77.0,50.0,33.0,35.0,18.0,25.0,31.0,20.0
Tally counter,87.0,78.0,64.0,87.0,41.0,62.0,46.0,44.0
Haemoglobinometer and hydrochloric acid solution,63.0,62.0,47.0,78.0,42.0,88.0,69.0,44.0
Spectrophotometer,80.0,53.0,28.0,78.0,6.0,31.0,54.0,11.0
Microhaematocrit centrifuge (manual or electric),83.0,85.0,85.0,100.0,43.0,62.0,38.0,47.0
Balance for reading results,83.0,73.0,61.0,83.0,27.0,50.0,46.0,32.0
Heparinized capillary tubes (75x1.5mm),90.0,87.0,81.0,83.0,52.0,69.0,69.0,56.0
Spirit lamp,93.0,87.0,78.0,70.0,66.0,88.0,92.0,68.0
Ethanol,97.0,91.0,75.0,91.0,51.0,81.0,62.0,55.0
Test tubes,100.0,98.0,93.0,100.0,90.0,100.0,100.0,90.0
Test tube rack,100.0,99.0,95.0,100.0,87.0,100.0,100.0,88.0
Beaker (various sizes),97.0,79.0,66.0,61.0,37.0,56.0,69.0,41.0
Ammonia,20.0,15.0,7.0,9.0,4.0,12.0,0.0,5.0
Lugols iodine solution,87.0,82.0,55.0,70.0,27.0,88.0,77.0,32.0
CD4 machine,97.0,65.0,35.0,17.0,4.0,0.0,8.0,8.0

In [707]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221waw.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Laboratory equipment and supplies for blood transfusion/Percent of facilities with a laboratory that have basic laboratory supplies.csv")

In [28]:
my_tab = pd.crosstab(data['FT2'], data['Q101_7'])
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_according_to_partograph_usage_characteristics_partographs[0]
#del  Percent_of_facilities_according_to_partograph_usage_characteristics_partographs[0]
del  Percent_of_facilities_according_to_partograph_usage_characteristics_partographs[-999]
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Uses partographs']
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q101_7']==1)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs

                                  Uses partographs
Facility
Hospitals/ MCH specialty centres              82.0
Health centres/clinics1                       74.0
National                                      74.0

In [29]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q102A_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Modified WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q102A_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO

                                  Modified WHO partograph
Facility
Hospitals/ MCH specialty centres                     90.0
Health centres/clinics1                              86.0
National                                             86.0

In [30]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q102B_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Simplified WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q102B_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO

                                  Simplified WHO partograph
Facility
Hospitals/ MCH specialty centres                        2.0
Health centres/clinics1                                 1.0
National                                                1.0

In [31]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q102C_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Composite WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q102C_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO

                                  Composite WHO partograph
Facility
Hospitals/ MCH specialty centres                       2.0
Health centres/clinics1                                2.0
National                                               2.0

In [32]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q102D_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Other types of partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Other.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q102D_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Other.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Other

                                  Other types of partograph
Facility
Hospitals/ MCH specialty centres                        1.0
Health centres/clinics1                                 0.0
National                                                0.0

In [33]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_partographs.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Other.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221000=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221000

Facility,Hospitals/ MCH specialty centres,Health centres/clinics1,National
,,,
Uses partographs,82.0,74.0,74.0
Modified WHO partograph,90.0,86.0,86.0
Simplified WHO partograph,2.0,1.0,1.0
Composite WHO partograph,2.0,2.0,2.0
Other types of partograph,1.0,0.0,0.0

In [34]:
my_tab = pd.crosstab(data['MA3'], data['Q101_7'])
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1[0]
#del  Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1[0]
del  Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Uses partographs']
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q102A_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Modified WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q102B_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Simplified WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q102C_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Composite WHO partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q102D_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Other types of partograph']
Percent_of_facilities_according_to_partograph_usage_characteristics_Other1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Other1.index.names= [labels_of_col1[0]]

In [35]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_partographs1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_WHO1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_WHO1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_WHO1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Other1.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12210033=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12210033

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Uses partographs,75.0,40.0,80.0
Modified WHO partograph,87.0,70.0,83.0
Simplified WHO partograph,1.0,9.0,0.0
Composite WHO partograph,2.0,3.0,2.0
Other types of partograph,0.0,9.0,0.0

In [36]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q105_7']==0), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'No management protocol']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q105_7']==0)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q105_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Protocol exists and was observed by the data collector']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q105_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q105_7']==2), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Protocol exists but was not observed by the data collector']
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q105_7']==2)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol

                                  Protocol exists but was not observed by the data collector
Facility
Hospitals/ MCH specialty centres                                               10.0
Health centres/clinics1                                                         8.0
National                                                                        8.0

In [37]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeee=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeee

Facility,Hospitals/ MCH specialty centres,Health centres/clinics1,National
,,,
No management protocol,32.0,44.0,43.0
Protocol exists and was observed by the data collector,58.0,48.0,48.0
Protocol exists but was not observed by the data collector,10.0,8.0,8.0

In [38]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q105_7']==0), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'No management protocol']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q105_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Protocol exists and was observed by the data collector']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1.index.names= [labels_of_col1[0]]
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q105_7']==2), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Protocol exists but was not observed by the data collector']
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol1.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
No management protocol,43.0,36.0,38.0
Protocol exists and was observed by the data collector,49.0,48.0,47.0
Protocol exists but was not observed by the data collector,8.0,15.0,15.0

In [39]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q103A_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'ANC card (includes partograph)']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q103A_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q103B_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Clinical/case file']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q103B_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q103C_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Administrative/financial file']
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q103C_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.loc['National'] = cc
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol12.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol12.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol12.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1

Facility,Hospitals/ MCH specialty centres,Health centres/clinics1,National
,,,
ANC card (includes partograph),55.0,50.0,50.0
Clinical/case file,61.0,40.0,42.0
Administrative/financial file,16.0,5.0,6.0

In [40]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q103A_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'ANC card (includes partograph)']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q103B_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Clinical/case file']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113.index.names= [labels_of_col1[0]]
#Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q103C_7']==1), colnames=['Facility'], aggfunc='mean'))*100
#del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
#Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol113=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
#labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
#labels_of_col = ["",'Administrative/financial file']
#Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol113.columns= labels_of_col[1:]
#Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol113.index= labels_of_col1[1:]
#Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol113.columns.names= [labels_of_col[0]]
#Percent_of_facilities_according_to_partograph_usage_characteristics_Composite_protocol113.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
ANC card (includes partograph),50.0,61.0,60.0
Clinical/case file,42.0,58.0,38.0

In [41]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q104_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'ANC card (includes partograph)']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q104_7']==1)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['FT2'], columns=(data['Q101_7']==1), values=(data['Q104_7']==2), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Facility","Hospitals/ MCH specialty centres" , "Health centres/clinics1"]
labels_of_col = ["",'Clinical/case file']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q101_7']==1, data['Q104_7']==2)
b = len(data.loc[((data['Q101_7']==1))])
my_tab1 = ((my_tab121[1][1])/b)*100
cc= round((my_tab1),0)
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.loc['National'] = cc
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol1200.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol1200.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo8=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo8

Facility,Hospitals/ MCH specialty centres,Health centres/clinics1,National
,,,
ANC card (includes partograph),42.0,45.0,45.0
Clinical/case file,35.0,18.0,20.0

In [42]:
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q104_7']==1), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'ANC card (includes partograph)']
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM.index.names= [labels_of_col1[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM
Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood = (pd.crosstab(index=data['MA3'], columns=(data['Q101_7']==1), values=(data['Q104_7']==2), colnames=['Facility'], aggfunc='mean'))*100
del Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood[False]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM=round((Guidelines_and_equipment_and_supplies_for_blood_collection_Bags_for_collecting_blood),0)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Clinical/case file']
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM.columns= labels_of_col[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM.index= labels_of_col1[1:]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM.columns.names= [labels_of_col[0]]
Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_according_to_partograph_usage_characteristics_Modified_protocol113MM.transpose(),Percent_of_facilities_according_to_partograph_usage_characteristics_Simplified_protocol113MM.transpose())
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo277=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo277

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
ANC card (includes partograph),44.0,55.0,55.0
Clinical/case file,20.0,30.0,11.0

In [43]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12210033,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo277)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12RR=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Equipment and supplies for donor blood transfusion', 'Blood collection equipment','Blood screening equipment and supplies'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12RR

Managing_authority                                                                                     Public/government  \

Equipment and supplies for donor blood transfusion Uses partographs                                                 75.0
                                                   Modified WHO partograph                                          87.0
                                                   Simplified WHO partograph                                         1.0
                                                   Composite WHO partograph                                          2.0
                                                   Other types of partograph                                         0.0
Blood collection equipment                         No management protocol                                           43.0
                                                   Protocol exists and was observed by the data co...               49.0
                                                   Protocol exists but was not observed by the dat...                8.0
Blood screening equipment and supplies             ANC card (includes partograph)                                   50.0
                                                   Clinical/case file                                               42.0

Managing_authority                                                                                     Private-for-profit  \

Equipment and supplies for donor blood transfusion Uses partographs                                                  40.0
                                                   Modified WHO partograph                                           70.0
                                                   Simplified WHO partograph                                          9.0
                                                   Composite WHO partograph                                           3.0
                                                   Other types of partograph                                          9.0
Blood collection equipment                         No management protocol                                            36.0
                                                   Protocol exists and was observed by the data co...                48.0
                                                   Protocol exists but was not observed by the dat...                15.0
Blood screening equipment and supplies             ANC card (includes partograph)                                    61.0
                                                   Clinical/case file                                                58.0

Managing_authority                                                                                     Private-not-for-profit

Equipment and supplies for donor blood transfusion Uses partographs                                                       80.0
                                                   Modified WHO partograph                                                83.0
                                                   Simplified WHO partograph                                               0.0
                                                   Composite WHO partograph                                                2.0
                                                   Other types of partograph                                               0.0
Blood collection equipment                         No management protocol                                                 38.0
                                                   Protocol exists and was observed by the data co...                     47.0
                                                   Protocol exists but was not observed by the dat...                     15.0
Blood screening equipment and supplies             ANC card (includes partograph)                                         60.0
                                                   Clinical/case file                                                     38.0

In [44]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery12210033,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Type of partograph ','Labour management protocol','Facility has other document to fill in for women in labour','When prioritized, with which document do you start'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000

Managing_authority                                                                                     Public/government  \

Type of partograph                                 Uses partographs                                                 75.0
                                                   Modified WHO partograph                                          87.0
                                                   Simplified WHO partograph                                         1.0
                                                   Composite WHO partograph                                          2.0
                                                   Other types of partograph                                         0.0
Labour management protocol                         No management protocol                                           43.0
                                                   Protocol exists and was observed by the data co...               49.0
                                                   Protocol exists but was not observed by the dat...                8.0
Facility has other document to fill in for wome... ANC card (includes partograph)                                   50.0
                                                   Clinical/case file                                               42.0
When prioritized, with which document do you start ANC card (includes partograph)                                   50.0
                                                   Clinical/case file                                               42.0

Managing_authority                                                                                     Private-for-profit  \

Type of partograph                                 Uses partographs                                                  40.0
                                                   Modified WHO partograph                                           70.0
                                                   Simplified WHO partograph                                          9.0
                                                   Composite WHO partograph                                           3.0
                                                   Other types of partograph                                          9.0
Labour management protocol                         No management protocol                                            36.0
                                                   Protocol exists and was observed by the data co...                48.0
                                                   Protocol exists but was not observed by the dat...                15.0
Facility has other document to fill in for wome... ANC card (includes partograph)                                    61.0
                                                   Clinical/case file                                                58.0
When prioritized, with which document do you start ANC card (includes partograph)                                    61.0
                                                   Clinical/case file                                                58.0

Managing_authority                                                                                     Private-not-for-profit

Type of partograph                                 Uses partographs                                                       80.0
                                                   Modified WHO partograph                                                83.0
                                                   Simplified WHO partograph                                               0.0
                                                   Composite WHO partograph                                                2.0
                                                   Other types of partograph                                               0.0
Labour management protocol                         No management protocol                                                 38.0
                                                   Protocol exists and was observed by the data co...                     47.0
                                                   Protocol exists but was not observed by the dat...                     15.0
Facility has other document to fill in for wome... ANC card (includes partograph)                                         60.0
                                                   Clinical/case file                                                     38.0
When prioritized, with which document do you start ANC card (includes partograph)                                         60.0
                                                   Clinical/case file                                                     38.0

In [45]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221000,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeee,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo8)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000YT=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Type of partograph ','Labour management protocol','Facility has other document to fill in for women in labour','When prioritized, with which document do you start'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000YT

Facility                                                                                               Hospitals/ MCH specialty centres  \

Type of partograph                                 Uses partographs                                                                82.0
                                                   Modified WHO partograph                                                         90.0
                                                   Simplified WHO partograph                                                        2.0
                                                   Composite WHO partograph                                                         2.0
                                                   Other types of partograph                                                        1.0
Labour management protocol                         No management protocol                                                          32.0
                                                   Protocol exists and was observed by the data co...                              58.0
                                                   Protocol exists but was not observed by the dat...                              10.0
Facility has other document to fill in for wome... ANC card (includes partograph)                                                  55.0
                                                   Clinical/case file                                                              61.0
                                                   Administrative/financial file                                                   16.0
When prioritized, with which document do you start ANC card (includes partograph)                                                  42.0
                                                   Clinical/case file                                                              35.0

Facility                                                                                               Health centres/clinics1  \

Type of partograph                                 Uses partographs                                                       74.0
                                                   Modified WHO partograph                                                86.0
                                                   Simplified WHO partograph                                               1.0
                                                   Composite WHO partograph                                                2.0
                                                   Other types of partograph                                               0.0
Labour management protocol                         No management protocol                                                 44.0
                                                   Protocol exists and was observed by the data co...                     48.0
                                                   Protocol exists but was not observed by the dat...                      8.0
Facility has other document to fill in for wome... ANC card (includes partograph)                                         50.0
                                                   Clinical/case file                                                     40.0
                                                   Administrative/financial file                                           5.0
When prioritized, with which document do you start ANC card (includes partograph)                                         45.0
                                                   Clinical/case file                                                     18.0

Facility                                                                                               National

Type of partograph                                 Uses partographs                                        74.0
                                                   Modified WHO partograph                                 86.0
                                                   Simplified WHO partograph                                1.0
                                                   Composite WHO partograph                                 2.0
                                                   Other types of partograph                                0.0
Labour management protocol                         No management protocol                                  43.0
                                                   Protocol exists and was observed by the data co...      48.0
                                                   Protocol exists but was not observed by the dat...       8.0
Facility has other document to fill in for wome... ANC card (includes partograph)                          50.0
                                                   Clinical/case file                                      42.0
                                                   Administrative/financial file                            6.0
When prioritized, with which document do you start ANC card (includes partograph)                          45.0
                                                   Clinical/case file                                      20.0

In [47]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000YT,Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12000)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221kk=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False,keys=['Facility type ', 'Managing authority'])
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221kk

                                                                                                                        Facility type   \
                                                                                                      Hospitals/ MCH specialty centres

Facility has other document to fill in for wome... ANC card (includes partograph)                                                 55.0
                                                   Administrative/financial file                                                  16.0
                                                   Clinical/case file                                                             61.0
Labour management protocol                         No management protocol                                                         32.0
                                                   Protocol exists and was observed by the data co...                             58.0
                                                   Protocol exists but was not observed by the dat...                             10.0
Type of partograph                                 Composite WHO partograph                                                        2.0
                                                   Modified WHO partograph                                                        90.0
                                                   Other types of partograph                                                       1.0
                                                   Simplified WHO partograph                                                       2.0
                                                   Uses partographs                                                               82.0
When prioritized, with which document do you start ANC card (includes partograph)                                                 42.0
                                                   Clinical/case file                                                             35.0

                                                                                                                               \
                                                                                                      Health centres/clinics1

Facility has other document to fill in for wome... ANC card (includes partograph)                                        50.0
                                                   Administrative/financial file                                          5.0
                                                   Clinical/case file                                                    40.0
Labour management protocol                         No management protocol                                                44.0
                                                   Protocol exists and was observed by the data co...                    48.0
                                                   Protocol exists but was not observed by the dat...                     8.0
Type of partograph                                 Composite WHO partograph                                               2.0
                                                   Modified WHO partograph                                               86.0
                                                   Other types of partograph                                              0.0
                                                   Simplified WHO partograph                                              1.0
                                                   Uses partographs                                                      74.0
When prioritized, with which document do you start ANC card (includes partograph)                                        45.0
                                                   Clinical/case file                                                    18.0

                                                                                                                \
                                                                                                      National

Facility has other document to fill in for wome... ANC card (includes partograph)                         50.0
                                                   Administrative/financial file                           6.0
                                                   Clinical/case file                                     42.0
Labour management protocol                         No management protocol                                 43.0
                                                   Protocol exists and was observed by the data co...     48.0
                                                   Protocol exists but was not observed by the dat...      8.0
Type of partograph                                 Composite WHO partograph                                2.0
                                                   Modified WHO partograph                                86.0
                                                   Other types of partograph                               0.0
                                                   Simplified WHO partograph                               1.0
                                                   Uses partographs                                       74.0
When prioritized, with which document do you start ANC card (includes partograph)                         45.0
                                                   Clinical/case file                                     20.0

                                                                                                      Managing authority  \
                                                                                                       Public/government

Facility has other document to fill in for wome... ANC card (includes partograph)                                   50.0
                                                   Administrative/financial file                                     NaN
                                                   Clinical/case file                                               42.0
Labour management protocol                         No management protocol                                           43.0
                                                   Protocol exists and was observed by the data co...               49.0
                                                   Protocol exists but was not observed by the dat...                8.0
Type of partograph                                 Composite WHO partograph                                          2.0
                                                   Modified WHO partograph                                          87.0
                                                   Other types of partograph                                         0.0
                                                   Simplified WHO partograph                                         1.0
                                                   Uses partographs                                                 75.0
When prioritized, with which document do you start ANC card (includes partograph)                                   50.0
                                                   Clinical/case file                                               42.0

                                                                                                                          \
                                                                                                      Private-for-profit

Facility has other document to fill in for wome... ANC card (includes partograph)                                   61.0
                                                   Administrative/financial file                                     NaN
                                                   Clinical/case file                                               58.0
Labour management protocol                         No management protocol                                           36.0
                                                   Protocol exists and was observed by the data co...               48.0
                                                   Protocol exists but was not observed by the dat...               15.0
Type of partograph                                 Composite WHO partograph                                          3.0
                                                   Modified WHO partograph                                          70.0
                                                   Other types of partograph                                         9.0
                                                   Simplified WHO partograph                                         9.0
                                                   Uses partographs                                                 40.0
When prioritized, with which document do you start ANC card (includes partograph)                                   61.0
                                                   Clinical/case file                                               58.0


                                                                                                      Private-not-for-profit

Facility has other document to fill in for wome... ANC card (includes partograph)                                        60.0
                                                   Administrative/financial file                                          NaN
                                                   Clinical/case file                                                    38.0
Labour management protocol                         No management protocol                                                38.0
                                                   Protocol exists and was observed by the data co...                    47.0
                                                   Protocol exists but was not observed by the dat...                    15.0
Type of partograph                                 Composite WHO partograph                                               2.0
                                                   Modified WHO partograph                                               83.0
                                                   Other types of partograph                                              0.0
                                                   Simplified WHO partograph                                              0.0
                                                   Uses partographs                                                      80.0
When prioritized, with which document do you start ANC card (includes partograph)                                        60.0
                                                   Clinical/case file                                                    38.0

In [48]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery1221kk.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Partograph reviews/ Percent of facilities according to partograph usage characteristics.csv")

In [22]:
my_tab = pd.crosstab(data['Q005'], data['Q101_11'])
provided_obstetric_and_newborn_care_24_7_Region = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Region[0]
del  provided_obstetric_and_newborn_care_24_7_Region[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Provides obstetric care 24/7']
provided_obstetric_and_newborn_care_24_7_Region.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Region.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Region.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Region.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q101_11'], data['Q101_11'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
provided_obstetric_and_newborn_care_24_7_Region.loc['National'] = cc
provided_obstetric_and_newborn_care_24_7_Region

                   Provides obstetric care 24/7
Region
Tigray                                    100.0
Afar                                       97.0
Amhara                                    100.0
Oromia                                    100.0
Somali                                     96.0
Benishangul-Gumuz                         100.0
SNNP                                       99.0
Gambella                                  100.0
Harari                                     93.0
Addis Ababa                               100.0
Dire Dawa                                 100.0
National                                   99.0

In [23]:
my_tab = pd.crosstab(data['Q005'], data['Q102_11'])
provided_obstetric_and_newborn_care_24_7_Region1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Region1[0]
del  provided_obstetric_and_newborn_care_24_7_Region1[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Provides newborn care 24/7']
provided_obstetric_and_newborn_care_24_7_Region1.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Region1.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Region1.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Region1.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q102_11'], data['Q102_11'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
provided_obstetric_and_newborn_care_24_7_Region1.loc['National'] = cc
provided_obstetric_and_newborn_care_24_7_Region1

                   Provides newborn care 24/7
Region1
Tigray                                   99.0
Afar                                     97.0
Amhara                                   99.0
Oromia                                   99.0
Somali                                   88.0
Benishangul-Gumuz                       100.0
SNNP                                     97.0
Gambella                                100.0
Harari                                   73.0
Addis Ababa                              99.0
Dire Dawa                                38.0
National                                 97.0

In [24]:
my_tab = pd.crosstab(data['Q005'], data['Q103_11'])
provided_obstetric_and_newborn_care_24_7_Region12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Region12[0]
del  provided_obstetric_and_newborn_care_24_7_Region12[-999]
labels_of_col1 =["Region12","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Staff on call can reach facility within 30 min']
provided_obstetric_and_newborn_care_24_7_Region12.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Region12.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Region12.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Region12.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q103_11'], data['Q103_11'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
provided_obstetric_and_newborn_care_24_7_Region12.loc['National'] = cc
provided_obstetric_and_newborn_care_24_7_Region12

                   Staff on call can reach facility within 30 min
Region12
Tigray                                                       92.0
Afar                                                         34.0
Amhara                                                       86.0
Oromia                                                       90.0
Somali                                                       70.0
Benishangul-Gumuz                                            84.0
SNNP                                                         62.0
Gambella                                                     74.0
Harari                                                       67.0
Addis Ababa                                                  64.0
Dire Dawa                                                    38.0
National                                                     80.0

In [25]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(provided_obstetric_and_newborn_care_24_7_Region,provided_obstetric_and_newborn_care_24_7_Region1,provided_obstetric_and_newborn_care_24_7_Region12)
facilities_that_provided_obstetric_and_newborn_care_Region=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
facilities_that_provided_obstetric_and_newborn_care_Region

,Provides obstetric care 24/7,Provides newborn care 24/7,Staff on call can reach facility within 30 min
Tigray,100.0,99.0,92.0
Afar,97.0,97.0,34.0
Amhara,100.0,99.0,86.0
Oromia,100.0,99.0,90.0
Somali,96.0,88.0,70.0
Benishangul-Gumuz,100.0,100.0,84.0
SNNP,99.0,97.0,62.0
Gambella,100.0,100.0,74.0
Harari,93.0,73.0,67.0
Addis Ababa,100.0,99.0,64.0
Dire Dawa,100.0,38.0,38.0
National,99.0,97.0,80.0

In [26]:
my_tab = pd.crosstab(data['FT7'], data['Q101_11'])
provided_obstetric_and_newborn_care_24_7_Facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Facility[0]
del  provided_obstetric_and_newborn_care_24_7_Facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Provides obstetric care 24/7']
provided_obstetric_and_newborn_care_24_7_Facility.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Facility.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Facility.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Facility.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['FT7'], data['Q102_11'])
provided_obstetric_and_newborn_care_24_7_Facility1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Facility1[0]
del  provided_obstetric_and_newborn_care_24_7_Facility1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Provides newborn care 24/7']
provided_obstetric_and_newborn_care_24_7_Facility1.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Facility1.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Facility1.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Facility1.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['FT7'], data['Q103_11'])
provided_obstetric_and_newborn_care_24_7_Facility12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Facility12[0]
del  provided_obstetric_and_newborn_care_24_7_Facility12[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Staff on call can reach facility within 30 min']
provided_obstetric_and_newborn_care_24_7_Facility12.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Facility12.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Facility12.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Facility12.index.names= [labels_of_col1[0]]
provided_obstetric_and_newborn_care_24_7_Facility12
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(provided_obstetric_and_newborn_care_24_7_Facility,provided_obstetric_and_newborn_care_24_7_Facility1,provided_obstetric_and_newborn_care_24_7_Facility12)
facilities_that_provided_obstetric_and_newborn_care_Facility=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
facilities_that_provided_obstetric_and_newborn_care_Facility

,Provides obstetric care 24/7,Provides newborn care 24/7,Staff on call can reach facility within 30 min
Facility,,,
Referral/specialized,100.0,100.0,93.0
General hospitals,99.0,97.0,93.0
Primary hospitals,99.0,96.0,88.0
MCH specialized centres,96.0,96.0,83.0
Health centres,99.0,98.0,79.0
MCH specialty clinics,94.0,81.0,69.0
Higher clinics,92.0,85.0,85.0

In [30]:
my_tab = pd.crosstab(data['MA3'], data['Q101_11'])
provided_obstetric_and_newborn_care_24_7_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Managing_authority[0]
del  provided_obstetric_and_newborn_care_24_7_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Provides obstetric care 24/7']
provided_obstetric_and_newborn_care_24_7_Managing_authority.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Managing_authority.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['MA3'], data['Q102_11'])
provided_obstetric_and_newborn_care_24_7_Managing_authority1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Managing_authority1[0]
del  provided_obstetric_and_newborn_care_24_7_Managing_authority1[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Provides newborn care 24/7']
provided_obstetric_and_newborn_care_24_7_Managing_authority1.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority1.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority1.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Managing_authority1.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['MA3'], data['Q103_11'])
provided_obstetric_and_newborn_care_24_7_Managing_authority12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Managing_authority12[0]
del  provided_obstetric_and_newborn_care_24_7_Managing_authority12[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Staff on call can reach facility within 30 min']
provided_obstetric_and_newborn_care_24_7_Managing_authority12.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority12.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Managing_authority12.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Managing_authority12.index.names= [labels_of_col1[0]]
provided_obstetric_and_newborn_care_24_7_Managing_authority12
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(provided_obstetric_and_newborn_care_24_7_Managing_authority,provided_obstetric_and_newborn_care_24_7_Managing_authority1,provided_obstetric_and_newborn_care_24_7_Managing_authority12)
facilities_that_provided_obstetric_and_newborn_care_Managing_authority=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
facilities_that_provided_obstetric_and_newborn_care_Managing_authority

,Provides obstetric care 24/7,Provides newborn care 24/7,Staff on call can reach facility within 30 min
Managing_authority,,,
Public/government,99.0,98.0,80.0
Private-for-profit,98.0,89.0,88.0
Private-not-for-profit,95.0,95.0,73.0

In [31]:
my_tab = pd.crosstab(data['Q009'], data['Q101_11'])
provided_obstetric_and_newborn_care_24_7_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Location[0]
del  provided_obstetric_and_newborn_care_24_7_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Provides obstetric care 24/7']
provided_obstetric_and_newborn_care_24_7_Location.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Location.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Location.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Location.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['Q009'], data['Q102_11'])
provided_obstetric_and_newborn_care_24_7_Location1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Location1[0]
del  provided_obstetric_and_newborn_care_24_7_Location1[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Provides newborn care 24/7']
provided_obstetric_and_newborn_care_24_7_Location1.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Location1.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Location1.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Location1.index.names= [labels_of_col1[0]]
my_tab = pd.crosstab(data['Q009'], data['Q103_11'])
provided_obstetric_and_newborn_care_24_7_Location12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  provided_obstetric_and_newborn_care_24_7_Location12[0]
del  provided_obstetric_and_newborn_care_24_7_Location12[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Staff on call can reach facility within 30 min']
provided_obstetric_and_newborn_care_24_7_Location12.columns= labels_of_col[1:]
provided_obstetric_and_newborn_care_24_7_Location12.index= labels_of_col1[1:]
provided_obstetric_and_newborn_care_24_7_Location12.columns.names= [labels_of_col[0]]
provided_obstetric_and_newborn_care_24_7_Location12.index.names= [labels_of_col1[0]]
provided_obstetric_and_newborn_care_24_7_Location12
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(provided_obstetric_and_newborn_care_24_7_Location,provided_obstetric_and_newborn_care_24_7_Location1,provided_obstetric_and_newborn_care_24_7_Location12)
facilities_that_provided_obstetric_and_newborn_care_Location=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
facilities_that_provided_obstetric_and_newborn_care_Location

,Provides obstetric care 24/7,Provides newborn care 24/7,Staff on call can reach facility within 30 min
Location,,,
Urban,99.0,97.0,79.0
Rural,99.0,98.0,80.0

In [32]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(facilities_that_provided_obstetric_and_newborn_care_Region,facilities_that_provided_obstetric_and_newborn_care_Facility,facilities_that_provided_obstetric_and_newborn_care_Managing_authority,facilities_that_provided_obstetric_and_newborn_care_Location)
Percent_of_facilities_with_a_pharmacy_or_supply12=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Region','Facility type','Managing authority','Location'])
Percent_of_facilities_with_a_pharmacy_or_supply12

                                            Provides obstetric care 24/7  \
Region             Tigray                                          100.0
                   Afar                                             97.0
                   Amhara                                          100.0
                   Oromia                                          100.0
                   Somali                                           96.0
                   Benishangul-Gumuz                               100.0
                   SNNP                                             99.0
                   Gambella                                        100.0
                   Harari                                           93.0
                   Addis Ababa                                     100.0
                   Dire Dawa                                       100.0
                   National                                         99.0
Facility type      Referral/specialized                            100.0
                   General hospitals                                99.0
                   Primary hospitals                                99.0
                   MCH specialized centres                          96.0
                   Health centres                                   99.0
                   MCH specialty clinics                            94.0
                   Higher clinics                                   92.0
Managing authority Public/government                                99.0
                   Private-for-profit                               98.0
                   Private-not-for-profit                           95.0
Location           Urban                                            99.0
                   Rural                                            99.0

                                            Provides newborn care 24/7  \
Region             Tigray                                         99.0
                   Afar                                           97.0
                   Amhara                                         99.0
                   Oromia                                         99.0
                   Somali                                         88.0
                   Benishangul-Gumuz                             100.0
                   SNNP                                           97.0
                   Gambella                                      100.0
                   Harari                                         73.0
                   Addis Ababa                                    99.0
                   Dire Dawa                                      38.0
                   National                                       97.0
Facility type      Referral/specialized                          100.0
                   General hospitals                              97.0
                   Primary hospitals                              96.0
                   MCH specialized centres                        96.0
                   Health centres                                 98.0
                   MCH specialty clinics                          81.0
                   Higher clinics                                 85.0
Managing authority Public/government                              98.0
                   Private-for-profit                             89.0
                   Private-not-for-profit                         95.0
Location           Urban                                          97.0
                   Rural                                          98.0

                                            Staff on call can reach facility within 30 min
Region             Tigray                                                             92.0
                   Afar                                                               34.0
                   Amhara                                                             86.0
                   Oromia                                                             90.0
                   Somali                                                             70.0
                   Benishangul-Gumuz                                                  84.0
                   SNNP                                                               62.0
                   Gambella                                                           74.0
                   Harari                                                             67.0
                   Addis Ababa                                                        64.0
                   Dire Dawa                                                          38.0
                   National                                                           80.0
Facility type      Referral/specialized                                               93.0
                   General hospitals                                                  93.0
                   Primary hospitals                                                  88.0
                   MCH specialized centres                                            83.0
                   Health centres                                                     79.0
                   MCH specialty clinics                                              69.0
                   Higher clinics                                                     85.0
Managing authority Public/government                                                  80.0
                   Private-for-profit                                                 88.0
                   Private-not-for-profit                                             73.0
Location           Urban                                                              79.0
                   Rural                                                              80.0

In [34]:
Percent_of_facilities_with_a_pharmacy_or_supply12.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of emergency services 24per7 and distance to nearest facility with obstetric surgery/Percent of facilities that provided obstetric and newborn care and whether staff on call can reach the facility within 30 minutes.csv")

In [54]:
my_tab = pd.crosstab(data['Q005'], data['Q104_11']<=25)
not_provide_obstetric_surgery1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  not_provide_obstetric_surgery1[0]
#del  not_provide_obstetric_surgery1[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'≤25 kms']
not_provide_obstetric_surgery1.columns= labels_of_col[1:]
not_provide_obstetric_surgery1.index= labels_of_col1[1:]
not_provide_obstetric_surgery1.columns.names= [labels_of_col[0]]
not_provide_obstetric_surgery1.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q203B_3']<=25, data['Q203B_3']<=25)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
not_provide_obstetric_surgery1.loc['National'] = cc
not_provide_obstetric_surgery1

                   ≤25 kms
Region1
Tigray                49.0
Afar                  22.0
Amhara                32.0
Oromia                33.0
Somali                17.0
Benishangul-Gumuz     26.0
SNNP                  47.0
Gambella              15.0
Harari               100.0
Addis Ababa           95.0
Dire Dawa             76.0
National             100.0

In [55]:
my_tab = pd.crosstab(data['Q005'],(data['Q104_11'].between(26, 50)))
not_provide_obstetric_surgery2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  not_provide_obstetric_surgery2[0]
#del  not_provide_obstetric_surgery2[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'26-50 kms']
not_provide_obstetric_surgery2.columns= labels_of_col[1:]
not_provide_obstetric_surgery2.index= labels_of_col1[1:]
not_provide_obstetric_surgery2.columns.names= [labels_of_col[0]]
not_provide_obstetric_surgery2.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q104_11'].between(26, 50), data['Q104_11'].between(26, 50))
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
not_provide_obstetric_surgery2.loc['National'] = cc
not_provide_obstetric_surgery2

                   26-50 kms
Region1
Tigray                  34.0
Afar                    25.0
Amhara                  25.0
Oromia                  29.0
Somali                  16.0
Benishangul-Gumuz       19.0
SNNP                    29.0
Gambella                22.0
Harari                   0.0
Addis Ababa              1.0
Dire Dawa               24.0
National                26.0

In [59]:
my_tab = pd.crosstab(data['Q005'], data['Q104_11']>=50)
not_provide_obstetric_surgery3 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  not_provide_obstetric_surgery3[0]
#del  not_provide_obstetric_surgery3[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'>=50']
not_provide_obstetric_surgery3.columns= labels_of_col[1:]
not_provide_obstetric_surgery3.index= labels_of_col1[1:]
not_provide_obstetric_surgery3.columns.names= [labels_of_col[0]]
not_provide_obstetric_surgery3.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q104_11']>=50, data['Q104_11']>=50)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
not_provide_obstetric_surgery3.loc['National'] = cc
not_provide_obstetric_surgery3

                   >=50
Region1
Tigray             18.0
Afar               60.0
Amhara             46.0
Oromia             41.0
Somali             70.0
Benishangul-Gumuz  58.0
SNNP               27.0
Gambella           63.0
Harari              0.0
Addis Ababa         5.0
Dire Dawa           0.0
National           38.0

In [71]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(not_provide_obstetric_surgery1,not_provide_obstetric_surgery2,not_provide_obstetric_surgery3)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeootyt=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeootyt

                   ≤25 kms  26-50 kms  >=50
Region1
Tigray                49.0       34.0  18.0
Afar                  22.0       25.0  60.0
Amhara                32.0       25.0  46.0
Oromia                33.0       29.0  41.0
Somali                17.0       16.0  70.0
Benishangul-Gumuz     26.0       19.0  58.0
SNNP                  47.0       29.0  27.0
Gambella              15.0       22.0  63.0
Harari               100.0        0.0   0.0
Addis Ababa           95.0        1.0   5.0
Dire Dawa             76.0       24.0   0.0
National             100.0       26.0  38.0

In [73]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeootyt.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of emergency services 24per7 and distance to nearest facility with obstetric surgery/Percent distribution of health centres or clinics that did not provide obstetric surgery in the last 3 months according to distance to nearest facility that provided obstetric surgery.csv")

In [221]:
my_tab = pd.crosstab(data['Q005'], data['Q503A_11']==1)
with_on_site_ambulance_transport = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_transport[0]
#del  with_on_site_ambulance_transport[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'At least one motor vehicle ambulance Available functional']
with_on_site_ambulance_transport.columns= labels_of_col[1:]
with_on_site_ambulance_transport.index= labels_of_col1[1:]
with_on_site_ambulance_transport.columns.names= [labels_of_col[0]]
with_on_site_ambulance_transport.index.names= [labels_of_col1[0]]
with_on_site_ambulance_transport

                   At least one motor vehicle ambulance Available functional
Region1
Tigray                                                          18.0
Afar                                                            36.0
Amhara                                                          10.0
Oromia                                                           8.0
Somali                                                          48.0
Benishangul-Gumuz                                               65.0
SNNP                                                             9.0
Gambella                                                        22.0
Harari                                                          47.0
Addis Ababa                                                     25.0
Dire Dawa                                                       62.0

In [222]:
my_tab = pd.crosstab(data['Q005'], data['Q503B_11']==1)
with_on_site_ambulance_transport1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_transport1[0]
#del  with_on_site_ambulance_transport1[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'At least one motor vehicle ambulance Available needs repair']
with_on_site_ambulance_transport1.columns= labels_of_col[1:]
with_on_site_ambulance_transport1.index= labels_of_col1[1:]
with_on_site_ambulance_transport1.columns.names= [labels_of_col[0]]
with_on_site_ambulance_transport1.index.names= [labels_of_col1[0]]
with_on_site_ambulance_transport1

                   At least one motor vehicle ambulance Available needs repair
Region1
Tigray                                                           5.0
Afar                                                             8.0
Amhara                                                           4.0
Oromia                                                           2.0
Somali                                                          13.0
Benishangul-Gumuz                                               21.0
SNNP                                                             2.0
Gambella                                                         4.0
Harari                                                           0.0
Addis Ababa                                                      6.0
Dire Dawa                                                        0.0

In [223]:
my_tab = pd.crosstab(data['Q005'], data['Q504A_11']==1)
with_on_site_ambulance_transport12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_transport12[0]
#del  with_on_site_ambulance_transport12[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance functional']
with_on_site_ambulance_transport12.columns= labels_of_col[1:]
with_on_site_ambulance_transport12.index= labels_of_col1[1:]
with_on_site_ambulance_transport12.columns.names= [labels_of_col[0]]
with_on_site_ambulance_transport12.index.names= [labels_of_col1[0]]
with_on_site_ambulance_transport12

                   At least one motorcycle/tricycle ambulance functional
Region1
Tigray                                                           4.0
Afar                                                             8.0
Amhara                                                           5.0
Oromia                                                           1.0
Somali                                                          12.0
Benishangul-Gumuz                                               26.0
SNNP                                                             2.0
Gambella                                                         4.0
Harari                                                           0.0
Addis Ababa                                                      2.0
Dire Dawa                                                        5.0

In [224]:
my_tab = pd.crosstab(data['Q005'], data['Q503B_11']==1)
with_on_site_ambulance_transport123 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_transport123[0]
#del  with_on_site_ambulance_transport123[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_transport123.columns= labels_of_col[1:]
with_on_site_ambulance_transport123.index= labels_of_col1[1:]
with_on_site_ambulance_transport123.columns.names= [labels_of_col[0]]
with_on_site_ambulance_transport123.index.names= [labels_of_col1[0]]
with_on_site_ambulance_transport123

                   At least one motorcycle/tricycle ambulance Available needs repair
Region1
Tigray                                                           5.0
Afar                                                             8.0
Amhara                                                           4.0
Oromia                                                           2.0
Somali                                                          13.0
Benishangul-Gumuz                                               21.0
SNNP                                                             2.0
Gambella                                                         4.0
Harari                                                           0.0
Addis Ababa                                                      6.0
Dire Dawa                                                        0.0

In [225]:
my_tab = pd.crosstab(data['Q005'], data['Q505A_11']!=-999)
with_on_site_ambulance_transport124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_transport124[0]
#del  with_on_site_ambulance_transport124[-999]
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_transport124.columns= labels_of_col[1:]
with_on_site_ambulance_transport124.index= labels_of_col1[1:]
with_on_site_ambulance_transport124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_transport124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_transport124

                   At least one motorcycle/tricycle ambulance Available needs repair
Region1
Tigray                                                          22.0
Afar                                                            40.0
Amhara                                                          20.0
Oromia                                                          10.0
Somali                                                          58.0
Benishangul-Gumuz                                               74.0
SNNP                                                            12.0
Gambella                                                        26.0
Harari                                                          53.0
Addis Ababa                                                     37.0
Dire Dawa                                                       62.0

In [236]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(with_on_site_ambulance_transport,with_on_site_ambulance_transport1,with_on_site_ambulance_transport12,with_on_site_ambulance_transport123,with_on_site_ambulance_transport124)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1

,At least one motor vehicle ambulance Available functional,At least one motor vehicle ambulance Available needs repair,At least one motorcycle/tricycle ambulance functional,At least one motorcycle/tricycle ambulance Available needs repair,At least one motorcycle/tricycle ambulance Available needs repair
Region1,,,,,
Tigray,18.0,5.0,4.0,5.0,22.0
Afar,36.0,8.0,8.0,8.0,40.0
Amhara,10.0,4.0,5.0,4.0,20.0
Oromia,8.0,2.0,1.0,2.0,10.0
Somali,48.0,13.0,12.0,13.0,58.0
Benishangul-Gumuz,65.0,21.0,26.0,21.0,74.0
SNNP,9.0,2.0,2.0,2.0,12.0
Gambella,22.0,4.0,4.0,4.0,26.0
Harari,47.0,0.0,0.0,0.0,53.0
Addis Ababa,25.0,6.0,2.0,6.0,37.0
Dire Dawa,62.0,0.0,5.0,0.0,62.0

In [235]:
my_tab = pd.crosstab(data['FT7'], data['Q503A_11']==1)
with_on_site_ambulance_facility = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility[0]
#del  with_on_site_ambulance_facility[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motor vehicle ambulance Available functional']
with_on_site_ambulance_facility.columns= labels_of_col[1:]
with_on_site_ambulance_facility.index= labels_of_col1[1:]
with_on_site_ambulance_facility.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility
my_tab = pd.crosstab(data['FT7'], data['Q503B_11']!=-999)
with_on_site_ambulance_facility1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility1[0]
#del  with_on_site_ambulance_facility1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motor vehicle ambulance Available needs repair']
with_on_site_ambulance_facility1.columns= labels_of_col[1:]
with_on_site_ambulance_facility1.index= labels_of_col1[1:]
with_on_site_ambulance_facility1.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility1.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility1
my_tab = pd.crosstab(data['FT7'], data['Q504A_11']==1)
with_on_site_ambulance_facility12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility12[0]
#del  with_on_site_ambulance_facility12[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance functional']
with_on_site_ambulance_facility12.columns= labels_of_col[1:]
with_on_site_ambulance_facility12.index= labels_of_col1[1:]
with_on_site_ambulance_facility12.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility12.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility12
my_tab = pd.crosstab(data['FT7'], data['Q503B_11']==1)
with_on_site_ambulance_facility123 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility123[0]
#del  with_on_site_ambulance_facility123[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_facility123.columns= labels_of_col[1:]
with_on_site_ambulance_facility123.index= labels_of_col1[1:]
with_on_site_ambulance_facility123.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility123.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility123
my_tab = pd.crosstab(data['FT7'], data['Q505A_11']!=-999)
with_on_site_ambulance_facility124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility124[0]
#del  with_on_site_ambulance_facility124[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_facility124.columns= labels_of_col[1:]
with_on_site_ambulance_facility124.index= labels_of_col1[1:]
with_on_site_ambulance_facility124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility124
my_tab = pd.crosstab(data['FT7'], data['Q505A_11']!=-999)
with_on_site_ambulance_facility124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_facility124[0]
#del  with_on_site_ambulance_facility124[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_facility124.columns= labels_of_col[1:]
with_on_site_ambulance_facility124.index= labels_of_col1[1:]
with_on_site_ambulance_facility124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_facility124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_facility124
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(with_on_site_ambulance_facility,with_on_site_ambulance_facility1,with_on_site_ambulance_facility12,with_on_site_ambulance_facility123,with_on_site_ambulance_facility124)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2

,At least one motor vehicle ambulance Available functional,At least one motor vehicle ambulance Available needs repair,At least one motorcycle/tricycle ambulance functional,At least one motorcycle/tricycle ambulance Available needs repair,At least one motorcycle/tricycle ambulance Available needs repair
Facility,,,,,
Referral/specialized,50.0,87.0,3.0,23.0,87.0
General hospitals,55.0,83.0,9.0,16.0,83.0
Primary hospitals,48.0,57.0,6.0,9.0,57.0
MCH specialized centres,74.0,87.0,0.0,4.0,87.0
Health centres,10.0,14.0,3.0,3.0,14.0
MCH specialty clinics,19.0,31.0,0.0,0.0,31.0
Higher clinics,31.0,31.0,0.0,0.0,31.0

In [234]:
my_tab = pd.crosstab(data['MA3'], data['Q503A_11']==1)
with_on_site_ambulance_Managing_authority = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority[0]
#del  with_on_site_ambulance_Managing_authority[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motor vehicle ambulance Available functional']
with_on_site_ambulance_Managing_authority.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority
my_tab = pd.crosstab(data['MA3'], data['Q503B_11']!=-999)
with_on_site_ambulance_Managing_authority1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority1[0]
#del  with_on_site_ambulance_Managing_authority1[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motor vehicle ambulance Available needs repair']
with_on_site_ambulance_Managing_authority1.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority1.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority1.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority1.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority1
my_tab = pd.crosstab(data['MA3'], data['Q504A_11']==1)
with_on_site_ambulance_Managing_authority12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority12[0]
#del  with_on_site_ambulance_Managing_authority12[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance functional']
with_on_site_ambulance_Managing_authority12.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority12.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority12.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority12.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority12
my_tab = pd.crosstab(data['MA3'], data['Q503B_11']==1)
with_on_site_ambulance_Managing_authority123 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority123[0]
#del  with_on_site_ambulance_Managing_authority123[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Managing_authority123.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority123.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority123.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority123.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority123
my_tab = pd.crosstab(data['MA3'], data['Q505A_11']!=-999)
with_on_site_ambulance_Managing_authority124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority124[0]
#del  with_on_site_ambulance_Managing_authority124[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Managing_authority124.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority124.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority124
my_tab = pd.crosstab(data['MA3'], data['Q505A_11']!=-999)
with_on_site_ambulance_Managing_authority124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Managing_authority124[0]
#del  with_on_site_ambulance_Managing_authority124[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Managing_authority124.columns= labels_of_col[1:]
with_on_site_ambulance_Managing_authority124.index= labels_of_col1[1:]
with_on_site_ambulance_Managing_authority124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Managing_authority124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Managing_authority124
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(with_on_site_ambulance_Managing_authority,with_on_site_ambulance_Managing_authority1,with_on_site_ambulance_Managing_authority12,with_on_site_ambulance_Managing_authority123,with_on_site_ambulance_Managing_authority124)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo3

,At least one motor vehicle ambulance Available functional,At least one motor vehicle ambulance Available needs repair,At least one motorcycle/tricycle ambulance functional,At least one motorcycle/tricycle ambulance Available needs repair,At least one motorcycle/tricycle ambulance Available needs repair
Managing_authority,,,,,
Public/government,12.0,17.0,3.0,3.0,17.0
Private-for-profit,53.0,70.0,2.0,5.0,70.0
Private-not-for-profit,46.0,58.0,5.0,5.0,58.0

In [233]:
my_tab = pd.crosstab(data['Q009'], data['Q503A_11']==1)
with_on_site_ambulance_Location = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location[0]
#del  with_on_site_ambulance_Location[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motor vehicle ambulance Available functional']
with_on_site_ambulance_Location.columns= labels_of_col[1:]
with_on_site_ambulance_Location.index= labels_of_col1[1:]
with_on_site_ambulance_Location.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location
my_tab = pd.crosstab(data['Q009'], data['Q503B_11']!=-999)
with_on_site_ambulance_Location1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location1[0]
#del  with_on_site_ambulance_Location1[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motor vehicle ambulance Available needs repair']
with_on_site_ambulance_Location1.columns= labels_of_col[1:]
with_on_site_ambulance_Location1.index= labels_of_col1[1:]
with_on_site_ambulance_Location1.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location1.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location1
my_tab = pd.crosstab(data['Q009'], data['Q504A_11']==1)
with_on_site_ambulance_Location12 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location12[0]
#del  with_on_site_ambulance_Location12[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance functional']
with_on_site_ambulance_Location12.columns= labels_of_col[1:]
with_on_site_ambulance_Location12.index= labels_of_col1[1:]
with_on_site_ambulance_Location12.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location12.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location12
my_tab = pd.crosstab(data['Q009'], data['Q503B_11']==1)
with_on_site_ambulance_Location123 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location123[0]
#del  with_on_site_ambulance_Location123[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Location123.columns= labels_of_col[1:]
with_on_site_ambulance_Location123.index= labels_of_col1[1:]
with_on_site_ambulance_Location123.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location123.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location123
my_tab = pd.crosstab(data['Q009'], data['Q505A_11']!=-999)
with_on_site_ambulance_Location124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location124[0]
#del  with_on_site_ambulance_Location124[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Location124.columns= labels_of_col[1:]
with_on_site_ambulance_Location124.index= labels_of_col1[1:]
with_on_site_ambulance_Location124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location124
my_tab = pd.crosstab(data['Q009'], data['Q505A_11']!=-999)
with_on_site_ambulance_Location124 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del  with_on_site_ambulance_Location124[0]
#del  with_on_site_ambulance_Location124[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'At least one motorcycle/tricycle ambulance Available needs repair']
with_on_site_ambulance_Location124.columns= labels_of_col[1:]
with_on_site_ambulance_Location124.index= labels_of_col1[1:]
with_on_site_ambulance_Location124.columns.names= [labels_of_col[0]]
with_on_site_ambulance_Location124.index.names= [labels_of_col1[0]]
with_on_site_ambulance_Location124
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(with_on_site_ambulance_Location,with_on_site_ambulance_Location1,with_on_site_ambulance_Location12,with_on_site_ambulance_Location123,with_on_site_ambulance_Location124)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo4=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo4

,At least one motor vehicle ambulance Available functional,At least one motor vehicle ambulance Available needs repair,At least one motorcycle/tricycle ambulance functional,At least one motorcycle/tricycle ambulance Available needs repair,At least one motorcycle/tricycle ambulance Available needs repair
Location,,,,,
Urban,23.0,32.0,5.0,6.0,32.0
Rural,7.0,10.0,2.0,2.0,10.0

In [237]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo1,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo2,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo3,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo4)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12565=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Region','Facility type','Managing authority','Location'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12565

                                            At least one motor vehicle ambulance Available functional  \
Region             Tigray                                                                18.0
                   Afar                                                                  36.0
                   Amhara                                                                10.0
                   Oromia                                                                 8.0
                   Somali                                                                48.0
                   Benishangul-Gumuz                                                     65.0
                   SNNP                                                                   9.0
                   Gambella                                                              22.0
                   Harari                                                                47.0
                   Addis Ababa                                                           25.0
                   Dire Dawa                                                             62.0
Facility type      Referral/specialized                                                  50.0
                   General hospitals                                                     55.0
                   Primary hospitals                                                     48.0
                   MCH specialized centres                                               74.0
                   Health centres                                                        10.0
                   MCH specialty clinics                                                 19.0
                   Higher clinics                                                        31.0
Managing authority Public/government                                                     12.0
                   Private-for-profit                                                    53.0
                   Private-not-for-profit                                                46.0
Location           Urban                                                                 23.0
                   Rural                                                                  7.0

                                            At least one motor vehicle ambulance Available needs repair  \
Region             Tigray                                                                 5.0
                   Afar                                                                   8.0
                   Amhara                                                                 4.0
                   Oromia                                                                 2.0
                   Somali                                                                13.0
                   Benishangul-Gumuz                                                     21.0
                   SNNP                                                                   2.0
                   Gambella                                                               4.0
                   Harari                                                                 0.0
                   Addis Ababa                                                            6.0
                   Dire Dawa                                                              0.0
Facility type      Referral/specialized                                                  87.0
                   General hospitals                                                     83.0
                   Primary hospitals                                                     57.0
                   MCH specialized centres                                               87.0
                   Health centres                                                        14.0
                   MCH specialty clinics                                                 31.0
                   Higher clinics                                                        31.0
Managing authority Public/government                                                     17.0
                   Private-for-profit                                                    70.0
                   Private-not-for-profit                                                58.0
Location           Urban                                                                 32.0
                   Rural                                                                 10.0

                                            At least one motorcycle/tricycle ambulance functional  \
Region             Tigray                                                                 4.0
                   Afar                                                                   8.0
                   Amhara                                                                 5.0
                   Oromia                                                                 1.0
                   Somali                                                                12.0
                   Benishangul-Gumuz                                                     26.0
                   SNNP                                                                   2.0
                   Gambella                                                               4.0
                   Harari                                                                 0.0
                   Addis Ababa                                                            2.0
                   Dire Dawa                                                              5.0
Facility type      Referral/specialized                                                   3.0
                   General hospitals                                                      9.0
                   Primary hospitals                                                      6.0
                   MCH specialized centres                                                0.0
                   Health centres                                                         3.0
                   MCH specialty clinics                                                  0.0
                   Higher clinics                                                         0.0
Managing authority Public/government                                                      3.0
                   Private-for-profit                                                     2.0
                   Private-not-for-profit                                                 5.0
Location           Urban                                                                  5.0
                   Rural                                                                  2.0

                                            At least one motorcycle/tricycle ambulance Available needs repair  \
Region             Tigray                                                                 5.0
                   Afar                                                                   8.0
                   Amhara                                                                 4.0
                   Oromia                                                                 2.0
                   Somali                                                                13.0
                   Benishangul-Gumuz                                                     21.0
                   SNNP                                                                   2.0
                   Gambella                                                               4.0
                   Harari                                                                 0.0
                   Addis Ababa                                                            6.0
                   Dire Dawa                                                              0.0
Facility type      Referral/specialized                                                  23.0
                   General hospitals                                                     16.0
                   Primary hospitals                                                      9.0
                   MCH specialized centres                                                4.0
                   Health centres                                                         3.0
                   MCH specialty clinics                                                  0.0
                   Higher clinics                                                         0.0
Managing authority Public/government                                                      3.0
                   Private-for-profit                                                     5.0
                   Private-not-for-profit                                                 5.0
Location           Urban                                                                  6.0
                   Rural                                                                  2.0

                                            At least one motorcycle/tricycle ambulance Available needs repair
Region             Tigray                                                                22.0
                   Afar                                                                  40.0
                   Amhara                                                                20.0
                   Oromia                                                                10.0
                   Somali                                                                58.0
                   Benishangul-Gumuz                                                     74.0
                   SNNP                                                                  12.0
                   Gambella                                                              26.0
                   Harari                                                                53.0
                   Addis Ababa                                                           37.0
                   Dire Dawa                                                             62.0
Facility type      Referral/specialized                                                  87.0
                   General hospitals                                                     83.0
                   Primary hospitals                                                     57.0
                   MCH specialized centres                                               87.0
                   Health centres                                                        14.0
                   MCH specialty clinics                                                 31.0
                   Higher clinics                                                        31.0
Managing authority Public/government                                                     17.0
                   Private-for-profit                                                    70.0
                   Private-not-for-profit                                                58.0
Location           Urban                                                                 32.0
                   Rural                                                                 10.0

In [238]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12565.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of means of transportation/Percent of facilities with on-site ambulance transport and whether it was functional or needed repair.csv")

In [257]:
my_tab1 = pd.crosstab(data['Q501_11'], data['Q501_11'])
b = len(data.loc[((data['Q005']))])
my_tab11 = ((my_tab1[0][0])/b)*100
my_tab12 = ((my_tab1[1][1])/b)*100
my_tab13 = ((my_tab1[2][2])/b)*100
my_tab14 = ((my_tab1[3][3])/b)*100
my_tab15 = ((my_tab1[4][4])/b)*100
my_tab16 = ((my_tab1[5][5])/b)*100
my_tab17 = ((my_tab1[96][96])/b)*100
cc= round((my_tab11),0)
cc1= round((my_tab12),0)
cc2= round((my_tab13),0)
cc3= round((my_tab14),0)
cc4= round((my_tab15),0)
cc5= round((my_tab16),0)
cc6= round((my_tab17),0)
fata23 = [['No one person on duty', cc],['Facility administrator', cc1], ['Liaison officer', cc2], ['Medical officer', cc3], ['Transport officer', cc4], ['Nurse/CO/midwife ', cc5], ['Other', cc6]]
df23 = pd.DataFrame(fata23, columns = ['Who is in charge of managing emergency transport', 'percentage'])
df23

  Who is in charge of managing emergency transport  percentage
0                            No one person on duty        22.0
1                           Facility administrator        27.0
2                                  Liaison officer         5.0
3                                  Medical officer         7.0
4                                Transport officer         1.0
5                                Nurse/CO/midwife         36.0
6                                            Other         2.0

In [258]:
df23.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Availability of means of transportation/Percent distribution of facilities according to staff member in charge of managing the emergency transport system.csv")

In [474]:
Deliveries=data.pivot_table(values = 'totdeliveries', index = 'Q005', aggfunc = 'sum')
labels_of_col1 =["Region1","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Deliverie']
Deliveries.columns= labels_of_col[1:]
Deliveries.index= labels_of_col1[1:]
Deliveries.columns.names= [labels_of_col[0]]
Deliveries.index.names= [labels_of_col1[0]]
tabl1212=Deliveries.sum()
Deliveries.loc['National'] = tabl1212
Deliveries

                   Deliverie
Region1
Tigray                113425
Afar                    7678
Amhara                386131
Oromia                844287
Somali                 22036
Benishangul-Gumuz      12288
SNNP                  417697
Gambella                3383
Harari                  7579
Addis Ababa           101401
Dire Dawa               8425
National             1924330

In [475]:
table = pd.pivot_table(data, values=['Q215_4TOT','Q216_4TOT','Q217_4TOT','Q218_4TOT','Q207_4TOT','Q211_4TOT','Q214_4TOT','Q212_4TOT','Q213_4TOT','Q219_4TOT','Q220_4TOT','Q221_4TOT','Q222_4TOT','Q223_4TOT','Q224_4TOT','Q225_4TOT'], index=['Q005'], aggfunc=np.sum)
Deliveries1=table.sum(axis=1)
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Deliveries']
Deliveries1.columns= labels_of_col[1:]
Deliveries1.index= labels_of_col1[1:]
#Deliveries1.columns.names= [labels_of_col[0]]
Deliveries1.index.names= [labels_of_col1[0]]
tabl1212=Deliveries1.sum()
Deliveries1.loc['National'] = tabl1212
Deliveries1

Region
Tigray                19281
Afar                   1344
Amhara                41218
Oromia                55419
Somali                 3899
Benishangul-Gumuz      2429
SNNP                  31197
Gambella                451
Harari                 2635
Addis Ababa           40451
Dire Dawa              2568
National             200892
dtype: int64

In [476]:
Deliveries2 = pd.pivot_table(data, values=['Q256_4TOT'], index=['Q005'], aggfunc=np.sum)
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Referrals_out_due_to_maternal_indications']
Deliveries2.columns= labels_of_col[1:]
Deliveries2.index= labels_of_col1[1:]
#Deliveries2.columns.names= [labels_of_col[0]]
Deliveries2.index.names= [labels_of_col1[0]]
tabl1212=Deliveries2.sum()
Deliveries2.loc['National'] = tabl1212
Deliveries2

                   Referrals_out_due_to_maternal_indications
Region
Tigray                                                  7110
Afar                                                     324
Amhara                                                 13784
Oromia                                                 21378
Somali                                                   641
Benishangul-Gumuz                                        511
SNNP                                                    9657
Gambella                                                  18
Harari                                                   121
Addis Ababa                                            15502
Dire Dawa                                                559
National                                               69605

In [477]:
Deliveries3= (Deliveries2['Referrals_out_due_to_maternal_indications']/Deliveries['Deliverie'])*100
Deliveries4=round((Deliveries3),0)
print(Deliveries4)

Region
Tigray                6.0
Afar                  4.0
Amhara                4.0
Oromia                3.0
Somali                3.0
Benishangul-Gumuz     4.0
SNNP                  2.0
Gambella              1.0
Harari                2.0
Addis Ababa          15.0
Dire Dawa             7.0
National              4.0
dtype: float64

In [478]:
Deliveries3= (Deliveries2['Referrals_out_due_to_maternal_indications']/Deliveries1)*100
Deliveries5=round((Deliveries3),0)
print(Deliveries5)

Region
Tigray               37.0
Afar                 24.0
Amhara               33.0
Oromia               39.0
Somali               16.0
Benishangul-Gumuz    21.0
SNNP                 31.0
Gambella              4.0
Harari                5.0
Addis Ababa          38.0
Dire Dawa            22.0
National             35.0
dtype: float64

In [479]:
Deliveries6 = pd.pivot_table(data, values=['Q257_4TOT'], index=['Q005'], aggfunc=np.sum)
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Referrals out due to newborn indications']
Deliveries6.columns= labels_of_col[1:]
Deliveries6.index= labels_of_col1[1:]
#Deliveries6.columns.names= [labels_of_col[0]]
Deliveries6.index.names= [labels_of_col1[0]]
tabl1212=Deliveries6.sum()
Deliveries6.loc['National'] = tabl1212
Deliveries6

                   Referrals out due to newborn indications
Region
Tigray                                                  701
Afar                                                     24
Amhara                                                 1194
Oromia                                                 1959
Somali                                                   67
Benishangul-Gumuz                                        40
SNNP                                                    756
Gambella                                                  2
Harari                                                    9
Addis Ababa                                            1438
Dire Dawa                                                41
National                                               6231

In [480]:
Deliveries3= (Deliveries6['Referrals out due to newborn indications']/Deliveries['Deliverie'])*100
Deliveries7=round((Deliveries3),1)
print(Deliveries7)

Region
Tigray               0.6
Afar                 0.3
Amhara               0.3
Oromia               0.2
Somali               0.3
Benishangul-Gumuz    0.3
SNNP                 0.2
Gambella             0.1
Harari               0.1
Addis Ababa          1.4
Dire Dawa            0.5
National             0.3
dtype: float64

In [482]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Deliveries,Deliveries1,Deliveries2,Deliveries4,Deliveries5,Deliveries6,Deliveries7)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo741=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo741

,Deliverie,0,Referrals_out_due_to_maternal_indications,1,2,Referrals out due to newborn indications,3
Tigray,113425,19281,7110,6.0,37.0,701,0.6
Afar,7678,1344,324,4.0,24.0,24,0.3
Amhara,386131,41218,13784,4.0,33.0,1194,0.3
Oromia,844287,55419,21378,3.0,39.0,1959,0.2
Somali,22036,3899,641,3.0,16.0,67,0.3
Benishangul-Gumuz,12288,2429,511,4.0,21.0,40,0.3
SNNP,417697,31197,9657,2.0,31.0,756,0.2
Gambella,3383,451,18,1.0,4.0,2,0.1
Harari,7579,2635,121,2.0,5.0,9,0.1
Addis Ababa,101401,40451,15502,15.0,38.0,1438,1.4
Dire Dawa,8425,2568,559,7.0,22.0,41,0.5
National,1924330,200892,69605,4.0,35.0,6231,0.3

In [483]:
Facility=data.pivot_table(values = 'totdeliveries', index = 'FT7', aggfunc = 'sum')
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Deliverie']
Facility.columns= labels_of_col[1:]
Facility.index= labels_of_col1[1:]
Facility.columns.names= [labels_of_col[0]]
Facility.index.names= [labels_of_col1[0]]
tabl1212=Facility.sum()
Facility.loc['National'] = tabl1212
Facility
table = pd.pivot_table(data, values=['Q215_4TOT','Q216_4TOT','Q217_4TOT','Q218_4TOT','Q207_4TOT','Q211_4TOT','Q214_4TOT','Q212_4TOT','Q213_4TOT','Q219_4TOT','Q220_4TOT','Q221_4TOT','Q222_4TOT','Q223_4TOT','Q224_4TOT','Q225_4TOT'], index=['FT7'], aggfunc=np.sum)
Facility1=table.sum(axis=1)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Facility']
Facility1.columns= labels_of_col[1:]
Facility1.index= labels_of_col1[1:]
#Facility1.columns.names= [labels_of_col[0]]
Facility1.index.names= [labels_of_col1[0]]
tabl1212=Facility1.sum()
Facility1.loc['National'] = tabl1212
Facility1
Facility2 = pd.pivot_table(data, values=['Q256_4TOT'], index=['FT7'], aggfunc=np.sum)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Referrals_out_due_to_maternal_indications']
Facility2.columns= labels_of_col[1:]
Facility2.index= labels_of_col1[1:]
#Facility2.columns.names= [labels_of_col[0]]
Facility2.index.names= [labels_of_col1[0]]
tabl1212=Facility2.sum()
Facility2.loc['National'] = tabl1212
Facility2
Deliveries3= (Facility2['Referrals_out_due_to_maternal_indications']/Facility['Deliverie'])*100
Facility4=round((Deliveries3),0)
Facility3= (Facility2['Referrals_out_due_to_maternal_indications']/Facility1)*100
Facility5=round((Facility3),0)
Facility6 = pd.pivot_table(data, values=['Q257_4TOT'], index=['FT7'], aggfunc=np.sum)
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Referrals out due to newborn indications']
Facility6.columns= labels_of_col[1:]
Facility6.index= labels_of_col1[1:]
#Facility6.columns.names= [labels_of_col[0]]
Facility6.index.names= [labels_of_col1[0]]
tabl1212=Facility6.sum()
Facility6.loc['National'] = tabl1212
Facility6
Facility3= (Facility6['Referrals out due to newborn indications']/Facility['Deliverie'])*100
Facility7=round((Facility3),1)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Facility,Facility1,Facility2,Facility4,Facility5,Facility6,Facility7)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo742=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo742

,Deliverie,0,Referrals_out_due_to_maternal_indications,1,2,Referrals out due to newborn indications,3
Facility,,,,,,,
Referral/specialized,103331,43994,3312,3.0,8.0,385,0.4
General hospitals,127099,44844,1080,1.0,2.0,336,0.3
Primary hospitals,104624,21625,3533,3.0,16.0,515,0.5
MCH specialized centres,17628,5199,285,2.0,5.0,50,0.3
Health centres,1565273,84357,61292,4.0,73.0,4926,0.3
MCH specialty clinics,3304,696,63,2.0,9.0,17,0.5
Higher clinics,3071,177,40,1.0,23.0,2,0.1
National,1924330,200892,69605,4.0,35.0,6231,0.3

In [484]:
Managing_authority=data.pivot_table(values = 'totdeliveries', index = 'MA3', aggfunc = 'sum')
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Deliverie']
Managing_authority.columns= labels_of_col[1:]
Managing_authority.index= labels_of_col1[1:]
Managing_authority.columns.names= [labels_of_col[0]]
Managing_authority.index.names= [labels_of_col1[0]]
tabl1212=Managing_authority.sum()
Managing_authority.loc['National'] = tabl1212
Managing_authority
table = pd.pivot_table(data, values=['Q215_4TOT','Q216_4TOT','Q217_4TOT','Q218_4TOT','Q207_4TOT','Q211_4TOT','Q214_4TOT','Q212_4TOT','Q213_4TOT','Q219_4TOT','Q220_4TOT','Q221_4TOT','Q222_4TOT','Q223_4TOT','Q224_4TOT','Q225_4TOT'], index=['MA3'], aggfunc=np.sum)
Managing_authority1=table.sum(axis=1)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Managing_authority']
Managing_authority1.columns= labels_of_col[1:]
Managing_authority1.index= labels_of_col1[1:]
#Managing_authority1.columns.names= [labels_of_col[0]]
Managing_authority1.index.names= [labels_of_col1[0]]
tabl1212=Managing_authority1.sum()
Managing_authority1.loc['National'] = tabl1212
Managing_authority1
Managing_authority2 = pd.pivot_table(data, values=['Q256_4TOT'], index=['MA3'], aggfunc=np.sum)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Referrals_out_due_to_maternal_indications']
Managing_authority2.columns= labels_of_col[1:]
Managing_authority2.index= labels_of_col1[1:]
#Managing_authority2.columns.names= [labels_of_col[0]]
Managing_authority2.index.names= [labels_of_col1[0]]
tabl1212=Managing_authority2.sum()
Managing_authority2.loc['National'] = tabl1212
Managing_authority2
Deliveries3= (Managing_authority2['Referrals_out_due_to_maternal_indications']/Managing_authority['Deliverie'])*100
Managing_authority4=round((Deliveries3),0)
Managing_authority3= (Managing_authority2['Referrals_out_due_to_maternal_indications']/Managing_authority1)*100
Managing_authority5=round((Managing_authority3),0)
Managing_authority6 = pd.pivot_table(data, values=['Q257_4TOT'], index=['MA3'], aggfunc=np.sum)
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Referrals out due to newborn indications']
Managing_authority6.columns= labels_of_col[1:]
Managing_authority6.index= labels_of_col1[1:]
#Managing_authority6.columns.names= [labels_of_col[0]]
Managing_authority6.index.names= [labels_of_col1[0]]
tabl1212=Managing_authority6.sum()
Managing_authority6.loc['National'] = tabl1212
Managing_authority6
Managing_authority3= (Managing_authority6['Referrals out due to newborn indications']/Managing_authority['Deliverie'])*100
Managing_authority7=round((Managing_authority3),1)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Managing_authority,Managing_authority1,Managing_authority2,Managing_authority4,Managing_authority5,Managing_authority6,Managing_authority7)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo743=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo743

,Deliverie,0,Referrals_out_due_to_maternal_indications,1,2,Referrals out due to newborn indications,3
Managing_authority,,,,,,,
Public/government,1861793,184780,68109,4.0,37.0,6040,0.3
Private-for-profit,28489,10350,93,0.0,1.0,127,0.4
Private-not-for-profit,34048,5762,1403,4.0,24.0,64,0.2
National,1924330,200892,69605,4.0,35.0,6231,0.3

In [485]:
Location=data.pivot_table(values = 'totdeliveries', index = 'Q009', aggfunc = 'sum')
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Deliverie']
Location.columns= labels_of_col[1:]
Location.index= labels_of_col1[1:]
Location.columns.names= [labels_of_col[0]]
Location.index.names= [labels_of_col1[0]]
tabl1212=Location.sum()
Location.loc['National'] = tabl1212
Location
table = pd.pivot_table(data, values=['Q215_4TOT','Q216_4TOT','Q217_4TOT','Q218_4TOT','Q207_4TOT','Q211_4TOT','Q214_4TOT','Q212_4TOT','Q213_4TOT','Q219_4TOT','Q220_4TOT','Q221_4TOT','Q222_4TOT','Q223_4TOT','Q224_4TOT','Q225_4TOT'], index=['Q009'], aggfunc=np.sum)
Location1=table.sum(axis=1)
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Location']
Location1.columns= labels_of_col[1:]
Location1.index= labels_of_col1[1:]
#Location1.columns.names= [labels_of_col[0]]
Location1.index.names= [labels_of_col1[0]]
tabl1212=Location1.sum()
Location1.loc['National'] = tabl1212
Location1
Location2 = pd.pivot_table(data, values=['Q256_4TOT'], index=['Q009'], aggfunc=np.sum)
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Referrals_out_due_to_maternal_indications']
Location2.columns= labels_of_col[1:]
Location2.index= labels_of_col1[1:]
#Location2.columns.names= [labels_of_col[0]]
Location2.index.names= [labels_of_col1[0]]
tabl1212=Location2.sum()
Location2.loc['National'] = tabl1212
Location2
Deliveries3= (Location2['Referrals_out_due_to_maternal_indications']/Location['Deliverie'])*100
Location4=round((Deliveries3),0)
Location3= (Location2['Referrals_out_due_to_maternal_indications']/Location1)*100
Location5=round((Location3),0)
Location6 = pd.pivot_table(data, values=['Q257_4TOT'], index=['Q009'], aggfunc=np.sum)
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Referrals out due to newborn indications']
Location6.columns= labels_of_col[1:]
Location6.index= labels_of_col1[1:]
#Location6.columns.names= [labels_of_col[0]]
Location6.index.names= [labels_of_col1[0]]
tabl1212=Location6.sum()
Location6.loc['National'] = tabl1212
Location6
Location3= (Location6['Referrals out due to newborn indications']/Location['Deliverie'])*100
Location7=round((Location3),1)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Location,Location1,Location2,Location4,Location5,Location6,Location7)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo744=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo744

,Deliverie,0,Referrals_out_due_to_maternal_indications,1,2,Referrals out due to newborn indications,3
Location,,,,,,,
Urban,971504,170285,47915,5.0,28.0,4240,0.4
Rural,952826,30607,21690,2.0,71.0,1991,0.2
National,1924330,200892,69605,4.0,35.0,6231,0.3

In [487]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo741,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo742,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo743,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeoo744)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12hgt=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Region','Facility type','Managing authority','Location'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12hgt

                                            Deliverie       0  \
Region             Tigray                      113425   19281
                   Afar                          7678    1344
                   Amhara                      386131   41218
                   Oromia                      844287   55419
                   Somali                       22036    3899
                   Benishangul-Gumuz            12288    2429
                   SNNP                        417697   31197
                   Gambella                      3383     451
                   Harari                        7579    2635
                   Addis Ababa                 101401   40451
                   Dire Dawa                     8425    2568
                   National                   1924330  200892
Facility type      Referral/specialized        103331   43994
                   General hospitals           127099   44844
                   Primary hospitals           104624   21625
                   MCH specialized centres      17628    5199
                   Health centres             1565273   84357
                   MCH specialty clinics         3304     696
                   Higher clinics                3071     177
                   National                   1924330  200892
Managing authority Public/government          1861793  184780
                   Private-for-profit           28489   10350
                   Private-not-for-profit       34048    5762
                   National                   1924330  200892
Location           Urban                       971504  170285
                   Rural                       952826   30607
                   National                   1924330  200892

                                            Referrals_out_due_to_maternal_indications  \
Region             Tigray                                                        7110
                   Afar                                                           324
                   Amhara                                                       13784
                   Oromia                                                       21378
                   Somali                                                         641
                   Benishangul-Gumuz                                              511
                   SNNP                                                          9657
                   Gambella                                                        18
                   Harari                                                         121
                   Addis Ababa                                                  15502
                   Dire Dawa                                                      559
                   National                                                     69605
Facility type      Referral/specialized                                          3312
                   General hospitals                                             1080
                   Primary hospitals                                             3533
                   MCH specialized centres                                        285
                   Health centres                                               61292
                   MCH specialty clinics                                           63
                   Higher clinics                                                  40
                   National                                                     69605
Managing authority Public/government                                            68109
                   Private-for-profit                                              93
                   Private-not-for-profit                                        1403
                   National                                                     69605
Location           Urban                                                        47915
                   Rural                                                        21690
                   National                                                     69605

                                               1     2  \
Region             Tigray                    6.0  37.0
                   Afar                      4.0  24.0
                   Amhara                    4.0  33.0
                   Oromia                    3.0  39.0
                   Somali                    3.0  16.0
                   Benishangul-Gumuz         4.0  21.0
                   SNNP                      2.0  31.0
                   Gambella                  1.0   4.0
                   Harari                    2.0   5.0
                   Addis Ababa              15.0  38.0
                   Dire Dawa                 7.0  22.0
                   National                  4.0  35.0
Facility type      Referral/specialized      3.0   8.0
                   General hospitals         1.0   2.0
                   Primary hospitals         3.0  16.0
                   MCH specialized centres   2.0   5.0
                   Health centres            4.0  73.0
                   MCH specialty clinics     2.0   9.0
                   Higher clinics            1.0  23.0
                   National                  4.0  35.0
Managing authority Public/government         4.0  37.0
                   Private-for-profit        0.0   1.0
                   Private-not-for-profit    4.0  24.0
                   National                  4.0  35.0
Location           Urban                     5.0  28.0
                   Rural                     2.0  71.0
                   National                  4.0  35.0

                                            Referrals out due to newborn indications  \
Region             Tigray                                                        701
                   Afar                                                           24
                   Amhara                                                       1194
                   Oromia                                                       1959
                   Somali                                                         67
                   Benishangul-Gumuz                                              40
                   SNNP                                                          756
                   Gambella                                                        2
                   Harari                                                          9
                   Addis Ababa                                                  1438
                   Dire Dawa                                                      41
                   National                                                     6231
Facility type      Referral/specialized                                          385
                   General hospitals                                             336
                   Primary hospitals                                             515
                   MCH specialized centres                                        50
                   Health centres                                               4926
                   MCH specialty clinics                                          17
                   Higher clinics                                                  2
                   National                                                     6231
Managing authority Public/government                                            6040
                   Private-for-profit                                            127
                   Private-not-for-profit                                         64
                   National                                                     6231
Location           Urban                                                        4240
                   Rural                                                        1991
                   National                                                     6231

                                              3
Region             Tigray                   0.6
                   Afar                     0.3
                   Amhara                   0.3
                   Oromia                   0.2
                   Somali                   0.3
                   Benishangul-Gumuz        0.3
                   SNNP                     0.2
                   Gambella                 0.1
                   Harari                   0.1
                   Addis Ababa              1.4
                   Dire Dawa                0.5
                   National                 0.3
Facility type      Referral/specialized     0.4
                   General hospitals        0.3
                   Primary hospitals        0.5
                   MCH specialized centres  0.3
                   Health centres           0.3
                   MCH specialty clinics    0.5
                   Higher clinics           0.1
                   National                 0.3
Managing authority Public/government        0.3
                   Private-for-profit       0.4
                   Private-not-for-profit   0.2
                   National                 0.3
Location           Urban                    0.4
                   Rural                    0.2
                   National                 0.3

In [498]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12hgt.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management and policies for clients referred out and referred in/women with complications who were referred out due to maternal or newborn indications.csv")

In [571]:
functional_motorized_transport = pd.crosstab(data['Q005'], data['transport_motor_any'])
del   functional_motorized_transport[0]
#del   functional_motorized_transport[8]
#del   functional_motorized_transport[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Functional motorized transport']
functional_motorized_transport.columns= labels_of_col[1:]
functional_motorized_transport.index= labels_of_col1[1:]
functional_motorized_transport.columns.names= [labels_of_col[0]]
functional_motorized_transport.index.names= [labels_of_col1[0]]
functional_motorized_transport

                   Functional motorized transport
Region
Tigray                                         99
Afar                                           44
Amhara                                        289
Oromia                                        427
Somali                                         97
Benishangul-Gumuz                              40
SNNP                                          194
Gambella                                        7
Harari                                          9
Addis Ababa                                    64
Dire Dawa                                      15

In [572]:
functional_motorized_transport1 = pd.crosstab(data['Q005'], data['Q522_11'])
del   functional_motorized_transport1[0]
del   functional_motorized_transport1[8]
del   functional_motorized_transport1[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Sufficient fuel to transport client ']
functional_motorized_transport1.columns= labels_of_col[1:]
functional_motorized_transport1.index= labels_of_col1[1:]
functional_motorized_transport1.columns.names= [labels_of_col[0]]
functional_motorized_transport1.index.names= [labels_of_col1[0]]
functional_motorized_transport1

                   Sufficient fuel to transport client
Region
Tigray                                               69
Afar                                                 44
Amhara                                              233
Oromia                                              305
Somali                                               77
Benishangul-Gumuz                                    34
SNNP                                                125
Gambella                                              4
Harari                                                9
Addis Ababa                                          62
Dire Dawa                                            14

In [573]:
functional_motorized_transport2 = pd.crosstab(data['Q005'], data['Q520_11'])
del   functional_motorized_transport2[0]
del   functional_motorized_transport2[8]
del   functional_motorized_transport2[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Sufficient funds for maintenance']
functional_motorized_transport2.columns= labels_of_col[1:]
functional_motorized_transport2.index= labels_of_col1[1:]
functional_motorized_transport2.columns.names= [labels_of_col[0]]
functional_motorized_transport2.index.names= [labels_of_col1[0]]
functional_motorized_transport2

                   Sufficient funds for maintenance
Region
Tigray                                           69
Afar                                             40
Amhara                                          196
Oromia                                          364
Somali                                           58
Benishangul-Gumuz                                34
SNNP                                            135
Gambella                                          5
Harari                                            7
Addis Ababa                                      56
Dire Dawa                                        14

In [574]:
functional_motorized_transport3 = pd.crosstab(data['Q005'], data['Q526_11'])
del   functional_motorized_transport3[0]
del   functional_motorized_transport3[8]
del   functional_motorized_transport3[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Driver on staff']
functional_motorized_transport3.columns= labels_of_col[1:]
functional_motorized_transport3.index= labels_of_col1[1:]
functional_motorized_transport3.columns.names= [labels_of_col[0]]
functional_motorized_transport3.index.names= [labels_of_col1[0]]
functional_motorized_transport3

                   Driver on staff
Region
Tigray                          29
Afar                            15
Amhara                          62
Oromia                          55
Somali                          13
Benishangul-Gumuz               13
SNNP                            44
Gambella                         0
Harari                           1
Addis Ababa                     26
Dire Dawa                        2

In [575]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(functional_motorized_transport,functional_motorized_transport1,functional_motorized_transport2,functional_motorized_transport3)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological376r=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological376r

,Functional motorized transport,Sufficient fuel to transport client,Sufficient funds for maintenance,Driver on staff
Region,,,,
Tigray,99,69,69,29
Afar,44,44,40,15
Amhara,289,233,196,62
Oromia,427,305,364,55
Somali,97,77,58,13
Benishangul-Gumuz,40,34,34,13
SNNP,194,125,135,44
Gambella,7,4,5,0
Harari,9,9,7,1
Addis Ababa,64,62,56,26
Dire Dawa,15,14,14,2

In [576]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological376r.to_csv("C:/Users/user/Desktop/Presentation/Presentation05/Management of vehicles and drivers/Number of facilities with their own functional motorized transport with access toresources for fuel and maintenance and with a driver on staff.csv")

In [35]:
dfsd = pd.DataFrame(data, columns = ['Q005', 'mwh'])
dfsd.replace(0, -999)
Facilities_with_MWH_room0=dfsd.groupby(['Q005']).sum()
labels_of_col1 = ["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of Facilities with a MWH/room']
Facilities_with_MWH_room0.columns= labels_of_col[1:]
Facilities_with_MWH_room0.index= labels_of_col1[1:]
Facilities_with_MWH_room0.columns.names= [labels_of_col[0]]
Facilities_with_MWH_room0.index.names= [labels_of_col1[0]]
fara=pd.DataFrame(data, columns = ['mwh'])
fara['mwh']=np.where(fara['mwh'] ==-999,  np.nan, fara['mwh'])
my_tab1aw= fara['mwh'].sum()
Facilities_with_MWH_room0.loc['National'] = my_tab1aw
Facilities_with_MWH_room0

                   Number of Facilities with a MWH/room
Region
Tigray                                             93.0
Afar                                                5.0
Amhara                                            631.0
Oromia                                            792.0
Somali                                             11.0
Benishangul-Gumuz                                  11.0
SNNP                                              444.0
Gambella                                            0.0
Harari                                              1.0
Addis Ababa                                        11.0
Dire Dawa                                           2.0
National                                         2001.0

In [14]:
my_tab = pd.crosstab(data['Q005'], data['mwh'])
Facilities_with_MWH_room1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_with_MWH_room1[0]
#del Facilities_with_MWH_room1[2]
#del Facilities_with_MWH_room1[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'percentage of Facilities with a MWH/room']
Facilities_with_MWH_room1.columns= labels_of_col[1:]
Facilities_with_MWH_room1.index= labels_of_col1[1:]
Facilities_with_MWH_room1.columns.names= [labels_of_col[0]]
Facilities_with_MWH_room1.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['mwh'], data['mwh'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Facilities_with_MWH_room1.loc['National'] = cc
Facilities_with_MWH_room1

                   percentage of Facilities with a MWH/room
Region
Tigray                                                 36.0
Afar                                                    6.0
Amhara                                                 72.0
Oromia                                                 56.0
Somali                                                  7.0
Benishangul-Gumuz                                      26.0
SNNP                                                   57.0
Gambella                                                0.0
Harari                                                  7.0
Addis Ababa                                             7.0
Dire Dawa                                              10.0
National                                               53.0

In [15]:
my_tab = pd.crosstab(data['Q005'], data['Q101_12']==2)
Facilities_with_MWH_room2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_with_MWH_room2[0]
#del Facilities_with_MWH_room2[2]
#del Facilities_with_MWH_room2[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'%Facilities with a stand alone MWH']
Facilities_with_MWH_room2.columns= labels_of_col[1:]
Facilities_with_MWH_room2.index= labels_of_col1[1:]
Facilities_with_MWH_room2.columns.names= [labels_of_col[0]]
Facilities_with_MWH_room2.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q101_12']==2, data['Q101_12']==2)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Facilities_with_MWH_room2.loc['National'] = cc
Facilities_with_MWH_room2

                   %Facilities with a stand alone MWH
Region
Tigray                                            9.0
Afar                                              1.0
Amhara                                           24.0
Oromia                                           23.0
Somali                                            3.0
Benishangul-Gumuz                                 0.0
SNNP                                             26.0
Gambella                                          0.0
Harari                                            0.0
Addis Ababa                                       1.0
Dire Dawa                                         0.0
National                                         20.0

In [16]:
my_tab = pd.crosstab(data['Q005'], data['Q101_12'])
Facilities_with_MWH_room3 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_with_MWH_room3[0]
del Facilities_with_MWH_room3[2]
#del Facilities_with_MWH_room3[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'%Facilities with a maternity waiting room']
Facilities_with_MWH_room3.columns= labels_of_col[1:]
Facilities_with_MWH_room3.index= labels_of_col1[1:]
Facilities_with_MWH_room3.columns.names= [labels_of_col[0]]
Facilities_with_MWH_room3.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q101_12'], data['Q101_12'])
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Facilities_with_MWH_room3.loc['National'] = cc
Facilities_with_MWH_room3

                   %Facilities with a maternity waiting room
Region
Tigray                                                  27.0
Afar                                                     5.0
Amhara                                                  48.0
Oromia                                                  33.0
Somali                                                   4.0
Benishangul-Gumuz                                       26.0
SNNP                                                    32.0
Gambella                                                 0.0
Harari                                                   7.0
Addis Ababa                                              7.0
Dire Dawa                                               10.0
National                                                32.0

In [17]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Facilities_with_MWH_room0,Facilities_with_MWH_room1,Facilities_with_MWH_room2,Facilities_with_MWH_room3)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase

,Number of Facilities with a MWH/room,percentage of Facilities with a MWH/room,%Facilities with a stand alone MWH,%Facilities with a maternity waiting room
Region,,,,
Tigray,93.0,36.0,9.0,27.0
Afar,5.0,6.0,1.0,5.0
Amhara,631.0,72.0,24.0,48.0
Oromia,792.0,56.0,23.0,33.0
Somali,11.0,7.0,3.0,4.0
Benishangul-Gumuz,11.0,26.0,0.0,26.0
SNNP,444.0,57.0,26.0,32.0
Gambella,0.0,0.0,0.0,0.0
Harari,1.0,7.0,0.0,7.0
Addis Ababa,11.0,7.0,1.0,7.0
Dire Dawa,2.0,10.0,0.0,10.0
National,2001.0,53.0,20.0,32.0

In [18]:
dfsd = pd.DataFrame(data, columns = ['FT7', 'mwh'])
dfsd.replace(0, -999)
Facilities_type_with_MWH_room0=dfsd.groupby(['FT7']).sum()
labels_of_col1 = ["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of Facilities with a MWH/room']
Facilities_type_with_MWH_room0.columns= labels_of_col[1:]
Facilities_type_with_MWH_room0.index= labels_of_col1[1:]
Facilities_type_with_MWH_room0.columns.names= [labels_of_col[0]]
Facilities_type_with_MWH_room0.index.names= [labels_of_col1[0]]
Facilities_type_with_MWH_room0
my_tab = pd.crosstab(data['FT7'], data['mwh'])
Facilities_type_with_MWH_room1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_type_with_MWH_room1[0]
#del Facilities_type_with_MWH_room1[2]
#del Facilities_type_with_MWH_room1[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'percentage of Facilities with a MWH/room']
Facilities_type_with_MWH_room1.columns= labels_of_col[1:]
Facilities_type_with_MWH_room1.index= labels_of_col1[1:]
Facilities_type_with_MWH_room1.columns.names= [labels_of_col[0]]
Facilities_type_with_MWH_room1.index.names= [labels_of_col1[0]]
Facilities_type_with_MWH_room1
my_tab = pd.crosstab(data['FT7'], data['Q101_12']==2)
Facilities_type_with_MWH_room2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_type_with_MWH_room2[0]
#del Facilities_type_with_MWH_room2[2]
#del Facilities_type_with_MWH_room2[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'%Facilities with a stand alone MWH']
Facilities_type_with_MWH_room2.columns= labels_of_col[1:]
Facilities_type_with_MWH_room2.index= labels_of_col1[1:]
Facilities_type_with_MWH_room2.columns.names= [labels_of_col[0]]
Facilities_type_with_MWH_room2.index.names= [labels_of_col1[0]]
Facilities_type_with_MWH_room2
my_tab = pd.crosstab(data['FT7'], data['Q101_12'])
Facilities_type_with_MWH_room3 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Facilities_type_with_MWH_room3[0]
del Facilities_type_with_MWH_room3[2]
#del Facilities_type_with_MWH_room3[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'%Facilities with a maternity waiting room']
Facilities_type_with_MWH_room3.columns= labels_of_col[1:]
Facilities_type_with_MWH_room3.index= labels_of_col1[1:]
Facilities_type_with_MWH_room3.columns.names= [labels_of_col[0]]
Facilities_type_with_MWH_room3.index.names= [labels_of_col1[0]]
Facilities_type_with_MWH_room3
Percent_of_Facilities_type_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Facilities_type_with_MWH_room0,Facilities_type_with_MWH_room1,Facilities_type_with_MWH_room2,Facilities_type_with_MWH_room3)
Percent_of_Facilities_type_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase=pd.concat( Percent_of_Facilities_type_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_Facilities_type_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase

,Number of Facilities with a MWH/room,percentage of Facilities with a MWH/room,%Facilities with a stand alone MWH,%Facilities with a maternity waiting room
Facility,,,,
Referral/specialized,0,0.0,0.0,0.0
General hospitals,15,15.0,7.0,8.0
Primary hospitals,43,27.0,8.0,19.0
MCH specialized centres,0,0.0,0.0,0.0
Health centres,1943,56.0,22.0,35.0
MCH specialty clinics,0,0.0,0.0,0.0
Higher clinics,0,0.0,0.0,0.0

In [19]:
dfsd = pd.DataFrame(data, columns = ['MA3', 'mwh'])
dfsd.replace(0, -999)
Managing_authority_with_MWH_room0=dfsd.groupby(['MA3']).sum()
labels_of_col1 = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of Facilities with a MWH/room']
Managing_authority_with_MWH_room0.columns= labels_of_col[1:]
Managing_authority_with_MWH_room0.index= labels_of_col1[1:]
Managing_authority_with_MWH_room0.columns.names= [labels_of_col[0]]
Managing_authority_with_MWH_room0.index.names= [labels_of_col1[0]]
Managing_authority_with_MWH_room0
my_tab = pd.crosstab(data['MA3'], data['mwh'])
Managing_authority_with_MWH_room1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Managing_authority_with_MWH_room1[0]
#del Managing_authority_with_MWH_room1[2]
#del Managing_authority_with_MWH_room1[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'percentage of Facilities with a MWH/room']
Managing_authority_with_MWH_room1.columns= labels_of_col[1:]
Managing_authority_with_MWH_room1.index= labels_of_col1[1:]
Managing_authority_with_MWH_room1.columns.names= [labels_of_col[0]]
Managing_authority_with_MWH_room1.index.names= [labels_of_col1[0]]
Managing_authority_with_MWH_room1
my_tab = pd.crosstab(data['MA3'], data['Q101_12']==2)
Managing_authority_with_MWH_room2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Managing_authority_with_MWH_room2[0]
#del Managing_authority_with_MWH_room2[2]
#del Managing_authority_with_MWH_room2[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'%Facilities with a stand alone MWH']
Managing_authority_with_MWH_room2.columns= labels_of_col[1:]
Managing_authority_with_MWH_room2.index= labels_of_col1[1:]
Managing_authority_with_MWH_room2.columns.names= [labels_of_col[0]]
Managing_authority_with_MWH_room2.index.names= [labels_of_col1[0]]
Managing_authority_with_MWH_room2
my_tab = pd.crosstab(data['MA3'], data['Q101_12'])
Managing_authority_with_MWH_room3 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Managing_authority_with_MWH_room3[0]
del Managing_authority_with_MWH_room3[2]
#del Managing_authority_with_MWH_room3[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'%Facilities with a maternity waiting room']
Managing_authority_with_MWH_room3.columns= labels_of_col[1:]
Managing_authority_with_MWH_room3.index= labels_of_col1[1:]
Managing_authority_with_MWH_room3.columns.names= [labels_of_col[0]]
Managing_authority_with_MWH_room3.index.names= [labels_of_col1[0]]
Managing_authority_with_MWH_room3
Percent_of_Managing_authority_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Managing_authority_with_MWH_room0,Managing_authority_with_MWH_room1,Managing_authority_with_MWH_room2,Managing_authority_with_MWH_room3)
Percent_of_Managing_authority_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase=pd.concat( Percent_of_Managing_authority_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_Managing_authority_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase

,Number of Facilities with a MWH/room,percentage of Facilities with a MWH/room,%Facilities with a stand alone MWH,%Facilities with a maternity waiting room
Managing_authority,,,,
Public/government,1984,54.0,21.0,33.0
Private-for-profit,0,0.0,0.0,0.0
Private-not-for-profit,17,29.0,12.0,17.0

In [20]:
dfsd = pd.DataFrame(data, columns = ['Q009', 'mwh'])
dfsd.replace(0, -999)
Location_with_MWH_room0=dfsd.groupby(['Q009']).sum()
labels_of_col1 = ["Location","Urban" , "Rural"]
labels_of_col = ["",'Number of Facilities with a MWH/room']
Location_with_MWH_room0.columns= labels_of_col[1:]
Location_with_MWH_room0.index= labels_of_col1[1:]
Location_with_MWH_room0.columns.names= [labels_of_col[0]]
Location_with_MWH_room0.index.names= [labels_of_col1[0]]
Location_with_MWH_room0
my_tab = pd.crosstab(data['Q009'], data['mwh'])
Location_with_MWH_room1 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Location_with_MWH_room1[0]
#del Location_with_MWH_room1[2]
#del Location_with_MWH_room1[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'percentage of Facilities with a MWH/room']
Location_with_MWH_room1.columns= labels_of_col[1:]
Location_with_MWH_room1.index= labels_of_col1[1:]
Location_with_MWH_room1.columns.names= [labels_of_col[0]]
Location_with_MWH_room1.index.names= [labels_of_col1[0]]
Location_with_MWH_room1
my_tab = pd.crosstab(data['Q009'], data['Q101_12']==2)
Location_with_MWH_room2 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Location_with_MWH_room2[0]
#del Location_with_MWH_room2[2]
#del Location_with_MWH_room2[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'%Facilities with a stand alone MWH']
Location_with_MWH_room2.columns= labels_of_col[1:]
Location_with_MWH_room2.index= labels_of_col1[1:]
Location_with_MWH_room2.columns.names= [labels_of_col[0]]
Location_with_MWH_room2.index.names= [labels_of_col1[0]]
Location_with_MWH_room2
my_tab = pd.crosstab(data['Q009'], data['Q101_12'])
Location_with_MWH_room3 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Location_with_MWH_room3[0]
del Location_with_MWH_room3[2]
#del Location_with_MWH_room3[-999]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'%Facilities with a maternity waiting room']
Location_with_MWH_room3.columns= labels_of_col[1:]
Location_with_MWH_room3.index= labels_of_col1[1:]
Location_with_MWH_room3.columns.names= [labels_of_col[0]]
Location_with_MWH_room3.index.names= [labels_of_col1[0]]
Location_with_MWH_room3
Percent_of_Location_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Location_with_MWH_room0,Location_with_MWH_room1,Location_with_MWH_room2,Location_with_MWH_room3)
Percent_of_Location_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase=pd.concat( Percent_of_Location_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Percent_of_Location_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase

,Number of Facilities with a MWH/room,percentage of Facilities with a MWH/room,%Facilities with a stand alone MWH,%Facilities with a maternity waiting room
Location,,,,
Urban,724,48.0,19.0,29.0
Rural,1277,55.0,21.0,35.0

In [21]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase,Percent_of_Facilities_type_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase,Percent_of_Managing_authority_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase,Percent_of_Location_with_delivery_sets_dressing_instrument_sets_Labour_deliveryeeeooase)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12krte=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Region','Facility type','Managing authority','Location'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12krte

                                            Number of Facilities with a MWH/room  \
Region             Tigray                                                   93.0
                   Afar                                                      5.0
                   Amhara                                                  631.0
                   Oromia                                                  792.0
                   Somali                                                   11.0
                   Benishangul-Gumuz                                        11.0
                   SNNP                                                    444.0
                   Gambella                                                  0.0
                   Harari                                                    1.0
                   Addis Ababa                                              11.0
                   Dire Dawa                                                 2.0
                   National                                               2001.0
Facility type      Referral/specialized                                      0.0
                   General hospitals                                        15.0
                   Primary hospitals                                        43.0
                   MCH specialized centres                                   0.0
                   Health centres                                         1943.0
                   MCH specialty clinics                                     0.0
                   Higher clinics                                            0.0
Managing authority Public/government                                      1984.0
                   Private-for-profit                                        0.0
                   Private-not-for-profit                                   17.0
Location           Urban                                                   724.0
                   Rural                                                  1277.0

                                            percentage of Facilities with a MWH/room  \
Region             Tigray                                                       36.0
                   Afar                                                          6.0
                   Amhara                                                       72.0
                   Oromia                                                       56.0
                   Somali                                                        7.0
                   Benishangul-Gumuz                                            26.0
                   SNNP                                                         57.0
                   Gambella                                                      0.0
                   Harari                                                        7.0
                   Addis Ababa                                                   7.0
                   Dire Dawa                                                    10.0
                   National                                                     53.0
Facility type      Referral/specialized                                          0.0
                   General hospitals                                            15.0
                   Primary hospitals                                            27.0
                   MCH specialized centres                                       0.0
                   Health centres                                               56.0
                   MCH specialty clinics                                         0.0
                   Higher clinics                                                0.0
Managing authority Public/government                                            54.0
                   Private-for-profit                                            0.0
                   Private-not-for-profit                                       29.0
Location           Urban                                                        48.0
                   Rural                                                        55.0

                                            %Facilities with a stand alone MWH  \
Region             Tigray                                                  9.0
                   Afar                                                    1.0
                   Amhara                                                 24.0
                   Oromia                                                 23.0
                   Somali                                                  3.0
                   Benishangul-Gumuz                                       0.0
                   SNNP                                                   26.0
                   Gambella                                                0.0
                   Harari                                                  0.0
                   Addis Ababa                                             1.0
                   Dire Dawa                                               0.0
                   National                                               20.0
Facility type      Referral/specialized                                    0.0
                   General hospitals                                       7.0
                   Primary hospitals                                       8.0
                   MCH specialized centres                                 0.0
                   Health centres                                         22.0
                   MCH specialty clinics                                   0.0
                   Higher clinics                                          0.0
Managing authority Public/government                                      21.0
                   Private-for-profit                                      0.0
                   Private-not-for-profit                                 12.0
Location           Urban                                                  19.0
                   Rural                                                  21.0

                                            %Facilities with a maternity waiting room
Region             Tigray                                                        27.0
                   Afar                                                           5.0
                   Amhara                                                        48.0
                   Oromia                                                        33.0
                   Somali                                                         4.0
                   Benishangul-Gumuz                                             26.0
                   SNNP                                                          32.0
                   Gambella                                                       0.0
                   Harari                                                         7.0
                   Addis Ababa                                                    7.0
                   Dire Dawa                                                     10.0
                   National                                                      32.0
Facility type      Referral/specialized                                           0.0
                   General hospitals                                              8.0
                   Primary hospitals                                             19.0
                   MCH specialized centres                                        0.0
                   Health centres                                                35.0
                   MCH specialty clinics                                          0.0
                   Higher clinics                                                 0.0
Managing authority Public/government                                             33.0
                   Private-for-profit                                             0.0
                   Private-not-for-profit                                        17.0
Location           Urban                                                         29.0
                   Rural                                                         35.0

In [27]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12krte.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Infrastructure, support, and services/Percent of facilities with a MWH room.csv")

In [252]:
my_tab = pd.crosstab(data['Q005'], data['Q105_8_1']!=-999)
Per_Comes_on_automatically_when_needed_Region21 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Region21[0]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Percent of facilities where caesareans were reviewed']
Per_Comes_on_automatically_when_needed_Region21.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Region21.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Region21.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Region21.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q105_8_1']!=-999, data['Q105_8_1']!=-999)
b = len(data.loc[((data['Q005']))])
my_tab1 = ((my_tab1[1][1])/b)*100
cc= round((my_tab1),0)
Per_Comes_on_automatically_when_needed_Region21.loc['National'] = cc
Per_Comes_on_automatically_when_needed_Region21

                   Percent of facilities where caesareans were reviewed
Region
Tigray                                                          15.0
Afar                                                             9.0
Amhara                                                           5.0
Oromia                                                           5.0
Somali                                                           6.0
Benishangul-Gumuz                                                5.0
SNNP                                                             7.0
Gambella                                                         4.0
Harari                                                          40.0
Addis Ababa                                                     32.0
Dire Dawa                                                       29.0
National                                                         8.0

In [260]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22 = pd.crosstab(data['Q005'], data['Q105_8_2']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities where two timecaesareans were reviewed']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q105_8_2']!=-999, data['Q105_8_2']!=-999)
b = 1
my_tab1 = ((my_tab1[1][1])/b)
cc= round((my_tab1),0)
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.loc['National'] = cc
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22.loc['National'] = my_tab1
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22

                   Number of facilities where two timecaesareans were reviewed
Region
Tigray                                                          36.0
Afar                                                             6.0
Amhara                                                          46.0
Oromia                                                          71.0
Somali                                                          10.0
Benishangul-Gumuz                                                2.0
SNNP                                                            49.0
Gambella                                                         1.0
Harari                                                           6.0
Addis Ababa                                                     47.0
Dire Dawa                                                        6.0
National                                                       280.0

In [261]:
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23 = pd.crosstab(data['Q005'], data['Q105_8_1']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23[-999]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.index.names= [labels_of_col1[0]]
my_tab1 = pd.crosstab(data['Q105_8_1']!=-999, data['Q105_8_1']!=-999)
b = 1
my_tab1 = ((my_tab1[1][1])/b)
cc= round((my_tab1),0)
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.loc['National'] = cc
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23.loc['National'] = my_tab1
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23

                   Number of facilities with a water source
Region
Tigray                                                 38.0
Afar                                                    7.0
Amhara                                                 47.0
Oromia                                                 72.0
Somali                                                 10.0
Benishangul-Gumuz                                       2.0
SNNP                                                   51.0
Gambella                                                1.0
Harari                                                  6.0
Addis Ababa                                            48.0
Dire Dawa                                               6.0
National                                              288.0

In [267]:
Region1 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23["Number of facilities with a water source"]-Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22["Number of facilities where two timecaesareans were reviewed"]
Region1

Region
Tigray               2.0
Afar                 1.0
Amhara               1.0
Oromia               1.0
Somali               0.0
Benishangul-Gumuz    0.0
SNNP                 2.0
Gambella             0.0
Harari               0.0
Addis Ababa          1.0
Dire Dawa            0.0
National             8.0
dtype: float64

In [269]:
Region2 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22["Number of facilities where two timecaesareans were reviewed"] + Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region23["Number of facilities with a water source"]
Region2

Region
Tigray                74.0
Afar                  13.0
Amhara                93.0
Oromia               143.0
Somali                20.0
Benishangul-Gumuz      4.0
SNNP                 100.0
Gambella               2.0
Harari                12.0
Addis Ababa           95.0
Dire Dawa             12.0
National             568.0
dtype: float64

In [273]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Per_Comes_on_automatically_when_needed_Region21,Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Region22,Region1,Region2)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3

,Percent of facilities where caesareans were reviewed,Number of facilities where two timecaesareans were reviewed,0,1
Region,,,,
Tigray,15.0,36.0,2.0,74.0
Afar,9.0,6.0,1.0,13.0
Amhara,5.0,46.0,1.0,93.0
Oromia,5.0,71.0,1.0,143.0
Somali,6.0,10.0,0.0,20.0
Benishangul-Gumuz,5.0,2.0,0.0,4.0
SNNP,7.0,49.0,2.0,100.0
Gambella,4.0,1.0,0.0,2.0
Harari,40.0,6.0,0.0,12.0
Addis Ababa,32.0,47.0,1.0,95.0
Dire Dawa,29.0,6.0,0.0,12.0
National,8.0,280.0,8.0,568.0

In [274]:
my_tab = pd.crosstab(data['FT7'], data['Q105_8_1']!=-999)
Per_Comes_on_automatically_when_needed_Facility21 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Facility21[0]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Percent of facilities where caesareans were reviewed']
Per_Comes_on_automatically_when_needed_Facility21.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Facility21.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Facility21.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Facility21.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22 = pd.crosstab(data['FT7'], data['Q105_8_2']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities where two timecaesareans were reviewed']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23 = pd.crosstab(data['FT7'], data['Q105_8_1']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[-999]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index.names= [labels_of_col1[0]]
Facility1 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]-Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"]
Facility2 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"] + Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Per_Comes_on_automatically_when_needed_Facility21,Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22,Facility1,Facility2)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3010=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3010

,Percent of facilities where caesareans were reviewed,Number of facilities where two timecaesareans were reviewed,0,1
Facility,,,,
Referral/specialized,100.0,30,0,60
General hospitals,96.0,97,2,196
Primary hospitals,73.0,112,5,229
MCH specialized centres,74.0,17,0,34
Health centres,1.0,17,1,35
MCH specialty clinics,31.0,5,0,10
Higher clinics,15.0,2,0,4

In [275]:
my_tab = pd.crosstab(data['MA3'], data['Q105_8_1']!=-999)
Per_Comes_on_automatically_when_needed_Facility21 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Facility21[0]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Percent of facilities where caesareans were reviewed']
Per_Comes_on_automatically_when_needed_Facility21.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Facility21.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Facility21.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Facility21.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22 = pd.crosstab(data['MA3'], data['Q105_8_2']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities where two timecaesareans were reviewed']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23 = pd.crosstab(data['MA3'], data['Q105_8_1']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[-999]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index.names= [labels_of_col1[0]]
Facility1 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]-Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"]
Facility2 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"] + Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Per_Comes_on_automatically_when_needed_Facility21,Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22,Facility1,Facility2)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3011=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3011

,Percent of facilities where caesareans were reviewed,Number of facilities where two timecaesareans were reviewed,0,1
Managing_authority,,,,
Public/government,6.0,201,7,409
Private-for-profit,77.0,63,1,127
Private-not-for-profit,27.0,16,0,32

In [280]:
my_tab = pd.crosstab(data['emonc3'], data['Q105_8_1']!=-999)
Per_Comes_on_automatically_when_needed_Facility21 = round((my_tab.div(my_tab.sum(axis=1), axis=0) * 100),0)
del Per_Comes_on_automatically_when_needed_Facility21[0]
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Percent of facilities where caesareans were reviewed']
Per_Comes_on_automatically_when_needed_Facility21.columns= labels_of_col[1:]
Per_Comes_on_automatically_when_needed_Facility21.index= labels_of_col1[1:]
Per_Comes_on_automatically_when_needed_Facility21.columns.names= [labels_of_col[0]]
Per_Comes_on_automatically_when_needed_Facility21.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22 = pd.crosstab(data['emonc3'], data['Q105_8_2']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22[-999]
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Number of facilities where two timecaesareans were reviewed']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22.index.names= [labels_of_col1[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23 = pd.crosstab(data['emonc3'], data['Q105_8_1']!=-999)
del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[0]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[8]
#del  Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23[-999]
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Number of facilities with a water source']
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns= labels_of_col[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index= labels_of_col1[1:]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.columns.names= [labels_of_col[0]]
Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23.index.names= [labels_of_col1[0]]
Facility1 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]-Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"]
Facility2 = Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22["Number of facilities where two timecaesareans were reviewed"] + Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility23["Number of facilities with a water source"]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4=(Per_Comes_on_automatically_when_needed_Facility21,Percent_distribution_of_facilities_according_to_their_primary_source_of_water_by_Facility22,Facility1,Facility2)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3012=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological_4, axis=1, sort=False)
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3012

,Percent of facilities where caesareans were reviewed,Number of facilities where two timecaesareans were reviewed,0,1
EmONC classification,,,,
CEmONC,96.0,142,0,284
BEmONC,15.0,32,2,66
Partially functioning,3.0,106,6,218

In [281]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3010,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3011,Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_and_gynaecological3012)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Region','Facility type','Managing authority','EmONC classification'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl

                                              Percent of facilities where caesareans were reviewed  \
Region               Tigray                                                                15.0
                     Afar                                                                   9.0
                     Amhara                                                                 5.0
                     Oromia                                                                 5.0
                     Somali                                                                 6.0
                     Benishangul-Gumuz                                                      5.0
                     SNNP                                                                   7.0
                     Gambella                                                               4.0
                     Harari                                                                40.0
                     Addis Ababa                                                           32.0
                     Dire Dawa                                                             29.0
                     National                                                               8.0
Facility type        Referral/specialized                                                 100.0
                     General hospitals                                                     96.0
                     Primary hospitals                                                     73.0
                     MCH specialized centres                                               74.0
                     Health centres                                                         1.0
                     MCH specialty clinics                                                 31.0
                     Higher clinics                                                        15.0
Managing authority   CEmONC                                                                96.0
                     BEmONC                                                                15.0
                     Partially functioning                                                  3.0
EmONC classification CEmONC                                                                96.0
                     BEmONC                                                                15.0
                     Partially functioning                                                  3.0

                                              Number of facilities where two timecaesareans were reviewed  \
Region               Tigray                                                                36.0
                     Afar                                                                   6.0
                     Amhara                                                                46.0
                     Oromia                                                                71.0
                     Somali                                                                10.0
                     Benishangul-Gumuz                                                      2.0
                     SNNP                                                                  49.0
                     Gambella                                                               1.0
                     Harari                                                                 6.0
                     Addis Ababa                                                           47.0
                     Dire Dawa                                                              6.0
                     National                                                             280.0
Facility type        Referral/specialized                                                  30.0
                     General hospitals                                                     97.0
                     Primary hospitals                                                    112.0
                     MCH specialized centres                                               17.0
                     Health centres                                                        17.0
                     MCH specialty clinics                                                  5.0
                     Higher clinics                                                         2.0
Managing authority   CEmONC                                                               142.0
                     BEmONC                                                                32.0
                     Partially functioning                                                106.0
EmONC classification CEmONC                                                               142.0
                     BEmONC                                                                32.0
                     Partially functioning                                                106.0

                                                0      1
Region               Tigray                   2.0   74.0
                     Afar                     1.0   13.0
                     Amhara                   1.0   93.0
                     Oromia                   1.0  143.0
                     Somali                   0.0   20.0
                     Benishangul-Gumuz        0.0    4.0
                     SNNP                     2.0  100.0
                     Gambella                 0.0    2.0
                     Harari                   0.0   12.0
                     Addis Ababa              1.0   95.0
                     Dire Dawa                0.0   12.0
                     National                 8.0  568.0
Facility type        Referral/specialized     0.0   60.0
                     General hospitals        2.0  196.0
                     Primary hospitals        5.0  229.0
                     MCH specialized centres  0.0   34.0
                     Health centres           1.0   35.0
                     MCH specialty clinics    0.0   10.0
                     Higher clinics           0.0    4.0
Managing authority   CEmONC                   0.0  284.0
                     BEmONC                   2.0   66.0
                     Partially functioning    6.0  218.0
EmONC classification CEmONC                   0.0  284.0
                     BEmONC                   2.0   66.0
                     Partially functioning    6.0  218.0

In [283]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Caesarean delivery reviews/Percent of facilities where caesarean deliveries were reviewed, number of facilities with 1 or 2 cases, and total number of cases reviewed.csv")

In [922]:
deno=568
zaree_N=data.loc[((data['Q104_8_1']==1))]
zaree_D=data.loc[((data['Q104_8_2']==1))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare1  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Spontaneous']
zare1 .index= labels_of_col1[1:]
zare1 .index.names= [labels_of_col1[0]]
zare1

             Percent of caesareans reviewed
\t
Spontaneous                            61.0

In [923]:
zaree_N=data.loc[((data['Q104_8_1']==2))]
zaree_D=data.loc[((data['Q104_8_2']==2))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare2  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Induced']
zare2 .index= labels_of_col1[1:]
zare2 .index.names= [labels_of_col1[0]]
zare2

         Percent of caesareans reviewed
\t
Induced                             6.0

In [924]:
zaree_N=data.loc[((data['Q104_8_1']==3))]
zaree_D=data.loc[((data['Q104_8_2']==3))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare3  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Caesarean before labour']
zare3 .index= labels_of_col1[1:]
zare3 .index.names= [labels_of_col1[0]]
zare3

                         Percent of caesareans reviewed
\t
Caesarean before labour                            23.0

In [925]:
zaree_N=data.loc[((data['Q104_8_1']==9))]
zaree_D=data.loc[((data['Q104_8_2']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare4  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare4 .index= labels_of_col1[1:]
zare4 .index.names= [labels_of_col1[0]]
zare4

                Percent of caesareans reviewed
\t
No information                             9.0

In [926]:
gtr_4=(zare1,zare2,zare3,zare4)
gol=pd.concat( gtr_4, axis=0, sort=False)
gol

                         Percent of caesareans reviewed
\t
Spontaneous                                        61.0
Induced                                             6.0
Caesarean before labour                            23.0
No information                                      9.0

In [927]:
zaree_N=data.loc[((data['Q105_8_1']==1)) | ((data['Q105_8_1']==9))]
zaree_D=data.loc[((data['Q105_8_2']==1)) | ((data['Q105_8_2']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Emergency']
zare41 .index= labels_of_col1[1:]
zare41 .index.names= [labels_of_col1[0]]
zare41

           Percent of caesareans reviewed
\t
Emergency                            84.0

In [928]:
zaree_N=data.loc[((data['Q105_8_1']==2)) | ((data['Q105_8_1']==9)) & ((data['Q105_8_2']==2)) | ((data['Q105_8_2']==9))]
zaree_1=(len( zaree_N))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare42  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Elective']
zare42 .index= labels_of_col1[1:]
zare42 .index.names= [labels_of_col1[0]]
zare42

          Percent of caesareans reviewed
\t
Elective                            12.0

In [929]:
zaree_N=data.loc[((data['Q105_8_1']==9)) | ((data['Q105_8_2']==9))]
zaree_1=(len( zaree_N))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare43  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare43 .index= labels_of_col1[1:]
zare43 .index.names= [labels_of_col1[0]]
zare43

                Percent of caesareans reviewed
\t
No information                             6.0

In [930]:
gtr_4=(zare41,zare42,zare43)
gol1=pd.concat( gtr_4, axis=0, sort=False)
gol1

                Percent of caesareans reviewed
\t
Emergency                                 84.0
Elective                                  12.0
No information                             6.0

In [931]:
zaree_N=data.loc[((data['Q116_8_1']==1))]
zaree_D=data.loc[((data['Q116_8_2']==1))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare411  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Partograph used']
zare411 .index= labels_of_col1[1:]
zare411 .index.names= [labels_of_col1[0]]
zare411

                 Percent of caesareans reviewed
\t
Partograph used                            31.0

In [932]:
zaree_N=data.loc[((data['Q116_8_1']==2))]
zaree_D=data.loc[((data['Q116_8_2']==2))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare412  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Partograph not used']
zare412 .index= labels_of_col1[1:]
zare412 .index.names= [labels_of_col1[0]]
zare412

                     Percent of caesareans reviewed
\t
Partograph not used                            52.0

In [933]:
zaree_N=data.loc[((data['Q116_8_1']==0))]
zaree_D=data.loc[((data['Q116_8_2']==0))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare413  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Partograph not used because considered elective but went into labour']
zare413 .index= labels_of_col1[1:]
zare413 .index.names= [labels_of_col1[0]]
zare413

                                                    Percent of caesareans reviewed
\t
Partograph not used because considered elective...                            12.0

In [934]:
zaree_N=data.loc[((data['Q116_8_1']==9))]
zaree_D=data.loc[((data['Q116_8_2']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare414  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare414 .index= labels_of_col1[1:]
zare414 .index.names= [labels_of_col1[0]]
zare414

                Percent of caesareans reviewed
\t
No information                             5.0

In [935]:
gtr_4=(zare411,zare412,zare413,zare414)
gol2=pd.concat( gtr_4, axis=0, sort=False)
gol2

                                                    Percent of caesareans reviewed
\t
Partograph used                                                               31.0
Partograph not used                                                           52.0
Partograph not used because considered elective...                            12.0
No information                                                                 5.0

In [936]:
zaree_N=data.loc[((data['Q107_8_1']==1))]
zaree_D=data.loc[((data['Q107_8_2']==1))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare4140  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Cephalic']
zare4140 .index= labels_of_col1[1:]
zare4140 .index.names= [labels_of_col1[0]]
zare4140

          Percent of caesareans reviewed
\t
Cephalic                            67.0

In [937]:
zaree_N=data.loc[((data['Q107_8_1']==2))]
zaree_D=data.loc[((data['Q107_8_2']==2))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare4141  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Breech']
zare4141 .index= labels_of_col1[1:]
zare4141 .index.names= [labels_of_col1[0]]
zare4141

        Percent of caesareans reviewed
\t
Breech                            10.0

In [938]:
zaree_N=data.loc[((data['Q107_8_1']==3))]
zaree_D=data.loc[((data['Q107_8_2']==3))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare4142  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Transversal or oblique']
zare4142 .index= labels_of_col1[1:]
zare4142 .index.names= [labels_of_col1[0]]
zare4142

                        Percent of caesareans reviewed
\t
Transversal or oblique                             7.0

In [939]:
zaree_N=data.loc[((data['Q107_8_1']==9))]
zaree_D=data.loc[((data['Q107_8_2']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare4143  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare4143 .index= labels_of_col1[1:]
zare4143 .index.names= [labels_of_col1[0]]
zare4143

                Percent of caesareans reviewed
\t
No information                            17.0

In [940]:
gtr_4=(zare4140,zare4141,zare4142,zare414)
gol3=pd.concat( gtr_4, axis=0, sort=False)
gol3

                        Percent of caesareans reviewed
\t
Cephalic                                          67.0
Breech                                            10.0
Transversal or oblique                             7.0
No information                                     5.0

In [941]:
zaree_N=data.loc[((data['Q108_8_1']==1))]
zaree_D=data.loc[((data['Q108_8_2']==1)) | ((data['Q108_8_1']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare401  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Singleton']
zare401 .index= labels_of_col1[1:]
zare401 .index.names= [labels_of_col1[0]]
zare401

           Percent of caesareans reviewed
\t
Singleton                            90.0

In [942]:
zaree_N=data.loc[((data['Q108_8_1']==2))]
zaree_D=data.loc[((data['Q108_8_2']==2))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare402  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Multiple']
zare402 .index= labels_of_col1[1:]
zare402 .index.names= [labels_of_col1[0]]
zare402

          Percent of caesareans reviewed
\t
Multiple                             7.0

In [943]:
zaree_N=data.loc[((data['Q108_8_1']==9))]
zaree_D=data.loc[((data['Q108_8_2']==9))]
zaree_1=(len( zaree_N)+(len( zaree_D)))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare403  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare403 .index= labels_of_col1[1:]
zare403 .index.names= [labels_of_col1[0]]
zare403

                Percent of caesareans reviewed
\t
No information                             3.0

In [944]:
gtr_4=(zare401,zare402,zare403)
gol41=pd.concat( gtr_4, axis=0, sort=False)
gol41

                Percent of caesareans reviewed
\t
Singleton                                 90.0
Multiple                                   7.0
No information                             3.0

In [945]:
zaree_N=data.loc[((data['Q110_8_1']==0) | (data['Q110_8_1']==99))]
zaree_D=data.loc[((data['Q110_8_1']==0) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==0))]
zaree_1=(len(zaree_N)+(len(zaree_D)))
zaree=round(((zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41a  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'zero']
zare41a .index= labels_of_col1[1:]
zare41a .index.names= [labels_of_col1[0]]
zare41a

      Percent of caesareans reviewed
\t
zero                            28.0

In [946]:
zaree_N=data.loc[(data['Q110_8_1']==99)]
zaree_D=data.loc[((data['Q110_8_2']==1))]
zaree_1=(len(zaree_N)+(len(zaree_D)))
zaree=round(((zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41b  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'one']
zare41b .index= labels_of_col1[1:]
zare41b .index.names= [labels_of_col1[0]]
zare41b

     Percent of caesareans reviewed
\t
one                            20.0

In [947]:
zaree_N=data.loc[((data['Q110_8_1']==2) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==2) | (data['Q110_8_2']==99))]
zaree_1=(len( zaree_N))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41c  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'greater than two']
zare41c .index= labels_of_col1[1:]
zare41c .index.names= [labels_of_col1[0]]
zare41c

                  Percent of caesareans reviewed
\t
greater than two                             5.0

In [948]:
zaree_N=data.loc[((data['Q110_8_1']!=-999))]
Dree_D=data.loc[((data['Q110_8_2']==0) | (data['Q110_8_2']==1) | (data['Q110_8_2']==2) | (data['Q110_8_2']==9))]
zaree_1=(len( zaree_N)+ len(Dree_D))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41d  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare41d .index= labels_of_col1[1:]
zare41d .index.names= [labels_of_col1[0]]
zare41d

                Percent of caesareans reviewed
\t
No information                            46.0

In [949]:
gtr_4=(zare41a,zare41b,zare41c,zare41d)
gol4=pd.concat( gtr_4, axis=0, sort=False)
gol4

                  Percent of caesareans reviewed
\t
zero                                        28.0
one                                         20.0
greater than two                             5.0
No information                              46.0

In [950]:
zaree_N=data.loc[((data['Q129_8_1']==1))]
Dree_D=data.loc[((data['Q129_8_2']==1))]
zaree_1=(len( zaree_N)+ len(Dree_D))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41d1  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Before caesarean']
zare41d1 .index= labels_of_col1[1:]
zare41d1 .index.names= [labels_of_col1[0]]
zare41d1

                  Percent of caesareans reviewed
\t
Before caesarean                            68.0

In [951]:
zaree_N=data.loc[((data['Q130_8_1']==1))]
Dree_D=data.loc[((data['Q130_8_2']==1))]
zaree_1=(len( zaree_N)+ len(Dree_D))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41d  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'After caesarean']
zare41d .index= labels_of_col1[1:]
zare41d .index.names= [labels_of_col1[0]]
zare41d

                 Percent of caesareans reviewed
\t
After caesarean                            90.0

In [952]:
gtr_4=(zare41d1,zare41d)
gol42=pd.concat( gtr_4, axis=0, sort=False)
gol42

                  Percent of caesareans reviewed
\t
Before caesarean                            68.0
After caesarean                             90.0

In [953]:
zaree_N=data.loc[((data['Q126B_8_2']==1))]
Dree_D=len(zaree_N)
zaree14 = [[Dree_D]]
zare41dv1  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Problem with intubation (n) ']
zare41dv1 .index= labels_of_col1[1:]
zare41dv1 .index.names= [labels_of_col1[0]]
zare41dv1

                              Percent of caesareans reviewed
\t
Problem with intubation (n)                                1

In [954]:
zaree_N0=data.loc[((data['Q126C_8_1']==1))]
zaree_N1=data.loc[((data['Q126C_8_2']==1))]
zaree_N=len(zaree_N0)+len(zaree_N1)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv2  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Postpartum haemorrhage (n)']
zare41dv2 .index= labels_of_col1[1:]
zare41dv2 .index.names= [labels_of_col1[0]]
zare41dv2

                            Percent of caesareans reviewed
\t
Postpartum haemorrhage (n)                               9

In [955]:
zaree_N0=data.loc[((data['Q126D_8_1']==1))]
zaree_N1=data.loc[((data['Q126D_8_2']==1))]
zaree_N=len(zaree_N0)+len(zaree_N1)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv3  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Bowel injury (n)']
zare41dv3 .index= labels_of_col1[1:]
zare41dv3 .index.names= [labels_of_col1[0]]
zare41dv3

                  Percent of caesareans reviewed
\t
Bowel injury (n)                               1

In [956]:
zaree_N0=data.loc[((data['Q126G_8_1']==1))]
zaree_N1=data.loc[((data['Q126G_8_2']==1))]
zaree_N=len(zaree_N0)+len(zaree_N1)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv4  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Other (uterine rupture) (n)']
zare41dv4 .index= labels_of_col1[1:]
zare41dv4 .index.names= [labels_of_col1[0]]
zare41dv4

                             Percent of caesareans reviewed
\t
Other (uterine rupture) (n)                               1

In [957]:
gtr_4=(zare41dv1,zare41dv2,zare41dv3,zare41dv4)
gol5=pd.concat( gtr_4, axis=0, sort=False)
gol5

                              Percent of caesareans reviewed
\t
Problem with intubation (n)                                1
Postpartum haemorrhage (n)                                 9
Bowel injury (n)                                           1
Other (uterine rupture) (n)                                1

In [958]:
zaree_N0=data.loc[((data['Q128A_8_1']==1)) | ((data['Q128A_8_2']==1))]
zaree_N=len(zaree_N0)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv41  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Wound infection (n)']
zare41dv41 .index= labels_of_col1[1:]
zare41dv41 .index.names= [labels_of_col1[0]]
zare41dv41

                     Percent of caesareans reviewed
\t
Wound infection (n)                               4

In [959]:
zaree_N0=data.loc[((data['Q128B_8_1']==1)) | ((data['Q128B_8_2']==1))]
zaree_N=len(zaree_N0)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv42  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Peritonitis/pelvic infection (n)']
zare41dv42 .index= labels_of_col1[1:]
zare41dv42 .index.names= [labels_of_col1[0]]
zare41dv42

                                  Percent of caesareans reviewed
\t
Peritonitis/pelvic infection (n)                               2

In [960]:
zaree_N0=data.loc[((data['Q128C_8_1']==1)) | ((data['Q128C_8_2']==1))]
zaree_N=len(zaree_N0)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv43  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Re-laparotomy (n)']
zare41dv43 .index= labels_of_col1[1:]
zare41dv43 .index.names= [labels_of_col1[0]]
zare41dv43

                   Percent of caesareans reviewed
\t
Re-laparotomy (n)                               1

In [961]:
zaree_N0=data.loc[((data['Q128D_8_1']==1)) | ((data['Q128D_8_2']==1))]
zaree_N=len(zaree_N0)
Dree_D=(zaree_N)
zaree14 = [[Dree_D]]
zare41dv44  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Other (anaemia, endometritis, bleeding, pre-eclampsia,pneumonia) (n)']
zare41dv44 .index= labels_of_col1[1:]
zare41dv44 .index.names= [labels_of_col1[0]]
zare41dv44

                                                    Percent of caesareans reviewed
\t
Other (anaemia, endometritis, bleeding, pre-ecl...                               6

In [962]:
gtr_4=(zare41dv41,zare41dv42,zare41dv43,zare41dv44)
gol50=pd.concat( gtr_4, axis=0, sort=False)
gol50

                                                    Percent of caesareans reviewed
\t
Wound infection (n)                                                              4
Peritonitis/pelvic infection (n)                                                 2
Re-laparotomy (n)                                                                1
Other (anaemia, endometritis, bleeding, pre-ecl...                               6

In [963]:
zaree_N0=data.loc[((data['Q122_8_1']==1))]
zaree_N1=data.loc[((data['Q122_8_2']==1))]
zaree_1=(len( zaree_N0)+ len(zaree_N1))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41dw1  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Alive']
zare41dw1 .index= labels_of_col1[1:]
zare41dw1 .index.names= [labels_of_col1[0]]
zare41dw1

       Percent of caesareans reviewed
\t
Alive                            97.0

In [964]:
zaree_N0=data.loc[((data['Q122_8_1']==2))]
zaree_N1=data.loc[((data['Q122_8_2']==2))]
zaree_1=(len( zaree_N0)+ len(zaree_N1))
zaree=round((( zaree_1)/(deno)*100),1)
zaree14 = [[zaree]]
zare41dw2  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'Dead']
zare41dw2 .index= labels_of_col1[1:]
zare41dw2 .index.names= [labels_of_col1[0]]
zare41dw2

      Percent of caesareans reviewed
\t
Dead                             0.2

In [965]:
zaree_N0=data.loc[((data['Q122_8_1']==9))]
zaree_N1=data.loc[((data['Q122_8_2']==9))]
zaree_1=(len( zaree_N0)+ len(zaree_N1))
zaree=round((( zaree_1)/(deno)*100),0)
zaree14 = [[zaree]]
zare41dw3  = pd.DataFrame(zaree14, columns =['Percent of caesareans reviewed'])
labels_of_col1 = ["	",'No information']
zare41dw3 .index= labels_of_col1[1:]
zare41dw3 .index.names= [labels_of_col1[0]]
zare41dw3

                Percent of caesareans reviewed
\t
No information                             3.0

In [966]:
gtr_4=(zare41dw1,zare41dw2,zare41dw3)
gol51=pd.concat( gtr_4, axis=0, sort=False)
gol51

                Percent of caesareans reviewed
\t
Alive                                     97.0
Dead                                       0.2
No information                             3.0

In [967]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(gol,gol1,gol2,gol3,gol41,gol4,gol42,gol5,gol50,gol51)
last0=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Onset of labour','Type of caesarean','Partograph use','Foetal presentation','Number of neonates','Number of previous caesareans','Antibiotics administered','Developed a complication during operation (n)','Developed a complication post-operation (n)','Maternal outcome'])
last0

                                                                                                  Percent of caesareans reviewed
                                              \t
Onset of labour                               Spontaneous                                                                   61.0
                                              Induced                                                                        6.0
                                              Caesarean before labour                                                       23.0
                                              No information                                                                 9.0
Type of caesarean                             Emergency                                                                     84.0
                                              Elective                                                                      12.0
                                              No information                                                                 6.0
Partograph use                                Partograph used                                                               31.0
                                              Partograph not used                                                           52.0
                                              Partograph not used because considered elective...                            12.0
                                              No information                                                                 5.0
Foetal presentation                           Cephalic                                                                      67.0
                                              Breech                                                                        10.0
                                              Transversal or oblique                                                         7.0
                                              No information                                                                 5.0
Number of neonates                            Singleton                                                                     90.0
                                              Multiple                                                                       7.0
                                              No information                                                                 3.0
Number of previous caesareans                 zero                                                                          28.0
                                              one                                                                           20.0
                                              greater than two                                                               5.0
                                              No information                                                                46.0
Antibiotics administered                      Before caesarean                                                              68.0
                                              After caesarean                                                               90.0
Developed a complication during operation (n) Problem with intubation (n)                                                    1.0
                                              Postpartum haemorrhage (n)                                                     9.0
                                              Bowel injury (n)                                                               1.0
                                              Other (uterine rupture) (n)                                                    1.0
Developed a complication post-operation (n)   Wound infection (n)                                                            4.0
                                              Peritonitis/pelvic infection (n)                                               2.0
                                              Re-laparotomy (n)                                                              1.0
                                              Other (anaemia, endometritis, bleeding, pre-ecl...                             6.0
Maternal outcome                              Alive                                                                         97.0
                                              Dead                                                                           0.2
                                              No information                                                                 3.0

In [968]:
deno1=409
zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q104_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q104_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree11  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Spontaneous']
zaree11 .index= labels_of_col1[1:]
zaree11 .index.names= [labels_of_col1[0]]
zaree11

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q104_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q104_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree12  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Induced']
zaree12 .index= labels_of_col1[1:]
zaree12 .index.names= [labels_of_col1[0]]
zaree12

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q104_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q104_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree13  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Caesarean before labour']
zaree13 .index= labels_of_col1[1:]
zaree13 .index.names= [labels_of_col1[0]]
zaree13

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q104_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q104_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree14  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree14 .index= labels_of_col1[1:]
zaree14 .index.names= [labels_of_col1[0]]
zaree14

gtr1_4=(zaree11,zaree12,zaree13,zaree14)
gool=pd.concat( gtr1_4, axis=0, sort=False)
gool

zaree1e_N=data.loc[(((data['MA3']==1)) &((data['Q105_8_1']==1)))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q105_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Emergency']
zaree141 .index= labels_of_col1[1:]
zaree141 .index.names= [labels_of_col1[0]]
zaree141

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q105_8_1']==2))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree142  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Elective']
zaree142 .index= labels_of_col1[1:]
zaree142 .index.names= [labels_of_col1[0]]
zaree142

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q105_8_1']==9))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree143  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree143 .index= labels_of_col1[1:]
zaree143 .index.names= [labels_of_col1[0]]
zaree143

gtr1_4=(zaree141,zaree142,zaree143)
gool1=pd.concat( gtr1_4, axis=0, sort=False)
gool1

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q116_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q116_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1411  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Partograph used']
zaree1411 .index= labels_of_col1[1:]
zaree1411 .index.names= [labels_of_col1[0]]
zaree1411

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q116_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q116_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1412  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Partograph not used']
zaree1412 .index= labels_of_col1[1:]
zaree1412 .index.names= [labels_of_col1[0]]
zaree1412

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q116_8_1']==0))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q116_8_2']==0))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1413  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Partograph not used because considered elective but went into labour']
zaree1413 .index= labels_of_col1[1:]
zaree1413 .index.names= [labels_of_col1[0]]
zaree1413

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q116_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q116_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1414  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree1414 .index= labels_of_col1[1:]
zaree1414 .index.names= [labels_of_col1[0]]
zaree1414

gtr1_4=(zaree1411,zaree1412,zaree1413,zaree1414)
gool2=pd.concat( gtr1_4, axis=0, sort=False)
gool2

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q107_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q107_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree14140  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Cephalic']
zaree14140 .index= labels_of_col1[1:]
zaree14140 .index.names= [labels_of_col1[0]]
zaree14140

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q107_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q107_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree14141  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Breech']
zaree14141 .index= labels_of_col1[1:]
zaree14141 .index.names= [labels_of_col1[0]]
zaree14141

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q107_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q107_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree14142  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Transversal or oblique']
zaree14142 .index= labels_of_col1[1:]
zaree14142 .index.names= [labels_of_col1[0]]
zaree14142

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q107_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q107_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree14143  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree14143 .index= labels_of_col1[1:]
zaree14143 .index.names= [labels_of_col1[0]]
zaree14143

gtr1_4=(zaree14140,zaree14141,zaree14142,zaree1414)
gool3=pd.concat( gtr1_4, axis=0, sort=False)
gool3

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q108_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q108_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1401  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Singleton']
zaree1401 .index= labels_of_col1[1:]
zaree1401 .index.names= [labels_of_col1[0]]
zaree1401

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q108_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q108_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1402  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Multiple']
zaree1402 .index= labels_of_col1[1:]
zaree1402 .index.names= [labels_of_col1[0]]
zaree1402

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q108_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q108_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree1403  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree1403 .index= labels_of_col1[1:]
zaree1403 .index.names= [labels_of_col1[0]]
zaree1403

gtr1_4=(zaree1401,zaree1402,zaree1403)
gool41=pd.concat( gtr1_4, axis=0, sort=False)
gool41

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99))]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==0))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141a  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'zero']
zaree141a .index= labels_of_col1[1:]
zaree141a .index.names= [labels_of_col1[0]]
zaree141a

zaree1e_N=data.loc[((data['MA3']==1)) &(data['Q110_8_1']==99)]
zaree1e_D=data.loc[((data['MA3']==1)) &((data['Q110_8_2']==1))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141b  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'one']
zaree141b .index= labels_of_col1[1:]
zaree141b .index.names= [labels_of_col1[0]]
zaree141b

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q110_8_1']==2) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==2) | (data['Q110_8_2']==99))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141c  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'greater than two']
zaree141c .index= labels_of_col1[1:]
zaree141c .index.names= [labels_of_col1[0]]
zaree141c

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q110_8_1']!=-999))]
Dree_D=data.loc[((data['MA3']==1)) &((data['Q110_8_2']==0) | (data['Q110_8_2']==1) | (data['Q110_8_2']==2) | (data['Q110_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141a,zaree141b,zaree141c,zaree141d)
gool4=pd.concat( gtr1_4, axis=0, sort=False)
gool4

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q129_8_1']==1))]
Dree_D=data.loc[((data['MA3']==1)) &((data['Q129_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d1  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Before caesarean']
zaree141d1 .index= labels_of_col1[1:]
zaree141d1 .index.names= [labels_of_col1[0]]
zaree141d1

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q130_8_1']==1))]
Dree_D=data.loc[((data['MA3']==1)) &((data['Q130_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'After caesarean']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141d1,zaree141d)
gool42=pd.concat( gtr1_4, axis=0, sort=False)
gool42

zaree1e_N=data.loc[((data['MA3']==1)) &((data['Q126B_8_2']==1))]
Dree_D=len(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv1  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Problem with intubation (n) ']
zaree141dv1 .index= labels_of_col1[1:]
zaree141dv1 .index.names= [labels_of_col1[0]]
zaree141dv1

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q126C_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q126C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv2  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Postpartum haemorrhage (n)']
zaree141dv2 .index= labels_of_col1[1:]
zaree141dv2 .index.names= [labels_of_col1[0]]
zaree141dv2

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q126D_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q126D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv3  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Bowel injury (n)']
zaree141dv3 .index= labels_of_col1[1:]
zaree141dv3 .index.names= [labels_of_col1[0]]
zaree141dv3

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q126G_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q126G_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv4  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Other (uterine rupture) (n)']
zaree141dv4 .index= labels_of_col1[1:]
zaree141dv4 .index.names= [labels_of_col1[0]]
zaree141dv4

gtr1_4=(zaree141dv1,zaree141dv2,zaree141dv3,zaree141dv4)
gool5=pd.concat( gtr1_4, axis=0, sort=False)
gool5

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q128A_8_1']==1)) | ((data['Q128A_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv41  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Wound infection (n)']
zaree141dv41 .index= labels_of_col1[1:]
zaree141dv41 .index.names= [labels_of_col1[0]]
zaree141dv41

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q128B_8_1']==1)) | ((data['Q128B_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv42  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Peritonitis/pelvic infection (n)']
zaree141dv42 .index= labels_of_col1[1:]
zaree141dv42 .index.names= [labels_of_col1[0]]
zaree141dv42

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q128C_8_1']==1)) | ((data['Q128C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv43  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Re-laparotomy (n)']
zaree141dv43 .index= labels_of_col1[1:]
zaree141dv43 .index.names= [labels_of_col1[0]]
zaree141dv43

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q128D_8_1']==1)) | ((data['Q128D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv44  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Other (anaemia, endometritis, bleeding, pre-eclampsia,pneumonia) (n)']
zaree141dv44 .index= labels_of_col1[1:]
zaree141dv44 .index.names= [labels_of_col1[0]]
zaree141dv44

gtr1_4=(zaree141dv41,zaree141dv42,zaree141dv43,zaree141dv44)
gool50=pd.concat( gtr1_4, axis=0, sort=False)
gool50

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q122_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q122_8_2']==1))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw1  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Alive']
zaree141dw1 .index= labels_of_col1[1:]
zaree141dw1 .index.names= [labels_of_col1[0]]
zaree141dw1

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q122_8_1']==2))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q122_8_2']==2))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno1)*100),1)
zaree1e14 = [[zaree1e]]
zaree141dw2  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'Dead']
zaree141dw2 .index= labels_of_col1[1:]
zaree141dw2 .index.names= [labels_of_col1[0]]
zaree141dw2

zaree1e_N0=data.loc[((data['MA3']==1)) &((data['Q122_8_1']==9))]
zaree1e_N1=data.loc[((data['MA3']==1)) &((data['Q122_8_2']==9))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno1)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw3  = pd.DataFrame(zaree1e14, columns =['Public/ government'])
labels_of_col1 = ["	",'No information']
zaree141dw3 .index= labels_of_col1[1:]
zaree141dw3 .index.names= [labels_of_col1[0]]
zaree141dw3

gtr1_4=(zaree141dw1,zaree141dw2,zaree141dw3)
gool51=pd.concat( gtr1_4, axis=0, sort=False)
gool51

Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(gool,gool1,gool2,gool3,gool41,gool4,gool42,gool5,gool50,gool51)
last1=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Onset of labour','Type of caesarean','Partograph use','Foetal presentation','Number of neonates','Number of previous caesareans','Antibiotics administered','Developed a complication during operation (n)','Developed a complication post-operation (n)','Maternal outcome'])
last1

                                                                                                  Public/ government
                                              \t
Onset of labour                               Spontaneous                                                       69.0
                                              Induced                                                            7.0
                                              Caesarean before labour                                           18.0
                                              No information                                                     7.0
Type of caesarean                             Emergency                                                         84.0
                                              Elective                                                           5.0
                                              No information                                                     4.0
Partograph use                                Partograph used                                                   40.0
                                              Partograph not used                                               47.0
                                              Partograph not used because considered elective...                 8.0
                                              No information                                                     5.0
Foetal presentation                           Cephalic                                                          72.0
                                              Breech                                                             9.0
                                              Transversal or oblique                                             9.0
                                              No information                                                     5.0
Number of neonates                            Singleton                                                         90.0
                                              Multiple                                                           9.0
                                              No information                                                     2.0
Number of previous caesareans                 zero                                                              28.0
                                              one                                                               17.0
                                              greater than two                                                   4.0
                                              No information                                                    42.0
Antibiotics administered                      Before caesarean                                                  68.0
                                              After caesarean                                                   91.0
Developed a complication during operation (n) Problem with intubation (n)                                        1.0
                                              Postpartum haemorrhage (n)                                         9.0
                                              Bowel injury (n)                                                   1.0
                                              Other (uterine rupture) (n)                                        1.0
Developed a complication post-operation (n)   Wound infection (n)                                                3.0
                                              Peritonitis/pelvic infection (n)                                   2.0
                                              Re-laparotomy (n)                                                  1.0
                                              Other (anaemia, endometritis, bleeding, pre-ecl...                 6.0
Maternal outcome                              Alive                                                             98.0
                                              Dead                                                               0.2
                                              No information                                                     1.0

In [969]:
deno2=127
zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q104_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q104_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree11  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Spontaneous']
zaree11 .index= labels_of_col1[1:]
zaree11 .index.names= [labels_of_col1[0]]
zaree11

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q104_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q104_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree12  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Induced']
zaree12 .index= labels_of_col1[1:]
zaree12 .index.names= [labels_of_col1[0]]
zaree12

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q104_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q104_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree13  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Caesarean before labour']
zaree13 .index= labels_of_col1[1:]
zaree13 .index.names= [labels_of_col1[0]]
zaree13

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q104_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q104_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree14  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree14 .index= labels_of_col1[1:]
zaree14 .index.names= [labels_of_col1[0]]
zaree14

gtr1_4=(zaree11,zaree12,zaree13,zaree14)
gool=pd.concat( gtr1_4, axis=0, sort=False)
gool

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q105_8_1']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Emergency']
zaree141 .index= labels_of_col1[1:]
zaree141 .index.names= [labels_of_col1[0]]
zaree141

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q105_8_1']==2))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree142  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Elective']
zaree142 .index= labels_of_col1[1:]
zaree142 .index.names= [labels_of_col1[0]]
zaree142

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q105_8_1']==9))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree143  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree143 .index= labels_of_col1[1:]
zaree143 .index.names= [labels_of_col1[0]]
zaree143

gtr1_4=(zaree141,zaree142,zaree143)
gool1=pd.concat( gtr1_4, axis=0, sort=False)
gool1

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q116_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q116_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1411  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Partograph used']
zaree1411 .index= labels_of_col1[1:]
zaree1411 .index.names= [labels_of_col1[0]]
zaree1411

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q116_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q116_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1412  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Partograph not used']
zaree1412 .index= labels_of_col1[1:]
zaree1412 .index.names= [labels_of_col1[0]]
zaree1412

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q116_8_1']==0))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q116_8_2']==0))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1413  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Partograph not used because considered elective but went into labour']
zaree1413 .index= labels_of_col1[1:]
zaree1413 .index.names= [labels_of_col1[0]]
zaree1413

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q116_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q116_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1414  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree1414 .index= labels_of_col1[1:]
zaree1414 .index.names= [labels_of_col1[0]]
zaree1414

gtr1_4=(zaree1411,zaree1412,zaree1413,zaree1414)
gool2=pd.concat( gtr1_4, axis=0, sort=False)
gool2

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q107_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q107_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree14140  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Cephalic']
zaree14140 .index= labels_of_col1[1:]
zaree14140 .index.names= [labels_of_col1[0]]
zaree14140

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q107_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q107_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree14141  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Breech']
zaree14141 .index= labels_of_col1[1:]
zaree14141 .index.names= [labels_of_col1[0]]
zaree14141

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q107_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q107_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree14142  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Transversal or oblique']
zaree14142 .index= labels_of_col1[1:]
zaree14142 .index.names= [labels_of_col1[0]]
zaree14142

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q107_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q107_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree14143  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree14143 .index= labels_of_col1[1:]
zaree14143 .index.names= [labels_of_col1[0]]
zaree14143

gtr1_4=(zaree14140,zaree14141,zaree14142,zaree1414)
gool3=pd.concat( gtr1_4, axis=0, sort=False)
gool3

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q108_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q108_8_1']==1)) | ((data['Q108_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1401  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Singleton']
zaree1401 .index= labels_of_col1[1:]
zaree1401 .index.names= [labels_of_col1[0]]
zaree1401

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q108_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q108_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1402  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Multiple']
zaree1402 .index= labels_of_col1[1:]
zaree1402 .index.names= [labels_of_col1[0]]
zaree1402

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q108_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q108_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree1403  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree1403 .index= labels_of_col1[1:]
zaree1403 .index.names= [labels_of_col1[0]]
zaree1403

gtr1_4=(zaree1401,zaree1402,zaree1403)
gool41=pd.concat( gtr1_4, axis=0, sort=False)
gool41

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99))]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==0))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141a  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'zero']
zaree141a .index= labels_of_col1[1:]
zaree141a .index.names= [labels_of_col1[0]]
zaree141a

zaree1e_N=data.loc[((data['MA3']==2)) &(data['Q110_8_1']==99)]
zaree1e_D=data.loc[((data['MA3']==2)) &((data['Q110_8_2']==1))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141b  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'one']
zaree141b .index= labels_of_col1[1:]
zaree141b .index.names= [labels_of_col1[0]]
zaree141b

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q110_8_1']==2) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==2) | (data['Q110_8_2']==99))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141c  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'greater than two']
zaree141c .index= labels_of_col1[1:]
zaree141c .index.names= [labels_of_col1[0]]
zaree141c

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q110_8_1']!=-999))]
Dree_D=data.loc[((data['MA3']==2)) &((data['Q110_8_2']==0) | (data['Q110_8_2']==1) | (data['Q110_8_2']==2) | (data['Q110_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141a,zaree141b,zaree141c,zaree141d)
gool4=pd.concat( gtr1_4, axis=0, sort=False)
gool4

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q129_8_1']==1))]
Dree_D=data.loc[((data['MA3']==2)) &((data['Q129_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d1  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Before caesarean']
zaree141d1 .index= labels_of_col1[1:]
zaree141d1 .index.names= [labels_of_col1[0]]
zaree141d1

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q130_8_1']==1))]
Dree_D=data.loc[((data['MA3']==2)) &((data['Q130_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'After caesarean']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141d1,zaree141d)
gool42=pd.concat( gtr1_4, axis=0, sort=False)
gool42

zaree1e_N=data.loc[((data['MA3']==2)) &((data['Q126B_8_2']==1))]
Dree_D=len(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv1  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Problem with intubation (n) ']
zaree141dv1 .index= labels_of_col1[1:]
zaree141dv1 .index.names= [labels_of_col1[0]]
zaree141dv1

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q126C_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q126C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv2  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Postpartum haemorrhage (n)']
zaree141dv2 .index= labels_of_col1[1:]
zaree141dv2 .index.names= [labels_of_col1[0]]
zaree141dv2

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q126D_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q126D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv3  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Bowel injury (n)']
zaree141dv3 .index= labels_of_col1[1:]
zaree141dv3 .index.names= [labels_of_col1[0]]
zaree141dv3

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q126G_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q126G_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv4  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Other (uterine rupture) (n)']
zaree141dv4 .index= labels_of_col1[1:]
zaree141dv4 .index.names= [labels_of_col1[0]]
zaree141dv4

gtr1_4=(zaree141dv1,zaree141dv2,zaree141dv3,zaree141dv4)
gool5=pd.concat( gtr1_4, axis=0, sort=False)
gool5

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q128A_8_1']==1)) | ((data['Q128A_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv41  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Wound infection (n)']
zaree141dv41 .index= labels_of_col1[1:]
zaree141dv41 .index.names= [labels_of_col1[0]]
zaree141dv41

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q128B_8_1']==1)) | ((data['Q128B_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv42  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Peritonitis/pelvic infection (n)']
zaree141dv42 .index= labels_of_col1[1:]
zaree141dv42 .index.names= [labels_of_col1[0]]
zaree141dv42

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q128C_8_1']==1)) | ((data['Q128C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv43  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Re-laparotomy (n)']
zaree141dv43 .index= labels_of_col1[1:]
zaree141dv43 .index.names= [labels_of_col1[0]]
zaree141dv43

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q128D_8_1']==1)) | ((data['Q128D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv44  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Other (anaemia, endometritis, bleeding, pre-eclampsia,pneumonia) (n)']
zaree141dv44 .index= labels_of_col1[1:]
zaree141dv44 .index.names= [labels_of_col1[0]]
zaree141dv44

gtr1_4=(zaree141dv41,zaree141dv42,zaree141dv43,zaree141dv44)
gool50=pd.concat( gtr1_4, axis=0, sort=False)
gool50

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q122_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q122_8_2']==1))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw1  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Alive']
zaree141dw1 .index= labels_of_col1[1:]
zaree141dw1 .index.names= [labels_of_col1[0]]
zaree141dw1

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q122_8_1']==2))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q122_8_2']==2))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno2)*100),1)
zaree1e14 = [[zaree1e]]
zaree141dw2  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'Dead']
zaree141dw2 .index= labels_of_col1[1:]
zaree141dw2 .index.names= [labels_of_col1[0]]
zaree141dw2

zaree1e_N0=data.loc[((data['MA3']==2)) &((data['Q122_8_1']==9))]
zaree1e_N1=data.loc[((data['MA3']==2)) &((data['Q122_8_2']==9))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno2)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw3  = pd.DataFrame(zaree1e14, columns =['Private for profit'])
labels_of_col1 = ["	",'No information']
zaree141dw3 .index= labels_of_col1[1:]
zaree141dw3 .index.names= [labels_of_col1[0]]
zaree141dw3

gtr1_4=(zaree141dw1,zaree141dw2,zaree141dw3)
gool51=pd.concat( gtr1_4, axis=0, sort=False)
gool51

Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(gool,gool1,gool2,gool3,gool41,gool4,gool42,gool5,gool50,gool51)
last2=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Onset of labour','Type of caesarean','Partograph use','Foetal presentation','Number of neonates','Number of previous caesareans','Antibiotics administered','Developed a complication during operation (n)','Developed a complication post-operation (n)','Maternal outcome'])
last2

                                                                                                  Private for profit
                                              \t
Onset of labour                               Spontaneous                                                       36.0
                                              Induced                                                            6.0
                                              Caesarean before labour                                           43.0
                                              No information                                                    15.0
Type of caesarean                             Emergency                                                         33.0
                                              Elective                                                          17.0
                                              No information                                                     9.0
Partograph use                                Partograph used                                                    4.0
                                              Partograph not used                                               63.0
                                              Partograph not used because considered elective...                24.0
                                              No information                                                     7.0
Foetal presentation                           Cephalic                                                          57.0
                                              Breech                                                             9.0
                                              Transversal or oblique                                             0.0
                                              No information                                                     7.0
Number of neonates                            Singleton                                                         94.0
                                              Multiple                                                           5.0
                                              No information                                                     6.0
Number of previous caesareans                 zero                                                              28.0
                                              one                                                               29.0
                                              greater than two                                                  10.0
                                              No information                                                    57.0
Antibiotics administered                      Before caesarean                                                  65.0
                                              After caesarean                                                   91.0
Developed a complication during operation (n) Problem with intubation (n)                                        0.0
                                              Postpartum haemorrhage (n)                                         0.0
                                              Bowel injury (n)                                                   0.0
                                              Other (uterine rupture) (n)                                        0.0
Developed a complication post-operation (n)   Wound infection (n)                                                1.0
                                              Peritonitis/pelvic infection (n)                                   2.0
                                              Re-laparotomy (n)                                                  0.0
                                              Other (anaemia, endometritis, bleeding, pre-ecl...                 2.0
Maternal outcome                              Alive                                                             94.0
                                              Dead                                                               0.0
                                              No information                                                     6.0

In [970]:
deno3=32
zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q104_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q104_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree11  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Spontaneous']
zaree11 .index= labels_of_col1[1:]
zaree11 .index.names= [labels_of_col1[0]]
zaree11

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q104_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q104_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree12  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Induced']
zaree12 .index= labels_of_col1[1:]
zaree12 .index.names= [labels_of_col1[0]]
zaree12

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q104_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q104_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree13  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Caesarean before labour']
zaree13 .index= labels_of_col1[1:]
zaree13 .index.names= [labels_of_col1[0]]
zaree13

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q104_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q104_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree14  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree14 .index= labels_of_col1[1:]
zaree14 .index.names= [labels_of_col1[0]]
zaree14

gtr1_4=(zaree11,zaree12,zaree13,zaree14)
gool=pd.concat( gtr1_4, axis=0, sort=False)
gool

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q105_8_1']==1))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Emergency']
zaree141 .index= labels_of_col1[1:]
zaree141 .index.names= [labels_of_col1[0]]
zaree141

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q105_8_1']==2))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree142  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Elective']
zaree142 .index= labels_of_col1[1:]
zaree142 .index.names= [labels_of_col1[0]]
zaree142

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q105_8_1']==9))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree143  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree143 .index= labels_of_col1[1:]
zaree143 .index.names= [labels_of_col1[0]]
zaree143

gtr1_4=(zaree141,zaree142,zaree143)
gool1=pd.concat( gtr1_4, axis=0, sort=False)
gool1

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q116_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q116_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1411  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Partograph used']
zaree1411 .index= labels_of_col1[1:]
zaree1411 .index.names= [labels_of_col1[0]]
zaree1411

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q116_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q116_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1412  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Partograph not used']
zaree1412 .index= labels_of_col1[1:]
zaree1412 .index.names= [labels_of_col1[0]]
zaree1412

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q116_8_1']==0))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q116_8_2']==0))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1413  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Partograph not used because considered elective but went into labour']
zaree1413 .index= labels_of_col1[1:]
zaree1413 .index.names= [labels_of_col1[0]]
zaree1413

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q116_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q116_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1414  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree1414 .index= labels_of_col1[1:]
zaree1414 .index.names= [labels_of_col1[0]]
zaree1414

gtr1_4=(zaree1411,zaree1412,zaree1413,zaree1414)
gool2=pd.concat( gtr1_4, axis=0, sort=False)
gool2

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q107_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q107_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree14140  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Cephalic']
zaree14140 .index= labels_of_col1[1:]
zaree14140 .index.names= [labels_of_col1[0]]
zaree14140

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q107_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q107_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree14141  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Breech']
zaree14141 .index= labels_of_col1[1:]
zaree14141 .index.names= [labels_of_col1[0]]
zaree14141

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q107_8_1']==3))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q107_8_2']==3))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree14142  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Transversal or oblique']
zaree14142 .index= labels_of_col1[1:]
zaree14142 .index.names= [labels_of_col1[0]]
zaree14142

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q107_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q107_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree14143  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree14143 .index= labels_of_col1[1:]
zaree14143 .index.names= [labels_of_col1[0]]
zaree14143

gtr1_4=(zaree14140,zaree14141,zaree14142,zaree1414)
gool3=pd.concat( gtr1_4, axis=0, sort=False)
gool3

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q108_8_1']==1))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q108_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1401  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Singleton']
zaree1401 .index= labels_of_col1[1:]
zaree1401 .index.names= [labels_of_col1[0]]
zaree1401

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q108_8_1']==2))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q108_8_2']==2))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1402  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Multiple']
zaree1402 .index= labels_of_col1[1:]
zaree1402 .index.names= [labels_of_col1[0]]
zaree1402

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q108_8_1']==9))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q108_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+(len( zaree1e_D)))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree1403  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree1403 .index= labels_of_col1[1:]
zaree1403 .index.names= [labels_of_col1[0]]
zaree1403

gtr1_4=(zaree1401,zaree1402,zaree1403)
gool41=pd.concat( gtr1_4, axis=0, sort=False)
gool41

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99))]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q110_8_1']==0) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==0))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141a  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'zero']
zaree141a .index= labels_of_col1[1:]
zaree141a .index.names= [labels_of_col1[0]]
zaree141a

zaree1e_N=data.loc[((data['MA3']==3)) &(data['Q110_8_1']==99)]
zaree1e_D=data.loc[((data['MA3']==3)) &((data['Q110_8_2']==1))]
zaree1e_1=(len(zaree1e_N)+(len(zaree1e_D)))
zaree1e=round(((zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141b  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'one']
zaree141b .index= labels_of_col1[1:]
zaree141b .index.names= [labels_of_col1[0]]
zaree141b

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q110_8_1']==2) | (data['Q110_8_1']==99)) & ((data['Q110_8_2']==2) | (data['Q110_8_2']==99))]
zaree1e_1=(len( zaree1e_N))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141c  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'greater than two']
zaree141c .index= labels_of_col1[1:]
zaree141c .index.names= [labels_of_col1[0]]
zaree141c

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q110_8_1']!=-999))]
Dree_D=data.loc[((data['MA3']==3)) &((data['Q110_8_2']==0) | (data['Q110_8_2']==1) | (data['Q110_8_2']==2) | (data['Q110_8_2']==9))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141a,zaree141b,zaree141c,zaree141d)
gool4=pd.concat( gtr1_4, axis=0, sort=False)
gool4

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q129_8_1']==1))]
Dree_D=data.loc[((data['MA3']==3)) &((data['Q129_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d1  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Before caesarean']
zaree141d1 .index= labels_of_col1[1:]
zaree141d1 .index.names= [labels_of_col1[0]]
zaree141d1

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q130_8_1']==1))]
Dree_D=data.loc[((data['MA3']==3)) &((data['Q130_8_2']==1))]
zaree1e_1=(len( zaree1e_N)+ len(Dree_D))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141d  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'After caesarean']
zaree141d .index= labels_of_col1[1:]
zaree141d .index.names= [labels_of_col1[0]]
zaree141d

gtr1_4=(zaree141d1,zaree141d)
gool42=pd.concat( gtr1_4, axis=0, sort=False)
gool42

zaree1e_N=data.loc[((data['MA3']==3)) &((data['Q126B_8_2']==1))]
Dree_D=len(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv1  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Problem with intubation (n) ']
zaree141dv1 .index= labels_of_col1[1:]
zaree141dv1 .index.names= [labels_of_col1[0]]
zaree141dv1

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q126C_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q126C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv2  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Postpartum haemorrhage (n)']
zaree141dv2 .index= labels_of_col1[1:]
zaree141dv2 .index.names= [labels_of_col1[0]]
zaree141dv2

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q126D_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q126D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv3  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Bowel injury (n)']
zaree141dv3 .index= labels_of_col1[1:]
zaree141dv3 .index.names= [labels_of_col1[0]]
zaree141dv3

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q126G_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q126G_8_2']==1))]
zaree1e_N=len(zaree1e_N0)+len(zaree1e_N1)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv4  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Other (uterine rupture) (n)']
zaree141dv4 .index= labels_of_col1[1:]
zaree141dv4 .index.names= [labels_of_col1[0]]
zaree141dv4

gtr1_4=(zaree141dv1,zaree141dv2,zaree141dv3,zaree141dv4)
gool5=pd.concat( gtr1_4, axis=0, sort=False)
gool5

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q128A_8_1']==1)) | ((data['Q128A_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv41  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Wound infection (n)']
zaree141dv41 .index= labels_of_col1[1:]
zaree141dv41 .index.names= [labels_of_col1[0]]
zaree141dv41

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q128B_8_1']==1)) | ((data['Q128B_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv42  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Peritonitis/pelvic infection (n)']
zaree141dv42 .index= labels_of_col1[1:]
zaree141dv42 .index.names= [labels_of_col1[0]]
zaree141dv42

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q128C_8_1']==1)) | ((data['Q128C_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv43  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Re-laparotomy (n)']
zaree141dv43 .index= labels_of_col1[1:]
zaree141dv43 .index.names= [labels_of_col1[0]]
zaree141dv43

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q128D_8_1']==1)) | ((data['Q128D_8_2']==1))]
zaree1e_N=len(zaree1e_N0)
Dree_D=(zaree1e_N)
zaree1e14 = [[Dree_D]]
zaree141dv44  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Other (anaemia, endometritis, bleeding, pre-eclampsia,pneumonia) (n)']
zaree141dv44 .index= labels_of_col1[1:]
zaree141dv44 .index.names= [labels_of_col1[0]]
zaree141dv44

gtr1_4=(zaree141dv41,zaree141dv42,zaree141dv43,zaree141dv44)
gool50=pd.concat( gtr1_4, axis=0, sort=False)
gool50

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q122_8_1']==1))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q122_8_2']==1))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw1  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Alive']
zaree141dw1 .index= labels_of_col1[1:]
zaree141dw1 .index.names= [labels_of_col1[0]]
zaree141dw1

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q122_8_1']==2))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q122_8_2']==2))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno3)*100),1)
zaree1e14 = [[zaree1e]]
zaree141dw2  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'Dead']
zaree141dw2 .index= labels_of_col1[1:]
zaree141dw2 .index.names= [labels_of_col1[0]]
zaree141dw2

zaree1e_N0=data.loc[((data['MA3']==3)) &((data['Q122_8_1']==9))]
zaree1e_N1=data.loc[((data['MA3']==3)) &((data['Q122_8_2']==9))]
zaree1e_1=(len( zaree1e_N0)+ len(zaree1e_N1))
zaree1e=round((( zaree1e_1)/(deno3)*100),0)
zaree1e14 = [[zaree1e]]
zaree141dw3  = pd.DataFrame(zaree1e14, columns =['Private not for profit'])
labels_of_col1 = ["	",'No information']
zaree141dw3 .index= labels_of_col1[1:]
zaree141dw3 .index.names= [labels_of_col1[0]]
zaree141dw3

gtr1_4=(zaree141dw1,zaree141dw2,zaree141dw3)
gool51=pd.concat( gtr1_4, axis=0, sort=False)
gool51

Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(gool,gool1,gool2,gool3,gool41,gool4,gool42,gool5,gool50,gool51)
last3=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Onset of labour','Type of caesarean','Partograph use','Foetal presentation','Number of neonates','Number of previous caesareans','Antibiotics administered','Developed a complication during operation (n)','Developed a complication post-operation (n)','Maternal outcome'])

In [971]:
waaw=last0.join(last1, how='outer')

In [972]:
waaw1=last2.join(last3, how='outer')

In [985]:
waaw10=waaw.join(waaw1, how='inner')

In [986]:
waaw10.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Caesarean delivery reviews/Percent distribution of caesarean deliveries reviewed according to delivery characteristics and maternal survival status.csv")

In [187]:

MDR_RR2minL2= (pd.crosstab(index=data['Q005'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_RR2minL2[False]        
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_RR2minL2.columns= labels_of_col[1:]
MDR_RR2minL2.index= labels_of_col1[1:]
MDR_RR2minL2.columns.names= [labels_of_col[0]]
MDR_RR2minL2.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab122 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==-999)
my_tab1 = ((my_tab121[1][1]))+((my_tab122[1][1]))
MDR_RR2minL2.loc['National'] = my_tab1
MDR_RR1mint1 = pd.crosstab(data['Q005'], data['Q120_9B_2']==1)
del MDR_RR1mint1[False]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_RR1mint1.columns= labels_of_col[1:]
MDR_RR1mint1.index= labels_of_col1[1:]
MDR_RR1mint1.columns.names= [labels_of_col[0]]
MDR_RR1mint1.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab1 = ((my_tab121[1][1]))
MDR_RR1mint1.loc['National'] = my_tab1
MDR_RR1=MDR_RR2minL2-MDR_RR1mint1
MDR_RR1

                   Number of facilities where maternal deaths one times reviewed
Region
Tigray                                                            11
Afar                                                               2
Amhara                                                            75
Oromia                                                            94
Somali                                                            14
Benishangul-Gumuz                                                  9
SNNP                                                              20
Gambella                                                           0
Harari                                                             2
Addis Ababa                                                        5
Dire Dawa                                                          3
National                                                         236

In [188]:
MDR_RR2 = pd.crosstab(data['Q005'], data['Q120_9B_2']==1)
del MDR_RR2[False]
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Number of facilities where maternal deaths two times reviewed']
MDR_RR2.columns= labels_of_col[1:]
MDR_RR2.index= labels_of_col1[1:]
MDR_RR2.columns.names= [labels_of_col[0]]
MDR_RR2.index.names= [labels_of_col1[0]]
my_tab121 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab1 = ((my_tab121[1][1]))
MDR_RR2.loc['National'] = my_tab1
MDR_RR2

                   Number of facilities where maternal deaths two times reviewed
Region
Tigray                                                             7
Afar                                                               4
Amhara                                                            46
Oromia                                                            87
Somali                                                             9
Benishangul-Gumuz                                                  2
SNNP                                                              20
Gambella                                                           1
Harari                                                             5
Addis Ababa                                                        5
Dire Dawa                                                          1
National                                                         186

In [189]:
MDR_RR2minL2= (pd.crosstab(index=data['Q005'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_RR2minL2[False]
MDR_RR1mint1 = pd.crosstab(data['Q005'], data['Q120_9B_2']==1)
del MDR_RR1mint1[False]
MDR_RR1mint1=MDR_RR2minL2-MDR_RR1mint1
MDR_RR2time = pd.crosstab(data['Q005'], data['Q120_9B_2']==1)
del MDR_RR2time[False]
MDR_RR2time2 = pd.crosstab(data['Q005'], data['Q120_9B_2']==1)
del MDR_RR2time2[False]
MDR_RTsumR1mint1=MDR_RR2time+MDR_RR2time2
MDR_RR3=MDR_RTsumR1mint1+MDR_RR1mint1
my_tab121 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab122 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab123 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==-999)
my_tab1 = ((my_tab121[1][1]))+((my_tab122[1][1]))+((my_tab123[1][1]))
MDR_RR3.loc['National'] = my_tab1
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa','National']
labels_of_col = ["",'Total number of maternal deaths reviewed']
MDR_RR3.columns= labels_of_col[1:]
MDR_RR3.index= labels_of_col1[1:]
MDR_RR3.columns.names= [labels_of_col[0]]
MDR_RR3.index.names= [labels_of_col1[0]]
MDR_RR3

                   Total number of maternal deaths reviewed
Region
Tigray                                                   25
Afar                                                     10
Amhara                                                  167
Oromia                                                  268
Somali                                                   32
Benishangul-Gumuz                                        13
SNNP                                                     60
Gambella                                                  2
Harari                                                   12
Addis Ababa                                              15
Dire Dawa                                                 5
National                                                608

In [190]:
MDR_RR110= (pd.crosstab(index=data['Q005'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_RR110[False]
my_tab2 = pd.crosstab(data['Q005'], data['Q005'])
MDR_RR110['Sz']=my_tab2.sum()
MDR_RR110['Percent of facilities where maternal deaths were reviewed']= MDR_RR110[1]/MDR_RR110['Sz']
labels_of_col1 =["Region","Tigray" , "Afar",'Amhara','Oromia','Somali','Benishangul-Gumuz','SNNP','Gambella','Harari','Addis Ababa','Dire Dawa']
labels_of_col = ["",'Total number of maternal','uuu','Percent of facilities where maternal deaths were reviewed']
MDR_RR110.columns= labels_of_col[1:]
MDR_RR110.index= labels_of_col1[1:]
MDR_RR110.columns.names= [labels_of_col[0]]
MDR_RR110.index.names= [labels_of_col1[0]]
del MDR_RR110['Total number of maternal']
del MDR_RR110['uuu']
MDR_RR1Per12=round((MDR_RR110)*100,0)
MDR_RR1Per12

                   Percent of facilities where maternal deaths were reviewed
Region
Tigray                                                           7.0
Afar                                                             8.0
Amhara                                                          14.0
Oromia                                                          13.0
Somali                                                          14.0
Benishangul-Gumuz                                               26.0
SNNP                                                             5.0
Gambella                                                         4.0
Harari                                                          47.0
Addis Ababa                                                      7.0
Dire Dawa                                                       19.0

In [192]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_RR1Per12,MDR_RR1,MDR_RR2,MDR_RR3)
MDR_RR1T=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
MDR_RR1T

,Percent of facilities where maternal deaths were reviewed,Number of facilities where maternal deaths one times reviewed,Number of facilities where maternal deaths two times reviewed,Total number of maternal deaths reviewed
Tigray,7.0,11,7,25
Afar,8.0,2,4,10
Amhara,14.0,75,46,167
Oromia,13.0,94,87,268
Somali,14.0,14,9,32
Benishangul-Gumuz,26.0,9,2,13
SNNP,5.0,20,20,60
Gambella,4.0,0,1,2
Harari,47.0,2,5,12
Addis Ababa,7.0,5,5,15
Dire Dawa,19.0,3,1,5
National,NaN,236,186,608

In [216]:
MDR_FR2minL2= (pd.crosstab(index=data['FT7'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_FR2minL2[False]        
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_FR2minL2.columns= labels_of_col[1:]
MDR_FR2minL2.index= labels_of_col1[1:]
MDR_FR2minL2.columns.names= [labels_of_col[0]]
MDR_FR2minL2.index.names= [labels_of_col1[0]]
MDR_FR1mint1 = pd.crosstab(data['FT7'], data['Q120_9B_2']==1)
del MDR_FR1mint1[False]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_FR1mint1.columns= labels_of_col[1:]
MDR_FR1mint1.index= labels_of_col1[1:]
MDR_FR1mint1.columns.names= [labels_of_col[0]]
MDR_FR1mint1.index.names= [labels_of_col1[0]]
MDR_FR1=MDR_FR2minL2-MDR_FR1mint1
MDR_FR1
MDR_FR2 = pd.crosstab(data['FT7'], data['Q120_9B_2']==1)
del MDR_FR2[False]
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Number of facilities where maternal deaths two times reviewed']
MDR_FR2.columns= labels_of_col[1:]
MDR_FR2.index= labels_of_col1[1:]
MDR_FR2.columns.names= [labels_of_col[0]]
MDR_FR2.index.names= [labels_of_col1[0]]
MDR_FR2
MDR_FR2minL2= (pd.crosstab(index=data['FT7'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_FR2minL2[False]
MDR_FR1mint1 = pd.crosstab(data['FT7'], data['Q120_9B_2']==1)
del MDR_FR1mint1[False]
MDR_FR1mint1=MDR_FR2minL2-MDR_FR1mint1
MDR_FR2time = pd.crosstab(data['FT7'], data['Q120_9B_2']==1)
del MDR_FR2time[False]
MDR_FR2time2 = pd.crosstab(data['FT7'], data['Q120_9B_2']==1)
del MDR_FR2time2[False]
MDR_RTsumR1mint1=MDR_FR2time+MDR_FR2time2
MDR_FR3=MDR_RTsumR1mint1+MDR_FR1mint1
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Total number of maternal deaths reviewed']
MDR_FR3.columns= labels_of_col[1:]
MDR_FR3.index= labels_of_col1[1:]
MDR_FR3.columns.names= [labels_of_col[0]]
MDR_FR3.index.names= [labels_of_col1[0]]
MDR_FR3
MDR_FR110= (pd.crosstab(index=data['FT7'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_FR110[False]
my_tab2 = pd.crosstab(data['FT7'], data['FT7'])
MDR_FR110['Sz']=my_tab2.sum()
MDR_FR110['Percent of facilities where maternal deaths were reviewed']= MDR_FR110[1]/MDR_FR110['Sz']
labels_of_col1 =["Facility","Referral/specialized" , "General hospitals",'Primary hospitals ','MCH specialized centres','Health centres','MCH specialty clinics','Higher clinics']
labels_of_col = ["",'Total number of maternal','uuu','Percent of facilities where maternal deaths were reviewed']
MDR_FR110.columns= labels_of_col[1:]
MDR_FR110.index= labels_of_col1[1:]
MDR_FR110.columns.names= [labels_of_col[0]]
MDR_FR110.index.names= [labels_of_col1[0]]
del MDR_FR110['Total number of maternal']
del MDR_FR110['uuu']
MDR_FR1Per12=round((MDR_FR110)*100,0)
MDR_FR1Per12
MDR_FR1con=(MDR_FR1Per12,MDR_FR1,MDR_FR2,MDR_FR3)
MDR_FR1T=pd.concat(MDR_FR1con, axis=1, sort=False)
MDR_FR1T

,Percent of facilities where maternal deaths were reviewed,Number of facilities where maternal deaths one times reviewed,Number of facilities where maternal deaths two times reviewed,Total number of maternal deaths reviewed
Facility,,,,
Referral/specialized,80.0,3.0,21,45.0
General hospitals,51.0,10.0,43,96.0
Primary hospitals,36.0,29.0,29,87.0
MCH specialized centres,13.0,1.0,2,5.0
Health centres,8.0,191.0,92,375.0
MCH specialty clinics,NaN,NaN,0,NaN
Higher clinics,8.0,1.0,0,1.0

In [217]:
MDR_MAR2minL2= (pd.crosstab(index=data['MA3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_MAR2minL2[False]        
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_MAR2minL2.columns= labels_of_col[1:]
MDR_MAR2minL2.index= labels_of_col1[1:]
MDR_MAR2minL2.columns.names= [labels_of_col[0]]
MDR_MAR2minL2.index.names= [labels_of_col1[0]]
MDR_MAR1mint1 = pd.crosstab(data['MA3'], data['Q120_9B_2']==1)
del MDR_MAR1mint1[False]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_MAR1mint1.columns= labels_of_col[1:]
MDR_MAR1mint1.index= labels_of_col1[1:]
MDR_MAR1mint1.columns.names= [labels_of_col[0]]
MDR_MAR1mint1.index.names= [labels_of_col1[0]]
MDR_MAR1=MDR_MAR2minL2-MDR_MAR1mint1
MDR_MAR1
MDR_MAR2 = pd.crosstab(data['MA3'], data['Q120_9B_2']==1)
del MDR_MAR2[False]
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Number of facilities where maternal deaths two times reviewed']
MDR_MAR2.columns= labels_of_col[1:]
MDR_MAR2.index= labels_of_col1[1:]
MDR_MAR2.columns.names= [labels_of_col[0]]
MDR_MAR2.index.names= [labels_of_col1[0]]
MDR_MAR2
MDR_MAR2minL2= (pd.crosstab(index=data['MA3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_MAR2minL2[False]
MDR_MAR1mint1 = pd.crosstab(data['MA3'], data['Q120_9B_2']==1)
del MDR_MAR1mint1[False]
MDR_MAR1mint1=MDR_MAR2minL2-MDR_MAR1mint1
MDR_MAR2time = pd.crosstab(data['MA3'], data['Q120_9B_2']==1)
del MDR_MAR2time[False]
MDR_MAR2time2 = pd.crosstab(data['MA3'], data['Q120_9B_2']==1)
del MDR_MAR2time2[False]
MDR_RTsumR1mint1=MDR_MAR2time+MDR_MAR2time2
MDR_MAR3=MDR_RTsumR1mint1+MDR_MAR1mint1
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Total number of maternal deaths reviewed']
MDR_MAR3.columns= labels_of_col[1:]
MDR_MAR3.index= labels_of_col1[1:]
MDR_MAR3.columns.names= [labels_of_col[0]]
MDR_MAR3.index.names= [labels_of_col1[0]]
MDR_MAR3
MDR_MAR110= (pd.crosstab(index=data['MA3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_MAR110[False]
my_tab2 = pd.crosstab(data['MA3'], data['MA3'])
MDR_MAR110['Sz']=my_tab2.sum()
MDR_MAR110['Percent of facilities where maternal deaths were reviewed']= MDR_MAR110[1]/MDR_MAR110['Sz']
labels_of_col1 =["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
labels_of_col = ["",'Total number of maternal','uuu','Percent of facilities where maternal deaths were reviewed']
MDR_MAR110.columns= labels_of_col[1:]
MDR_MAR110.index= labels_of_col1[1:]
MDR_MAR110.columns.names= [labels_of_col[0]]
MDR_MAR110.index.names= [labels_of_col1[0]]
del MDR_MAR110['Total number of maternal']
del MDR_MAR110['uuu']
MDR_MAR1Per12=round((MDR_MAR110)*100,0)
MDR_MAR1Per12
MDR_MAR1con=(MDR_MAR1Per12,MDR_MAR1,MDR_MAR2,MDR_MAR3)
MDR_MAR1T=pd.concat(MDR_MAR1con, axis=1, sort=False)
MDR_MAR1T

,Percent of facilities where maternal deaths were reviewed,Number of facilities where maternal deaths one times reviewed,Number of facilities where maternal deaths two times reviewed,Total number of maternal deaths reviewed
Managing_authority,,,,
Public/government,11.0,227,177,581
Private-for-profit,10.0,3,5,13
Private-not-for-profit,17.0,5,5,15

In [218]:
MDR_LR2minL2= (pd.crosstab(index=data['Q009'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_LR2minL2[False]        
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_LR2minL2.columns= labels_of_col[1:]
MDR_LR2minL2.index= labels_of_col1[1:]
MDR_LR2minL2.columns.names= [labels_of_col[0]]
MDR_LR2minL2.index.names= [labels_of_col1[0]]
MDR_LR1mint1 = pd.crosstab(data['Q009'], data['Q120_9B_2']==1)
del MDR_LR1mint1[False]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_LR1mint1.columns= labels_of_col[1:]
MDR_LR1mint1.index= labels_of_col1[1:]
MDR_LR1mint1.columns.names= [labels_of_col[0]]
MDR_LR1mint1.index.names= [labels_of_col1[0]]
MDR_LR1=MDR_LR2minL2-MDR_LR1mint1
MDR_LR1
MDR_LR2 = pd.crosstab(data['Q009'], data['Q120_9B_2']==1)
del MDR_LR2[False]
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Number of facilities where maternal deaths two times reviewed']
MDR_LR2.columns= labels_of_col[1:]
MDR_LR2.index= labels_of_col1[1:]
MDR_LR2.columns.names= [labels_of_col[0]]
MDR_LR2.index.names= [labels_of_col1[0]]
MDR_LR2
MDR_LR2minL2= (pd.crosstab(index=data['Q009'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_LR2minL2[False]
MDR_LR1mint1 = pd.crosstab(data['Q009'], data['Q120_9B_2']==1)
del MDR_LR1mint1[False]
MDR_LR1mint1=MDR_LR2minL2-MDR_LR1mint1
MDR_LR2time = pd.crosstab(data['Q009'], data['Q120_9B_2']==1)
del MDR_LR2time[False]
MDR_LR2time2 = pd.crosstab(data['Q009'], data['Q120_9B_2']==1)
del MDR_LR2time2[False]
MDR_RTsumR1mint1=MDR_LR2time+MDR_LR2time2
MDR_LR3=MDR_RTsumR1mint1+MDR_LR1mint1
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Total number of maternal deaths reviewed']
MDR_LR3.columns= labels_of_col[1:]
MDR_LR3.index= labels_of_col1[1:]
MDR_LR3.columns.names= [labels_of_col[0]]
MDR_LR3.index.names= [labels_of_col1[0]]
MDR_LR3
MDR_LR110= (pd.crosstab(index=data['Q009'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_LR110[False]
my_tab2 = pd.crosstab(data['Q009'], data['Q009'])
MDR_LR110['Sz']=my_tab2.sum()
MDR_LR110['Percent of facilities where maternal deaths were reviewed']= MDR_LR110[1]/MDR_LR110['Sz']
labels_of_col1 =["Location","Urban" , "Rural"]
labels_of_col = ["",'Total number of maternal','uuu','Percent of facilities where maternal deaths were reviewed']
MDR_LR110.columns= labels_of_col[1:]
MDR_LR110.index= labels_of_col1[1:]
MDR_LR110.columns.names= [labels_of_col[0]]
MDR_LR110.index.names= [labels_of_col1[0]]
del MDR_LR110['Total number of maternal']
del MDR_LR110['uuu']
MDR_LR1Per12=round((MDR_LR110)*100,0)
MDR_LR1Per12
MDR_LR1con=(MDR_LR1Per12,MDR_LR1,MDR_LR2,MDR_LR3)
MDR_LR1T=pd.concat(MDR_LR1con, axis=1, sort=False)
MDR_LR1T

,Percent of facilities where maternal deaths were reviewed,Number of facilities where maternal deaths one times reviewed,Number of facilities where maternal deaths two times reviewed,Total number of maternal deaths reviewed
Location,,,,
Urban,14.0,96,114,324
Rural,9.0,139,73,285

In [220]:
MDR_EMR2minL2= (pd.crosstab(index=data['emonc3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_EMR2minL2[False]        
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_EMR2minL2.columns= labels_of_col[1:]
MDR_EMR2minL2.index= labels_of_col1[1:]
MDR_EMR2minL2.columns.names= [labels_of_col[0]]
MDR_EMR2minL2.index.names= [labels_of_col1[0]]
MDR_EMR1mint1 = pd.crosstab(data['emonc3'], data['Q120_9B_2']==1)
del MDR_EMR1mint1[False]
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Number of facilities where maternal deaths one times reviewed']
MDR_EMR1mint1.columns= labels_of_col[1:]
MDR_EMR1mint1.index= labels_of_col1[1:]
MDR_EMR1mint1.columns.names= [labels_of_col[0]]
MDR_EMR1mint1.index.names= [labels_of_col1[0]]
MDR_EMR1=MDR_EMR2minL2-MDR_EMR1mint1
MDR_EMR1
MDR_EMR2 = pd.crosstab(data['emonc3'], data['Q120_9B_2']==1)
del MDR_EMR2[False]
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Number of facilities where maternal deaths two times reviewed']
MDR_EMR2.columns= labels_of_col[1:]
MDR_EMR2.index= labels_of_col1[1:]
MDR_EMR2.columns.names= [labels_of_col[0]]
MDR_EMR2.index.names= [labels_of_col1[0]]
MDR_EMR2
MDR_EMR2minL2= (pd.crosstab(index=data['emonc3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_EMR2minL2[False]
MDR_EMR1mint1 = pd.crosstab(data['emonc3'], data['Q120_9B_2']==1)
del MDR_EMR1mint1[False]
MDR_EMR1mint1=MDR_EMR2minL2-MDR_EMR1mint1
MDR_EMR2time = pd.crosstab(data['emonc3'], data['Q120_9B_2']==1)
del MDR_EMR2time[False]
MDR_EMR2time2 = pd.crosstab(data['emonc3'], data['Q120_9B_2']==1)
del MDR_EMR2time2[False]
MDR_RTsumR1mint1=MDR_EMR2time+MDR_EMR2time2
MDR_EMR3=MDR_RTsumR1mint1+MDR_EMR1mint1
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Total number of maternal deaths reviewed']
MDR_EMR3.columns= labels_of_col[1:]
MDR_EMR3.index= labels_of_col1[1:]
MDR_EMR3.columns.names= [labels_of_col[0]]
MDR_EMR3.index.names= [labels_of_col1[0]]
MDR_EMR3
MDR_EMR110= (pd.crosstab(index=data['emonc3'], columns=(data['Q120_9B_1']==1), values=(data['Q120_9B_2']==1), colnames=['Facility'], aggfunc='count'))
del MDR_EMR110[False]
my_tab2 = pd.crosstab(data['emonc3'], data['emonc3'])
MDR_EMR110['Sz']=my_tab2.sum()
MDR_EMR110['Percent of facilities where maternal deaths were reviewed']= MDR_EMR110[1]/MDR_EMR110['Sz']
labels_of_col1 =["EmONC classification","CEmONC","BEmONC" , "Partially functioning"]
labels_of_col = ["",'Total number of maternal','uuu','Percent of facilities where maternal deaths were reviewed']
MDR_EMR110.columns= labels_of_col[1:]
MDR_EMR110.index= labels_of_col1[1:]
MDR_EMR110.columns.names= [labels_of_col[0]]
MDR_EMR110.index.names= [labels_of_col1[0]]
del MDR_EMR110['Total number of maternal']
del MDR_EMR110['uuu']
MDR_EMR1Per12=round((MDR_EMR110)*100,0)
MDR_EMR1Per12
MDR_EMR1con=(MDR_EMR1Per12,MDR_EMR1,MDR_EMR2,MDR_EMR3)
MDR_EMR1T=pd.concat(MDR_EMR1con, axis=1, sort=False)
MDR_EMR1T

,Percent of facilities where maternal deaths were reviewed,Number of facilities where maternal deaths one times reviewed,Number of facilities where maternal deaths two times reviewed,Total number of maternal deaths reviewed
EmONC classification,,,,
CEmONC,66.0,21,77,175
BEmONC,14.0,18,12,42
Partially functioning,9.0,196,98,392

In [224]:
MDRC_RT1=(MDR_RR1T,MDR_FR1T,MDR_MAR1T,MDR_LR1T,MDR_EMR1T)
MDRC_RT=pd.concat(MDRC_RT1, keys=['Region','Facility','Managing Authority','location','Types of EmNOC'])
MDRC_RT

                                            Percent of facilities where maternal deaths were reviewed  \
Region             Tigray                                                                 7.0
                   Afar                                                                   8.0
                   Amhara                                                                14.0
                   Oromia                                                                13.0
                   Somali                                                                14.0
                   Benishangul-Gumuz                                                     26.0
                   SNNP                                                                   5.0
                   Gambella                                                               4.0
                   Harari                                                                47.0
                   Addis Ababa                                                            7.0
                   Dire Dawa                                                             19.0
                   National                                                               NaN
Facility           Referral/specialized                                                  80.0
                   General hospitals                                                     51.0
                   Primary hospitals                                                     36.0
                   MCH specialized centres                                               13.0
                   Health centres                                                         8.0
                   MCH specialty clinics                                                  NaN
                   Higher clinics                                                         8.0
Managing Authority Public/government                                                     11.0
                   Private-for-profit                                                    10.0
                   Private-not-for-profit                                                17.0
location           Urban                                                                 14.0
                   Rural                                                                  9.0
Types of EmNOC     CEmONC                                                                66.0
                   BEmONC                                                                14.0
                   Partially functioning                                                  9.0

                                            Number of facilities where maternal deaths one times reviewed  \
Region             Tigray                                                                11.0
                   Afar                                                                   2.0
                   Amhara                                                                75.0
                   Oromia                                                                94.0
                   Somali                                                                14.0
                   Benishangul-Gumuz                                                      9.0
                   SNNP                                                                  20.0
                   Gambella                                                               0.0
                   Harari                                                                 2.0
                   Addis Ababa                                                            5.0
                   Dire Dawa                                                              3.0
                   National                                                             236.0
Facility           Referral/specialized                                                   3.0
                   General hospitals                                                     10.0
                   Primary hospitals                                                     29.0
                   MCH specialized centres                                                1.0
                   Health centres                                                       191.0
                   MCH specialty clinics                                                  NaN
                   Higher clinics                                                         1.0
Managing Authority Public/government                                                    227.0
                   Private-for-profit                                                     3.0
                   Private-not-for-profit                                                 5.0
location           Urban                                                                 96.0
                   Rural                                                                139.0
Types of EmNOC     CEmONC                                                                21.0
                   BEmONC                                                                18.0
                   Partially functioning                                                196.0

                                            Number of facilities where maternal deaths two times reviewed  \
Region             Tigray                                                                   7
                   Afar                                                                     4
                   Amhara                                                                  46
                   Oromia                                                                  87
                   Somali                                                                   9
                   Benishangul-Gumuz                                                        2
                   SNNP                                                                    20
                   Gambella                                                                 1
                   Harari                                                                   5
                   Addis Ababa                                                              5
                   Dire Dawa                                                                1
                   National                                                               186
Facility           Referral/specialized                                                    21
                   General hospitals                                                       43
                   Primary hospitals                                                       29
                   MCH specialized centres                                                  2
                   Health centres                                                          92
                   MCH specialty clinics                                                    0
                   Higher clinics                                                           0
Managing Authority Public/government                                                      177
                   Private-for-profit                                                       5
                   Private-not-for-profit                                                   5
location           Urban                                                                  114
                   Rural                                                                   73
Types of EmNOC     CEmONC                                                                  77
                   BEmONC                                                                  12
                   Partially functioning                                                   98

                                            Total number of maternal deaths reviewed
Region             Tigray                                                       25.0
                   Afar                                                         10.0
                   Amhara                                                      167.0
                   Oromia                                                      268.0
                   Somali                                                       32.0
                   Benishangul-Gumuz                                            13.0
                   SNNP                                                         60.0
                   Gambella                                                      2.0
                   Harari                                                       12.0
                   Addis Ababa                                                  15.0
                   Dire Dawa                                                     5.0
                   National                                                    608.0
Facility           Referral/specialized                                         45.0
                   General hospitals                                            96.0
                   Primary hospitals                                            87.0
                   MCH specialized centres                                       5.0
                   Health centres                                              375.0
                   MCH specialty clinics                                         NaN
                   Higher clinics                                                1.0
Managing Authority Public/government                                           581.0
                   Private-for-profit                                           13.0
                   Private-not-for-profit                                       15.0
location           Urban                                                       324.0
                   Rural                                                       285.0
Types of EmNOC     CEmONC                                                      175.0
                   BEmONC                                                       42.0
                   Partially functioning                                       392.0

In [225]:
MDRC_RT.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Maternal death reviews/Number of facilities where maternal deaths were reviewed and how many were reviewed.csv")

In [1021]:
my_tab121 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab122 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==1)
my_tab123 = pd.crosstab(data['Q120_9B_1']==1, data['Q120_9B_2']==-999)
my_tab1denom = ((my_tab121[1][1]))+((my_tab122[1][1]))+((my_tab123[1][1]))
Timing_of_deaths1= (pd.crosstab(index=data['Q105_9B_1'], columns=(data['Q105_9B_1']==-999), values=(data['Q105_9B_1']==-999), colnames=['Facility'], aggfunc='count'))
del Timing_of_deaths1[1]
Timing_of_deaths1=Timing_of_deaths1.drop([-999])
Timing_of_deaths2= (pd.crosstab(index=data['Q105_9B_2'], columns=(data['Q105_9B_2']==-999), values=(data['Q105_9B_2']==-999), colnames=['Facility'], aggfunc='count'))
del Timing_of_deaths2[1]
Timing_of_deaths2=Timing_of_deaths2.drop([-999])
Timing_of_deathsT=(Timing_of_deaths1)+(Timing_of_deaths2)
Timing_of_deaths=round((Timing_of_deathsT/my_tab1denom)*100,0)
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'All maternal deaths reviewed']
Timing_of_deaths.columns= labels_of_col[1:]
Timing_of_deaths.index= labels_of_col1[1:]
Timing_of_deaths.columns.names= [labels_of_col[0]]
Timing_of_deaths.index.names= [labels_of_col1[0]]
Timing_of_deaths

                                  All maternal deaths reviewed
Timing of death
During pregnancy/before delivery                          10.0
During or after an abortion                                1.0
During vaginal delivery                                    9.0
During obstetric surgery                                   4.0
After delivery                                            50.0
No information                                            26.0

In [1022]:
data['MDR_recode'] =np.nan
data['MDR_recode'] = np.where((data['Q108_9B_1'] >=  1 ) & (data['Q108_9B_1'] <= 10), 1, data['MDR_recode'])
data['MDR_recode1'] =np.nan
data['MDR_recode1'] = np.where((data['Q108_9B_2'] >=  1 ) & (data['Q108_9B_2'] <= 10), 1, data['MDR_recode1'])
Timing_of_deeath_N1=data.loc[(data['MDR_recode']==1)]
Timing_of_deeath_N2=data.loc[(data['MDR_recode1']==1)]
Timing_of_deeath_NT=(len(Timing_of_deeath_N1)+len(Timing_of_deeath_N2))
Timing_of_de= (pd.crosstab(index=data['Q105_9B_1'], columns=(data['MDR_recode']==1), values=(data['MDR_recode']==1), colnames=['Facility'], aggfunc='count'))
del Timing_of_de[0]
Timing_of_de1148=Timing_of_de.drop([-999])
Timing_of_de1= (pd.crosstab(index=data['Q105_9B_2'], columns=(data['MDR_recode1']==1), values=(data['MDR_recode1']==1), colnames=['Facility'], aggfunc='count'))
del Timing_of_de1[0]
Timing_of_de114=Timing_of_de1.drop([-999])
Timing_of_death=Timing_of_de114+Timing_of_de1148
Timing_of_deathT=round((Timing_of_death/Timing_of_deeath_NT)*100,0)
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'Direct causes']
Timing_of_deathT.columns= labels_of_col[1:]
Timing_of_deathT.index= labels_of_col1[1:]
Timing_of_deathT.columns.names= [labels_of_col[0]]
Timing_of_deathT.index.names= [labels_of_col1[0]]
Timing_of_deathT

                                  Direct causes
Timing of death
During pregnancy/before delivery           17.0
During or after an abortion                 2.0
During vaginal delivery                    10.0
During obstetric surgery                    7.0
After delivery                             55.0
No information                              9.0

In [1023]:
data['MDR_recodein'] =np.nan
data['MDR_recodein'] = np.where((data['Q108_9B_1'] >=  11 ) & (data['Q108_9B_1'] <= 15), 1, data['MDR_recodein'])
data['MDR_recodein1'] =np.nan
data['MDR_recodein1'] = np.where((data['Q108_9B_2'] >=  11 ) & (data['Q108_9B_2'] <= 15), 1, data['MDR_recodein1'])
Timing_of_deeath_N1=data.loc[(data['MDR_recodein']==1)]
Timing_of_deeath_N2=data.loc[(data['MDR_recodein1']==1)]
Timing_of_deeafth_NT=(len(Timing_of_deeath_N1)+len(Timing_of_deeath_N2))
Timing_of_de= (pd.crosstab(index=data['Q105_9B_1'], columns=(data['MDR_recodein']==1), values=(data['MDR_recodein']==1), colnames=['Facility'], aggfunc='count'))
Timing_of_de.fillna(0)
del Timing_of_de[0]
Timing_of_de1148=Timing_of_de.drop([-999])
Timing_of_deeath_Ind=Timing_of_de1148.fillna(0)
Timing_of_de1= (pd.crosstab(index=data['Q105_9B_2'], columns=(data['MDR_recodein1']==1), values=(data['MDR_recodein1']==1), colnames=['Facility'], aggfunc='count'))
Timing_of_de1.fillna(0)
del Timing_of_de1[0]
Timing_of_de114=Timing_of_de1.drop([-999])
Timing_of_deeath_Ind1=Timing_of_de114.fillna(0)
Timing_of_death=Timing_of_deeath_Ind1+Timing_of_deeath_Ind
Timing_of_deathT1=round((Timing_of_death/Timing_of_deeafth_NT)*100,0)
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'InDirect causes']
Timing_of_deathT1.columns= labels_of_col[1:]
Timing_of_deathT1.index= labels_of_col1[1:]
Timing_of_deathT1.columns.names= [labels_of_col[0]]
Timing_of_deathT1.index.names= [labels_of_col1[0]]
Timing_of_deathT1

                                  InDirect causes
Timing of death
During pregnancy/before delivery             15.0
During or after an abortion                   0.0
During vaginal delivery                       2.0
During obstetric surgery                     10.0
After delivery                               72.0
No information                                0.0

In [1024]:
data['MDR_recodeinn'] =np.nan
data['MDR_recodeinn'] = np.where((data['Q108_9B_1'] >=  88 ) & (data['Q108_9B_1'] <= 99), 1, data['MDR_recodeinn'])
data['MDR_recodeinn1'] =np.nan
data['MDR_recodeinn1'] = np.where((data['Q108_9B_2'] >=  88 ) & (data['Q108_9B_2'] <= 99), 1, data['MDR_recodeinn1'])
Timing_of_deeath_N1=data.loc[(data['MDR_recodeinn']==1)]
Timing_of_deeath_N2=data.loc[(data['MDR_recodeinn1']==1)]
Timing_of_deeathff_NT=(len(Timing_of_deeath_N1)+len(Timing_of_deeath_N2))
Timing_of_de= (pd.crosstab(index=data['Q105_9B_1'], columns=(data['MDR_recodeinn']==1), values=(data['MDR_recodeinn']==1), colnames=['Facility'], aggfunc='count'))
Timing_of_de.fillna(0)
del Timing_of_de[0]
Timing_of_de1148=Timing_of_de.drop([-999])
Timing_of_deeath_Ind=Timing_of_de1148.fillna(0)
Timing_of_de1= (pd.crosstab(index=data['Q105_9B_2'], columns=(data['MDR_recodeinn1']==1), values=(data['MDR_recodeinn1']==1), colnames=['Facility'], aggfunc='count'))
Timing_of_de1.fillna(0)
del Timing_of_de1[0]
Timing_of_de114=Timing_of_de1.drop([-999])
Timing_of_deeath_Ind1=Timing_of_de114.fillna(0)
Timing_of_death=Timing_of_deeath_Ind1+Timing_of_deeath_Ind
Timing_of_deathT2=round((Timing_of_death/Timing_of_deeathff_NT)*100,0)
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'Unknown causes/no information']
Timing_of_deathT2.columns= labels_of_col[1:]
Timing_of_deathT2.index= labels_of_col1[1:]
Timing_of_deathT2.columns.names= [labels_of_col[0]]
Timing_of_deathT2.index.names= [labels_of_col1[0]]
Timing_of_deathT2

                                  Unknown causes/no information
Timing of death
During pregnancy/before delivery                            3.0
During or after an abortion                                 0.0
During vaginal delivery                                     9.0
During obstetric surgery                                    1.0
After delivery                                             41.0
No information                                             46.0

In [1025]:
MDR_F21=pd.crosstab(data['Q105_9B_1'], (data['FT2']))
MDR_F22=pd.crosstab(data['Q105_9B_2'], (data['FT2']))
MDR_F2T=MDR_F21+MDR_F22
MDR_F2TT=MDR_F2T.drop([-999])
MDR_F2TT1 = MDR_F2TT[1].sum()
MDR_F2TT2 = MDR_F2TT[2].sum()
MDR_F2TTTT=((MDR_F2TT[1]/MDR_F2TT1)*100).round(0)
MDR_F2TTTT1=((MDR_F2TT[2]/MDR_F2TT2)*100).round(0)
list1=MDR_F2TTTT.to_list()
MDR_F2TTTTff  = pd.DataFrame(list1, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'Hospitals/MCH specialty centres']
MDR_F2TTTTff.columns= labels_of_col[1:]
MDR_F2TTTTff.index= labels_of_col1[1:]
MDR_F2TTTTff.columns.names= [labels_of_col[0]]
MDR_F2TTTTff.index.names= [labels_of_col1[0]]
MDR_F2TTTTff

                                  Hospitals/MCH specialty centres
Timing of death
During pregnancy/before delivery                             14.0
During or after an abortion                                   2.0
During vaginal delivery                                       3.0
During obstetric surgery                                     11.0
After delivery                                               58.0
No information                                               12.0

In [1026]:
MDR_F2TTTT1=((MDR_F2TT[2]/MDR_F2TT2)*100).round(0)
list1=MDR_F2TTTT1.to_list()
MDR_F2TTTTff1  = pd.DataFrame(list1, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["",'Health centres/clinics']
MDR_F2TTTTff1.columns= labels_of_col[1:]
MDR_F2TTTTff1.index= labels_of_col1[1:]
MDR_F2TTTTff1.columns.names= [labels_of_col[0]]
MDR_F2TTTTff1.index.names= [labels_of_col1[0]]
MDR_F2TTTTff1

                                  Health centres/clinics
Timing of death
During pregnancy/before delivery                     8.0
During or after an abortion                          1.0
During vaginal delivery                             13.0
During obstetric surgery                             0.0
After delivery                                      44.0
No information                                      34.0

In [1027]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTff,MDR_F2TTTTff1)
MDR_F2TTTTff1rrrr=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
MDR_F2TTTTff1rrrr

,Hospitals/MCH specialty centres,Health centres/clinics
Timing of death,,
During pregnancy/before delivery,14.0,8.0
During or after an abortion,2.0,1.0
During vaginal delivery,3.0,13.0
During obstetric surgery,11.0,0.0
After delivery,58.0,44.0
No information,12.0,34.0

In [1028]:
my_tab121MA = pd.crosstab(data['Q105_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q105_9B_2'], data['MA3'])
aaaaaaa=my_tab121MA+my_tab121MA1
aaaaaaabb=aaaaaaa.drop([-999])
x=[581,13,15]
li=list(aaaaaaabb.columns)
j=0
for i in li:
    aaaaaaabb[i]=aaaaaaabb[i]/x[j]
    j=j+1
MDR_TDMA=((aaaaaaabb)*100).round(0) 
labels_of_col1 =["Timing of death","During pregnancy/before delivery","During or after an abortion" , "During vaginal delivery","During obstetric surgery","After delivery ","No information"]
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_TDMA.columns= labels_of_col[1:]
MDR_TDMA.index= labels_of_col1[1:]
MDR_TDMA.columns.names= [labels_of_col[0]]
MDR_TDMA.index.names= [labels_of_col1[0]]
MDR_TDMA

,Public/government,Private-for-profit,Private-not-for-profit
Timing of death,,,
During pregnancy/before delivery,10.0,0.0,20.0
During or after an abortion,1.0,0.0,0.0
During vaginal delivery,9.0,15.0,7.0
During obstetric surgery,4.0,0.0,7.0
After delivery,50.0,54.0,47.0
No information,26.0,31.0,20.0

In [1029]:
MDR_timing_of_death1=(Timing_of_deaths,Timing_of_deathT,Timing_of_deathT1,Timing_of_deathT2,MDR_F2TTTTff1rrrr,MDR_TDMA)
MDR_timing_of_death=pd.concat(MDR_timing_of_death1, axis=1, sort=False)
MDR_timing_of_death

,All maternal deaths reviewed,Direct causes,InDirect causes,Unknown causes/no information,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
Timing of death,,,,,,,,,
During pregnancy/before delivery,10.0,17.0,15.0,3.0,14.0,8.0,10.0,0.0,20.0
During or after an abortion,1.0,2.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0
During vaginal delivery,9.0,10.0,2.0,9.0,3.0,13.0,9.0,15.0,7.0
During obstetric surgery,4.0,7.0,10.0,1.0,11.0,0.0,4.0,0.0,7.0
After delivery,50.0,55.0,72.0,41.0,58.0,44.0,50.0,54.0,47.0
No information,26.0,9.0,0.0,46.0,12.0,34.0,26.0,31.0,20.0

In [1030]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['Q115_9B_1'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['Q115_9B_2'])
week_of_death=my_tab121MA+my_tab121MA1
del week_of_death[-999] 
week_of_death1=week_of_death.drop(-999)
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Day_of_the_week1=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Weekday','Weekend','No information']
labels_of_col = ["","All maternal deaths reviewed"]
Day_of_the_week1.columns= labels_of_col[1:]
Day_of_the_week1.index= labels_of_col1[1:]
Day_of_the_week1.columns.names= [labels_of_col[0]]
Day_of_the_week1.index.names= [labels_of_col1[0]]
Day_of_the_week1

                All maternal deaths reviewed

Weekday                                 51.0
Weekend                                 16.0
No information                          33.0

In [1031]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['MDR_recode'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['MDR_recode1'])
week_of_death125=my_tab121MA+my_tab121MA1
week_of_death_dir=((week_of_death125/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Weekday','Weekend','No information']
labels_of_col = ["","Direct causes"]
week_of_death_dir.columns= labels_of_col[1:]
week_of_death_dir.index= labels_of_col1[1:]
week_of_death_dir.columns.names= [labels_of_col[0]]
week_of_death_dir.index.names= [labels_of_col1[0]]
week_of_death_dir

                Direct causes

Weekday                  59.0
Weekend                  18.0
No information           23.0

In [1032]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['MDR_recodein'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['MDR_recodein1'])
week_of_death125=my_tab121MA+my_tab121MA1
week_of_death_ind=((week_of_death125/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Weekday','Weekend','No information']
labels_of_col = ["","InDirect causes"]
week_of_death_ind.columns= labels_of_col[1:]
week_of_death_ind.index= labels_of_col1[1:]
week_of_death_ind.columns.names= [labels_of_col[0]]
week_of_death_ind.index.names= [labels_of_col1[0]]
week_of_death_ind

                InDirect causes

Weekday                    68.0
Weekend                    20.0
No information             12.0

In [1033]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['MDR_recodeinn'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['MDR_recodeinn1'])
week_of_death125=my_tab121MA+my_tab121MA1
week_of_death_noinfo=((week_of_death125/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Weekday','Weekend','No information']
labels_of_col = ["","Unknown causes/no information"]
week_of_death_noinfo.columns= labels_of_col[1:]
week_of_death_noinfo.index= labels_of_col1[1:]
week_of_death_noinfo.columns.names= [labels_of_col[0]]
week_of_death_noinfo.index.names= [labels_of_col1[0]]
week_of_death_noinfo

                Unknown causes/no information

Weekday                                  41.0
Weekend                                  13.0
No information                           46.0

In [1034]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
labels_of_col1 =["",'jjjj','Weekday','Weekend','No information']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2f.columns= labels_of_col[1:]
week_of_death_fas2f.index= labels_of_col1[1:]
week_of_death_fas2f.columns.names= [labels_of_col[0]]
week_of_death_fas2f.index.names= [labels_of_col1[0]]
week_of_death_fas2fo=week_of_death_fas2f.drop('jjjj')
week_of_death_fas2fo

                Hospitals/MCH specialty centres  Health centres/clinics

Weekday                                    55.0                    48.0
Weekend                                    21.0                    13.0
No information                             24.0                    39.0

In [1035]:
my_tab121MA = pd.crosstab(data['Q115_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q115_9B_2'], data['MA3'])
aaaaaaa=my_tab121MA+my_tab121MA1
aaaaaaabb=aaaaaaa.drop([-999])
x=[581,13,15]
li=list(aaaaaaabb.columns)
j=0
for i in li:
    aaaaaaabb[i]=aaaaaaabb[i]/x[j]
    j=j+1
MDR_TDMA1=((aaaaaaabb)*100).round(0) 
labels_of_col1 =["",'Weekday','Weekend','No information']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_TDMA1.columns= labels_of_col[1:]
MDR_TDMA1.index= labels_of_col1[1:]
MDR_TDMA1.columns.names= [labels_of_col[0]]
MDR_TDMA1.index.names= [labels_of_col1[0]]
MDR_TDMA1

                Public/government  Private-for-profit  Private-not-for-profit

Weekday                      51.0                23.0                     60.0
Weekend                      16.0                 8.0                      7.0
No information               32.0                69.0                     33.0

In [1036]:
MDR_MDTime1=(Day_of_the_week1,week_of_death_dir,week_of_death_ind,week_of_death_noinfo,week_of_death_fas2fo,MDR_TDMA1)
MDR_MDTime=pd.concat(MDR_MDTime1, axis=1, sort=False)
MDR_MDTime

,All maternal deaths reviewed,Direct causes,InDirect causes,Unknown causes/no information,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,,,,
Weekday,51.0,59.0,68.0,41.0,55.0,48.0,51.0,23.0,60.0
Weekend,16.0,18.0,20.0,13.0,21.0,13.0,16.0,8.0,7.0
No information,33.0,23.0,12.0,46.0,24.0,39.0,32.0,69.0,33.0

In [1037]:
my_tab121MA = pd.crosstab(data['Q120A_9B_1']==1, data['Q120A_9B_1']==1)
my_tab121MA1 = pd.crosstab(data['Q120A_9B_2']==1, data['Q120A_9B_2']==1)
week_of_death1=(my_tab121MA+my_tab121MA1)
week_of_death1p=week_of_death1.drop(False)
del week_of_death1[False]
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Contribution_death=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["","All maternal deaths reviewed"]
Contribution_death.columns= labels_of_col[1:]
Contribution_death.index= labels_of_col1[1:]
Contribution_death.columns.names= [labels_of_col[0]]
Contribution_death.index.names= [labels_of_col1[0]]
Contribution_death

                                     All maternal deaths reviewed

Delay in arrival to health facility                          40.0

In [1038]:
my_tab121MA = pd.crosstab(data['Q120B_9B_1']==1, data['Q120B_9B_1']==1)
my_tab121MA1 = pd.crosstab(data['Q120B_9B_2']==1, data['Q120B_9B_2']==1)
week_of_death1=(my_tab121MA+my_tab121MA1)
week_of_death1p=week_of_death1.drop(False)
del week_of_death1[False]
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Contribution_death1=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["","All maternal deaths reviewed"]
Contribution_death1.columns= labels_of_col[1:]
Contribution_death1.index= labels_of_col1[1:]
Contribution_death1.columns.names= [labels_of_col[0]]
Contribution_death1.index.names= [labels_of_col1[0]]
Contribution_death1

                                               All maternal deaths reviewed

Delayed transfer to appropriate level of care                          29.0

In [1039]:
my_tab121MA = pd.crosstab(data['Q120C_9B_1']==1, data['Q120C_9B_1']==1)
my_tab121MA1 = pd.crosstab(data['Q120C_9B_2']==1, data['Q120C_9B_2']==1)
week_of_death1=(my_tab121MA+my_tab121MA1)
week_of_death1p=week_of_death1.drop(False)
del week_of_death1[False]
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Contribution_death2=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["","All maternal deaths reviewed"]
Contribution_death2.columns= labels_of_col[1:]
Contribution_death2.index= labels_of_col1[1:]
Contribution_death2.columns.names= [labels_of_col[0]]
Contribution_death2.index.names= [labels_of_col1[0]]
Contribution_death2

                               All maternal deaths reviewed

Delay due to lack of supplies                          17.0

In [1040]:
my_tab121MA = pd.crosstab(data['Q120D_9B_1']==1, data['Q120D_9B_1']==1)
my_tab121MA1 = pd.crosstab(data['Q120D_9B_2']==1, data['Q120D_9B_2']==1)
week_of_death1=(my_tab121MA+my_tab121MA1)
week_of_death1p=week_of_death1.drop(False)
del week_of_death1[False]
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Contribution_death3=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["","All maternal deaths reviewed"]
Contribution_death3.columns= labels_of_col[1:]
Contribution_death3.index= labels_of_col1[1:]
Contribution_death3.columns.names= [labels_of_col[0]]
Contribution_death3.index.names= [labels_of_col1[0]]
Contribution_death3

                                                    All maternal deaths reviewed

Delay due to absence or slowness of human resou...                          14.0

In [1041]:
my_tab121MA = pd.crosstab(data['Q120E_9B_1']==1, data['Q120E_9B_1']==1)
my_tab121MA1 = pd.crosstab(data['Q120E_9B_2']==1, data['Q120E_9B_2']==1)
week_of_death1=(my_tab121MA+my_tab121MA1)
week_of_death1p=week_of_death1.drop(False)
del week_of_death1[False]
week_of_death12=week_of_death1.sum()
Day_of_the_week= pd.DataFrame(week_of_death12, columns =['Day of the week of death'])
Contribution_death4=((Day_of_the_week/my_tab1denom)*100).round(0)
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["","All maternal deaths reviewed"]
Contribution_death4.columns= labels_of_col[1:]
Contribution_death4.index= labels_of_col1[1:]
Contribution_death4.columns.names= [labels_of_col[0]]
Contribution_death4.index.names= [labels_of_col1[0]]
Contribution_death4

                            All maternal deaths reviewed

Delay in correct diagnosis                          18.0

In [1042]:
factors_death1=(Contribution_death,Contribution_death1,Contribution_death2,Contribution_death3,Contribution_death4)
factors_death=pd.concat(factors_death1, axis=0, sort=False)
factors_death

                                                    All maternal deaths reviewed

Delay in arrival to health facility                                         40.0
Delayed transfer to appropriate level of care                               29.0
Delay due to lack of supplies                                               17.0
Delay due to absence or slowness of human resou...                          14.0
Delay in correct diagnosis                                                  18.0

In [1043]:
FCD = pd.crosstab(data['Q120A_9B_1']==1, data['MDR_recode']==1)
FCD1 = pd.crosstab(data['Q120A_9B_2']==1, data['MDR_recode1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death=((FCD_Np/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["","Direct causes"]
Contribution_death.columns= labels_of_col[1:]
Contribution_death.index= labels_of_col1[1:]
Contribution_death.columns.names= [labels_of_col[0]]
Contribution_death.index.names= [labels_of_col1[0]]
Contribution_death
FCD = pd.crosstab(data['Q120B_9B_1']==1, data['MDR_recode']==1)
FCD1 = pd.crosstab(data['Q120B_9B_2']==1, data['MDR_recode1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death1=((FCD_Np/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["","Direct causes"]
Contribution_death1.columns= labels_of_col[1:]
Contribution_death1.index= labels_of_col1[1:]
Contribution_death1.columns.names= [labels_of_col[0]]
Contribution_death1.index.names= [labels_of_col1[0]]
Contribution_death1
FCD = pd.crosstab(data['Q120C_9B_1']==1, data['MDR_recode']==1)
FCD1 = pd.crosstab(data['Q120C_9B_2']==1, data['MDR_recode1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death2=((FCD_Np/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["","Direct causes"]
Contribution_death2.columns= labels_of_col[1:]
Contribution_death2.index= labels_of_col1[1:]
Contribution_death2.columns.names= [labels_of_col[0]]
Contribution_death2.index.names= [labels_of_col1[0]]
Contribution_death2
FCD = pd.crosstab(data['Q120D_9B_1']==1, data['MDR_recode']==1)
FCD1 = pd.crosstab(data['Q120D_9B_2']==1, data['MDR_recode1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death3=((FCD_Np/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["","Direct causes"]
Contribution_death3.columns= labels_of_col[1:]
Contribution_death3.index= labels_of_col1[1:]
Contribution_death3.columns.names= [labels_of_col[0]]
Contribution_death3.index.names= [labels_of_col1[0]]
Contribution_death3
FCD = pd.crosstab(data['Q120E_9B_1']==1, data['MDR_recode']==1)
FCD1 = pd.crosstab(data['Q120E_9B_2']==1, data['MDR_recode1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death4=((FCD_Np/Timing_of_deeath_NT)*100).round(0)
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["","Direct causes"]
Contribution_death4.columns= labels_of_col[1:]
Contribution_death4.index= labels_of_col1[1:]
Contribution_death4.columns.names= [labels_of_col[0]]
Contribution_death4.index.names= [labels_of_col1[0]]
factors_death1=(Contribution_death,Contribution_death1,Contribution_death2,Contribution_death3,Contribution_death4)
factors_death12=pd.concat(factors_death1, axis=0, sort=False)
factors_death12

                                                    Direct causes

Delay in arrival to health facility                          53.0
Delayed transfer to appropriate level of care                43.0
Delay due to lack of supplies                                23.0
Delay due to absence or slowness of human resou...           21.0
Delay in correct diagnosis                                   21.0

In [1044]:
FCD = pd.crosstab(data['Q120A_9B_1']==1, data['MDR_recodein']==1)
FCD1 = pd.crosstab(data['Q120A_9B_2']==1, data['MDR_recodein1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death=((FCD_Np/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["","InDirect causes"]
Contribution_death.columns= labels_of_col[1:]
Contribution_death.index= labels_of_col1[1:]
Contribution_death.columns.names= [labels_of_col[0]]
Contribution_death.index.names= [labels_of_col1[0]]
Contribution_death
FCD = pd.crosstab(data['Q120B_9B_1']==1, data['MDR_recodein']==1)
FCD1 = pd.crosstab(data['Q120B_9B_2']==1, data['MDR_recodein1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death1=((FCD_Np/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["","InDirect causes"]
Contribution_death1.columns= labels_of_col[1:]
Contribution_death1.index= labels_of_col1[1:]
Contribution_death1.columns.names= [labels_of_col[0]]
Contribution_death1.index.names= [labels_of_col1[0]]
Contribution_death1
FCD = pd.crosstab(data['Q120C_9B_1']==1, data['MDR_recodein']==1)
FCD1 = pd.crosstab(data['Q120C_9B_2']==1, data['MDR_recodein1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death2=((FCD_Np/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["","InDirect causes"]
Contribution_death2.columns= labels_of_col[1:]
Contribution_death2.index= labels_of_col1[1:]
Contribution_death2.columns.names= [labels_of_col[0]]
Contribution_death2.index.names= [labels_of_col1[0]]
Contribution_death2
FCD = pd.crosstab(data['Q120D_9B_1']==1, data['MDR_recodein']==1)
FCD1 = pd.crosstab(data['Q120D_9B_2']==1, data['MDR_recodein1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death3=((FCD_Np/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["","InDirect causes"]
Contribution_death3.columns= labels_of_col[1:]
Contribution_death3.index= labels_of_col1[1:]
Contribution_death3.columns.names= [labels_of_col[0]]
Contribution_death3.index.names= [labels_of_col1[0]]
Contribution_death3
FCD = pd.crosstab(data['Q120E_9B_1']==1, data['MDR_recodein']==1)
FCD1 = pd.crosstab(data['Q120E_9B_2']==1, data['MDR_recodein1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death4=((FCD_Np/Timing_of_deeafth_NT)*100).round(0)
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["","InDirect causes"]
Contribution_death4.columns= labels_of_col[1:]
Contribution_death4.index= labels_of_col1[1:]
Contribution_death4.columns.names= [labels_of_col[0]]
Contribution_death4.index.names= [labels_of_col1[0]]
factors_death1=(Contribution_death,Contribution_death1,Contribution_death2,Contribution_death3,Contribution_death4)
factors_death13=pd.concat(factors_death1, axis=0, sort=False)
factors_death13

                                                    InDirect causes

Delay in arrival to health facility                            30.0
Delayed transfer to appropriate level of care                  38.0
Delay due to lack of supplies                                  10.0
Delay due to absence or slowness of human resou...             20.0
Delay in correct diagnosis                                     48.0

In [1045]:
FCD = pd.crosstab(data['Q120A_9B_1']==1, data['MDR_recodeinn']==1)
FCD1 = pd.crosstab(data['Q120A_9B_2']==1, data['MDR_recodeinn1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death=((FCD_Np/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["","Unknown causes/no information"]
Contribution_death.columns= labels_of_col[1:]
Contribution_death.index= labels_of_col1[1:]
Contribution_death.columns.names= [labels_of_col[0]]
Contribution_death.index.names= [labels_of_col1[0]]
Contribution_death
FCD = pd.crosstab(data['Q120B_9B_1']==1, data['MDR_recodeinn']==1)
FCD1 = pd.crosstab(data['Q120B_9B_2']==1, data['MDR_recodeinn1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death1=((FCD_Np/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["","Unknown causes/no information"]
Contribution_death1.columns= labels_of_col[1:]
Contribution_death1.index= labels_of_col1[1:]
Contribution_death1.columns.names= [labels_of_col[0]]
Contribution_death1.index.names= [labels_of_col1[0]]
Contribution_death1
FCD = pd.crosstab(data['Q120C_9B_1']==1, data['MDR_recodeinn']==1)
FCD1 = pd.crosstab(data['Q120C_9B_2']==1, data['MDR_recodeinn1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death2=((FCD_Np/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["","Unknown causes/no information"]
Contribution_death2.columns= labels_of_col[1:]
Contribution_death2.index= labels_of_col1[1:]
Contribution_death2.columns.names= [labels_of_col[0]]
Contribution_death2.index.names= [labels_of_col1[0]]
Contribution_death2
FCD = pd.crosstab(data['Q120D_9B_1']==1, data['MDR_recodeinn']==1)
FCD1 = pd.crosstab(data['Q120D_9B_2']==1, data['MDR_recodeinn1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death3=((FCD_Np/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["","Unknown causes/no information"]
Contribution_death3.columns= labels_of_col[1:]
Contribution_death3.index= labels_of_col1[1:]
Contribution_death3.columns.names= [labels_of_col[0]]
Contribution_death3.index.names= [labels_of_col1[0]]
Contribution_death3
FCD = pd.crosstab(data['Q120E_9B_1']==1, data['MDR_recodeinn']==1)
FCD1 = pd.crosstab(data['Q120E_9B_2']==1, data['MDR_recodeinn1']==1)
FCD_N=(FCD+FCD1)
FCD_Np=FCD_N.drop(False)
del FCD_Np[False]
#FCD_Np= pd.DataFrame(FCD_Np, columns =['Day of the week of death'])
Contribution_death4=((FCD_Np/Timing_of_deeathff_NT)*100).round(0)
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["","Unknown causes/no information"]
Contribution_death4.columns= labels_of_col[1:]
Contribution_death4.index= labels_of_col1[1:]
Contribution_death4.columns.names= [labels_of_col[0]]
Contribution_death4.index.names= [labels_of_col1[0]]
factors_death1=(Contribution_death,Contribution_death1,Contribution_death2,Contribution_death3,Contribution_death4)
factors_death14=pd.concat(factors_death1, axis=0, sort=False)
factors_death14

                                                    Unknown causes/no information

Delay in arrival to health facility                                          28.0
Delayed transfer to appropriate level of care                                14.0
Delay due to lack of supplies                                                13.0
Delay due to absence or slowness of human resou...                            7.0
Delay in correct diagnosis                                                   12.0

In [1046]:
my_tab121MA = pd.crosstab(data['Q120A_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q120A_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
week_of_death_fas2fhk=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2fhk.columns= labels_of_col[1:]
week_of_death_fas2fhk.index= labels_of_col1[1:]
week_of_death_fas2fhk.columns.names= [labels_of_col[0]]
week_of_death_fas2fhk.index.names= [labels_of_col1[0]]
week_of_death_fas2fhk

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delay in arrival to health facility,45.0,36.0

In [1047]:
my_tab121MA = pd.crosstab(data['Q120B_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q120B_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
week_of_death_fas2fhk1=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2fhk1.columns= labels_of_col[1:]
week_of_death_fas2fhk1.index= labels_of_col1[1:]
week_of_death_fas2fhk1.columns.names= [labels_of_col[0]]
week_of_death_fas2fhk1.index.names= [labels_of_col1[0]]
week_of_death_fas2fhk1

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delayed transfer to appropriate level of care,38.0,23.0

In [1048]:
my_tab121MA = pd.crosstab(data['Q120C_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q120C_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
week_of_death_fas2fhk2=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2fhk2.columns= labels_of_col[1:]
week_of_death_fas2fhk2.index= labels_of_col1[1:]
week_of_death_fas2fhk2.columns.names= [labels_of_col[0]]
week_of_death_fas2fhk2.index.names= [labels_of_col1[0]]
week_of_death_fas2fhk2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delay due to lack of supplies,17.0,17.0

In [1049]:
my_tab121MA = pd.crosstab(data['Q120D_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q120D_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
week_of_death_fas2fhk3=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2fhk3.columns= labels_of_col[1:]
week_of_death_fas2fhk3.index= labels_of_col1[1:]
week_of_death_fas2fhk3.columns.names= [labels_of_col[0]]
week_of_death_fas2fhk3.index.names= [labels_of_col1[0]]
week_of_death_fas2fhk3

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delay due to absence or slowness of human resources,23.0,9.0

In [1050]:
my_tab121MA = pd.crosstab(data['Q120E_9B_1'], data['FT2'])
my_tab121MA1 = pd.crosstab(data['Q120E_9B_2'], data['FT2'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[MDR_F2TT1,MDR_F2TT2]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
week_of_death_fas2fhk4=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2fhk4.columns= labels_of_col[1:]
week_of_death_fas2fhk4.index= labels_of_col1[1:]
week_of_death_fas2fhk4.columns.names= [labels_of_col[0]]
week_of_death_fas2fhk4.index.names= [labels_of_col1[0]]
week_of_death_fas2fhk4

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delay in correct diagnosis,25.0,14.0

In [1051]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(week_of_death_fas2fhk,week_of_death_fas2fhk1,week_of_death_fas2fhk2,week_of_death_fas2fhk3,week_of_death_fas2fhk4)
CFD_F2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
CFD_F2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Delay in arrival to health facility,45.0,36.0
Delayed transfer to appropriate level of care,38.0,23.0
Delay due to lack of supplies,17.0,17.0
Delay due to absence or slowness of human resources,23.0,9.0
Delay in correct diagnosis,25.0,14.0

In [1052]:
my_tab121MA = pd.crosstab(data['Q120A_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q120A_9B_2'], data['MA3'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[581,13,15]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
FCD_MA=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay in arrival to health facility']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
FCD_MA.columns= labels_of_col[1:]
FCD_MA.index= labels_of_col1[1:]
FCD_MA.columns.names= [labels_of_col[0]]
FCD_MA.index.names= [labels_of_col1[0]]
FCD_MA
my_tab121MA = pd.crosstab(data['Q120B_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q120B_9B_2'], data['MA3'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[581,13,15]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
FCD_MA1=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delayed transfer to appropriate level of care']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
FCD_MA1.columns= labels_of_col[1:]
FCD_MA1.index= labels_of_col1[1:]
FCD_MA1.columns.names= [labels_of_col[0]]
FCD_MA1.index.names= [labels_of_col1[0]]
FCD_MA1
my_tab121MA = pd.crosstab(data['Q120C_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q120C_9B_2'], data['MA3'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[581,13,15]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
FCD_MA2=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay due to lack of supplies']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
FCD_MA2.columns= labels_of_col[1:]
FCD_MA2.index= labels_of_col1[1:]
FCD_MA2.columns.names= [labels_of_col[0]]
FCD_MA2.index.names= [labels_of_col1[0]]
FCD_MA2
my_tab121MA = pd.crosstab(data['Q120D_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q120D_9B_2'], data['MA3'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[581,13,15]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
FCD_MA3=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay due to absence or slowness of human resources']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
FCD_MA3.columns= labels_of_col[1:]
FCD_MA3.index= labels_of_col1[1:]
FCD_MA3.columns.names= [labels_of_col[0]]
FCD_MA3.index.names= [labels_of_col1[0]]
FCD_MA3
my_tab121MA = pd.crosstab(data['Q120E_9B_1'], data['MA3'])
my_tab121MA1 = pd.crosstab(data['Q120E_9B_2'], data['MA3'])
week_of_death_fas2=my_tab121MA+my_tab121MA1
x=[581,13,15]
li=list(week_of_death_fas2.columns)
j=0
for i in li:
    week_of_death_fas2[i]=week_of_death_fas2[i]/x[j]
    j=j+1
week_of_death_fas2f=((week_of_death_fas2)*100).round(0) 
FCD_MA4=(week_of_death_fas2f.drop([0, 8,-999]))
labels_of_col1 =["",'Delay in correct diagnosis']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
FCD_MA4.columns= labels_of_col[1:]
FCD_MA4.index= labels_of_col1[1:]
FCD_MA4.columns.names= [labels_of_col[0]]
FCD_MA4.index.names= [labels_of_col1[0]]
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(FCD_MA,FCD_MA1,FCD_MA2,FCD_MA3,FCD_MA4)
CFD_MAT=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
CFD_MAT

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Delay in arrival to health facility,40.0,38.0,40.0
Delayed transfer to appropriate level of care,29.0,8.0,40.0
Delay due to lack of supplies,18.0,8.0,7.0
Delay due to absence or slowness of human resources,15.0,0.0,0.0
Delay in correct diagnosis,18.0,8.0,20.0

In [ ]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(factors_death,factors_death12,factors_death13,factors_death14,CFD_F2,CFD_MAT)
CFD_MA_F2T=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=True)
CFD_MA_F2T

,All maternal deaths reviewed,Direct causes,InDirect causes,Unknown causes/no information,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,,,,
Delay due to absence or slowness of human resources,14.0,21.0,20.0,7.0,23.0,9.0,15.0,0.0,0.0
Delay due to lack of supplies,17.0,23.0,10.0,13.0,17.0,17.0,18.0,8.0,7.0
Delay in arrival to health facility,40.0,53.0,30.0,28.0,45.0,36.0,40.0,38.0,40.0
Delay in correct diagnosis,18.0,21.0,48.0,12.0,25.0,14.0,18.0,8.0,20.0
Delayed transfer to appropriate level of care,29.0,43.0,38.0,14.0,38.0,23.0,29.0,8.0,40.0

In [1063]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(MDR_timing_of_death,MDR_MDTime,CFD_MA_F2T)
MDR_F2MATD=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Timing of death','Day of the week of death','Factors contributing to death'])
MDR_F2MATD

                                                                                  All maternal deaths reviewed  \
Timing of death               During pregnancy/before delivery                                            10.0
                              During or after an abortion                                                  1.0
                              During vaginal delivery                                                      9.0
                              During obstetric surgery                                                     4.0
                              After delivery                                                              50.0
                              No information                                                              26.0
Day of the week of death      Weekday                                                                     51.0
                              Weekend                                                                     16.0
                              No information                                                              33.0
Factors contributing to death Delay due to absence or slowness of human resou...                          14.0
                              Delay due to lack of supplies                                               17.0
                              Delay in arrival to health facility                                         40.0
                              Delay in correct diagnosis                                                  18.0
                              Delayed transfer to appropriate level of care                               29.0

                                                                                  Direct causes  \
Timing of death               During pregnancy/before delivery                             17.0
                              During or after an abortion                                   2.0
                              During vaginal delivery                                      10.0
                              During obstetric surgery                                      7.0
                              After delivery                                               55.0
                              No information                                                9.0
Day of the week of death      Weekday                                                      59.0
                              Weekend                                                      18.0
                              No information                                               23.0
Factors contributing to death Delay due to absence or slowness of human resou...           21.0
                              Delay due to lack of supplies                                23.0
                              Delay in arrival to health facility                          53.0
                              Delay in correct diagnosis                                   21.0
                              Delayed transfer to appropriate level of care                43.0

                                                                                  InDirect causes  \
Timing of death               During pregnancy/before delivery                               15.0
                              During or after an abortion                                     0.0
                              During vaginal delivery                                         2.0
                              During obstetric surgery                                       10.0
                              After delivery                                                 72.0
                              No information                                                  0.0
Day of the week of death      Weekday                                                        68.0
                              Weekend                                                        20.0
                              No information                                                 12.0
Factors contributing to death Delay due to absence or slowness of human resou...             20.0
                              Delay due to lack of supplies                                  10.0
                              Delay in arrival to health facility                            30.0
                              Delay in correct diagnosis                                     48.0
                              Delayed transfer to appropriate level of care                  38.0

                                                                                  Unknown causes/no information  \
Timing of death               During pregnancy/before delivery                                              3.0
                              During or after an abortion                                                   0.0
                              During vaginal delivery                                                       9.0
                              During obstetric surgery                                                      1.0
                              After delivery                                                               41.0
                              No information                                                               46.0
Day of the week of death      Weekday                                                                      41.0
                              Weekend                                                                      13.0
                              No information                                                               46.0
Factors contributing to death Delay due to absence or slowness of human resou...                            7.0
                              Delay due to lack of supplies                                                13.0
                              Delay in arrival to health facility                                          28.0
                              Delay in correct diagnosis                                                   12.0
                              Delayed transfer to appropriate level of care                                14.0

                                                                                  Hospitals/MCH specialty centres  \
Timing of death               During pregnancy/before delivery                                               14.0
                              During or after an abortion                                                     2.0
                              During vaginal delivery                                                         3.0
                              During obstetric surgery                                                       11.0
                              After delivery                                                                 58.0
                              No information                                                                 12.0
Day of the week of death      Weekday                                                                        55.0
                              Weekend                                                                        21.0
                              No information                                                                 24.0
Factors contributing to death Delay due to absence or slowness of human resou...                             23.0
                              Delay due to lack of supplies                                                  17.0
                              Delay in arrival to health facility                                            45.0
                              Delay in correct diagnosis                                                     25.0
                              Delayed transfer to appropriate level of care                                  38.0

                                                                                  Health centres/clinics  \
Timing of death               During pregnancy/before delivery                                       8.0
                              During or after an abortion                                            1.0
                              During vaginal delivery                                               13.0
                              During obstetric surgery                                               0.0
                              After delivery                                                        44.0
                              No information                                                        34.0
Day of the week of death      Weekday                                                               48.0
                              Weekend                                                               13.0
                              No information                                                        39.0
Factors contributing to death Delay due to absence or slowness of human resou...                     9.0
                              Delay due to lack of supplies                                         17.0
                              Delay in arrival to health facility                                   36.0
                              Delay in correct diagnosis                                            14.0
                              Delayed transfer to appropriate level of care                         23.0

                                                                                  Public/government  \
Timing of death               During pregnancy/before delivery                                 10.0
                              During or after an abortion                                       1.0
                              During vaginal delivery                                           9.0
                              During obstetric surgery                                          4.0
                              After delivery                                                   50.0
                              No information                                                   26.0
Day of the week of death      Weekday                                                          51.0
                              Weekend                                                          16.0
                              No information                                                   32.0
Factors contributing to death Delay due to absence or slowness of human resou...               15.0
                              Delay due to lack of supplies                                    18.0
                              Delay in arrival to health facility                              40.0
                              Delay in correct diagnosis                                       18.0
                              Delayed transfer to appropriate level of care                    29.0

                                                                                  Private-for-profit  \
Timing of death               During pregnancy/before delivery                                   0.0
                              During or after an abortion                                        0.0
                              During vaginal delivery                                           15.0
                              During obstetric surgery                                           0.0
                              After delivery                                                    54.0
                              No information                                                    31.0
Day of the week of death      Weekday                                                           23.0
                              Weekend                                                            8.0
                              No information                                                    69.0
Factors contributing to death Delay due to absence or slowness of human resou...                 0.0
                              Delay due to lack of supplies                                      8.0
                              Delay in arrival to health facility                               38.0
                              Delay in correct diagnosis                                         8.0
                              Delayed transfer to appropriate level of care                      8.0

                                                                                  Private-not-for-profit
Timing of death               During pregnancy/before delivery                                       20.0
                              During or after an abortion                                             0.0
                              During vaginal delivery                                                 7.0
                              During obstetric surgery                                                7.0
                              After delivery                                                         47.0
                              No information                                                         20.0
Day of the week of death      Weekday                                                                60.0
                              Weekend                                                                 7.0
                              No information                                                         33.0
Factors contributing to death Delay due to absence or slowness of human resou...                      0.0
                              Delay due to lack of supplies                                           7.0
                              Delay in arrival to health facility                                    40.0
                              Delay in correct diagnosis                                             20.0
                              Delayed transfer to appropriate level of care                          40.0

In [1064]:
MDR_F2MATD.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Maternal death reviews/Percent distribution of reviewed maternal deaths according to timing of death Day of the week of death and factors contributing to death.csv")

In [1453]:
MDR_TR1dd=pd.crosstab(data['Q108_9B_1'], (data['Q108_9B_1']))
MDR_TR2dd=pd.crosstab(data['Q108_9B_2'], (data['Q108_9B_2']))
reviewed_maternal_deaths_according_to_treatment=pd.concat([MDR_TR1dd,MDR_TR2dd], ignore_index=True, axis=0).sum()
reviewed_maternal_deaths_according_to_treatment1=reviewed_maternal_deaths_according_to_treatment.drop(-999)
reviewed_maternal_deaths_according_to_treatment_Total  = pd.DataFrame(reviewed_maternal_deaths_according_to_treatment1, columns =['All maternal deaths reviewed'])
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","All maternal deaths reviewed"]
reviewed_maternal_deaths_according_to_treatment_Total.columns= labels_of_col[1:]
reviewed_maternal_deaths_according_to_treatment_Total.index= labels_of_col1[1:]
reviewed_maternal_deaths_according_to_treatment_Total.columns.names= [labels_of_col[0]]
reviewed_maternal_deaths_according_to_treatment_Total.index.names= [labels_of_col1[0]]
reviewed_maternal_deaths_according_to_treatment_Total.loc['National'] = my_tab1denom
reviewed_maternal_deaths_according_to_treatment_Total

                                     All maternal deaths reviewed

APH                                                          27.0
PPH                                                          97.0
Retained placenta                                            16.0
Prolonged / Obstructed Labor                                 20.0
Ruptured uterus                                              15.0
Post partum Sepsis                                           15.0
Eclampsia                                                    61.0
Sever complications of Abortion                               7.0
Ectopic pregnancy                                             2.0
Other Direct complication                                    24.0
HIV/AIDS-related                                              2.0
Severe Anemia                                                11.0
Other indirect cause                                         27.0
Cause of death Unknown                                        6.0
No Information on on cause of death                         279.0
National                                                    608.0

In [1454]:
MDR_TRIV_fluids1=pd.crosstab(data['Q108_9B_1'], (data['Q116A_9B_1']))
MDR_TRIV_fluids2=pd.crosstab(data['Q108_9B_2'], (data['Q116A_9B_2']))
df1 = MDR_TRIV_fluids1.reset_index()
df2 = MDR_TRIV_fluids2.reset_index()
df = [MDR_TRIV_fluids1, MDR_TRIV_fluids2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MIV_fluids=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","IV_fluids",'rrrrrr']
MIV_fluids.columns= labels_of_col[1:]
MIV_fluids.index= labels_of_col1[1:]
MIV_fluids.columns.names= [labels_of_col[0]]
MIV_fluids.index.names= [labels_of_col1[0]]
MDR_MIV_fluids=MIV_fluids[["IV_fluids", "rrrrrr"]].sum(axis=1)
MDR_MIV_fluids_N= pd.DataFrame(MDR_MIV_fluids, columns =['IV_fluids'])
MDR_MIV_fluids_T=((MDR_MIV_fluids_N['IV_fluids']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MIV_fluids_Total= pd.DataFrame(MDR_MIV_fluids_T, columns =['IV_fluids'])
MDR_TROther1=pd.crosstab(data['Q116A_9B_1'], (data['Q116A_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116A_9B_2'], (data['Q116A_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MIV_fluids_Total.loc['National'] = MDR_MOther_National
MDR_MIV_fluids_Total

                                     IV_fluids

APH                                       70.0
Cause of death Unknown                    33.0
Eclampsia                                 69.0
Ectopic pregnancy                         50.0
HIV/AIDS-related                          50.0
National                                  44.0
No Information on on cause of death       13.0
Other Direct complication                 88.0
Other indirect cause                      70.0
PPH                                       65.0
Post partum Sepsis                        87.0
Prolonged / Obstructed Labor              60.0
Retained placenta                         69.0
Ruptured uterus                           87.0
Sever complications of Abortion           86.0
Severe Anemia                            100.0

In [1455]:
MDR_TRPlasma1=pd.crosstab(data['Q108_9B_1'], (data['Q116B_9B_1']))
MDR_TRPlasma2=pd.crosstab(data['Q108_9B_2'], (data['Q116B_9B_2']))
df1 = MDR_TRPlasma1.reset_index()
df2 = MDR_TRPlasma2.reset_index()
df = [MDR_TRPlasma1, MDR_TRPlasma2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MPlasma=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Plasma",'rrrrrr']
MPlasma.columns= labels_of_col[1:]
MPlasma.index= labels_of_col1[1:]
MPlasma.columns.names= [labels_of_col[0]]
MPlasma.index.names= [labels_of_col1[0]]
MDR_MPlasma=MPlasma[["Plasma", "rrrrrr"]].sum(axis=1)
MDR_MPlasma_N= pd.DataFrame(MDR_MPlasma, columns =['Plasma'])
MDR_MPlasma_T=((MDR_MPlasma_N['Plasma']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlasma_Total= pd.DataFrame(MDR_MPlasma_T, columns =['Plasma'])
MDR_TROther1=pd.crosstab(data['Q116B_9B_1'], (data['Q116B_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116B_9B_2'], (data['Q116B_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlasma_Total.loc['National'] = MDR_MOther_National
MDR_MPlasma_Total

                                     Plasma

APH                                    15.0
Cause of death Unknown                  0.0
Eclampsia                               7.0
Ectopic pregnancy                       0.0
HIV/AIDS-related                        0.0
National                                4.0
No Information on on cause of death     0.0
Other Direct complication              12.0
Other indirect cause                    4.0
PPH                                     5.0
Post partum Sepsis                      0.0
Prolonged / Obstructed Labor            0.0
Retained placenta                       0.0
Ruptured uterus                        13.0
Sever complications of Abortion         0.0
Severe Anemia                          27.0

In [1433]:
MDR_TRBlood_transfusion1=pd.crosstab(data['Q108_9B_1'], (data['Q116C_9B_1']))
MDR_TRBlood_transfusion2=pd.crosstab(data['Q108_9B_2'], (data['Q116C_9B_2']))
df1 = MDR_TRBlood_transfusion1.reset_index()
df2 = MDR_TRBlood_transfusion2.reset_index()
df = [MDR_TRBlood_transfusion1, MDR_TRBlood_transfusion2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MBlood_transfusion=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Blood_transfusion",'rrrrrr']
MBlood_transfusion.columns= labels_of_col[1:]
MBlood_transfusion.index= labels_of_col1[1:]
MBlood_transfusion.columns.names= [labels_of_col[0]]
MBlood_transfusion.index.names= [labels_of_col1[0]]
MDR_MBlood_transfusion=MBlood_transfusion[["Blood_transfusion", "rrrrrr"]].sum(axis=1)
MDR_MBlood_transfusion_N= pd.DataFrame(MDR_MBlood_transfusion, columns =['Blood_transfusion'])
MDR_MBlood_transfusion_T=((MDR_MBlood_transfusion_N['Blood_transfusion']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlBlood_transfusion= pd.DataFrame(MDR_MBlood_transfusion_T, columns =['Blood_transfusion'])
MDR_TROther1=pd.crosstab(data['Q116C_9B_1'], (data['Q116C_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116C_9B_2'], (data['Q116C_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlBlood_transfusion.loc['National'] = MDR_MOther_National
MDR_MPlBlood_transfusion

                                     Blood_transfusion

APH                                               30.0
PPH                                               32.0
Retained placenta                                  6.0
Prolonged / Obstructed Labor                       5.0
Ruptured uterus                                   47.0
Post partum Sepsis                                33.0
Eclampsia                                         16.0
Sever complications of Abortion                   43.0
Ectopic pregnancy                                 50.0
Other Direct complication                         21.0
HIV/AIDS-related                                  50.0
Severe Anemia                                     36.0
Other indirect cause                              22.0
Cause of death Unknown                             0.0
No Information on on cause of death                1.0
National                                          14.0

In [1434]:
MDR_TRAntibiotics1=pd.crosstab(data['Q108_9B_1'], (data['Q116D_9B_1']))
MDR_TRAntibiotics2=pd.crosstab(data['Q108_9B_2'], (data['Q116D_9B_2']))
df1 = MDR_TRAntibiotics1.reset_index()
df2 = MDR_TRAntibiotics2.reset_index()
df = [MDR_TRAntibiotics1, MDR_TRAntibiotics2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MAntibiotics=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Antibiotics",'rrrrrr']
MAntibiotics.columns= labels_of_col[1:]
MAntibiotics.index= labels_of_col1[1:]
MAntibiotics.columns.names= [labels_of_col[0]]
MAntibiotics.index.names= [labels_of_col1[0]]
MDR_MAntibiotics=MAntibiotics[["Antibiotics", "rrrrrr"]].sum(axis=1)
MDR_MAntibiotics_N= pd.DataFrame(MDR_MAntibiotics, columns =['Antibiotics'])
MDR_MAntibiotics_T=((MDR_MAntibiotics_N['Antibiotics']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlAntibiotics= pd.DataFrame(MDR_MAntibiotics_T, columns =['Antibiotics'])
MDR_TROther1=pd.crosstab(data['Q116D_9B_1'], (data['Q116D_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116D_9B_2'], (data['Q116D_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlAntibiotics.loc['National'] = MDR_MOther_National
MDR_MPlAntibiotics

                                     Antibiotics

APH                                         48.0
PPH                                         39.0
Retained placenta                           44.0
Prolonged / Obstructed Labor                30.0
Ruptured uterus                             53.0
Post partum Sepsis                          87.0
Eclampsia                                   61.0
Sever complications of Abortion             86.0
Ectopic pregnancy                           50.0
Other Direct complication                   71.0
HIV/AIDS-related                            50.0
Severe Anemia                               64.0
Other indirect cause                        81.0
Cause of death Unknown                      17.0
No Information on on cause of death          9.0
National                                    33.0

In [1435]:
MDR_TROxytocics1=pd.crosstab(data['Q108_9B_1'], (data['Q116E_9B_1']))
MDR_TROxytocics2=pd.crosstab(data['Q108_9B_2'], (data['Q116E_9B_2']))
df1 = MDR_TROxytocics1.reset_index()
df2 = MDR_TROxytocics2.reset_index()
df = [MDR_TROxytocics1, MDR_TROxytocics2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOxytocics=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Oxytocics",'rrrrrr']
MOxytocics.columns= labels_of_col[1:]
MOxytocics.index= labels_of_col1[1:]
MOxytocics.columns.names= [labels_of_col[0]]
MOxytocics.index.names= [labels_of_col1[0]]
MDR_MOxytocics=MOxytocics[["Oxytocics", "rrrrrr"]].sum(axis=1)
MDR_MOxytocics_N= pd.DataFrame(MDR_MOxytocics, columns =['Oxytocics'])
MDR_MOxytocics_T=((MDR_MOxytocics_N['Oxytocics']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlOxytocics= pd.DataFrame(MDR_MOxytocics_T, columns =['Oxytocics'])
MDR_TROther1=pd.crosstab(data['Q116E_9B_1'], (data['Q116E_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116E_9B_2'], (data['Q116E_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlOxytocics.loc['National'] = MDR_MOther_National
MDR_MPlOxytocics

                                     Oxytocics

APH                                       22.0
PPH                                       48.0
Retained placenta                         31.0
Prolonged / Obstructed Labor              25.0
Ruptured uterus                           20.0
Post partum Sepsis                        53.0
Eclampsia                                 30.0
Sever complications of Abortion            0.0
Ectopic pregnancy                          0.0
Other Direct complication                 50.0
HIV/AIDS-related                           0.0
Severe Anemia                             55.0
Other indirect cause                      41.0
Cause of death Unknown                     0.0
No Information on on cause of death       12.0
National                                  25.0

In [1436]:
MDR_TRManual_removal_of_placenta1=pd.crosstab(data['Q108_9B_1'], (data['Q116G_9B_1']))
MDR_TRManual_removal_of_placenta2=pd.crosstab(data['Q108_9B_2'], (data['Q116G_9B_2']))
df1 = MDR_TRManual_removal_of_placenta1.reset_index()
df2 = MDR_TRManual_removal_of_placenta2.reset_index()
df = [MDR_TRManual_removal_of_placenta1, MDR_TRManual_removal_of_placenta2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MManual_removal_of_placenta=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Manual_removal_of_placenta",'rrrrrr']
MManual_removal_of_placenta.columns= labels_of_col[1:]
MManual_removal_of_placenta.index= labels_of_col1[1:]
MManual_removal_of_placenta.columns.names= [labels_of_col[0]]
MManual_removal_of_placenta.index.names= [labels_of_col1[0]]
MDR_MManual_removal_of_placenta=MManual_removal_of_placenta[["Manual_removal_of_placenta", "rrrrrr"]].sum(axis=1)
MDR_MManual_removal_of_placenta_N= pd.DataFrame(MDR_MManual_removal_of_placenta, columns =['Manual_removal_of_placenta'])
MDR_MManual_removal_of_placenta_T=((MDR_MManual_removal_of_placenta_N['Manual_removal_of_placenta']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlManual_removal_of_placenta= pd.DataFrame(MDR_MManual_removal_of_placenta_T, columns =['Manual_removal_of_placenta'])
MDR_TROther1=pd.crosstab(data['Q116G_9B_1'], (data['Q116G_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116G_9B_2'], (data['Q116G_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlManual_removal_of_placenta.loc['National'] = MDR_MOther_National
MDR_MPlManual_removal_of_placenta

                                     Manual_removal_of_placenta

APH                                                         4.0
PPH                                                        14.0
Retained placenta                                          19.0
Prolonged / Obstructed Labor                                0.0
Ruptured uterus                                             7.0
Post partum Sepsis                                          0.0
Eclampsia                                                   7.0
Sever complications of Abortion                             0.0
Ectopic pregnancy                                           0.0
Other Direct complication                                   8.0
HIV/AIDS-related                                            0.0
Severe Anemia                                               9.0
Other indirect cause                                        7.0
Cause of death Unknown                                      0.0
No Information on on cause of death                         2.0
National                                                    5.0

In [1437]:
MDR_TRManual_vacuum_aspiration1=pd.crosstab(data['Q108_9B_1'], (data['Q116I_9B_1']))
MDR_TRManual_vacuum_aspiration2=pd.crosstab(data['Q108_9B_2'], (data['Q116I_9B_2']))
df1 = MDR_TRManual_vacuum_aspiration1.reset_index()
df2 = MDR_TRManual_vacuum_aspiration2.reset_index()
df = [MDR_TRManual_vacuum_aspiration1, MDR_TRManual_vacuum_aspiration2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MManual_vacuum_aspiration=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Manual_vacuum_aspiration",'rrrrrr']
MManual_vacuum_aspiration.columns= labels_of_col[1:]
MManual_vacuum_aspiration.index= labels_of_col1[1:]
MManual_vacuum_aspiration.columns.names= [labels_of_col[0]]
MManual_vacuum_aspiration.index.names= [labels_of_col1[0]]
MDR_MManual_vacuum_aspiration=MManual_vacuum_aspiration[["Manual_vacuum_aspiration", "rrrrrr"]].sum(axis=1)
MDR_MManual_vacuum_aspiration_N= pd.DataFrame(MDR_MManual_vacuum_aspiration, columns =['Manual_vacuum_aspiration'])
MDR_MManual_vacuum_aspiration_T=((MDR_MManual_vacuum_aspiration_N['Manual_vacuum_aspiration']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlManual_vacuum_aspiration= pd.DataFrame(MDR_MManual_vacuum_aspiration_T, columns =['Manual_vacuum_aspiration'])
MDR_TROther1=pd.crosstab(data['Q116I_9B_1'], (data['Q116I_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116I_9B_2'], (data['Q116I_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlManual_vacuum_aspiration.loc['National'] = MDR_MOther_National
MDR_MPlManual_vacuum_aspiration

                                     Manual_vacuum_aspiration

APH                                                       0.0
PPH                                                       1.0
Retained placenta                                         0.0
Prolonged / Obstructed Labor                              0.0
Ruptured uterus                                           0.0
Post partum Sepsis                                        0.0
Eclampsia                                                 2.0
Sever complications of Abortion                          43.0
Ectopic pregnancy                                         0.0
Other Direct complication                                 0.0
HIV/AIDS-related                                          0.0
Severe Anemia                                             0.0
Other indirect cause                                      0.0
Cause of death Unknown                                    0.0
No Information on on cause of death                       0.0
National                                                  1.0

In [1438]:
MDR_TRForceps1=pd.crosstab(data['Q108_9B_1'], (data['Q116J_9B_1']))
MDR_TRForceps2=pd.crosstab(data['Q108_9B_2'], (data['Q116J_9B_2']))
df1 = MDR_TRForceps1.reset_index()
df2 = MDR_TRForceps2.reset_index()
df = [MDR_TRForceps1, MDR_TRForceps2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MForceps=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Forceps",'rrrrrr']
MForceps.columns= labels_of_col[1:]
MForceps.index= labels_of_col1[1:]
MForceps.columns.names= [labels_of_col[0]]
MForceps.index.names= [labels_of_col1[0]]
MDR_MForceps=MForceps[["Forceps", "rrrrrr"]].sum(axis=1)
MDR_MForceps_N= pd.DataFrame(MDR_MForceps, columns =['Forceps'])
MDR_MForceps_T=((MDR_MForceps_N['Forceps']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlForceps= pd.DataFrame(MDR_MForceps_T, columns =['Forceps'])
MDR_TROther1=pd.crosstab(data['Q116J_9B_1'], (data['Q116J_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116J_9B_2'], (data['Q116J_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlForceps.loc['National'] = MDR_MOther_National
MDR_MPlForceps

                                     Forceps

APH                                      0.0
PPH                                      1.0
Retained placenta                        0.0
Prolonged / Obstructed Labor             0.0
Ruptured uterus                          0.0
Post partum Sepsis                       0.0
Eclampsia                                3.0
Sever complications of Abortion          0.0
Ectopic pregnancy                        0.0
Other Direct complication                8.0
HIV/AIDS-related                         0.0
Severe Anemia                            9.0
Other indirect cause                     7.0
Cause of death Unknown                   0.0
No Information on on cause of death      0.0
National                                 1.0

In [1439]:
MDR_TRVacuum_extraction1=pd.crosstab(data['Q108_9B_1'], (data['Q116K_9B_1']))
MDR_TRVacuum_extraction2=pd.crosstab(data['Q108_9B_2'], (data['Q116K_9B_2']))
df1 = MDR_TRVacuum_extraction1.reset_index()
df2 = MDR_TRVacuum_extraction2.reset_index()
df = [MDR_TRVacuum_extraction1, MDR_TRVacuum_extraction2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MVacuum_extraction=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Vacuum_extraction",'rrrrrr']
MVacuum_extraction.columns= labels_of_col[1:]
MVacuum_extraction.index= labels_of_col1[1:]
MVacuum_extraction.columns.names= [labels_of_col[0]]
MVacuum_extraction.index.names= [labels_of_col1[0]]
MDR_MVacuum_extraction=MVacuum_extraction[["Vacuum_extraction", "rrrrrr"]].sum(axis=1)
MDR_MVacuum_extraction_N= pd.DataFrame(MDR_MVacuum_extraction, columns =['Vacuum_extraction'])
MDR_MVacuum_extraction_T=((MDR_MVacuum_extraction_N['Vacuum_extraction']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlVacuum_extraction= pd.DataFrame(MDR_MVacuum_extraction_T, columns =['Vacuum_extraction'])
MDR_TROther1=pd.crosstab(data['Q116K_9B_1'], (data['Q116K_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116K_9B_2'], (data['Q116K_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlVacuum_extraction.loc['National'] = MDR_MOther_National
MDR_MPlVacuum_extraction

                                     Vacuum_extraction

APH                                                4.0
PPH                                                0.0
Retained placenta                                  0.0
Prolonged / Obstructed Labor                       0.0
Ruptured uterus                                    0.0
Post partum Sepsis                                 0.0
Eclampsia                                          7.0
Sever complications of Abortion                    0.0
Ectopic pregnancy                                  0.0
Other Direct complication                          0.0
HIV/AIDS-related                                   0.0
Severe Anemia                                      0.0
Other indirect cause                               0.0
Cause of death Unknown                             0.0
No Information on on cause of death                1.0
National                                           1.0

In [1440]:
MDR_TRCaesarean1=pd.crosstab(data['Q108_9B_1'], (data['Q116L_9B_1']))
MDR_TRCaesarean2=pd.crosstab(data['Q108_9B_2'], (data['Q116L_9B_2']))
df1 = MDR_TRCaesarean1.reset_index()
df2 = MDR_TRCaesarean2.reset_index()
df = [MDR_TRCaesarean1, MDR_TRCaesarean2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MCaesarean=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Caesarean",'rrrrrr']
MCaesarean.columns= labels_of_col[1:]
MCaesarean.index= labels_of_col1[1:]
MCaesarean.columns.names= [labels_of_col[0]]
MCaesarean.index.names= [labels_of_col1[0]]
MDR_MCaesarean=MCaesarean[["Caesarean", "rrrrrr"]].sum(axis=1)
MDR_MCaesarean_N= pd.DataFrame(MDR_MCaesarean, columns =['Caesarean'])
MDR_MCaesarean_T=((MDR_MCaesarean_N['Caesarean']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlCaesarean= pd.DataFrame(MDR_MCaesarean_T, columns =['Caesarean'])
MDR_TROther1=pd.crosstab(data['Q116L_9B_1'], (data['Q116L_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116L_9B_2'], (data['Q116L_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlCaesarean.loc['National'] = MDR_MOther_National
MDR_MPlCaesarean

                                     Caesarean

APH                                       26.0
PPH                                       11.0
Retained placenta                          6.0
Prolonged / Obstructed Labor              25.0
Ruptured uterus                           33.0
Post partum Sepsis                        40.0
Eclampsia                                 13.0
Sever complications of Abortion            0.0
Ectopic pregnancy                          0.0
Other Direct complication                 46.0
HIV/AIDS-related                          50.0
Severe Anemia                              9.0
Other indirect cause                      37.0
Cause of death Unknown                     0.0
No Information on on cause of death        3.0
National                                  12.0

In [1441]:
MDR_TRHysterectomy1=pd.crosstab(data['Q108_9B_1'], (data['Q116M_9B_1']))
MDR_TRHysterectomy2=pd.crosstab(data['Q108_9B_2'], (data['Q116M_9B_2']))
df1 = MDR_TRHysterectomy1.reset_index()
df2 = MDR_TRHysterectomy2.reset_index()
df = [MDR_TRHysterectomy1, MDR_TRHysterectomy2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MHysterectomy=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Hysterectomy",'rrrrrr']
MHysterectomy.columns= labels_of_col[1:]
MHysterectomy.index= labels_of_col1[1:]
MHysterectomy.columns.names= [labels_of_col[0]]
MHysterectomy.index.names= [labels_of_col1[0]]
MDR_MHysterectomy=MHysterectomy[["Hysterectomy", "rrrrrr"]].sum(axis=1)
MDR_MHysterectomy_N= pd.DataFrame(MDR_MHysterectomy, columns =['Hysterectomy'])
MDR_MHysterectomy_T=((MDR_MHysterectomy_N['Hysterectomy']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlHysterectomy= pd.DataFrame(MDR_MHysterectomy_T, columns =['Hysterectomy'])
MDR_TROther1=pd.crosstab(data['Q116M_9B_1'], (data['Q116M_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116M_9B_2'], (data['Q116M_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlHysterectomy.loc['National'] = MDR_MOther_National
MDR_MPlHysterectomy

                                     Hysterectomy

APH                                          11.0
PPH                                           6.0
Retained placenta                             6.0
Prolonged / Obstructed Labor                  5.0
Ruptured uterus                              40.0
Post partum Sepsis                            7.0
Eclampsia                                     0.0
Sever complications of Abortion              29.0
Ectopic pregnancy                             0.0
Other Direct complication                     4.0
HIV/AIDS-related                              0.0
Severe Anemia                                 0.0
Other indirect cause                          4.0
Cause of death Unknown                        0.0
No Information on on cause of death           0.0
National                                      4.0

In [1442]:
MDR_TRLaparotomy1=pd.crosstab(data['Q108_9B_1'], (data['Q116N_9B_1']))
MDR_TRLaparotomy2=pd.crosstab(data['Q108_9B_2'], (data['Q116N_9B_2']))
df1 = MDR_TRLaparotomy1.reset_index()
df2 = MDR_TRLaparotomy2.reset_index()
df = [MDR_TRLaparotomy1, MDR_TRLaparotomy2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MLaparotomy=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Laparotomy",'rrrrrr']
MLaparotomy.columns= labels_of_col[1:]
MLaparotomy.index= labels_of_col1[1:]
MLaparotomy.columns.names= [labels_of_col[0]]
MLaparotomy.index.names= [labels_of_col1[0]]
MDR_MLaparotomy=MLaparotomy[["Laparotomy", "rrrrrr"]].sum(axis=1)
MDR_MLaparotomy_N= pd.DataFrame(MDR_MLaparotomy, columns =['Laparotomy'])
MDR_MLaparotomy_T=((MDR_MLaparotomy_N['Laparotomy']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlLaparotomy= pd.DataFrame(MDR_MLaparotomy_T, columns =['Laparotomy'])
MDR_TROther1=pd.crosstab(data['Q116N_9B_1'], (data['Q116N_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116N_9B_2'], (data['Q116N_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlLaparotomy.loc['National'] = MDR_MOther_National
MDR_MPlLaparotomy

                                     Laparotomy

APH                                        15.0
PPH                                         5.0
Retained placenta                           0.0
Prolonged / Obstructed Labor                5.0
Ruptured uterus                            33.0
Post partum Sepsis                         20.0
Eclampsia                                   0.0
Sever complications of Abortion            43.0
Ectopic pregnancy                           0.0
Other Direct complication                   4.0
HIV/AIDS-related                            0.0
Severe Anemia                               0.0
Other indirect cause                        4.0
Cause of death Unknown                      0.0
No Information on on cause of death         0.0
National                                    4.0

In [1443]:
MDR_TRAntimalarials1=pd.crosstab(data['Q108_9B_1'], (data['Q116P_9B_1']))
MDR_TRAntimalarials2=pd.crosstab(data['Q108_9B_2'], (data['Q116P_9B_2']))
df1 = MDR_TRAntimalarials1.reset_index()
df2 = MDR_TRAntimalarials2.reset_index()
df = [MDR_TRAntimalarials1, MDR_TRAntimalarials2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MAntimalarials=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Antimalarials",'rrrrrr']
MAntimalarials.columns= labels_of_col[1:]
MAntimalarials.index= labels_of_col1[1:]
MAntimalarials.columns.names= [labels_of_col[0]]
MAntimalarials.index.names= [labels_of_col1[0]]
MDR_MAntimalarials=MAntimalarials[["Antimalarials", "rrrrrr"]].sum(axis=1)
MDR_MAntimalarials_N= pd.DataFrame(MDR_MAntimalarials, columns =['Antimalarials'])
MDR_MAntimalarials_T=((MDR_MAntimalarials_N['Antimalarials']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlAntimalarials= pd.DataFrame(MDR_MAntimalarials_T, columns =['Antimalarials'])
MDR_TROther1=pd.crosstab(data['Q116P_9B_1'], (data['Q116P_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116P_9B_2'], (data['Q116P_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlAntimalarials.loc['National'] = MDR_MOther_National
MDR_MPlAntimalarials

                                     Antimalarials

APH                                            0.0
PPH                                            2.0
Retained placenta                              6.0
Prolonged / Obstructed Labor                   5.0
Ruptured uterus                                0.0
Post partum Sepsis                            13.0
Eclampsia                                      5.0
Sever complications of Abortion                0.0
Ectopic pregnancy                              0.0
Other Direct complication                      0.0
HIV/AIDS-related                               0.0
Severe Anemia                                 27.0
Other indirect cause                           0.0
Cause of death Unknown                         0.0
No Information on on cause of death            1.0
National                                       2.0

In [1444]:
MDR_TROther1=pd.crosstab(data['Q108_9B_1'], (data['Q116Q_9B_1']))
MDR_TROther2=pd.crosstab(data['Q108_9B_2'], (data['Q116Q_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther=df_final.drop(-999)
labels_of_col1 =["",'APH','PPH','Retained placenta','Prolonged / Obstructed Labor','Ruptured uterus','Post partum Sepsis','Eclampsia','Sever complications of Abortion','Ectopic pregnancy','Other Direct complication','HIV/AIDS-related','Severe Anemia','Other indirect cause','Cause of death Unknown','No Information on on cause of death']
labels_of_col = ["","Other",'rrrrrr']
MOther.columns= labels_of_col[1:]
MOther.index= labels_of_col1[1:]
MOther.columns.names= [labels_of_col[0]]
MOther.index.names= [labels_of_col1[0]]
MDR_MOther=MOther[["Other", "rrrrrr"]].sum(axis=1)
MDR_MOther_N= pd.DataFrame(MDR_MOther, columns =['Other'])
MDR_MOther_T=((MDR_MOther_N['Other']/reviewed_maternal_deaths_according_to_treatment_Total['All maternal deaths reviewed'])*100).round(0)
MDR_MPlOther= pd.DataFrame(MDR_MOther_T, columns =['Other'])
MDR_TROther1=pd.crosstab(data['Q116Q_9B_1'], (data['Q116Q_9B_1']))
MDR_TROther2=pd.crosstab(data['Q116Q_9B_2'], (data['Q116Q_9B_2']))
df1 = MDR_TROther1.reset_index()
df2 = MDR_TROther2.reset_index()
df = [MDR_TROther1, MDR_TROther2]
df_final = pd.concat(df, axis=1)
del df_final[-999]
del df_final [0]
MOther1=df_final.drop(0)
MOthers=MOther1.drop(-999)
MDR_MOther=MOthers.sum()
MDR_MOtherddd=MDR_MOther.sum()
MDR_MOther_National=((MDR_MOtherddd/my_tab1denom)*100).round(0)
MDR_MPlOther.loc['National'] = MDR_MOther_National
MDR_MPlOther

                                     Other

APH                                    7.0
PPH                                   11.0
Retained placenta                      6.0
Prolonged / Obstructed Labor          15.0
Ruptured uterus                        7.0
Post partum Sepsis                     0.0
Eclampsia                             15.0
Sever complications of Abortion       14.0
Ectopic pregnancy                     50.0
Other Direct complication             17.0
HIV/AIDS-related                       0.0
Severe Anemia                          9.0
Other indirect cause                  15.0
Cause of death Unknown                17.0
No Information on on cause of death    1.0
National                               7.0

In [1456]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(reviewed_maternal_deaths_according_to_treatment_Total,MDR_MIV_fluids_Total,MDR_MPlasma_Total,MDR_MPlBlood_transfusion,MDR_MPlAntibiotics,MDR_MPlOxytocics,MDR_MPlManual_removal_of_placenta,MDR_MPlManual_vacuum_aspiration,MDR_MPlForceps,MDR_MPlVacuum_extraction,MDR_MPlCaesarean,MDR_MPlHysterectomy,MDR_MPlLaparotomy,MDR_MPlAntimalarials,MDR_MPlOther)
MDR_Treatment=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
MDR_Treatment1=MDR_Treatment.loc['APH':'Other Direct complication']
MDR_Treatment2=MDR_Treatment.loc['HIV/AIDS-related':'No Information on on cause of death']
MDR_Treatment3=MDR_Treatment.loc['National':]
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(MDR_Treatment1,MDR_Treatment2,MDR_Treatment3)
MDR_Treatment_Total=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Direct causes','Indirect causes','National'])
MDR_Treatment_Total

                                                     All maternal deaths reviewed  \
Direct causes   APH                                                          27.0
                PPH                                                          97.0
                Retained placenta                                            16.0
                Prolonged / Obstructed Labor                                 20.0
                Ruptured uterus                                              15.0
                Post partum Sepsis                                           15.0
                Eclampsia                                                    61.0
                Sever complications of Abortion                               7.0
                Ectopic pregnancy                                             2.0
                Other Direct complication                                    24.0
Indirect causes HIV/AIDS-related                                              2.0
                Severe Anemia                                                11.0
                Other indirect cause                                         27.0
                Cause of death Unknown                                        6.0
                No Information on on cause of death                         279.0
National        National                                                    608.0

                                                     IV_fluids  Plasma  \
Direct causes   APH                                       70.0    15.0
                PPH                                       65.0     5.0
                Retained placenta                         69.0     0.0
                Prolonged / Obstructed Labor              60.0     0.0
                Ruptured uterus                           87.0    13.0
                Post partum Sepsis                        87.0     0.0
                Eclampsia                                 69.0     7.0
                Sever complications of Abortion           86.0     0.0
                Ectopic pregnancy                         50.0     0.0
                Other Direct complication                 88.0    12.0
Indirect causes HIV/AIDS-related                          50.0     0.0
                Severe Anemia                            100.0    27.0
                Other indirect cause                      70.0     4.0
                Cause of death Unknown                    33.0     0.0
                No Information on on cause of death       13.0     0.0
National        National                                  44.0     4.0

                                                     Blood_transfusion  \
Direct causes   APH                                               30.0
                PPH                                               32.0
                Retained placenta                                  6.0
                Prolonged / Obstructed Labor                       5.0
                Ruptured uterus                                   47.0
                Post partum Sepsis                                33.0
                Eclampsia                                         16.0
                Sever complications of Abortion                   43.0
                Ectopic pregnancy                                 50.0
                Other Direct complication                         21.0
Indirect causes HIV/AIDS-related                                  50.0
                Severe Anemia                                     36.0
                Other indirect cause                              22.0
                Cause of death Unknown                             0.0
                No Information on on cause of death                1.0
National        National                                          14.0

                                                     Antibiotics  Oxytocics  \
Direct causes   APH                                         48.0       22.0
                PPH                                         39.0       48.0
                Retained placenta                           44.0       31.0
                Prolonged / Obstructed Labor                30.0       25.0
                Ruptured uterus                             53.0       20.0
                Post partum Sepsis                          87.0       53.0
                Eclampsia                                   61.0       30.0
                Sever complications of Abortion             86.0        0.0
                Ectopic pregnancy                           50.0        0.0
                Other Direct complication                   71.0       50.0
Indirect causes HIV/AIDS-related                            50.0        0.0
                Severe Anemia                               64.0       55.0
                Other indirect cause                        81.0       41.0
                Cause of death Unknown                      17.0        0.0
                No Information on on cause of death          9.0       12.0
National        National                                    33.0       25.0

                                                     Manual_removal_of_placenta  \
Direct causes   APH                                                         4.0
                PPH                                                        14.0
                Retained placenta                                          19.0
                Prolonged / Obstructed Labor                                0.0
                Ruptured uterus                                             7.0
                Post partum Sepsis                                          0.0
                Eclampsia                                                   7.0
                Sever complications of Abortion                             0.0
                Ectopic pregnancy                                           0.0
                Other Direct complication                                   8.0
Indirect causes HIV/AIDS-related                                            0.0
                Severe Anemia                                               9.0
                Other indirect cause                                        7.0
                Cause of death Unknown                                      0.0
                No Information on on cause of death                         2.0
National        National                                                    5.0

                                                     Manual_vacuum_aspiration  \
Direct causes   APH                                                       0.0
                PPH                                                       1.0
                Retained placenta                                         0.0
                Prolonged / Obstructed Labor                              0.0
                Ruptured uterus                                           0.0
                Post partum Sepsis                                        0.0
                Eclampsia                                                 2.0
                Sever complications of Abortion                          43.0
                Ectopic pregnancy                                         0.0
                Other Direct complication                                 0.0
Indirect causes HIV/AIDS-related                                          0.0
                Severe Anemia                                             0.0
                Other indirect cause                                      0.0
                Cause of death Unknown                                    0.0
                No Information on on cause of death                       0.0
National        National                                                  1.0

                                                     Forceps  \
Direct causes   APH                                      0.0
                PPH                                      1.0
                Retained placenta                        0.0
                Prolonged / Obstructed Labor             0.0
                Ruptured uterus                          0.0
                Post partum Sepsis                       0.0
                Eclampsia                                3.0
                Sever complications of Abortion          0.0
                Ectopic pregnancy                        0.0
                Other Direct complication                8.0
Indirect causes HIV/AIDS-related                         0.0
                Severe Anemia                            9.0
                Other indirect cause                     7.0
                Cause of death Unknown                   0.0
                No Information on on cause of death      0.0
National        National                                 1.0

                                                     Vacuum_extraction  \
Direct causes   APH                                                4.0
                PPH                                                0.0
                Retained placenta                                  0.0
                Prolonged / Obstructed Labor                       0.0
                Ruptured uterus                                    0.0
                Post partum Sepsis                                 0.0
                Eclampsia                                          7.0
                Sever complications of Abortion                    0.0
                Ectopic pregnancy                                  0.0
                Other Direct complication                          0.0
Indirect causes HIV/AIDS-related                                   0.0
                Severe Anemia                                      0.0
                Other indirect cause                               0.0
                Cause of death Unknown                             0.0
                No Information on on cause of death                1.0
National        National                                           1.0

                                                     Caesarean  Hysterectomy  \
Direct causes   APH                                       26.0          11.0
                PPH                                       11.0           6.0
                Retained placenta                          6.0           6.0
                Prolonged / Obstructed Labor              25.0           5.0
                Ruptured uterus                           33.0          40.0
                Post partum Sepsis                        40.0           7.0
                Eclampsia                                 13.0           0.0
                Sever complications of Abortion            0.0          29.0
                Ectopic pregnancy                          0.0           0.0
                Other Direct complication                 46.0           4.0
Indirect causes HIV/AIDS-related                          50.0           0.0
                Severe Anemia                              9.0           0.0
                Other indirect cause                      37.0           4.0
                Cause of death Unknown                     0.0           0.0
                No Information on on cause of death        3.0           0.0
National        National                                  12.0           4.0

                                                     Laparotomy  \
Direct causes   APH                                        15.0
                PPH                                         5.0
                Retained placenta                           0.0
                Prolonged / Obstructed Labor                5.0
                Ruptured uterus                            33.0
                Post partum Sepsis                         20.0
                Eclampsia                                   0.0
                Sever complications of Abortion            43.0
                Ectopic pregnancy                           0.0
                Other Direct complication                   4.0
Indirect causes HIV/AIDS-related                            0.0
                Severe Anemia                               0.0
                Other indirect cause                        4.0
                Cause of death Unknown                      0.0
                No Information on on cause of death         0.0
National        National                                    4.0

                                                     Antimalarials  Other
Direct causes   APH                                            0.0    7.0
                PPH                                            2.0   11.0
                Retained placenta                              6.0    6.0
                Prolonged / Obstructed Labor                   5.0   15.0
                Ruptured uterus                                0.0    7.0
                Post partum Sepsis                            13.0    0.0
                Eclampsia                                      5.0   15.0
                Sever complications of Abortion                0.0   14.0
                Ectopic pregnancy                              0.0   50.0
                Other Direct complication                      0.0   17.0
Indirect causes HIV/AIDS-related                               0.0    0.0
                Severe Anemia                                 27.0    9.0
                Other indirect cause                           0.0   15.0
                Cause of death Unknown                         0.0   17.0
                No Information on on cause of death            1.0    1.0
National        National                                       2.0    7.0

In [1457]:
MDR_Treatment_Total.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Maternal death reviews/Percent of reviewed maternal deaths according to treatment, by cause of death.csv")

In [395]:
MDRM_N1=pd.crosstab(data['Q109_9A_1'], (data['Q109_9A_1']))
MDRM_N2=pd.crosstab(data['Q109_9A_2'], (data['Q109_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_drop=df_final.drop(-999)
MDRM_fill=MDRM_drop.fillna(0)
MDRM_fill_sum=MDRM_fill.sum()
MDRM_fill_Total=MDRM_fill_sum.sum()
MDRM_fill_Total

1497

In [396]:
MDRM_N1=pd.crosstab(data['Q109_9A_1'], (data['Q103_9A_1']))
MDRM_N2=pd.crosstab(data['Q109_9A_2'], (data['Q103_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fill_sum=MDRM_fill.sum()
del MDRM_fill_sum[-999]
fffffff=((MDRM_fill_sum/MDRM_fill_Total)*100).round()
fffffff2=fffffff.drop(4)
fffffff3=fffffff2.drop(5)
eeeeee  = pd.DataFrame(fffffff3, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["","No evidence of complication/No information","Still birth or early neonatal death" , "Uterine scar","History of peripartum hemorrage","History of abortion","No previous pregnacy (Gravida=0)","Other specify in cell"]
labels_of_col = ["",'All PPH cases']
eeeeee.columns= labels_of_col[1:]
eeeeee.index= labels_of_col1[1:]
eeeeee.columns.names= [labels_of_col[0]]
eeeeee.index.names= [labels_of_col1[0]]
eeeeee

                                            All PPH cases

No evidence of complication/No information           80.0
Still birth or early neonatal death                   3.0
Uterine scar                                          1.0
History of peripartum hemorrage                       1.0
History of abortion                                   1.0
No previous pregnacy (Gravida=0)                     13.0
Other specify in cell                                 1.0

In [397]:
MDR_PPH1 = pd.crosstab(data['Q109_9A_1'], data['FT2'])
MDR_PPH2 = pd.crosstab(data['Q109_9A_2'], data['FT2'])
MDR_PPH_case=(MDR_PPH1+MDR_PPH2)
MDR_PPH=MDR_PPH_case.drop(-999)
MDR_PPH_cases=(MDR_PPH).sum()
MDR_PPH_Case_FT2  = pd.DataFrame(MDR_PPH_cases, columns =['Hospitals/MCH specialty centres'])
MDR_PPH_Case_FT2

     Hospitals/MCH specialty centres
FT2
1                                390
2                               1107

In [398]:
MDR_PPH1 = pd.crosstab(data['Q103_9A_1'], data['FT2'])
MDR_PPH2 = pd.crosstab(data['Q103_9A_2'], data['FT2'])
MDR_PPH_case=(MDR_PPH1+MDR_PPH2)
MDR_PPH=MDR_PPH_case.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_PPH.columns)
j=0
for i in li:
    MDR_PPH[i]=MDR_PPH[i]/x[j]
    j=j+1
week_of_death_fas2f=((MDR_PPH)*100).round(0) 
week_of_death_fas2fll=week_of_death_fas2f.drop(4)
week_of_death_fas2flld=week_of_death_fas2fll.drop(5)
labels_of_col1 =["","No evidence of complication/No information","Still birth or early neonatal death" , "Uterine scar","History of peripartum hemorrage","History of abortion","No previous pregnacy (Gravida=0)","Other specify in cell"]
labels_of_col = ["",'Hospitals/MCH specialty centres','Health centres/clinics']
week_of_death_fas2flld.columns= labels_of_col[1:]
week_of_death_fas2flld.index= labels_of_col1[1:]
week_of_death_fas2flld.columns.names= [labels_of_col[0]]
week_of_death_fas2flld.index.names= [labels_of_col1[0]]
week_of_death_fas2flld

,Hospitals/MCH specialty centres,Health centres/clinics
,,
No evidence of complication/No information,72.0,83.0
Still birth or early neonatal death,4.0,2.0
Uterine scar,2.0,0.0
History of peripartum hemorrage,1.0,1.0
History of abortion,2.0,1.0
No previous pregnacy (Gravida=0),17.0,12.0
Other specify in cell,2.0,1.0

In [399]:
MDR_PPH1 = pd.crosstab(data['Q109_9A_1'], data['MA3'])
MDR_PPH2 = pd.crosstab(data['Q109_9A_2'], data['MA3'])
MDR_PPH_case=(MDR_PPH1+MDR_PPH2)
MDR_PPH=MDR_PPH_case.drop(-999)
MDR_PPH_cases=(MDR_PPH).sum()
MDR_PPH_Case_FT  = pd.DataFrame(MDR_PPH_cases, columns =['Hospitals/MCH specialty centres'])
MDR_PPH_Case_FT

     Hospitals/MCH specialty centres
MA3
1                               1428
2                                 34
3                                 35

In [437]:
MDR_PPH_case
MDR_PPH1 = pd.crosstab(data['Q103_9A_1'], data['MA3'])
MDR_PPH2 = pd.crosstab(data['Q103_9A_2'], data['MA3'])
MDR_PPH_case=(MDR_PPH1+MDR_PPH2)
MDR_PPH=MDR_PPH_case.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_PPH.columns)
j=0
for i in li:
    MDR_PPH[i]=MDR_PPH[i]/x[j]
    j=j+1
week_of_death_fas2f=((MDR_PPH)*100).round(0) 
week_of_death_fas2fll=week_of_death_fas2f.drop(4)
week_of_death_fas2flld_MA3=week_of_death_fas2fll.drop(5)
labels_of_col1 =["","No evidence of complication/No information","Still birth or early neonatal death" , "Uterine scar","History of peripartum hemorrage","History of abortion","No previous pregnacy (Gravida=0)","Other specify in cell"]
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
week_of_death_fas2flld_MA3.columns= labels_of_col[1:]
week_of_death_fas2flld_MA3.index= labels_of_col1[1:]
week_of_death_fas2flld_MA3.columns.names= [labels_of_col[0]]
week_of_death_fas2flld_MA3.index.names= [labels_of_col1[0]]
week_of_death_fas2flld_MA3

,Public/government,Private-for-profit,Private-not-for-profit
,,,
No evidence of complication/No information,81.0,68.0,69.0
Still birth or early neonatal death,3.0,3.0,0.0
Uterine scar,1.0,6.0,3.0
History of peripartum hemorrage,1.0,0.0,0.0
History of abortion,1.0,12.0,0.0
No previous pregnacy (Gravida=0),13.0,12.0,29.0
Other specify in cell,1.0,0.0,0.0

In [438]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(eeeeee,week_of_death_fas2flld,week_of_death_fas2flld_MA3)
Couse_PPH=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Couse_PPH

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
No evidence of complication/No information,80.0,72.0,83.0,81.0,68.0,69.0
Still birth or early neonatal death,3.0,4.0,2.0,3.0,3.0,0.0
Uterine scar,1.0,2.0,0.0,1.0,6.0,3.0
History of peripartum hemorrage,1.0,1.0,1.0,1.0,0.0,0.0
History of abortion,1.0,2.0,1.0,1.0,12.0,0.0
No previous pregnacy (Gravida=0),13.0,17.0,12.0,13.0,12.0,29.0
Other specify in cell,1.0,2.0,1.0,1.0,0.0,0.0

In [439]:
MDRM_N1=pd.crosstab(data['Q105A_9A_1'], (data['Q105A_9A_1']))
MDRM_N2=pd.crosstab(data['Q105A_9A_2'], (data['Q105A_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fill_sum=df_final.sum()
MDRM_fill_sumrr=MDRM_fill_sum.drop(-999)
MDRM_fill_sumrrss=MDRM_fill_sumrr.drop(999)
MDR_CPPH=MDRM_fill_sumrrss.sum()
MDR_CPPHo=((MDR_CPPH/MDRM_fill_Total)*100).round(0)
MDR_CPPHo

67.0

In [440]:
MDRM_N1=pd.crosstab(data['Q106_9A_1'], (data['Q106_9A_1']))
MDRM_N2=pd.crosstab(data['Q106_9A_2'], (data['Q106_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fill_sum=df_final.sum()
MDRM_fill_sumrr=MDRM_fill_sum.drop(-999)
MDRM_fill_sumrrss=MDRM_fill_sumrr.drop(999)
MDR_CPPH=MDRM_fill_sumrrss.sum()
MDR_CPPHo1=((MDR_CPPH/MDRM_fill_Total)*100).round(0)
MDR_CPPHo1

50.0

In [441]:
MDRM_N1=pd.crosstab(data['Q107_9A_1'], (data['Q107_9A_1']))
MDRM_N2=pd.crosstab(data['Q107_9A_2'], (data['Q107_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fill_sum=MDRM_fill.sum()
MDRM_fill_sumrr=MDRM_fill_sum.drop(-999)
MDRM_fill_sumrrRR=MDRM_fill_sumrr.drop(0)
MDR_F2TTTTf  = pd.DataFrame(MDRM_fill_sumrrRR, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTff=((MDR_F2TTTTf/MDRM_fill_Total)*100).round(0)
labels_of_col1 =["",'Consciousness']
labels_of_col = ["","All PPH cases"]
MDR_F2TTTTff .columns= labels_of_col[1:]
MDR_F2TTTTff .index= labels_of_col1[1:]
MDR_F2TTTTff .columns.names= [labels_of_col[0]]
MDR_F2TTTTff .index.names= [labels_of_col1[0]]
MDR_F2TTTTff

               All PPH cases

Consciousness           88.0

In [442]:
MDRM_N1=pd.crosstab(data['Q108_9A_1'], (data['Q108_9A_1']))
MDRM_N2=pd.crosstab(data['Q108_9A_2'], (data['Q108_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fill_sum=MDRM_fill.sum()
MDRM_fill_sumrr=MDRM_fill_sum.drop(-999)
MDRM_fill_sumrrd=MDRM_fill_sumrr.drop(9999)
MDR_VSC=MDRM_fill_sumrrd.sum()
MDR_VSC1=(((MDR_VSC)/(MDRM_fill_Total))*100).round()
MDR_VSC1

13.0

In [443]:
fata = [['Blood pressure', 67], ['Pulse', 50], ['Consciousness', 88], ['Estimate of blood loss', 13]]
dffff = pd.DataFrame(fata, columns = ['', 'All PPH cases'])
PPH_casea  = pd.DataFrame(dffff, columns =['All PPH cases'])
labels_of_col1 =["",'Blood pressure','Pulse','Consciousness','Estimate of blood loss']
labels_of_col = ["",'All PPH cases']
PPH_casea.columns= labels_of_col[1:]
PPH_casea.index= labels_of_col1[1:]
PPH_casea.columns.names= [labels_of_col[0]]
PPH_casea.index.names= [labels_of_col1[0]]
PPH_casea

                        All PPH cases

Blood pressure                     67
Pulse                              50
Consciousness                      88
Estimate of blood loss             13

In [444]:
MDRM_N1=pd.crosstab(data['Q105A_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q105A_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fillrr=MDRM_fill.drop(-999)
MDRM_fillrrddd=MDRM_fillrr.drop(999)
ddddd=MDRM_fillrrddd.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f1=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Blood pressure']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2f1.columns= labels_of_col[1:]
week_of_death_fas2f1.index= labels_of_col1[1:]
week_of_death_fas2f1.columns.names= [labels_of_col[0]]
week_of_death_fas2f1.index.names= [labels_of_col1[0]]
week_of_death_fas2f1

                Hospitals/MCH specialty centres  Health centres/clinics

Blood pressure                             86.0                    60.0

In [445]:
MDRM_N1=pd.crosstab(data['Q106_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q106_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fillrr=MDRM_fill.drop(-999)
MDRM_fillrrddd=MDRM_fillrr.drop(999)
ddddd=MDRM_fillrrddd.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f2=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Pulse']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2f2.columns= labels_of_col[1:]
week_of_death_fas2f2.index= labels_of_col1[1:]
week_of_death_fas2f2.columns.names= [labels_of_col[0]]
week_of_death_fas2f2.index.names= [labels_of_col1[0]]
week_of_death_fas2f2

       Hospitals/MCH specialty centres  Health centres/clinics

Pulse                             79.0                    40.0

In [446]:
MDRM_N1=pd.crosstab(data['Q107_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q107_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalf=df_final.drop(0)
df_finalff=df_finalf.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f3=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Consciousness']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2f3.columns= labels_of_col[1:]
week_of_death_fas2f3.index= labels_of_col1[1:]
week_of_death_fas2f3.columns.names= [labels_of_col[0]]
week_of_death_fas2f3.index.names= [labels_of_col1[0]]
week_of_death_fas2f3

               Hospitals/MCH specialty centres  Health centres/clinics

Consciousness                             89.0                    88.0

In [447]:
MDRM_N1=pd.crosstab(data['Q108_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q108_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
df_finalffs=df_finalff.drop(9999)
ddddd=df_finalffs.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f4=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Estimate of blood loss']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
week_of_death_fas2f4.columns= labels_of_col[1:]
week_of_death_fas2f4.index= labels_of_col1[1:]
week_of_death_fas2f4.columns.names= [labels_of_col[0]]
week_of_death_fas2f4.index.names= [labels_of_col1[0]]
week_of_death_fas2f4

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Estimate of blood loss,18.0,11.0

In [448]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(week_of_death_fas2f1,week_of_death_fas2f2,week_of_death_fas2f3,week_of_death_fas2f4)
PPH_FT2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
PPH_FT2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Blood pressure,86.0,60.0
Pulse,79.0,40.0
Consciousness,89.0,88.0
Estimate of blood loss,18.0,11.0

In [449]:
MDRM_N1=pd.crosstab(data['Q105A_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q105A_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fillrr=MDRM_fill.drop(-999)
MDRM_fillrrddd=MDRM_fillrr.drop(999)
ddddd=MDRM_fillrrddd.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f1=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Blood pressure']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
week_of_death_fas2f1.columns= labels_of_col[1:]
week_of_death_fas2f1.index= labels_of_col1[1:]
week_of_death_fas2f1.columns.names= [labels_of_col[0]]
week_of_death_fas2f1.index.names= [labels_of_col1[0]]
week_of_death_fas2f1  
MDRM_N1=pd.crosstab(data['Q106_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q106_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
MDRM_fill=df_final.fillna(0)
MDRM_fillrr=MDRM_fill.drop(-999)
MDRM_fillrrddd=MDRM_fillrr.drop(999)
ddddd=MDRM_fillrrddd.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f2=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Pulse']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
week_of_death_fas2f2.columns= labels_of_col[1:]
week_of_death_fas2f2.index= labels_of_col1[1:]
week_of_death_fas2f2.columns.names= [labels_of_col[0]]
week_of_death_fas2f2.index.names= [labels_of_col1[0]]
week_of_death_fas2f2 
MDRM_N1=pd.crosstab(data['Q107_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q107_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalf=df_final.drop(0)
df_finalff=df_finalf.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f3=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Consciousness']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
week_of_death_fas2f3.columns= labels_of_col[1:]
week_of_death_fas2f3.index= labels_of_col1[1:]
week_of_death_fas2f3.columns.names= [labels_of_col[0]]
week_of_death_fas2f3.index.names= [labels_of_col1[0]]
week_of_death_fas2f3 
MDRM_N1=pd.crosstab(data['Q108_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q108_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
df_finalffs=df_finalff.drop(9999)
ddddd=df_finalffs.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffyyyy=MDR_F2TTTTff.transpose()
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_F2TTTTffyyyy.columns)
j=0
for i in li:
    MDR_F2TTTTffyyyy[i]=MDR_F2TTTTffyyyy[i]/x[j]
    j=j+1
week_of_death_fas2f4=((MDR_F2TTTTffyyyy)*100).round(0)  
labels_of_col1 =["",'Estimate of blood loss']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
week_of_death_fas2f4.columns= labels_of_col[1:]
week_of_death_fas2f4.index= labels_of_col1[1:]
week_of_death_fas2f4.columns.names= [labels_of_col[0]]
week_of_death_fas2f4.index.names= [labels_of_col1[0]]
week_of_death_fas2f4
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(week_of_death_fas2f1,week_of_death_fas2f2,week_of_death_fas2f3,week_of_death_fas2f4)
PPH_MA3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
PPH_MA3

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Blood pressure,66.0,94.0,74.0
Pulse,49.0,76.0,51.0
Consciousness,88.0,94.0,91.0
Estimate of blood loss,12.0,59.0,26.0

In [450]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(PPH_casea,PPH_FT2,PPH_MA3)
PPH_MA3_FT2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
PPH_MA3_FT2

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Blood pressure,67,86.0,60.0,66.0,94.0,74.0
Pulse,50,79.0,40.0,49.0,76.0,51.0
Consciousness,88,89.0,88.0,88.0,94.0,91.0
Estimate of blood loss,13,18.0,11.0,12.0,59.0,26.0

In [451]:
MDRM_N1=pd.crosstab(data['Q109_9A_1'], (data['Q109_9A_1']))
MDRM_N2=pd.crosstab(data['Q109_9A_2'], (data['Q109_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff= pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffd=MDR_F2TTTTff.drop(-999)
MDR_F2TTTTffddgggs=((MDR_F2TTTTffd/1497)*100).round(0)
labels_of_col1 =["",'Uterine atony','Trauma','Retained placenta','Clotting disorder','No information ','Other']
labels_of_col = ["",'All PPH cases']
MDR_F2TTTTffddggg.columns= labels_of_col[1:]
MDR_F2TTTTffddggg.index= labels_of_col1[1:]
MDR_F2TTTTffddggg.columns.names= [labels_of_col[0]]
MDR_F2TTTTffddggg.index.names= [labels_of_col1[0]]
MDR_F2TTTTffddggg

                   All PPH cases

Uterine atony               14.0
Trauma                       6.0
Retained placenta           19.0
Clotting disorder            1.0
No information              61.0
Other                        1.0

In [452]:
MDRM_N1=pd.crosstab(data['Q109_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q109_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
FT2_pph=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'Uterine atony','Trauma','Retained placenta','Clotting disorder','No information ','Other']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
FT2_pph.columns= labels_of_col[1:]
FT2_pph.index= labels_of_col1[1:]
FT2_pph.columns.names= [labels_of_col[0]]
FT2_pph.index.names= [labels_of_col1[0]]
FT2_pph

                   Hospitals/MCH specialty centres  Health centres/clinics

Uterine atony                                 25.0                    10.0
Trauma                                        12.0                     4.0
Retained placenta                             33.0                    14.0
Clotting disorder                              1.0                     1.0
No information                                28.0                    72.0
Other                                          1.0                     0.0

In [453]:
MDRM_N1=pd.crosstab(data['Q109_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q109_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
MA3_pph=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'Uterine atony','Trauma','Retained placenta','Clotting disorder','No information ','Other']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MA3_pph.columns= labels_of_col[1:]
MA3_pph.index= labels_of_col1[1:]
MA3_pph.columns.names= [labels_of_col[0]]
MA3_pph.index.names= [labels_of_col1[0]]
MA3_pph

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Uterine atony,13.0,29.0,20.0
Trauma,6.0,12.0,9.0
Retained placenta,19.0,12.0,14.0
Clotting disorder,0.0,6.0,6.0
No information,61.0,41.0,51.0
Other,1.0,0.0,0.0

In [454]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffddggg,FT2_pph,MA3_pph)
Cause_of_PPH_T=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Uterine atony,14.0,25.0,10.0,13.0,29.0,20.0
Trauma,6.0,12.0,4.0,6.0,12.0,9.0
Retained placenta,19.0,33.0,14.0,19.0,12.0,14.0
Clotting disorder,1.0,1.0,1.0,0.0,6.0,6.0
No information,61.0,28.0,72.0,61.0,41.0,51.0
Other,1.0,1.0,0.0,1.0,0.0,0.0

In [455]:
MDRM_N1=pd.crosstab(data['Q110_9A_1'], (data['Q110_9A_1']))
MDRM_N2=pd.crosstab(data['Q110_9A_2'], (data['Q110_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff= pd.DataFrame(ddddd, columns =['All PPH cases'])
df_finalffdd=MDR_F2TTTTff.drop(-999)
Antecedents=((df_finalffdd/1497)*100).round(0)
labels_of_col1 =["","No/no information" , "Yes, with oxytocin",'Yes, with other uterotonic']
labels_of_col = ["",'All PPH cases']
Antecedents.columns= labels_of_col[1:]
Antecedents.index= labels_of_col1[1:]
Antecedents.columns.names= [labels_of_col[0]]
Antecedents.index.names= [labels_of_col1[0]]
Antecedents

                            All PPH cases

No/no information                    93.0
Yes, with oxytocin                    7.0
Yes, with other uterotonic            1.0

In [456]:
MDRM_N1=pd.crosstab(data['Q110_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q110_9A_2'], (data['FT2']))
ddee=MDRM_N1+MDRM_N2
MDR_F2TTTTfft2=ddee.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(MDR_F2TTTTfft2 .columns)
j=0
for i in li:
    MDR_F2TTTTfft2[i]=MDR_F2TTTTfft2[i]/x[j]
    j=j+1
Antecedents_FT2=((MDR_F2TTTTfft2)*100).round(0)  
labels_of_col1 =["","No/no information" , "Yes, with oxytocin",'Yes, with other uterotonic']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Antecedents_FT2.columns= labels_of_col[1:]
Antecedents_FT2.index= labels_of_col1[1:]
Antecedents_FT2.columns.names= [labels_of_col[0]]
Antecedents_FT2.index.names= [labels_of_col1[0]]
Antecedents_FT2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
No/no information,85.0,95.0
"Yes, with oxytocin",13.0,4.0
"Yes, with other uterotonic",2.0,0.0

In [457]:
MDRM_N1=pd.crosstab(data['Q110_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q110_9A_2'], (data['MA3']))
ddee=MDRM_N1+MDRM_N2
MDR_F2TTTTfMA3=ddee.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(MDR_F2TTTTfMA3 .columns)
j=0
for i in li:
    MDR_F2TTTTfMA3[i]=MDR_F2TTTTfMA3[i]/x[j]
    j=j+1
Antecedents_MA3=((MDR_F2TTTTfMA3)*100).round(0)  
labels_of_col1 =["","No/no information" , "Yes, with oxytocin",'Yes, with other uterotonic']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
Antecedents_MA3.columns= labels_of_col[1:]
Antecedents_MA3.index= labels_of_col1[1:]
Antecedents_MA3.columns.names= [labels_of_col[0]]
Antecedents_MA3.index.names= [labels_of_col1[0]]
Antecedents_MA3

,Public/government,Private-for-profit,Private-not-for-profit
,,,
No/no information,93.0,71.0,80.0
"Yes, with oxytocin",6.0,26.0,17.0
"Yes, with other uterotonic",1.0,3.0,3.0

In [458]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Antecedents,Antecedents_FT2,Antecedents_MA3)
Cause_of_PPH_FT2_MA3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_FT2_MA3

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
No/no information,93.0,85.0,95.0,93.0,71.0,80.0
"Yes, with oxytocin",7.0,13.0,4.0,6.0,26.0,17.0
"Yes, with other uterotonic",1.0,2.0,0.0,1.0,3.0,3.0

In [459]:
MDRM_N1=pd.crosstab(data['Q111_9A_1'], (data['Q111_9A_1']))
MDRM_N2=pd.crosstab(data['Q111_9A_2'], (data['Q111_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff= pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffd=MDR_F2TTTTff.drop(-999)
MDR_F2TTTTffddgggs=((MDR_F2TTTTffd/1497)*100).round(0)
labels_of_col1 =["",'None/no information','APH','Multiple pregnancy','Uterine myoma','Pre eclampsia/eclampsia ','Other direct obstetric complication','Other indirect obstetric complication','Other specify']
labels_of_col = ["",'All PPH cases']
MDR_F2TTTTffddgggs.columns= labels_of_col[1:]
MDR_F2TTTTffddgggs.index= labels_of_col1[1:]
MDR_F2TTTTffddgggs.columns.names= [labels_of_col[0]]
MDR_F2TTTTffddgggs.index.names= [labels_of_col1[0]]
MDR_F2TTTTffddgggs

                                       All PPH cases

None/no information                             89.0
APH                                              3.0
Multiple pregnancy                               2.0
Uterine myoma                                    0.0
Pre eclampsia/eclampsia                          2.0
Other direct obstetric complication              1.0
Other indirect obstetric complication            1.0
Other specify                                    1.0

In [460]:
MDRM_N1=pd.crosstab(data['Q111_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q111_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
FT2_pph=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'None/no information','APH','Multiple pregnancy','Uterine myoma','Pre eclampsia/eclampsia ','Other direct obstetric complication','Other indirect obstetric complication','Other specify']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
FT2_pph.columns= labels_of_col[1:]
FT2_pph.index= labels_of_col1[1:]
FT2_pph.columns.names= [labels_of_col[0]]
FT2_pph.index.names= [labels_of_col1[0]]
FT2_pph1=FT2_pph.fillna(1)
FT2_pph1

,Hospitals/MCH specialty centres,Health centres/clinics
,,
None/no information,79.0,92.0
APH,4.0,3.0
Multiple pregnancy,4.0,2.0
Uterine myoma,1.0,0.0
Pre eclampsia/eclampsia,4.0,1.0
Other direct obstetric complication,3.0,0.0
Other indirect obstetric complication,4.0,0.0
Other specify,1.0,1.0

In [461]:
MDRM_N1=pd.crosstab(data['Q111_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q111_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
MA3_pph1=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'None/no information','APH','Multiple pregnancy','Uterine myoma','Pre eclampsia/eclampsia ','Other direct obstetric complication','Other indirect obstetric complication','Other specify']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MA3_pph1.columns= labels_of_col[1:]
MA3_pph1.index= labels_of_col1[1:]
MA3_pph1.columns.names= [labels_of_col[0]]
MA3_pph1.index.names= [labels_of_col1[0]]
MA3_pph1

,Public/government,Private-for-profit,Private-not-for-profit
,,,
None/no information,90.0,76.0,77.0
APH,3.0,6.0,9.0
Multiple pregnancy,2.0,3.0,3.0
Uterine myoma,0.0,0.0,0.0
Pre eclampsia/eclampsia,2.0,3.0,0.0
Other direct obstetric complication,1.0,6.0,9.0
Other indirect obstetric complication,1.0,3.0,0.0
Other specify,NaN,NaN,NaN

In [462]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffddgggs,FT2_pph1,MA3_pph1)
Cause_of_PPH_T2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T2

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
None/no information,89.0,79.0,92.0,90.0,76.0,77.0
APH,3.0,4.0,3.0,3.0,6.0,9.0
Multiple pregnancy,2.0,4.0,2.0,2.0,3.0,3.0
Uterine myoma,0.0,1.0,0.0,0.0,0.0,0.0
Pre eclampsia/eclampsia,2.0,4.0,1.0,2.0,3.0,0.0
Other direct obstetric complication,1.0,3.0,0.0,1.0,6.0,9.0
Other indirect obstetric complication,1.0,4.0,0.0,1.0,3.0,0.0
Other specify,1.0,1.0,1.0,NaN,NaN,NaN

In [463]:
MDRM_N1=pd.crosstab(data['Q113_9A_1'], (data['Q113_9A_1']))
MDRM_N2=pd.crosstab(data['Q113_9A_2'], (data['Q113_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
df_finalff0=df_finalff.drop(0)
ddddd=df_finalff0.sum()
MDR_F2TTTTff  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffd=MDR_F2TTTTff.drop(-999)
MDR_F2TTTTffddgggs=((MDR_F2TTTTffd/1497)*100).round(0)
labels_of_col1 =["",'None1','Episiotomy']
labels_of_col = ["",'All PPH cases']
MDR_F2TTTTffddgggs.columns= labels_of_col[1:]
MDR_F2TTTTffddgggs.index= labels_of_col1[1:]
MDR_F2TTTTffddgggs.columns.names= [labels_of_col[0]]
MDR_F2TTTTffddgggs.index.names= [labels_of_col1[0]]
MDR_F2TTTTffddgggsh=MDR_F2TTTTffddgggs.drop('None1')
MDR_F2TTTTffddgggsh

            All PPH cases

Episiotomy           10.0

In [464]:
MDRM_N1=pd.crosstab(data['Q113_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q113_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
FT2_pph=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'None1','Episiotomy']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
FT2_pph.columns= labels_of_col[1:]
FT2_pph.index= labels_of_col1[1:]
FT2_pph.columns.names= [labels_of_col[0]]
FT2_pph.index.names= [labels_of_col1[0]]
FT2_pph1=FT2_pph.fillna(1)
FT2_pph12=FT2_pph1.drop('None1')
FT2_pph12

            Hospitals/MCH specialty centres  Health centres/clinics

Episiotomy                             11.0                    10.0

In [465]:
MDRM_N1=pd.crosstab(data['Q113_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q113_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
MA3_pph1=((ffdrdd)*100).round(0)  
labels_of_col1 =["",'None1','Episiotomy']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MA3_pph1.columns= labels_of_col[1:]
MA3_pph1.index= labels_of_col1[1:]
MA3_pph1.columns.names= [labels_of_col[0]]
MA3_pph1.index.names= [labels_of_col1[0]]
MA3_pph112=MA3_pph1.drop('None1')
MA3_pph112

            Public/government  Private-for-profit  Private-not-for-profit

Episiotomy               10.0                15.0                     17.0

In [466]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffddgggsh,FT2_pph12,MA3_pph112)
Cause_of_PPH_T12=pd.concat(Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T12

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Episiotomy,10.0,11.0,10.0,10.0,15.0,17.0

In [467]:
MDRM_N1=pd.crosstab(data['Q112_9A_1'], (data['Q112_9A_1']))
MDRM_N2=pd.crosstab(data['Q112_9A_2'], (data['Q112_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalff=df_final.drop(-999)
ddddd=df_finalff.sum()
MDR_F2TTTTff= pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffd=MDR_F2TTTTff.drop(-999)
MDR_F2TTTTffddgggsl=((MDR_F2TTTTffd/1497)*100).round(0)
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["",'All PPH cases']
MDR_F2TTTTffddgggsl.columns= labels_of_col[1:]
MDR_F2TTTTffddgggsl.index= labels_of_col1[1:]
MDR_F2TTTTffddgggsl.columns.names= [labels_of_col[0]]
MDR_F2TTTTffddgggsl.index.names= [labels_of_col1[0]]
MDR_F2TTTTffddgggsl

                All PPH cases

Vaginal                  87.0
Instrumental              2.0
Caesarean                 3.0
No information            8.0

In [468]:
MDRM_N1=pd.crosstab(data['Q112_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q112_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT2['Hospitals/MCH specialty centres'][2]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
FT2_pph=((ffdrdd)*100).round(0)
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
FT2_pph.columns= labels_of_col[1:]
FT2_pph.index= labels_of_col1[1:]
FT2_pph.columns.names= [labels_of_col[0]]
FT2_pph.index.names= [labels_of_col1[0]]
FT2_pph13=FT2_pph.fillna(1)
FT2_pph13

                Hospitals/MCH specialty centres  Health centres/clinics

Vaginal                                    78.0                    90.0
Instrumental                                6.0                     1.0
Caesarean                                   9.0                     0.0
No information                              7.0                     8.0

In [469]:
MDRM_N1=pd.crosstab(data['Q112_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q112_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
x=[MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][1],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][2],MDR_PPH_Case_FT['Hospitals/MCH specialty centres'][3]]
li=list(ffdrdd.columns)
j=0
for i in li:
    ffdrdd[i]=ffdrdd[i]/x[j]
    j=j+1
MA3_pph13=((ffdrdd)*100).round(0) 
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MA3_pph13.columns= labels_of_col[1:]
MA3_pph13.index= labels_of_col1[1:]
MA3_pph13.columns.names= [labels_of_col[0]]
MA3_pph13.index.names= [labels_of_col1[0]]
MA3_pph13

                Public/government  Private-for-profit  Private-not-for-profit

Vaginal                      88.0                56.0                     83.0
Instrumental                  2.0                 3.0                      6.0
Caesarean                     1.0                38.0                     11.0
No information                8.0                 3.0                      0.0

In [470]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffddgggsl,FT2_pph13,MA3_pph13)
Cause_of_PPH_T3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T3

,All PPH cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Vaginal,87.0,78.0,90.0,88.0,56.0,83.0
Instrumental,2.0,6.0,1.0,2.0,3.0,6.0
Caesarean,3.0,9.0,0.0,1.0,38.0,11.0
No information,8.0,7.0,8.0,8.0,3.0,0.0

In [478]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Couse_PPH,PPH_MA3_FT2,Cause_of_PPH_T,Cause_of_PPH_FT2_MA3,Cause_of_PPH_T2,Cause_of_PPH_T12,Cause_of_PPH_T3)
last=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Complications in previous pregnancy','Vital signs checked on admission','Cause of PPH','Antecedents','Presence of complication other than PPH','Episiotomy','Mode of delivery'])
last

                                                                                    All PPH cases  \

Complications in previous pregnancy     No evidence of complication/No information           80.0
                                        Still birth or early neonatal death                   3.0
                                        Uterine scar                                          1.0
                                        History of peripartum hemorrage                       1.0
                                        History of abortion                                   1.0
                                        No previous pregnacy (Gravida=0)                     13.0
                                        Other specify in cell                                 1.0
Vital signs checked on admission        Blood pressure                                       67.0
                                        Pulse                                                50.0
                                        Consciousness                                        88.0
                                        Estimate of blood loss                               13.0
Cause of PPH                            Uterine atony                                        14.0
                                        Trauma                                                6.0
                                        Retained placenta                                    19.0
                                        Clotting disorder                                     1.0
                                        No information                                       61.0
                                        Other                                                 1.0
Antecedents                             No/no information                                    93.0
                                        Yes, with oxytocin                                    7.0
                                        Yes, with other uterotonic                            1.0
Presence of complication other than PPH None/no information                                  89.0
                                        APH                                                   3.0
                                        Multiple pregnancy                                    2.0
                                        Uterine myoma                                         0.0
                                        Pre eclampsia/eclampsia                               2.0
                                        Other direct obstetric complication                   1.0
                                        Other indirect obstetric complication                 1.0
                                        Other specify                                         1.0
Episiotomy                              Episiotomy                                           10.0
Mode of delivery                        Vaginal                                              87.0
                                        Instrumental                                          2.0
                                        Caesarean                                             3.0
                                        No information                                        8.0

                                                                                    Hospitals/MCH specialty centres  \

Complications in previous pregnancy     No evidence of complication/No information                             72.0
                                        Still birth or early neonatal death                                     4.0
                                        Uterine scar                                                            2.0
                                        History of peripartum hemorrage                                         1.0
                                        History of abortion                                                     2.0
                                        No previous pregnacy (Gravida=0)                                       17.0
                                        Other specify in cell                                                   2.0
Vital signs checked on admission        Blood pressure                                                         86.0
                                        Pulse                                                                  79.0
                                        Consciousness                                                          89.0
                                        Estimate of blood loss                                                 18.0
Cause of PPH                            Uterine atony                                                          25.0
                                        Trauma                                                                 12.0
                                        Retained placenta                                                      33.0
                                        Clotting disorder                                                       1.0
                                        No information                                                         28.0
                                        Other                                                                   1.0
Antecedents                             No/no information                                                      85.0
                                        Yes, with oxytocin                                                     13.0
                                        Yes, with other uterotonic                                              2.0
Presence of complication other than PPH None/no information                                                    79.0
                                        APH                                                                     4.0
                                        Multiple pregnancy                                                      4.0
                                        Uterine myoma                                                           1.0
                                        Pre eclampsia/eclampsia                                                 4.0
                                        Other direct obstetric complication                                     3.0
                                        Other indirect obstetric complication                                   4.0
                                        Other specify                                                           1.0
Episiotomy                              Episiotomy                                                             11.0
Mode of delivery                        Vaginal                                                                78.0
                                        Instrumental                                                            6.0
                                        Caesarean                                                               9.0
                                        No information                                                          7.0

                                                                                    Health centres/clinics  \

Complications in previous pregnancy     No evidence of complication/No information                    83.0
                                        Still birth or early neonatal death                            2.0
                                        Uterine scar                                                   0.0
                                        History of peripartum hemorrage                                1.0
                                        History of abortion                                            1.0
                                        No previous pregnacy (Gravida=0)                              12.0
                                        Other specify in cell                                          1.0
Vital signs checked on admission        Blood pressure                                                60.0
                                        Pulse                                                         40.0
                                        Consciousness                                                 88.0
                                        Estimate of blood loss                                        11.0
Cause of PPH                            Uterine atony                                                 10.0
                                        Trauma                                                         4.0
                                        Retained placenta                                             14.0
                                        Clotting disorder                                              1.0
                                        No information                                                72.0
                                        Other                                                          0.0
Antecedents                             No/no information                                             95.0
                                        Yes, with oxytocin                                             4.0
                                        Yes, with other uterotonic                                     0.0
Presence of complication other than PPH None/no information                                           92.0
                                        APH                                                            3.0
                                        Multiple pregnancy                                             2.0
                                        Uterine myoma                                                  0.0
                                        Pre eclampsia/eclampsia                                        1.0
                                        Other direct obstetric complication                            0.0
                                        Other indirect obstetric complication                          0.0
                                        Other specify                                                  1.0
Episiotomy                              Episiotomy                                                    10.0
Mode of delivery                        Vaginal                                                       90.0
                                        Instrumental                                                   1.0
                                        Caesarean                                                      0.0
                                        No information                                                 8.0

                                                                                    Public/government  \

Complications in previous pregnancy     No evidence of complication/No information               81.0
                                        Still birth or early neonatal death                       3.0
                                        Uterine scar                                              1.0
                                        History of peripartum hemorrage                           1.0
                                        History of abortion                                       1.0
                                        No previous pregnacy (Gravida=0)                         13.0
                                        Other specify in cell                                     1.0
Vital signs checked on admission        Blood pressure                                           66.0
                                        Pulse                                                    49.0
                                        Consciousness                                            88.0
                                        Estimate of blood loss                                   12.0
Cause of PPH                            Uterine atony                                            13.0
                                        Trauma                                                    6.0
                                        Retained placenta                                        19.0
                                        Clotting disorder                                         0.0
                                        No information                                           61.0
                                        Other                                                     1.0
Antecedents                             No/no information                                        93.0
                                        Yes, with oxytocin                                        6.0
                                        Yes, with other uterotonic                                1.0
Presence of complication other than PPH None/no information                                      90.0
                                        APH                                                       3.0
                                        Multiple pregnancy                                        2.0
                                        Uterine myoma                                             0.0
                                        Pre eclampsia/eclampsia                                   2.0
                                        Other direct obstetric complication                       1.0
                                        Other indirect obstetric complication                     1.0
                                        Other specify                                             NaN
Episiotomy                              Episiotomy                                               10.0
Mode of delivery                        Vaginal                                                  88.0
                                        Instrumental                                              2.0
                                        Caesarean                                                 1.0
                                        No information                                            8.0

                                                                                    Private-for-profit  \

Complications in previous pregnancy     No evidence of complication/No information                68.0
                                        Still birth or early neonatal death                        3.0
                                        Uterine scar                                               6.0
                                        History of peripartum hemorrage                            0.0
                                        History of abortion                                       12.0
                                        No previous pregnacy (Gravida=0)                          12.0
                                        Other specify in cell                                      0.0
Vital signs checked on admission        Blood pressure                                            94.0
                                        Pulse                                                     76.0
                                        Consciousness                                             94.0
                                        Estimate of blood loss                                    59.0
Cause of PPH                            Uterine atony                                             29.0
                                        Trauma                                                    12.0
                                        Retained placenta                                         12.0
                                        Clotting disorder                                          6.0
                                        No information                                            41.0
                                        Other                                                      0.0
Antecedents                             No/no information                                         71.0
                                        Yes, with oxytocin                                        26.0
                                        Yes, with other uterotonic                                 3.0
Presence of complication other than PPH None/no information                                       76.0
                                        APH                                                        6.0
                                        Multiple pregnancy                                         3.0
                                        Uterine myoma                                              0.0
                                        Pre eclampsia/eclampsia                                    3.0
                                        Other direct obstetric complication                        6.0
                                        Other indirect obstetric complication                      3.0
                                        Other specify                                              NaN
Episiotomy                              Episiotomy                                                15.0
Mode of delivery                        Vaginal                                                   56.0
                                        Instrumental                                               3.0
                                        Caesarean                                                 38.0
                                        No information                                             3.0

                                                                                    Private-not-for-profit

Complications in previous pregnancy     No evidence of complication/No information                     69.0
                                        Still birth or early neonatal death                             0.0
                                        Uterine scar                                                    3.0
                                        History of peripartum hemorrage                                 0.0
                                        History of abortion                                             0.0
                                        No previous pregnacy (Gravida=0)                               29.0
                                        Other specify in cell                                           0.0
Vital signs checked on admission        Blood pressure                                                 74.0
                                        Pulse                                                          51.0
                                        Consciousness                                                  91.0
                                        Estimate of blood loss                                         26.0
Cause of PPH                            Uterine atony                                                  20.0
                                        Trauma                                                          9.0
                                        Retained placenta                                              14.0
                                        Clotting disorder                                               6.0
                                        No information                                                 51.0
                                        Other                                                           0.0
Antecedents                             No/no information                                              80.0

In [480]:
last.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Not sent/Maternal complication reviews/reviewed PPH cases according tocomplications in previous pregnancy vital signs checked cause of PPH and antecedent.csv")

In [452]:
MDRM_N1=pd.crosstab(data['Q203_9A_1'], (data['Q203_9A_1']))
MDRM_N2=pd.crosstab(data['Q203_9A_2'], (data['Q203_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
MDR_F2TTTTffp  = pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffpd1=MDR_F2TTTTffp.drop(-999)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd1.drop(96)
MDR_F2TTTTffpd3=MDR_F2TTTTffpd2.drop(8)
MDR_F2TTTTffpd4=((MDR_F2TTTTffpd3/959)*100).round(0)
labels_of_col1 =["",'None/no information','Stillbirth or early neonatal death','History of PE/E','History of diabetes mellitus','History of chronic hypertension','History of abortion','No previous pregnancy']
labels_of_col = ["","All severe PE/E cases"]
MDR_F2TTTTffpd4.columns= labels_of_col[1:]
MDR_F2TTTTffpd4.index= labels_of_col1[1:]
MDR_F2TTTTffpd4.columns.names= [labels_of_col[0]]
MDR_F2TTTTffpd4.index.names= [labels_of_col1[0]]
MDR_F2TTTTffpd4

                                    All severe PE/E cases

None/no information                                  65.0
Stillbirth or early neonatal death                    3.0
History of PE/E                                       2.0
History of diabetes mellitus                          1.0
History of chronic hypertension                       1.0
History of abortion                                   3.0
No previous pregnancy                                26.0

In [453]:
MDRM_N1=pd.crosstab(data['Q203_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q203_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
MDR_F2TTTTffpd1=ffdrdd.drop(8)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd1.drop(96)
x=[417,542]
li=list(MDR_F2TTTTffpd2.columns)
j=0
for i in li:
    MDR_F2TTTTffpd2[i]=MDR_F2TTTTffpd2[i]/x[j]
    j=j+1
MDR_F2TTTTffpd2=((MDR_F2TTTTffpd2)*100).round(0)
labels_of_col1 =["",'None/no information','Stillbirth or early neonatal death','History of PE/E','History of diabetes mellitus','History of chronic hypertension','History of abortion','No previous pregnancy']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffpd2.columns= labels_of_col[1:]
MDR_F2TTTTffpd2.index= labels_of_col1[1:]
MDR_F2TTTTffpd2.columns.names= [labels_of_col[0]]
MDR_F2TTTTffpd2.index.names= [labels_of_col1[0]]
MDR_F2TTTTffpd2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
None/no information,56.0,72.0
Stillbirth or early neonatal death,4.0,2.0
History of PE/E,4.0,1.0
History of diabetes mellitus,1.0,0.0
History of chronic hypertension,1.0,1.0
History of abortion,4.0,1.0
No previous pregnancy,31.0,22.0

In [454]:
MDRM_N1=pd.crosstab(data['Q203_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q203_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
ffdrdd=ffdr.drop(-999)
MDR_F2TTTTffpd1=ffdrdd.drop(8)
MDR_F2TTTTffpd23=MDR_F2TTTTffpd1.drop(96)
x=[863,60,36]
li=list(MDR_F2TTTTffpd23.columns)
j=0
for i in li:
    MDR_F2TTTTffpd23[i]=MDR_F2TTTTffpd23[i]/x[j]
    j=j+1
MDR_F2TTTTffpd23=((MDR_F2TTTTffpd23)*100).round(0)
labels_of_col1 =["",'None/no information','Stillbirth or early neonatal death','History of PE/E','History of diabetes mellitus','History of chronic hypertension','History of abortion','No previous pregnancy']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffpd23.columns= labels_of_col[1:]
MDR_F2TTTTffpd23.index= labels_of_col1[1:]
MDR_F2TTTTffpd23.columns.names= [labels_of_col[0]]
MDR_F2TTTTffpd23.index.names= [labels_of_col1[0]]
MDR_F2TTTTffpd23

,Public/government,Private-for-profit,Private-not-for-profit
,,,
None/no information,66.0,47.0,61.0
Stillbirth or early neonatal death,3.0,2.0,3.0
History of PE/E,2.0,5.0,0.0
History of diabetes mellitus,0.0,3.0,0.0
History of chronic hypertension,1.0,0.0,0.0
History of abortion,2.0,13.0,3.0
No previous pregnancy,25.0,30.0,33.0

In [455]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffpd4,MDR_F2TTTTffpd2,MDR_F2TTTTffpd23)
Cause_of_PPH_TT=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_TT

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
None/no information,65.0,56.0,72.0,66.0,47.0,61.0
Stillbirth or early neonatal death,3.0,4.0,2.0,3.0,2.0,3.0
History of PE/E,2.0,4.0,1.0,2.0,5.0,0.0
History of diabetes mellitus,1.0,1.0,0.0,0.0,3.0,0.0
History of chronic hypertension,1.0,1.0,1.0,1.0,0.0,0.0
History of abortion,3.0,4.0,1.0,2.0,13.0,3.0
No previous pregnancy,26.0,31.0,22.0,25.0,30.0,33.0

In [456]:
MDRM_N1=pd.crosstab(data['Q205A_9A_1'], (data['Q205B_9A_1']))
MDRM_N2=pd.crosstab(data['Q205A_9A_2'], (data['Q205A_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalff1=df_finalff.drop(-999)
df_finalff2=df_finalff1.drop(999)
ddddd=df_finalff2.sum()
dddddvv=ddddd.sum()
dddddvvee=((dddddvv/959)*100).round(0)
dddddvvee

87.0

In [457]:
MDRM_N1=pd.crosstab(data['Q206_9A_1'], (data['Q206_9A_1']))
MDRM_N2=pd.crosstab(data['Q206_9A_2'], (data['Q206_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalff1=df_finalff.drop(-999)
df_finalff2=df_finalff1.drop(999)
ddddd=df_finalff2.sum()
dddddvv=ddddd.sum()
dddddvvee1=((dddddvv/959)*100).round(0)
dddddvvee1

60.0

In [458]:
MDRM_N1=pd.crosstab(data['Q207_9A_1'], (data['Q207_9A_1']))
MDRM_N2=pd.crosstab(data['Q207_9A_2'], (data['Q207_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddyy=ddddd.drop(-999)
dddddyya=dddddyy.drop(0)
dddddvvee1=((dddddyya/959)*100).round(0)
MDR_F2TTTTffwq  = pd.DataFrame(dddddvvee1, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffwq

   Hospitals/MCH specialty centres
1                             85.0

In [459]:
MDRM_N1=pd.crosstab(data['Q209_9A_1'], (data['Q209_9A_1']))
MDRM_N2=pd.crosstab(data['Q209_9A_2'], (data['Q209_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddyy=ddddd.drop(-999)
dddddyyaa=dddddyy.drop(99)
dddddvvee1=((dddddyyaa/959)*100).round(0)
MDR_F2TTTTffwqpyy=dddddvvee1.sum()
MDR_F2TTTTffwqpyy

44.0

In [460]:
MDRM_N1=pd.crosstab(data['Q208_9A_1'], (data['Q208_9A_1']))
MDRM_N2=pd.crosstab(data['Q208_9A_2'], (data['Q208_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddyy=ddddd.drop(-999)
dddddyya=dddddyy.drop(0)
dddddvvee1=((dddddyya/959)*100).round(0)
MDR_F2TTTTffwq  = pd.DataFrame(dddddvvee1, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffwq

   Hospitals/MCH specialty centres
1                             18.0

In [461]:
fata = [['Blood pressure', 87], ['Pulse', 60], ['Consciousness', 85], ['Respiratory rate', 44], ['Experienced seizures ', 18]]
dffff = pd.DataFrame(fata, columns = ['', 'All PPH cases'])
PPH_casea1  = pd.DataFrame(dffff, columns =['All PPH cases'])
labels_of_col1 =["",'Blood pressure','Pulse','Consciousness','Respiratory rate','Experienced seizures']
labels_of_col = ["",'All severe PE/E cases']
PPH_casea1.columns= labels_of_col[1:]
PPH_casea1.index= labels_of_col1[1:]
PPH_casea1.columns.names= [labels_of_col[0]]
PPH_casea1.index.names= [labels_of_col1[0]]
PPH_casea1

                      All severe PE/E cases

Blood pressure                           87
Pulse                                    60
Consciousness                            85
Respiratory rate                         44
Experienced seizures                     18

In [462]:
MDRM_N1=pd.crosstab(data['Q205A_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q205A_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpd=MDR_F2TTTTffp.drop(999)
MDR_F2TTTTffpd=MDR_F2TTTTffpd.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb1=MDR_F2TTTTffqwe.transpose()
x=[417,542]
li=list(MDR_F2TTTTffqweb1.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb1[i]=MDR_F2TTTTffqweb1[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb1=((MDR_F2TTTTffqweb1)*100).round(0)
labels_of_col1 =["",'Blood pressure']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffqweb1.columns= labels_of_col[1:]
MDR_F2TTTTffqweb1.index= labels_of_col1[1:]
MDR_F2TTTTffqweb1.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb1.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb1

                Hospitals/MCH specialty centres  Health centres/clinics

Blood pressure                             95.0                    75.0

In [463]:
MDRM_N1=pd.crosstab(data['Q206_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q206_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(999)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb2=MDR_F2TTTTffqwe.transpose()
x=[417,542]
li=list(MDR_F2TTTTffqweb2.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb2[i]=MDR_F2TTTTffqweb2[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb2=((MDR_F2TTTTffqweb2)*100).round(0)
labels_of_col1 =["",'Pulse']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffqweb2.columns= labels_of_col[1:]
MDR_F2TTTTffqweb2.index= labels_of_col1[1:]
MDR_F2TTTTffqweb2.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb2.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb2

       Hospitals/MCH specialty centres  Health centres/clinics

Pulse                             82.0                    37.0

In [464]:
MDRM_N1=pd.crosstab(data['Q207_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q207_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb3=MDR_F2TTTTffqwe.transpose()
x=[417,542]
li=list(MDR_F2TTTTffqweb3.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb3[i]=MDR_F2TTTTffqweb3[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb3=((MDR_F2TTTTffqweb3)*100).round(0)
labels_of_col1 =["",'Consciousness']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffqweb3.columns= labels_of_col[1:]
MDR_F2TTTTffqweb3.index= labels_of_col1[1:]
MDR_F2TTTTffqweb3.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb3.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb3

               Hospitals/MCH specialty centres  Health centres/clinics

Consciousness                             87.0                    84.0

In [465]:
MDRM_N1=pd.crosstab(data['Q209_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q209_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(99)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb4=MDR_F2TTTTffqwe.transpose()
x=[417,542]
li=list(MDR_F2TTTTffqweb4.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb4[i]=MDR_F2TTTTffqweb4[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb4=((MDR_F2TTTTffqweb4)*100).round(0)
labels_of_col1 =["",'Respiratory rate']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffqweb4.columns= labels_of_col[1:]
MDR_F2TTTTffqweb4.index= labels_of_col1[1:]
MDR_F2TTTTffqweb4.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb4.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb4

                  Hospitals/MCH specialty centres  Health centres/clinics

Respiratory rate                             72.0                    23.0

In [466]:
MDRM_N1=pd.crosstab(data['Q208_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q208_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb5=MDR_F2TTTTffqwe.transpose()
x=[417,542]
li=list(MDR_F2TTTTffqweb5.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb5[i]=MDR_F2TTTTffqweb5[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb5=((MDR_F2TTTTffqweb5)*100).round(0)
labels_of_col1 =["",'Experienced seizures']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffqweb5.columns= labels_of_col[1:]
MDR_F2TTTTffqweb5.index= labels_of_col1[1:]
MDR_F2TTTTffqweb5.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb5.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb5

                      Hospitals/MCH specialty centres  Health centres/clinics

Experienced seizures                             24.0                    14.0

In [467]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffqweb1,MDR_F2TTTTffqweb2,MDR_F2TTTTffqweb3,MDR_F2TTTTffqweb4,MDR_F2TTTTffqweb5)
Cause_of_PPH_TT1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Cause_of_PPH_TT1

                      Hospitals/MCH specialty centres  Health centres/clinics

Blood pressure                                   95.0                    75.0
Pulse                                            82.0                    37.0
Consciousness                                    87.0                    84.0
Respiratory rate                                 72.0                    23.0
Experienced seizures                             24.0                    14.0

In [468]:
MDRM_N1=pd.crosstab(data['Q205A_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q205A_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpd=MDR_F2TTTTffp.drop(999)
MDR_F2TTTTffpd=MDR_F2TTTTffpd.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb11=MDR_F2TTTTffqwe.transpose()
x=[863,60,36]
li=list(MDR_F2TTTTffqweb11.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb11[i]=MDR_F2TTTTffqweb11[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb11=((MDR_F2TTTTffqweb11)*100).round(0)
labels_of_col1 =["",'Blood pressure']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffqweb11.columns= labels_of_col[1:]
MDR_F2TTTTffqweb11.index= labels_of_col1[1:]
MDR_F2TTTTffqweb11.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb11.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb11

                Public/government  Private-for-profit  Private-not-for-profit

Blood pressure               83.0                95.0                     89.0

In [469]:
MDRM_N1=pd.crosstab(data['Q206_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q206_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(999)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb12=MDR_F2TTTTffqwe.transpose()
x=[863,60,36]
li=list(MDR_F2TTTTffqweb12.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb12[i]=MDR_F2TTTTffqweb12[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb12=((MDR_F2TTTTffqweb12)*100).round(0)
labels_of_col1 =["",'Pulse']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffqweb12.columns= labels_of_col[1:]
MDR_F2TTTTffqweb12.index= labels_of_col1[1:]
MDR_F2TTTTffqweb12.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb12.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb12

       Public/government  Private-for-profit  Private-not-for-profit

Pulse               56.0                77.0                     50.0

In [470]:
MDRM_N1=pd.crosstab(data['Q207_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q207_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb13=MDR_F2TTTTffqwe.transpose()
x=[863,60,36]
li=list(MDR_F2TTTTffqweb13.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb13[i]=MDR_F2TTTTffqweb13[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb13=((MDR_F2TTTTffqweb13)*100).round(0)
labels_of_col1 =["",'Consciousness']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffqweb13.columns= labels_of_col[1:]
MDR_F2TTTTffqweb13.index= labels_of_col1[1:]
MDR_F2TTTTffqweb13.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb13.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb13

               Public/government  Private-for-profit  Private-not-for-profit

Consciousness               84.0                95.0                     92.0

In [471]:
MDRM_N1=pd.crosstab(data['Q209_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q209_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(99)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb14=MDR_F2TTTTffqwe.transpose()
x=[863,60,36]
li=list(MDR_F2TTTTffqweb14.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb14[i]=MDR_F2TTTTffqweb14[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb14=((MDR_F2TTTTffqweb14)*100).round(0)
labels_of_col1 =["",'Respiratory rate']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffqweb14.columns= labels_of_col[1:]
MDR_F2TTTTffqweb14.index= labels_of_col1[1:]
MDR_F2TTTTffqweb14.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb14.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb14

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Respiratory rate,45.0,42.0,33.0

In [472]:
MDRM_N1=pd.crosstab(data['Q208_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q208_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
MDR_F2TTTTffpd2=MDR_F2TTTTffpd.sum()
MDR_F2TTTTffqwe = pd.DataFrame(MDR_F2TTTTffpd2, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffqweb15=MDR_F2TTTTffqwe.transpose()
x=[863,60,36]
li=list(MDR_F2TTTTffqweb15.columns)
j=0
for i in li:
    MDR_F2TTTTffqweb15[i]=MDR_F2TTTTffqweb15[i]/x[j]
    j=j+1
MDR_F2TTTTffqweb15=((MDR_F2TTTTffqweb15)*100).round(0)
labels_of_col1 =["",'Experienced seizures']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffqweb15.columns= labels_of_col[1:]
MDR_F2TTTTffqweb15.index= labels_of_col1[1:]
MDR_F2TTTTffqweb15.columns.names= [labels_of_col[0]]
MDR_F2TTTTffqweb15.index.names= [labels_of_col1[0]]
MDR_F2TTTTffqweb15

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Experienced seizures,19.0,12.0,8.0

In [473]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(MDR_F2TTTTffqweb11,MDR_F2TTTTffqweb12,MDR_F2TTTTffqweb13,MDR_F2TTTTffqweb14,MDR_F2TTTTffqweb15)
Cause_of_PPH_TT2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Cause_of_PPH_TT2

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Blood pressure,83.0,95.0,89.0
Pulse,56.0,77.0,50.0
Consciousness,84.0,95.0,92.0
Respiratory rate,45.0,42.0,33.0
Experienced seizures,19.0,12.0,8.0

In [474]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(PPH_casea1,Cause_of_PPH_TT1,Cause_of_PPH_TT2)
Cause_of_PPH_Total=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_Total

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Blood pressure,87,95.0,75.0,83.0,95.0,89.0
Pulse,60,82.0,37.0,56.0,77.0,50.0
Consciousness,85,87.0,84.0,84.0,95.0,92.0
Respiratory rate,44,72.0,23.0,45.0,42.0,33.0
Experienced seizures,18,24.0,14.0,19.0,12.0,8.0

In [475]:
MDRM_N1=pd.crosstab(data['Q211_9A_1'], (data['Q211_9A_1']))
MDRM_N2=pd.crosstab(data['Q211_9A_2'], (data['Q211_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
df_finalffs=df_final.drop(-999)
df_finalff=df_finalffs.drop(0)
ddddd=df_finalff.sum()
MDR_F2TTTTff= pd.DataFrame(ddddd, columns =['Hospitals/MCH specialty centres'])
MDR_F2TTTTffd=MDR_F2TTTTff.drop(-999)
Antihypertensive_administered=((MDR_F2TTTTffd/959)*100).round(0)
labels_of_col1 =["",'uuup','Hydralazine','Nifedipine','Both hydralazine and nifedipine','Methyldopa/aldomet','No information','Other']
labels_of_col = ["",'All severe PE/E cases']
Antihypertensive_administered.columns= labels_of_col[1:]
Antihypertensive_administered.index= labels_of_col1[1:]
Antihypertensive_administered.columns.names= [labels_of_col[0]]
Antihypertensive_administered.index.names= [labels_of_col1[0]]
Antihypertensive_administered1=Antihypertensive_administered.drop('uuup')
Antihypertensive_administered1

                                 All severe PE/E cases

Hydralazine                                       33.0
Nifedipine                                         5.0
Both hydralazine and nifedipine                    2.0
Methyldopa/aldomet                                 6.0
No information                                    52.0
Other                                              2.0

In [476]:
MDRM_N1=pd.crosstab(data['Q211_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q211_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd=MDR_F2TTTTffpf.fillna(0)
x=[417,542]
li=list(MDR_F2TTTTffpd.columns)
j=0
for i in li:
    MDR_F2TTTTffpd[i]=MDR_F2TTTTffpd[i]/x[j]
    j=j+1
MDR_F2TTTTffpd=((MDR_F2TTTTffpd)*100).round(0)
labels_of_col1 =["",'Hydralazine','Nifedipine','Both hydralazine and nifedipine','Methyldopa/aldomet','No information','Other']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
MDR_F2TTTTffpd.columns= labels_of_col[1:]
MDR_F2TTTTffpd.index= labels_of_col1[1:]
MDR_F2TTTTffpd.columns.names= [labels_of_col[0]]
MDR_F2TTTTffpd.index.names= [labels_of_col1[0]]
MDR_F2TTTTffpd

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Hydralazine,52.0,18.0
Nifedipine,9.0,2.0
Both hydralazine and nifedipine,4.0,0.0
Methyldopa/aldomet,6.0,5.0
No information,27.0,72.0
Other,2.0,2.0

In [477]:
MDRM_N1=pd.crosstab(data['Q211_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q211_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
MDR_F2TTTTffpf=MDR_F2TTTTffp.drop(0)
MDR_F2TTTTffpd_MA3=MDR_F2TTTTffpf.fillna(0)
x=[863,60,36]
li=list(MDR_F2TTTTffpd_MA3.columns)
j=0
for i in li:
    MDR_F2TTTTffpd_MA3[i]=MDR_F2TTTTffpd_MA3[i]/x[j]
    j=j+1
MDR_F2TTTTffpd_MA3=((MDR_F2TTTTffpd_MA3)*100).round(0)
labels_of_col1 =["",'Hydralazine','Nifedipine','Both hydralazine and nifedipine','Methyldopa/aldomet','No information','Other']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
MDR_F2TTTTffpd_MA3.columns= labels_of_col[1:]
MDR_F2TTTTffpd_MA3.index= labels_of_col1[1:]
MDR_F2TTTTffpd_MA3.columns.names= [labels_of_col[0]]
MDR_F2TTTTffpd_MA3.index.names= [labels_of_col1[0]]
MDR_F2TTTTffpd_MA3

,Public/government,Private-for-profit,Private-not-for-profit
,,,
Hydralazine,31.0,58.0,36.0
Nifedipine,5.0,2.0,3.0
Both hydralazine and nifedipine,2.0,5.0,0.0
Methyldopa/aldomet,6.0,5.0,6.0
No information,54.0,28.0,50.0
Other,2.0,2.0,6.0

In [478]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Antihypertensive_administered1,MDR_F2TTTTffpd,MDR_F2TTTTffpd_MA3)
Antihypertensive_administered_T=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Antihypertensive_administered_T

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Hydralazine,33.0,52.0,18.0,31.0,58.0,36.0
Nifedipine,5.0,9.0,2.0,5.0,2.0,3.0
Both hydralazine and nifedipine,2.0,4.0,0.0,2.0,5.0,0.0
Methyldopa/aldomet,6.0,6.0,5.0,6.0,5.0,6.0
No information,52.0,27.0,72.0,54.0,28.0,50.0
Other,2.0,2.0,2.0,2.0,2.0,6.0

In [479]:
MDRM_N1=pd.crosstab(data['Q212_9A_1'], (data['Q212_9A_1']))
MDRM_N2=pd.crosstab(data['Q212_9A_2'], (data['Q212_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_final = pd.concat(df, axis=0)
ddddd=df_final.sum()
df_finalffs=ddddd.drop(-999)
MDR_F2TTTTff= pd.DataFrame(df_finalffs, columns =['Hospitals/MCH specialty centres'])
Antihypertensive_administered=((MDR_F2TTTTff/959)*100).round(0)
labels_of_col1 =["",'1','2','3','4','5','7','8','9','10','14','15','16','No information ']
labels_of_col = ["",'All severe PE/E cases']
Antihypertensive_administered.columns= labels_of_col[1:]
Antihypertensive_administered.index= labels_of_col1[1:]
Antihypertensive_administered.columns.names= [labels_of_col[0]]
Antihypertensive_administered.index.names= [labels_of_col1[0]]
Antihypertensive_administered

                 All severe PE/E cases

1                                  1.0
2                                  0.0
3                                  0.0
4                                 10.0
5                                  3.0
7                                  0.0
8                                  1.0
9                                  3.0
10                                 4.0
14                                11.0
15                                 0.0
16                                 1.0
No information                    66.0

In [480]:
MDRM_N1=pd.crosstab(data['Q212_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q212_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'1','2','3','4','5','7','8','9','10','14','15','16','No information ']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphate0

                 Hospitals/MCH specialty centres  Health centres/clinics

1                                            1.0                     0.0
2                                            0.0                     0.0
3                                            0.0                     0.0
4                                           14.0                     7.0
5                                            7.0                     1.0
7                                            0.0                     0.0
8                                            1.0                     0.0
9                                            4.0                     2.0
10                                           7.0                     2.0
14                                          20.0                     4.0
15                                           0.0                     0.0
16                                           1.0                     0.0
No information                              44.0                    84.0

In [481]:
MDRM_N1=pd.crosstab(data['Q212_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q212_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate[i]=Loading_dose_of_magnesium_sulphate[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate=((Loading_dose_of_magnesium_sulphate)*100).round(0)
labels_of_col1 =["",'1','2','3','4','5','7','8','9','10','14','15','16','No information ']
labels_of_col = ["","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphate

,Public/government,Private-for-profit,Private-not-for-profit
,,,
1,0.0,3.0,0.0
2,0.0,0.0,0.0
3,0.0,0.0,0.0
4,11.0,2.0,6.0
5,3.0,8.0,11.0
7,0.0,0.0,0.0
8,1.0,0.0,0.0
9,2.0,12.0,0.0
10,4.0,0.0,14.0
14,11.0,5.0,8.0
15,0.0,0.0,0.0
16,1.0,0.0,0.0
No information,66.0,70.0,61.0

In [482]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Antihypertensive_administered,Loading_dose_of_magnesium_sulphate0,Loading_dose_of_magnesium_sulphate)
Loading_dose_of_magnesium_sulphate_T=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Loading_dose_of_magnesium_sulphate_T

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
1,1.0,1.0,0.0,0.0,3.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0
4,10.0,14.0,7.0,11.0,2.0,6.0
5,3.0,7.0,1.0,3.0,8.0,11.0
7,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,1.0,0.0,1.0,0.0,0.0
9,3.0,4.0,2.0,2.0,12.0,0.0
10,4.0,7.0,2.0,4.0,0.0,14.0
14,11.0,20.0,4.0,11.0,5.0,8.0
15,0.0,0.0,0.0,0.0,0.0,0.0
16,1.0,1.0,0.0,1.0,0.0,0.0
No information,66.0,44.0,84.0,66.0,70.0,61.0

In [483]:
MDRM_N1=pd.crosstab(data['Q214_9A_1'], (data['Q214_9A_1']))
MDRM_N2=pd.crosstab(data['Q214_9A_2'], (data['Q214_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwow=df_finalff1.drop(0)
df_finalffwowffff1  = pd.DataFrame(df_finalffwow, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Maintenance dose(s) given']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff1.columns= labels_of_col[1:]
df_finalffwowffff1.index= labels_of_col1[1:]
df_finalffwowffff1.columns.names= [labels_of_col[0]]
df_finalffwowffff1.index.names= [labels_of_col1[0]]
df_finalffwowffff1

                           All severe PE/E cases

Maintenance dose(s) given                   29.0

In [484]:
MDRM_N1=pd.crosstab(data['Q216_9A_1'], (data['Q216_9A_1']))
MDRM_N2=pd.crosstab(data['Q216_9A_2'], (data['Q216_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwow=df_finalff1.drop(0)
df_finalffwowffff2  = pd.DataFrame(df_finalffwow, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Respiratory rate monitored']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff2.columns= labels_of_col[1:]
df_finalffwowffff2.index= labels_of_col1[1:]
df_finalffwowffff2.columns.names= [labels_of_col[0]]
df_finalffwowffff2.index.names= [labels_of_col1[0]]
df_finalffwowffff2

                            All severe PE/E cases

Respiratory rate monitored                   35.0

In [485]:
MDRM_N1=pd.crosstab(data['Q217_9A_1'], (data['Q217_9A_1']))
MDRM_N2=pd.crosstab(data['Q217_9A_2'], (data['Q217_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwow=df_finalff1.drop(0)
df_finalffwowffff3  = pd.DataFrame(df_finalffwow, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Urine output monitored']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff3.columns= labels_of_col[1:]
df_finalffwowffff3.index= labels_of_col1[1:]
df_finalffwowffff3.columns.names= [labels_of_col[0]]
df_finalffwowffff3.index.names= [labels_of_col1[0]]
df_finalffwowffff3

                        All severe PE/E cases

Urine output monitored                   20.0

In [486]:
MDRM_N1=pd.crosstab(data['Q215_9A_1'], (data['Q215_9A_1']))
MDRM_N2=pd.crosstab(data['Q215_9A_2'], (data['Q215_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwow=df_finalff1.drop(0)
df_finalffwowffff4  = pd.DataFrame(df_finalffwow, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Tendon reflexes monitored']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff4.columns= labels_of_col[1:]
df_finalffwowffff4.index= labels_of_col1[1:]
df_finalffwowffff4.columns.names= [labels_of_col[0]]
df_finalffwowffff4.index.names= [labels_of_col1[0]]
df_finalffwowffff4

                           All severe PE/E cases

Tendon reflexes monitored                   11.0

In [487]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(df_finalffwowffff1,df_finalffwowffff2,df_finalffwowffff3,df_finalffwowffff4)
Treatment_tt1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Treatment_tt1

                            All severe PE/E cases

Maintenance dose(s) given                    29.0
Respiratory rate monitored                   35.0
Urine output monitored                       20.0
Tendon reflexes monitored                    11.0

In [488]:
MDRM_N1=pd.crosstab(data['Q214_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q214_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Maintenance dose(s) given']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates1=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates1

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Maintenance dose(s) given,59.0,5.0

In [489]:
MDRM_N1=pd.crosstab(data['Q216_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q216_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Respiratory rate monitored']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates2=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Respiratory rate monitored,69.0,9.0

In [490]:
MDRM_N1=pd.crosstab(data['Q217_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q217_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Urine output monitored']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates3=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates3

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Urine output monitored,43.0,2.0

In [491]:
MDRM_N1=pd.crosstab(data['Q215_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q215_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Tendon reflexes monitored']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates4=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates4

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Tendon reflexes monitored,23.0,2.0

In [492]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Loading_dose_of_magnesium_sulphates1,Loading_dose_of_magnesium_sulphates2,Loading_dose_of_magnesium_sulphates3,Loading_dose_of_magnesium_sulphates4)
Treatment_tt2=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Treatment_tt2

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Maintenance dose(s) given,59.0,5.0
Respiratory rate monitored,69.0,9.0
Urine output monitored,43.0,2.0
Tendon reflexes monitored,23.0,2.0

In [493]:
MDRM_N1=pd.crosstab(data['Q214_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q214_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Maintenance dose(s) given']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates1=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates1
MDRM_N1=pd.crosstab(data['Q216_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q216_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Respiratory rate monitored']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates2=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates2
MDRM_N1=pd.crosstab(data['Q217_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q217_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Urine output monitored']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates3=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates3
MDRM_N1=pd.crosstab(data['Q215_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q215_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp=ffdr.drop(-999)
Loading_dose_of_magnesium_sulphate0=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate0.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0[i]=Loading_dose_of_magnesium_sulphate0[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0=((Loading_dose_of_magnesium_sulphate0)*100).round(0)
labels_of_col1 =["",'eee','Tendon reflexes monitored']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate0.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphates4=Loading_dose_of_magnesium_sulphate0.drop('eee')
Loading_dose_of_magnesium_sulphates4
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Loading_dose_of_magnesium_sulphates1,Loading_dose_of_magnesium_sulphates2,Loading_dose_of_magnesium_sulphates3,Loading_dose_of_magnesium_sulphates4)
Treatment_tt3=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Treatment_tt3

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Maintenance dose(s) given,28.0,30.0,36.0
Respiratory rate monitored,34.0,45.0,50.0
Urine output monitored,18.0,50.0,25.0
Tendon reflexes monitored,10.0,13.0,25.0

In [494]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Treatment_tt1,Treatment_tt2,Treatment_tt3)
Treatment_tt3t=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Treatment_tt3t

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Maintenance dose(s) given,29.0,59.0,5.0,28.0,30.0,36.0
Respiratory rate monitored,35.0,69.0,9.0,34.0,45.0,50.0
Urine output monitored,20.0,43.0,2.0,18.0,50.0,25.0
Tendon reflexes monitored,11.0,23.0,2.0,10.0,13.0,25.0

In [495]:
MDRM_N1=pd.crosstab(data['Q218_9A_1'], (data['Q218_9A_1']))
MDRM_N2=pd.crosstab(data['Q218_9A_2'], (data['Q218_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwow=df_finalff1.drop(0)
df_finalffwowffff1ml  = pd.DataFrame(df_finalffwow, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff1ml.columns= labels_of_col[1:]
df_finalffwowffff1ml.index= labels_of_col1[1:]
df_finalffwowffff1ml.columns.names= [labels_of_col[0]]
df_finalffwowffff1ml.index.names= [labels_of_col1[0]]
df_finalffwowffff1ml

                All severe PE/E cases

Vaginal                          47.0
Instrumental                      4.0
Caesarean                        12.0
No information                   37.0

In [496]:
MDRM_N1=pd.crosstab(data['Q218_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q218_9A_2'], (data['FT2']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp1=ffdr.drop(-999)
MDR_F2TTTTffp=MDR_F2TTTTffp1.drop(0)
Loading_dose_of_magnesium_sulphate0b=MDR_F2TTTTffp.fillna(0)
x=[417,542]
li=list(Loading_dose_of_magnesium_sulphate0b.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0b[i]=Loading_dose_of_magnesium_sulphate0b[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0b=((Loading_dose_of_magnesium_sulphate0b)*100).round(0)
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
Loading_dose_of_magnesium_sulphate0b.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0b.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0b.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0b.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphate0b

                Hospitals/MCH specialty centres  Health centres/clinics

Vaginal                                    55.0                    41.0
Instrumental                                8.0                     1.0
Caesarean                                  26.0                     1.0
No information                             11.0                    57.0

In [497]:
MDRM_N1=pd.crosstab(data['Q218_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q218_9A_2'], (data['MA3']))
ffdr=MDRM_N1+MDRM_N2
MDR_F2TTTTffp1=ffdr.drop(-999)
MDR_F2TTTTffp=MDR_F2TTTTffp1.drop(0)
Loading_dose_of_magnesium_sulphate0mk=MDR_F2TTTTffp.fillna(0)
x=[863,60,36]
li=list(Loading_dose_of_magnesium_sulphate0mk.columns)
j=0
for i in li:
    Loading_dose_of_magnesium_sulphate0mk[i]=Loading_dose_of_magnesium_sulphate0mk[i]/x[j]
    j=j+1
Loading_dose_of_magnesium_sulphate0mk=((Loading_dose_of_magnesium_sulphate0mk)*100).round(0)
labels_of_col1 =["",'Vaginal','Instrumental','Caesarean','No information']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
Loading_dose_of_magnesium_sulphate0mk.columns= labels_of_col[1:]
Loading_dose_of_magnesium_sulphate0mk.index= labels_of_col1[1:]
Loading_dose_of_magnesium_sulphate0mk.columns.names= [labels_of_col[0]]
Loading_dose_of_magnesium_sulphate0mk.index.names= [labels_of_col1[0]]
Loading_dose_of_magnesium_sulphate0mk

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Vaginal,49.0,25.0,33.0
Instrumental,4.0,2.0,3.0
Caesarean,7.0,67.0,44.0
No information,40.0,7.0,19.0

In [498]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(df_finalffwowffff1ml,Loading_dose_of_magnesium_sulphate0b,Loading_dose_of_magnesium_sulphate0mk)
Treatment_tt3tm=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Treatment_tt3tm

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Vaginal,47.0,55.0,41.0,49.0,25.0,33.0
Instrumental,4.0,8.0,1.0,4.0,2.0,3.0
Caesarean,12.0,26.0,1.0,7.0,67.0,44.0
No information,37.0,11.0,57.0,40.0,7.0,19.0

In [499]:
MDRM_N1=pd.crosstab(data['Q221_9A_1'], (data['Q221_9A_1']))
MDRM_N2=pd.crosstab(data['Q221_9A_2'], (data['Q221_9A_2']))
df_finalff = MDRM_N1+MDRM_N2
df_finalff6tr=df_finalff.fillna(0)
df_finalff6trf1=df_finalff6tr.drop(99)
df_finalff6trfd=df_finalff6trf1.drop(-999)
df_finalff6trf=df_finalff6trfd.drop(1)
df_finalff6trfer=df_finalff6trf.sum()
treswww=df_finalff6trfer.sum()
df_finalffwowffff1ml=((treswww/959)*100).round(0)
df_finalffwowffff1ml

47.0

In [500]:
MDRM_N1=pd.crosstab(data['Q222_9A_1'], (data['Q222_9A_1']))
MDRM_N2=pd.crosstab(data['Q222_9A_2'], (data['Q222_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
seeaeae=df_finalffrrr.sum()
seeaeaeeee=seeaeae.drop(-999)
seeaeaeeeev=seeaeaeeee.drop(99999)
dseeeee=seeaeaeeeev.sum()
dddddvvee=((dseeeee/959)*100).round(0)
dddddvvee

17.0

In [501]:
MDRM_N1=pd.crosstab(data['Q223_9A_1'], (data['Q223_9A_1']))
MDRM_N2=pd.crosstab(data['Q223_9A_2'], (data['Q223_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
df_finalffrrrv=df_finalffrrr.drop(-999)
df_finalffrrrv=df_finalffrrrv.drop(99)
bdf_finalffrrrv=df_finalffrrrv.sum()
seeaeae=bdf_finalffrrrv.sum()
dddddvvee1=((seeaeae/959)*100).round(0)
dddddvvee1

41.0

In [502]:
fata = [['Blood pressure recorded >2 times', df_finalffwowffff1ml], ['Urine output recorded before discharge', dddddvvee], ['Number of days hospitalized noted', dddddvvee1]]
dfre = pd.DataFrame(fata, columns = ['', 'All severe PE/E cases'])
dfre

                                           All severe PE/E cases
0        Blood pressure recorded >2 times                   47.0
1  Urine output recorded before discharge                   17.0
2       Number of days hospitalized noted                   41.0

In [503]:
fata = [['Blood pressure recorded >2 times', df_finalffwowffff1ml], ['Urine output recorded before discharge', dddddvvee], ['Number of days hospitalized noted', dddddvvee1]]
df1 = pd.DataFrame(data=fata)
eeeeee=df1[1]
yrtfd = pd.DataFrame(data=eeeeee)
labels_of_col1 =["",'Blood pressure recorded >2 times','Urine output recorded before discharge','Number of days hospitalized noted']
labels_of_col = ["",'All severe PE/E cases']
yrtfd.columns= labels_of_col[1:]
yrtfd.index= labels_of_col1[1:]
yrtfd.columns.names= [labels_of_col[0]]
yrtfd.index.names= [labels_of_col1[0]]
yrtfd

                                        All severe PE/E cases

Blood pressure recorded >2 times                         47.0
Urine output recorded before discharge                   17.0
Number of days hospitalized noted                        41.0

In [504]:
MDRM_N1=pd.crosstab(data['Q221_9A_1'], (data['FT2']))
df_finalff6trf1=MDRM_N1.fillna(0)
df_finalff6trfd0=df_finalff6trf1.drop(0)
df_finalff6trfd3=df_finalff6trfd0.drop(1)
df_finalff6trfd4=df_finalff6trfd3.drop(2)
df_finalff6trfd5=df_finalff6trfd4.drop(99)
df_finalff6trfd6=df_finalff6trfd5.drop(-999)
Postpartum_monitoring=df_finalff6trfd6.sum()
MDRM_N1=pd.crosstab(data['Q221_9A_2'], (data['FT2']))
df_finalff6trf1=MDRM_N1.fillna(0)
df_finalff6trfd3=df_finalff6trf1.drop(1)
df_finalff6trfd4=df_finalff6trfd3.drop(2)
df_finalff6trfd5=df_finalff6trfd4.drop(99)
df_finalff6trfd6=df_finalff6trfd5.drop(-999)
Postpartum_monitoring1=df_finalff6trfd6.sum()
Postpartum_monitory=Postpartum_monitoring+Postpartum_monitoring1
df1 = pd.DataFrame(data=Postpartum_monitory)
rrretttee=df1.transpose()
x=[417,542]
li=list(rrretttee.columns)
j=0
for i in li:
    rrretttee[i]=rrretttee[i]/x[j]
    j=j+1
rrretttee=((rrretttee)*100).round(0)
labels_of_col1 =["",'Blood pressure recorded >2 times']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
rrretttee.columns= labels_of_col[1:]
rrretttee.index= labels_of_col1[1:]
rrretttee.columns.names= [labels_of_col[0]]
rrretttee.index.names= [labels_of_col1[0]]
rrretttee

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Blood pressure recorded >2 times,79.0,15.0

In [505]:
MDRM_N1=pd.crosstab(data['Q221_9A_1'], (data['MA3']))
df_finalff6trf1=MDRM_N1.fillna(0)
df_finalff6trfd0=df_finalff6trf1.drop(0)
df_finalff6trfd3=df_finalff6trfd0.drop(1)
df_finalff6trfd4=df_finalff6trfd3.drop(2)
df_finalff6trfd5=df_finalff6trfd4.drop(99)
df_finalff6trfd6=df_finalff6trfd5.drop(-999)
Postpartum_monitoring=df_finalff6trfd6.sum()
MDRM_N1=pd.crosstab(data['Q221_9A_2'], (data['MA3']))
df_finalff6trf1=MDRM_N1.fillna(0)
df_finalff6trfd3=df_finalff6trf1.drop(1)
df_finalff6trfd4=df_finalff6trfd3.drop(2)
df_finalff6trfd5=df_finalff6trfd4.drop(99)
df_finalff6trfd6=df_finalff6trfd5.drop(-999)
Postpartum_monitoring1=df_finalff6trfd6.sum()
Postpartum_monitory=Postpartum_monitoring+Postpartum_monitoring1
df1 = pd.DataFrame(data=Postpartum_monitory)
rrretttee1=df1.transpose()
x=[863,60,36]
li=list(rrretttee1.columns)
j=0
for i in li:
    rrretttee1[i]=rrretttee1[i]/x[j]
    j=j+1
rrretttee1=((rrretttee1)*100).round(0)
labels_of_col1 =["",'Blood pressure recorded >2 times']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
rrretttee1.columns= labels_of_col[1:]
rrretttee1.index= labels_of_col1[1:]
rrretttee1.columns.names= [labels_of_col[0]]
rrretttee1.index.names= [labels_of_col1[0]]
rrretttee1

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Blood pressure recorded >2 times,40.0,73.0,58.0

In [506]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(rrretttee,rrretttee1)
Cause_of_PPH_T47=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T47

,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,
Blood pressure recorded >2 times,79.0,15.0,40.0,73.0,58.0

In [507]:
MDRM_N1=pd.crosstab(data['Q222_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q222_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
dsew=df_finalffrrr.drop(-999)
dsew1=dsew.drop(99999)
Postpartum_monitory5=dsew1.sum()
df1 = pd.DataFrame(data=Postpartum_monitory5)
rrrettteel=df1.transpose()
x=[417,542]
li=list(rrrettteel.columns)
j=0
for i in li:
    rrrettteel[i]=rrrettteel[i]/x[j]
    j=j+1
rrrettteelk=((rrrettteel)*100).round(0)
labels_of_col1 =["",'Urine output recorded before discharge']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
rrrettteelk.columns= labels_of_col[1:]
rrrettteelk.index= labels_of_col1[1:]
rrrettteelk.columns.names= [labels_of_col[0]]
rrrettteelk.index.names= [labels_of_col1[0]]
rrrettteelk

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Urine output recorded before discharge,33.0,5.0

In [508]:
MDRM_N1=pd.crosstab(data['Q222_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q222_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
dsew=df_finalffrrr.drop(-999)
dsew1=dsew.drop(99999)
Postpartum_monitory5=dsew1.sum()
df1 = pd.DataFrame(data=Postpartum_monitory5)
rrrettteel1=df1.transpose()
x=[863,60,36]
li=list(rrrettteel1.columns)
j=0
for i in li:
    rrrettteel1[i]=rrrettteel1[i]/x[j]
    j=j+1
rrrettteel1=((rrrettteel1)*100).round(0)
labels_of_col1 =["",'Urine output recorded before discharge']
labels_of_col = labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
rrrettteel1.columns= labels_of_col[1:]
rrrettteel1.index= labels_of_col1[1:]
rrrettteel1.columns.names= [labels_of_col[0]]
rrrettteel1.index.names= [labels_of_col1[0]]
rrrettteel1

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Urine output recorded before discharge,16.0,35.0,22.0

In [509]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(rrrettteelk,rrrettteel1)
Cause_of_PPH_T47g=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T47g

,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,
Urine output recorded before discharge,33.0,5.0,16.0,35.0,22.0

In [510]:
MDRM_N1=pd.crosstab(data['Q223_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q223_9A_2'], (data['FT2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
dsew=df_finalffrrr.drop(-999)
seft=dsew.drop(99)
trewq=seft.sum()
df1 = pd.DataFrame(data=trewq)
rrrettteel=df1.transpose()
x=[417,542]
li=list(rrrettteel.columns)
j=0
for i in li:
    rrrettteel[i]=rrrettteel[i]/x[j]
    j=j+1
rrrettteels=((rrrettteel)*100).round(0)
labels_of_col1 =["",'Number of days hospitalized noted']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
rrrettteels.columns= labels_of_col[1:]
rrrettteels.index= labels_of_col1[1:]
rrrettteels.columns.names= [labels_of_col[0]]
rrrettteels.index.names= [labels_of_col1[0]]
rrrettteels

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Number of days hospitalized noted,72.0,17.0

In [511]:
MDRM_N1=pd.crosstab(data['Q223_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q223_9A_2'], (data['MA3']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
df_finalffrrr=df_finalff.fillna(0)
dsew=df_finalffrrr.drop(-999)
seft=dsew.drop(99)
trewq=seft.sum()
df1 = pd.DataFrame(data=trewq)
rrrettteel=df1.transpose()
x=[863,60,36]
li=list(rrrettteel.columns)
j=0
for i in li:
    rrrettteel[i]=rrrettteel[i]/x[j]
    j=j+1
rrrettteela=((rrrettteel)*100).round(0)
labels_of_col1 =["",'Number of days hospitalized noted']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
rrrettteela.columns= labels_of_col[1:]
rrrettteela.index= labels_of_col1[1:]
rrrettteela.columns.names= [labels_of_col[0]]
rrrettteela.index.names= [labels_of_col1[0]]
rrrettteela

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Number of days hospitalized noted,37.0,82.0,64.0

In [512]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(rrrettteels,rrrettteela)
Cause_of_PPH_T47gd=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T47gd

,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,
Number of days hospitalized noted,72.0,17.0,37.0,82.0,64.0

In [513]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Cause_of_PPH_T47,Cause_of_PPH_T47g,Cause_of_PPH_T47gd)
Cause_of_PPH_T47gdf=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Cause_of_PPH_T47gdf

,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,
Blood pressure recorded >2 times,79.0,15.0,40.0,73.0,58.0
Urine output recorded before discharge,33.0,5.0,16.0,35.0,22.0
Number of days hospitalized noted,72.0,17.0,37.0,82.0,64.0

In [530]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(yrtfd,Cause_of_PPH_T47gdf)
Cause_of_PPH_T47gdfw=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
cc

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Blood pressure recorded >2 times,47.0,79.0,15.0,40.0,73.0,58.0
Urine output recorded before discharge,17.0,33.0,5.0,16.0,35.0,22.0
Number of days hospitalized noted,41.0,72.0,17.0,37.0,82.0,64.0

In [517]:
MDRM_N1=pd.crosstab(data['Q224_9A_1'], (data['Q224_9A_1']))
MDRM_N2=pd.crosstab(data['Q224_9A_2'], (data['Q224_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwowffff1ml  = pd.DataFrame(df_finalff1, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Low birth weight','Birth Asphyxia','Meconium Aspiration syndrome','Marcosomia','No information','Other']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff1ml.columns= labels_of_col[1:]
df_finalffwowffff1ml.index= labels_of_col1[1:]
df_finalffwowffff1ml.columns.names= [labels_of_col[0]]
df_finalffwowffff1ml.index.names= [labels_of_col1[0]]
df_finalffwowffff1ml

                              All severe PE/E cases

Low birth weight                               10.0
Birth Asphyxia                                  3.0
Meconium Aspiration syndrome                    1.0
Marcosomia                                      0.0
No information                                 84.0
Other                                           2.0

In [518]:
MDRM_N1=pd.crosstab(data['Q224_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q224_9A_2'], (data['FT2']))
rett=MDRM_N1+MDRM_N2
deremkib=rett.drop(-999)
x=[417,542]
li=list(deremkib.columns)
j=0
for i in li:
    deremkib[i]=deremkib[i]/x[j]
    j=j+1
deremkib=((deremkib)*100).round(0)
labels_of_col1 =["",'Low birth weight','Birth Asphyxia','Meconium Aspiration syndrome','Marcosomia','No information','Other']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
deremkib.columns= labels_of_col[1:]
deremkib.index= labels_of_col1[1:]
deremkib.columns.names= [labels_of_col[0]]
deremkib.index.names= [labels_of_col1[0]]
deremkib

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Low birth weight,17.0,4.0
Birth Asphyxia,4.0,2.0
Meconium Aspiration syndrome,2.0,0.0
Marcosomia,0.0,0.0
No information,73.0,93.0
Other,3.0,1.0

In [519]:
MDRM_N1=pd.crosstab(data['Q224_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q224_9A_2'], (data['MA3']))
rett=MDRM_N1+MDRM_N2
deremkibv=rett.drop(-999)
x=[863,60,36]
li=list(deremkibv.columns)
j=0
for i in li:
    deremkibv[i]=deremkibv[i]/x[j]
    j=j+1
deremkibv=((deremkibv)*100).round(0)
labels_of_col1 =["",'Low birth weight','Birth Asphyxia','Meconium Aspiration syndrome','Marcosomia','No information','Other']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
deremkibv.columns= labels_of_col[1:]
deremkibv.index= labels_of_col1[1:]
deremkibv.columns.names= [labels_of_col[0]]
deremkibv.index.names= [labels_of_col1[0]]
deremkibv

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Low birth weight,9.0,15.0,17.0
Birth Asphyxia,3.0,0.0,0.0
Meconium Aspiration syndrome,1.0,3.0,0.0
Marcosomia,0.0,2.0,0.0
No information,85.0,77.0,78.0
Other,2.0,3.0,6.0

In [520]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(df_finalffwowffff1ml,deremkib,deremkibv)
Cause_of_PPH_T47gdfw=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T47gdfw

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Low birth weight,10.0,17.0,4.0,9.0,15.0,17.0
Birth Asphyxia,3.0,4.0,2.0,3.0,0.0,0.0
Meconium Aspiration syndrome,1.0,2.0,0.0,1.0,3.0,0.0
Marcosomia,0.0,0.0,0.0,0.0,2.0,0.0
No information,84.0,73.0,93.0,85.0,77.0,78.0
Other,2.0,3.0,1.0,2.0,3.0,6.0

In [523]:
MDRM_N1=pd.crosstab(data['Q225_9A_1'], (data['Q225_9A_1']))
MDRM_N2=pd.crosstab(data['Q225_9A_2'], (data['Q225_9A_2']))
df1 = MDRM_N1.reset_index()
df2 = MDRM_N2.reset_index()
df = [MDRM_N1, MDRM_N2]
df_finalff = pd.concat(df, axis=0)
ddddd=df_finalff.sum()
dddddvvee=((ddddd/959)*100).round(0)
df_finalff1=dddddvvee.drop(-999)
df_finalffwowffff1ml1  = pd.DataFrame(df_finalff1, columns =['Hospitals/MCH specialty centres'])
labels_of_col1 =["",'Alive at discharge','Stillbirth','Early neonatal death','Multiple gestation (live birth + stillbirth)','No information']
labels_of_col = ["",'All severe PE/E cases']
df_finalffwowffff1ml1.columns= labels_of_col[1:]
df_finalffwowffff1ml1.index= labels_of_col1[1:]
df_finalffwowffff1ml1.columns.names= [labels_of_col[0]]
df_finalffwowffff1ml1.index.names= [labels_of_col1[0]]
df_finalffwowffff1ml1

                                              All severe PE/E cases

Alive at discharge                                             48.0
Stillbirth                                                      8.0
Early neonatal death                                            1.0
Multiple gestation (live birth + stillbirth)                    1.0
No information                                                 42.0

In [524]:
MDRM_N1=pd.crosstab(data['Q225_9A_1'], (data['FT2']))
MDRM_N2=pd.crosstab(data['Q225_9A_2'], (data['FT2']))
rett=MDRM_N1+MDRM_N2
deremkib1=rett.drop(-999)
x=[417,542]
li=list(deremkib1.columns)
j=0
for i in li:
    deremkib1[i]=deremkib1[i]/x[j]
    j=j+1
deremkib1=((deremkib1)*100).round(0)
labels_of_col1 =["",'Alive at discharge','Stillbirth','Early neonatal death','Multiple gestation (live birth + stillbirth)','No information']
labels_of_col = ["","Hospitals/MCH specialty centres",'Health centres/clinics']
deremkib1.columns= labels_of_col[1:]
deremkib1.index= labels_of_col1[1:]
deremkib1.columns.names= [labels_of_col[0]]
deremkib1.index.names= [labels_of_col1[0]]
deremkib1

,Hospitals/MCH specialty centres,Health centres/clinics
,,
Alive at discharge,65.0,35.0
Stillbirth,13.0,3.0
Early neonatal death,2.0,0.0
Multiple gestation (live birth + stillbirth),0.0,1.0
No information,19.0,61.0

In [525]:
MDRM_N1=pd.crosstab(data['Q225_9A_1'], (data['MA3']))
MDRM_N2=pd.crosstab(data['Q225_9A_2'], (data['MA3']))
rett=MDRM_N1+MDRM_N2
deremkibv1=rett.drop(-999)
x=[863,60,36]
li=list(deremkibv1.columns)
j=0
for i in li:
    deremkibv1[i]=deremkibv1[i]/x[j]
    j=j+1
deremkibv1=((deremkibv1)*100).round(0)
labels_of_col1 =["",'Alive at discharge','Stillbirth','Early neonatal death','Multiple gestation (live birth + stillbirth)','No information']
labels_of_col = ["Managing_authority","Public/government" , "Private-for-profit","Private-not-for-profit "]
deremkibv1.columns= labels_of_col[1:]
deremkibv1.index= labels_of_col1[1:]
deremkibv1.columns.names= [labels_of_col[0]]
deremkibv1.index.names= [labels_of_col1[0]]
deremkibv1

Managing_authority,Public/government,Private-for-profit,Private-not-for-profit
,,,
Alive at discharge,46.0,72.0,67.0
Stillbirth,8.0,5.0,11.0
Early neonatal death,1.0,2.0,0.0
Multiple gestation (live birth + stillbirth),1.0,0.0,0.0
No information,45.0,22.0,22.0

In [526]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(df_finalffwowffff1ml1,deremkib1,deremkibv1)
Cause_of_PPH_T47gdfw1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_T47gdfw1

,All severe PE/E cases,Hospitals/MCH specialty centres,Health centres/clinics,Public/government,Private-for-profit,Private-not-for-profit
,,,,,,
Alive at discharge,48.0,65.0,35.0,46.0,72.0,67.0
Stillbirth,8.0,13.0,3.0,8.0,5.0,11.0
Early neonatal death,1.0,2.0,0.0,1.0,2.0,0.0
Multiple gestation (live birth + stillbirth),1.0,0.0,1.0,1.0,0.0,0.0
No information,42.0,19.0,61.0,45.0,22.0,22.0

In [535]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1=(Cause_of_PPH_TT,Cause_of_PPH_Total,Antihypertensive_administered_T,Loading_dose_of_magnesium_sulphate_T,Treatment_tt3t,Treatment_tt3tm,Cause_of_PPH_T47gdfw,Cause_of_PPH_T47gdfw1)
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl=pd.concat(Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12_Location_1, keys=['Complications in previous pregnancy','Vital signs checked on admission','Treatment','Loading dose of magnesium sulphate given (in grams)','Maintainance dose','Mode of delivery','Postpartum monitoring','Newborn outcomes','Newborn survival status'])
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl

                                                                                                 All severe PE/E cases  \

Complications in previous pregnancy                None/no information                                            65.0
                                                   Stillbirth or early neonatal death                              3.0
                                                   History of PE/E                                                 2.0
                                                   History of diabetes mellitus                                    1.0
                                                   History of chronic hypertension                                 1.0
                                                   History of abortion                                             3.0
                                                   No previous pregnancy                                          26.0
Vital signs checked on admission                   Blood pressure                                                 87.0
                                                   Pulse                                                          60.0
                                                   Consciousness                                                  85.0
                                                   Respiratory rate                                               44.0
                                                   Experienced seizures                                           18.0
Treatment                                          Hydralazine                                                    33.0
                                                   Nifedipine                                                      5.0
                                                   Both hydralazine and nifedipine                                 2.0
                                                   Methyldopa/aldomet                                              6.0
                                                   No information                                                 52.0
                                                   Other                                                           2.0
Loading dose of magnesium sulphate given (in gr... 1                                                               1.0
                                                   2                                                               0.0
                                                   3                                                               0.0
                                                   4                                                              10.0
                                                   5                                                               3.0
                                                   7                                                               0.0
                                                   8                                                               1.0
                                                   9                                                               3.0
                                                   10                                                              4.0
                                                   14                                                             11.0
                                                   15                                                              0.0
                                                   16                                                              1.0
                                                   No information                                                 66.0
Maintainance dose                                  Maintenance dose(s) given                                      29.0
                                                   Respiratory rate monitored                                     35.0
                                                   Urine output monitored                                         20.0
                                                   Tendon reflexes monitored                                      11.0
Mode of delivery                                   Vaginal                                                        47.0
                                                   Instrumental                                                    4.0
                                                   Caesarean                                                      12.0
                                                   No information                                                 37.0
Postpartum monitoring                              Blood pressure recorded >2 times                               47.0
                                                   Urine output recorded before discharge                         17.0
                                                   Number of days hospitalized noted                              41.0
Newborn outcomes                                   Alive at discharge                                             48.0
                                                   Stillbirth                                                      8.0
                                                   Early neonatal death                                            1.0
                                                   Multiple gestation (live birth + stillbirth)                    1.0
                                                   No information                                                 42.0

                                                                                                 Hospitals/MCH specialty centres  \

Complications in previous pregnancy                None/no information                                                      56.0
                                                   Stillbirth or early neonatal death                                        4.0
                                                   History of PE/E                                                           4.0
                                                   History of diabetes mellitus                                              1.0
                                                   History of chronic hypertension                                           1.0
                                                   History of abortion                                                       4.0
                                                   No previous pregnancy                                                    31.0
Vital signs checked on admission                   Blood pressure                                                           95.0
                                                   Pulse                                                                    82.0
                                                   Consciousness                                                            87.0
                                                   Respiratory rate                                                         72.0
                                                   Experienced seizures                                                     24.0
Treatment                                          Hydralazine                                                              52.0
                                                   Nifedipine                                                                9.0
                                                   Both hydralazine and nifedipine                                           4.0
                                                   Methyldopa/aldomet                                                        6.0
                                                   No information                                                           27.0
                                                   Other                                                                     2.0
Loading dose of magnesium sulphate given (in gr... 1                                                                         1.0
                                                   2                                                                         0.0
                                                   3                                                                         0.0
                                                   4                                                                        14.0
                                                   5                                                                         7.0
                                                   7                                                                         0.0
                                                   8                                                                         1.0
                                                   9                                                                         4.0
                                                   10                                                                        7.0
                                                   14                                                                       20.0
                                                   15                                                                        0.0
                                                   16                                                                        1.0
                                                   No information                                                           44.0
Maintainance dose                                  Maintenance dose(s) given                                                59.0
                                                   Respiratory rate monitored                                               69.0
                                                   Urine output monitored                                                   43.0
                                                   Tendon reflexes monitored                                                23.0
Mode of delivery                                   Vaginal                                                                  55.0
                                                   Instrumental                                                              8.0
                                                   Caesarean                                                                26.0
                                                   No information                                                           11.0
Postpartum monitoring                              Blood pressure recorded >2 times                                         79.0
                                                   Urine output recorded before discharge                                   33.0
                                                   Number of days hospitalized noted                                        72.0
Newborn outcomes                                   Alive at discharge                                                       65.0
                                                   Stillbirth                                                               13.0
                                                   Early neonatal death                                                      2.0
                                                   Multiple gestation (live birth + stillbirth)                              0.0
                                                   No information                                                           19.0

                                                                                                 Health centres/clinics  \

Complications in previous pregnancy                None/no information                                             72.0
                                                   Stillbirth or early neonatal death                               2.0
                                                   History of PE/E                                                  1.0
                                                   History of diabetes mellitus                                     0.0
                                                   History of chronic hypertension                                  1.0
                                                   History of abortion                                              1.0
                                                   No previous pregnancy                                           22.0
Vital signs checked on admission                   Blood pressure                                                  75.0
                                                   Pulse                                                           37.0
                                                   Consciousness                                                   84.0
                                                   Respiratory rate                                                23.0
                                                   Experienced seizures                                            14.0
Treatment                                          Hydralazine                                                     18.0
                                                   Nifedipine                                                       2.0
                                                   Both hydralazine and nifedipine                                  0.0
                                                   Methyldopa/aldomet                                               5.0
                                                   No information                                                  72.0
                                                   Other                                                            2.0
Loading dose of magnesium sulphate given (in gr... 1                                                                0.0
                                                   2                                                                0.0
                                                   3                                                                0.0
                                                   4                                                                7.0
                                                   5                                                                1.0
                                                   7                                                                0.0
                                                   8                                                                0.0
                                                   9                                                                2.0
                                                   10                                                               2.0
                                                   14                                                               4.0
                                                   15                                                               0.0
                                                   16                                                               0.0
                                                   No information                                                  84.0
Maintainance dose                                  Maintenance dose(s) given                                        5.0
                                                   Respiratory rate monitored                                       9.0
                                                   Urine output monitored                                           2.0
                                                   Tendon reflexes monitored                                        2.0
Mode of delivery                                   Vaginal                                                         41.0
                                                   Instrumental                                                     1.0
                                                   Caesarean                                                        1.0
                                                   No information                                                  57.0
Postpartum monitoring                              Blood pressure recorded >2 times                                15.0
                                                   Urine output recorded before discharge                           5.0
                                                   Number of days hospitalized noted                               17.0
Newborn outcomes                                   Alive at discharge                                              35.0
                                                   Stillbirth                                                       3.0
                                                   Early neonatal death                                             0.0
                                                   Multiple gestation (live birth + stillbirth)                     1.0
                                                   No information                                                  61.0

                                                                                                 Public/government  \

Complications in previous pregnancy                None/no information                                        66.0
                                                   Stillbirth or early neonatal death                          3.0
                                                   History of PE/E                                             2.0
                                                   History of diabetes mellitus                                0.0
                                                   History of chronic hypertension                             1.0
                                                   History of abortion                                         2.0
                                                   No previous pregnancy                                      25.0
Vital signs checked on admission                   Blood pressure                                             83.0
                                                   Pulse                                                      56.0
                                                   Consciousness                                              84.0
                                                   Respiratory rate                                           45.0
                                                   Experienced seizures                                       19.0
Treatment                                          Hydralazine                                                31.0
                                                   Nifedipine                                                  5.0
                                                   Both hydralazine and nifedipine                             2.0
                                                   Methyldopa/aldomet                                          6.0
                                                   No information                                             54.0
                                                   Other                                                       2.0
Loading dose of magnesium sulphate given (in gr... 1                                                           0.0

In [537]:
Percent_of_facilities_with_a_pharmacy_or_supply_of_medicines12okl.to_csv("C:/Users/Administrator/Desktop/Presentation/Presentation05/Not sent/Maternal complication reviews/Percent distribution of reviewed severe pre-eclampsia and eclampsia (PEE) cases according to complications in previous pregnancy.csv")

In [102]:
my_tab0 = pd.crosstab(data['Q101_10_1']<1500, data['Q101_10_1']<1500)
my_tab1 = pd.crosstab(data['Q101_10_2']<1500, data['Q101_10_2']<1500)
my_tab=my_tab0+my_tab1
week_of_death_fas2fdfhk1=my_tab.drop(0)
del week_of_death_fas2fdfhk1[0]
dreeee=((week_of_death_fas2fdfhk1/2433)*100).round(0)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Breathing difficulties"]
dreeee.columns= labels_of_col[1:]
dreeee.index= labels_of_col1[1:]
dreeee.columns.names= [labels_of_col[0]]
dreeee.index.names= [labels_of_col1[0]]
dreeee

                                      Breathing difficulties

Very low birth weight (<1,500 grams)                     3.0

In [103]:
my_tabter= pd.crosstab(data['Q101_10_1'],(data['Q101_10_1'].between(1500, 1999)))
my_tabter1= pd.crosstab(data['Q101_10_2'],(data['Q101_10_2'].between(1500, 1999)))
reaea=my_tabter+my_tabter1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee1=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Low birth weight (1,500-1,999 grams)']
labels_of_col = ["","Breathing difficulties"]
dreeee1.columns= labels_of_col[1:]
dreeee1.index= labels_of_col1[1:]
dreeee1.columns.names= [labels_of_col[0]]
dreeee1.index.names= [labels_of_col1[0]]
dreeee1

                                      Breathing difficulties

Low birth weight (1,500-1,999 grams)                     6.0

In [104]:
my_tabter= pd.crosstab(data['Q101_10_1'],(data['Q101_10_1'].between(2000, 2499)))
my_tabter1= pd.crosstab(data['Q101_10_2'],(data['Q101_10_2'].between(2000, 2499)))
reaea=my_tabter+my_tabter1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee12=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Low birth weight (2,000-2,499 grams)']
labels_of_col = ["","Breathing difficulties"]
dreeee12.columns= labels_of_col[1:]
dreeee12.index= labels_of_col1[1:]
dreeee12.columns.names= [labels_of_col[0]]
dreeee12.index.names= [labels_of_col1[0]]
dreeee12

                                      Breathing difficulties

Low birth weight (2,000-2,499 grams)                     9.0

In [105]:
my_tabter= pd.crosstab(data['Q101_10_1'],(data['Q101_10_1'].between(2500, 3999)))
my_tabter1= pd.crosstab(data['Q101_10_2'],(data['Q101_10_2'].between(2500, 3999)))
reaea=my_tabter+my_tabter1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee123=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Normal birth weight (2,500-3,999 grams)']
labels_of_col = ["","Breathing difficulties"]
dreeee123.columns= labels_of_col[1:]
dreeee123.index= labels_of_col1[1:]
dreeee123.columns.names= [labels_of_col[0]]
dreeee123.index.names= [labels_of_col1[0]]
dreeee123

                                         Breathing difficulties

Normal birth weight (2,500-3,999 grams)                    55.0

In [106]:
my_tabter= pd.crosstab(data['Q101_10_1'],(data['Q101_10_1'].between(3999, 5501)))
my_tabter1= pd.crosstab(data['Q101_10_2'],(data['Q101_10_2'].between(3999, 5501)))
reaea=my_tabter+my_tabter1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee1230=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Macrosomic (>4,000 grams)']
labels_of_col = ["","Breathing difficulties"]
dreeee1230.columns= labels_of_col[1:]
dreeee1230.index= labels_of_col1[1:]
dreeee1230.columns.names= [labels_of_col[0]]
dreeee1230.index.names= [labels_of_col1[0]]
dreeee1230

                           Breathing difficulties

Macrosomic (>4,000 grams)                     5.0

In [107]:
my_tab0 = pd.crosstab(data['Q101_10_1']==9999, data['Q101_10_1']==9999)
my_tab1 = pd.crosstab(data['Q101_10_2']==9999, data['Q101_10_2']==9999)
my_tab=my_tab0+my_tab1
week_of_death_fas2fdfhk1=my_tab.drop(0)
del week_of_death_fas2fdfhk1[0]
dreeee0=((week_of_death_fas2fdfhk1/2433)*100).round(0)
labels_of_col1 =["",'No information']
labels_of_col = ["","Breathing difficulties"]
dreeee0.columns= labels_of_col[1:]
dreeee0.index= labels_of_col1[1:]
dreeee0.columns.names= [labels_of_col[0]]
dreeee0.index.names= [labels_of_col1[0]]
dreeee0

                Breathing difficulties

No information                    23.0

In [108]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(dreeee,dreeee1,dreeee12,dreeee123,dreeee1230,dreeee0)
Weight=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Weight

                                         Breathing difficulties

Very low birth weight (<1,500 grams)                        3.0
Low birth weight (1,500-1,999 grams)                        6.0
Low birth weight (2,000-2,499 grams)                        9.0
Normal birth weight (2,500-3,999 grams)                    55.0
Macrosomic (>4,000 grams)                                   5.0
No information                                             23.0

In [109]:
my_tab0 = pd.crosstab(data['Q201_10_1']<1500, data['Q201_10_1']<1500)
my_tab1 = pd.crosstab(data['Q201_10_2']<1500, data['Q201_10_2']<1500)
my_tab=my_tab0+my_tab1
week_of_death_fas2fdfhk1=my_tab.drop(0)
del week_of_death_fas2fdfhk1[0]
dreeee1=((week_of_death_fas2fdfhk1/1144)*100).round(0)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee1.columns= labels_of_col[1:]
dreeee1.index= labels_of_col1[1:]
dreeee1.columns.names= [labels_of_col[0]]
dreeee1.index.names= [labels_of_col1[0]]
dreeee1

                                      Preterm/low birth weight babies

Very low birth weight (<1,500 grams)                             25.0

In [110]:
my_tabter= pd.crosstab(data['Q201_10_1'],(data['Q201_10_1'].between(1500, 1999)))
my_tabter1= pd.crosstab(data['Q201_10_2'],(data['Q201_10_2'].between(1500, 1999)))
reaea=my_tabter+my_tabter1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee11=((dreeeex/1144)*100).round(0)
labels_of_col1 =["",'Low birth weight (1,500-1,999 grams)']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee11.columns= labels_of_col[1:]
dreeee11.index= labels_of_col1[1:]
dreeee11.columns.names= [labels_of_col[0]]
dreeee11.index.names= [labels_of_col1[0]]
dreeee11

                                      Preterm/low birth weight babies

Low birth weight (1,500-1,999 grams)                             76.0

In [111]:
my_tab0 = pd.crosstab(data['Q201_10_1']<1500, data['Q201_10_1']<10)
my_tab1 = pd.crosstab(data['Q201_10_2']<1500, data['Q201_10_2']<10)
reaea=my_tab0+my_tab1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee131=((dreeeex/1144)*100).round(0)
labels_of_col1 =["",'Low birth weight (2,000-2,499 grams)']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee131.columns= labels_of_col[1:]
dreeee131.index= labels_of_col1[1:]
dreeee131.columns.names= [labels_of_col[0]]
dreeee131.index.names= [labels_of_col1[0]]
dreeee131

                                      Preterm/low birth weight babies

Low birth weight (2,000-2,499 grams)                              0.0

In [112]:
my_tab0 = pd.crosstab(data['Q201_10_1']<1500, data['Q201_10_1']<10)
my_tab1 = pd.crosstab(data['Q201_10_2']<1500, data['Q201_10_2']<10)
reaea=my_tab0+my_tab1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee1231=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Normal birth weight (2,500-3,999 grams)']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee1231.columns= labels_of_col[1:]
dreeee1231.index= labels_of_col1[1:]
dreeee1231.columns.names= [labels_of_col[0]]
dreeee1231.index.names= [labels_of_col1[0]]
dreeee1231

                                         Preterm/low birth weight babies

Normal birth weight (2,500-3,999 grams)                              0.0

In [113]:
my_tab0 = pd.crosstab(data['Q201_10_1']<1500, data['Q201_10_1']<10)
my_tab1 = pd.crosstab(data['Q201_10_2']<1500, data['Q201_10_2']<10)
reaea=my_tab0+my_tab1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee12301=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'Macrosomic (>4,000 grams)']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee12301.columns= labels_of_col[1:]
dreeee12301.index= labels_of_col1[1:]
dreeee12301.columns.names= [labels_of_col[0]]
dreeee12301.index.names= [labels_of_col1[0]]
dreeee12301

                           Preterm/low birth weight babies

Macrosomic (>4,000 grams)                              0.0

In [121]:
my_tab0 = pd.crosstab(data['Q201_10_1']<1500, data['Q201_10_1']<10)
my_tab1 = pd.crosstab(data['Q201_10_2']<1500, data['Q201_10_2']<10)
reaea=my_tab0+my_tab1
dreeeex=reaea.drop(0)
del dreeeex[0]
dreeee01=((dreeeex/2433)*100).round(0)
labels_of_col1 =["",'No information']
labels_of_col = ["","Preterm/low birth weight babies"]
dreeee01.columns= labels_of_col[1:]
dreeee01.index= labels_of_col1[1:]
dreeee01.columns.names= [labels_of_col[0]]
dreeee01.index.names= [labels_of_col1[0]]
dreeee01

                Preterm/low birth weight babies

No information                              0.0

In [122]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(dreeee1,dreeee11,dreeee131,dreeee1231,dreeee12301,dreeee01)
Weight1=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=0, sort=False)
Weight1

                                         Preterm/low birth weight babies

Very low birth weight (<1,500 grams)                                25.0
Low birth weight (1,500-1,999 grams)                                76.0
Low birth weight (2,000-2,499 grams)                                 0.0
Normal birth weight (2,500-3,999 grams)                              0.0
Macrosomic (>4,000 grams)                                            0.0
No information                                                       0.0

In [123]:
Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4=(Weight,Weight1)
Cause_of_PPH_Td=pd.concat( Percent_of_facilities_with_delivery_sets_dressing_instrument_sets_Labour_delivery122_4, axis=1, sort=False)
Cause_of_PPH_Td

,Breathing difficulties,Preterm/low birth weight babies
,,
"Very low birth weight (<1,500 grams)",3.0,25.0
"Low birth weight (1,500-1,999 grams)",6.0,76.0
"Low birth weight (2,000-2,499 grams)",9.0,0.0
"Normal birth weight (2,500-3,999 grams)",55.0,0.0
"Macrosomic (>4,000 grams)",5.0,0.0
No information,23.0,0.0

In [154]:
my_tab0 = pd.crosstab(data['Q101_10_1']<1500, data['Q310_10_1']==0)
my_tab1 = pd.crosstab(data['Q101_10_2']<1500, data['Q310_10_2']==0)
reaea=my_tab0+my_tab1
iuyyyyy=reaea.sum()
dereeew=iuyyyyy.drop(0)
retee=((dereeew/2258)*100).round(0)
frame = pd.DataFrame(retee)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Newborn/young infant infections"]
frame.columns= labels_of_col[1:]
frame.index= labels_of_col1[1:]
frame.columns.names= [labels_of_col[0]]
frame.index.names= [labels_of_col1[0]]
frame

                                      Newborn/young infant infections

Very low birth weight (<1,500 grams)                              1.0

In [153]:
my_tab0 = pd.crosstab(data['Q101_10_1'].between(1500, 1999), data['Q310_10_1']==0)
my_tab1 = pd.crosstab(data['Q101_10_2'].between(1500, 1999), data['Q310_10_2']==0)
reaea=my_tab0+my_tab1
iuyyyyy=reaea.sum()
dereeew=iuyyyyy.drop(0)
retee=((dereeew/2258)*100).round(0)
frame = pd.DataFrame(retee)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Newborn/young infant infections"]
frame.columns= labels_of_col[1:]
frame.index= labels_of_col1[1:]
frame.columns.names= [labels_of_col[0]]
frame.index.names= [labels_of_col1[0]]
frame

                                      Newborn/young infant infections

Very low birth weight (<1,500 grams)                              1.0

In [173]:
my_tab0j = pd.crosstab(data['Q310_10_1']<60, data['Q101_10_1'].between(2000, 2499))
my_tab1m = pd.crosstab(data['Q310_10_2']<60, data['Q101_10_2'].between(2000, 2499))
reaea=my_tab0j+my_tab1m
retetes=reaea.drop(True)
del retetes[0]
retee=((retetes/2245)*100).round(0)
frame1 = pd.DataFrame(retee)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Newborn/young infant infections"]
frame1.columns= labels_of_col[1:]
frame1.index= labels_of_col1[1:]
frame1.columns.names= [labels_of_col[0]]
frame1.index.names= [labels_of_col1[0]]
frame1

                                      Newborn/young infant infections

Very low birth weight (<1,500 grams)                              3.0

In [215]:
my_tab0j = pd.crosstab(data['Q310_10_1'], data['Q101_10_1']>=4000)
my_tab1m = pd.crosstab(data['Q310_10_2'], data['Q101_10_2']>=4000)
reaea=my_tab0j+my_tab1m
rerrrrre=reaea.fillna(0)
rerrrrrekkk=rerrrrre.drop(-999)
rerrrrrekkk1=rerrrrrekkk.drop(99)
rerrrrrekkk2=rerrrrrekkk1.drop(60)
tretyyy=rerrrrrekkk2.sum()
tretyyybb=tretyyy.drop(False)
retee=((tretyyybb/2258)*100).round(0)
frame1 = pd.DataFrame(retee)
labels_of_col1 =["",'Very low birth weight (<1,500 grams)']
labels_of_col = ["","Newborn/young infant infections"]
frame1.columns= labels_of_col[1:]
frame1.index= labels_of_col1[1:]
frame1.columns.names= [labels_of_col[0]]
frame1.index.names= [labels_of_col1[0]]
frame1

                                      Newborn/young infant infections

Very low birth weight (<1,500 grams)                             24.0

In [87]:
my_tab0 = pd.crosstab(data['Q128_9A_1'], data['Q128_9A_1'])
my_tab1 = pd.crosstab(data['Q128_9A_2'], data['Q128_9A_2'])
reaea=my_tab0+my_tab1
iuyyyyy=reaea.sum()
iuyyyyy

Q128_9A_1
-999    6111
 1      1144
 2        70
 3         9
 4         5
 9       269
dtype: int64